Repository betaflight/betaflight, pull requests merged in 2018-06, with the labels that each got.

#6013 Reordered and optimised pidProfile parameter group.
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: RN: IMPROVEMENT

#5891 Implemented 'beacon' command in CLI.
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/fc_init.c
  src/main/interface/cli.c
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/io/beeper.c
  src/main/io/beeper.h
  src/main/osd_slave/osd_slave_init.c
  src/main/pg/beeper.c
  src/main/pg/beeper.h
  src/main/target/ALIENWHOOP/config.c
Labels: RN: IMPROVEMENT

#6014 Made Dshot commands work in a non-blocking way.
  1.8
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/fc/fc_core.c
  src/main/interface/cli.c
  src/main/io/beeper.c
Labels: RN: BUGFIX

#6023 Fixed dumping of profile values in CLI.
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/fc/fc_init.c
  src/main/interface/cli.c
Labels: RN: BUGFIX

#6029 Fixed Dshot beacon activation conditions.
  src/main/io/beeper.c
Labels: RN: BUGFIX

#6032 Added RSSI offset to complement RSSI scaling.
  src/main/interface/settings.c
  src/main/pg/rx.c
  src/main/pg/rx.h
  src/main/rx/rx.c
Labels: RN: IMPROVEMENT

#6034 Fix altitude task when using GPS only.
  src/main/fc/fc_tasks.c
Labels: RN: BUGFIX

#6024 Added defaults and MSP support to filter settings.
  src/main/flight/pid.c
  src/main/interface/msp.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: RN: IMPROVEMENT

#6017 Experimental filter-based rc channel smoothing
  src/main/blackbox/blackbox.c
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/fc/fc_rc.c
  src/main/fc/rc_controls.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
  src/main/interface/settings.h
  src/main/pg/rx.c
  src/main/pg/rx.h
  src/main/target/common_fc_pre.h
Labels: RN: MAJOR FEATURE

#6042 Optimised the use of static variables in the PID loop.
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#6031 Fixed OSD altitude display for negative altitude > -1.
  src/main/io/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: BUGFIX

#6043 Added more options for RC interpolation channel selection.
  src/main/fc/fc_rc.c
  src/main/fc/fc_rc.h
  src/main/fc/rc_controls.h
  src/main/interface/settings.c
  src/main/pg/rx.c
Labels: RN: IMPROVEMENT

#6035 Added USE_TRANSPONDER to SPRACINGF3 to match the default features.
  src/main/target/SPRACINGF3/target.h
Labels: RN: TARGET UPDATE

#6049 AG3X Enable burst mode DMA by default
  src/main/target/AG3X/target.h
Labels: RN: TARGET UPDATE

#6044 Added validation checks for interpolation settings, made throttle boost conditional.
  src/main/fc/config.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/interface/settings.c
  src/main/target/common_fc_pre.h
Labels: RN: IMPROVEMENT

#6056 Moving sensor frame throttling from SmartPort to FPort only.
  src/main/rx/fport.c
  src/main/telemetry/smartport.c
  src/main/telemetry/smartport.h
Labels: RN: BUGFIX

#6052 Changed 'dtermSetpointWeight' to use decimal scaling.
  src/main/flight/pid.c
Labels: Needs entry in Release Notes, RN: IMPROVEMENT

#6060 Fixed null pointer reference
  src/main/rx/fport.c
  src/main/telemetry/smartport.c
Labels: RN: BUGFIX

#6062 Fixed 'beeper -ON_USB'.
  src/main/io/beeper.c
Labels: RN: BUGFIX

#6063 [GPS Rescue] - Do not run idle tasks when disarmed
  src/main/flight/gps_rescue.c
Labels: RN: BUGFIX

#6064 Added MAG support to DALRCF405.
  src/main/target/DALRCF405/target.h
  src/main/target/DALRCF405/target.mk
Labels: RN: TARGET UPDATE

#6070 Disabled Dshot beacon by default.
  src/main/pg/beeper.c
Labels: RN: IMPROVEMENT

#6069 Fixed Dshot beacon command description in CLI.
  src/main/interface/cli.c
Labels: RN: BUGFIX

#6068 Re-enabled building of KISSFCV2F7.
  make/targets.mk
Labels: RN: TARGET UPDATE

#6067 RC smoothing - add rx frame training delay to deal with CRSF initialization
  src/main/fc/fc_rc.c
Labels: RN: IMPROVEMENT

#6065 Joelucid's overworked ITerm relax.
  src/main/common/maths.c
  src/main/common/maths.h
  src/main/fc/fc_core.c
  src/main/fc/fc_core.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
  src/main/interface/settings.h
Labels: RN: IMPROVEMENT

#6036 Initial default suggestions for 3.4
  src/main/config/feature.c
  src/main/flight/pid.c
  src/main/pg/rx.c
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#6072 Adding FortiniF4 Rev3 target
  src/main/target/FF_FORTINIF4/FF_FORTINIF4_REV03.mk
  src/main/target/FF_FORTINIF4/config.c
  src/main/target/FF_FORTINIF4/hardware_revision.c
  src/main/target/FF_FORTINIF4/hardware_revision.h
  src/main/target/FF_FORTINIF4/target.c
  src/main/target/FF_FORTINIF4/target.h
Labels: RN: NEW TARGET

#6071 Lagged Moving Average smoothing/filter
  src/main/common/filter.c
  src/main/common/filter.h
Labels: RN: IMPROVEMENT

#6073 Improved 'applyDeadband()', added 'fapplyDeadband()' at @diehertz' request.
  src/main/common/maths.c
Labels: RN: IMPROVEMENT

#6075 Fix typo where assignment was used instead of equality
  src/main/fc/fc_rc.c
Labels: RN: BUGFIX

#6076 Fixed overflow FrSky X channel decoding.
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/rx/cc2500_frsky_shared.h
  src/main/rx/cc2500_frsky_x.c
  src/main/rx/rx.c
  src/test/unit/rx_ranges_unittest.cc
  src/test/unit/rx_rx_unittest.cc
Labels: RN: BUGFIX

#6079 Add guard time between dshot beacon and arming/disarming
  src/main/fc/fc_core.c
  src/main/fc/fc_core.h
  src/main/fc/rc_controls.c
  src/main/io/beeper.c
  src/main/io/beeper.h
  src/test/unit/rc_controls_unittest.cc
Labels: RN: IMPROVEMENT

#6080 Added 'dshotBeaconOffFlags' to MSP.
  src/main/interface/msp.c
Labels: RN: IMPROVEMENT

#6081 iTerm_relax update debug settings and change threshold for setpoint mode
  src/main/flight/pid.c
Labels: RN: BUGFIX

#6106 remove unused use copy profile
  src/main/target/BETAFLIGHTF3/target.h
  src/main/target/OMNIBUS/target.h
  src/main/target/RCEXPLORERF3/target.h
  src/main/target/SPRACINGF3EVO/target.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/common_fc_pre.h
Labels: RN: BUGFIX

#6097 Updated ALIENWHOOP defaults for Betaflight 3.4 Release
  src/main/target/ALIENWHOOP/config.c
Labels: RN: TARGET UPDATE

#6082 Make current in blackbox signed (fixes #6057)
  src/main/blackbox/blackbox.c
Labels: RN: BUGFIX

#6104 Display OSD message and countdown if arming is delayed due to beacon
  src/main/io/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: SAFETY IMPROVEMENT

#6125 remove double transponder update call
  src/main/fc/fc_core.c
Labels: RN: BUGFIX

#6124 Clean up duplicate OSD stat reset
  src/main/io/osd.c
Labels: Cleanup, RN: BUGFIX

#6123 Reduce beacon arming guard time to 1.2 seconds
  src/main/io/beeper.h
Labels: RN: BUGFIX

#6122 [GPS Rescue] - Fix the calculation of acceleration magnitude average to run at gps u…
  src/main/flight/gps_rescue.c
Labels: RN: BUGFIX

#6131 Marked LED DMA buffer FAST_RAM
  src/main/drivers/light_ws2811strip.c
Labels: RN: BUGFIX

#6113 Only reset motor directon on disarming when crash flip mode was active
  src/main/fc/fc_core.c
Labels: RN: BUGFIX

#6130 Stop Dshot commands from running when ESCs not disarmed.
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
Labels: RN: BUGFIX

#6132 Remove GPS rescue update from PID loop.
  src/main/fc/fc_core.c
  src/main/fc/fc_rc.c
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/flight/imu.c
  src/main/io/gps.c
Labels: RN: BUGFIX, Testing Required

#6117 Moved updateGPSRescueState to imuUpdateAttitude. gps_rescue.c tidy.
  src/main/fc/fc_core.c
  src/main/flight/gps_rescue.c
  src/main/flight/imu.c
  src/main/io/gps.c
Labels: RN: BUGFIX

#6121 Fix wrong QMC5883L mag detection
  src/main/drivers/compass/compass_qmc5883l.c
Labels: RN: BUGFIX, Testing Required

#6126 Removed tasks from PID loop that don't belong there.
  src/main/blackbox/blackbox.c
  src/main/common/maths.h
  src/main/drivers/serial_usb_vcp.c
  src/main/drivers/serial_usb_vcp.h
  src/main/fc/fc_core.c
  src/main/fc/fc_core.h
  src/main/fc/fc_tasks.c
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/main/target/SIRINFPV/target.h
  src/main/vcp_hal/usbd_cdc_interface.c
  src/main/vcp_hal/usbd_cdc_interface.h
  src/main/vcp_hal/usbd_conf.c
  src/test/unit/scheduler_unittest.cc
Labels: RN: BUGFIX

#6141 F4 DMA buffer should not reside in CCM
  src/main/drivers/light_ws2811strip.c
Labels: RN: BUGFIX

#6165 Increased travis cache load timeout to stop cache load (and SDK install) from failing.
  .travis.yml
Labels: Build System Improvement

#6096 GPS: handle negative and high altitudes; safer macros in maths.h
  src/main/common/maths.h
  src/main/interface/msp.c
  src/main/io/gps.c
  src/main/io/gps.h
Labels: RN: BUGFIX

#6166 Fix gps rescue heading edge case
  src/main/flight/gps_rescue.c
Labels: RN: BUGFIX

#6161 [GPS Rescue] - Wait for altitude offset to be applied before updating idleTask data
  src/main/flight/gps_rescue.c
  src/main/flight/position.c
  src/main/flight/position.h
Labels: RN: BUGFIX

#6173 Don't let PWM reset SOFTSERIAL
  src/main/fc/config.c
Labels: RN: BUGFIX

#6176 Added a hint of the HoTT single wire connection in Documentaion
  docs/Telemetry.md
Labels: Documentation update

#6188 Swapping external Betaflight OSD support on F3 for new tuning features.
  src/main/target/AG3X/target.h
  src/main/target/AIKONF4/target.h
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/BETAFLIGHTF3/target.h
  src/main/target/CRAZYBEEF3FR/target.h
  src/main/target/DALRCF405/target.h
  src/main/target/FOXEERF405/target.h
  src/main/target/FRSKYF3/target.h
  src/main/target/FURYF3/target.h
  src/main/target/FURYF4/target.h
  src/main/target/OMNIBUS/target.h
  src/main/target/OMNIBUSF4FW/target.h
  src/main/target/OMNINXT/target.h
  src/main/target/SPEEDYBEEF4/target.h
  src/main/target/SPRACINGF3/target.h
  src/main/target/SPRACINGF3EVO/target.h
  src/main/target/SPRACINGF3MINI/target.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/SPRACINGF4EVO/target.h
  src/main/target/STM32F3DISCOVERY/target.h
  src/main/target/common_fc_post.h
  src/main/target/common_fc_pre.h
Labels: RN: TARGET UPDATE

#6201 [GPS Rescue] - Failsafe fix
  src/main/flight/failsafe.c
Labels: RN: BUGFIX

#6196 Change rcsplit protocol to async
  make/source.mk
  src/main/fc/fc_init.c
  src/main/fc/fc_tasks.c
  src/main/io/displayport_rcdevice.c
  src/main/io/displayport_rcdevice.h
  src/main/io/rcdevice.c
  src/main/io/rcdevice.h
  src/main/io/rcdevice_cam.c
  src/main/io/rcdevice_cam.h
  src/main/io/rcdevice_osd.c
  src/main/io/rcdevice_osd.h
  src/test/Makefile
  src/test/unit/rcdevice_unittest.cc
Labels: RN: BUGFIX

#6204 Enabled rearming with 'GPS rescue' enabled and no GPS fix.
  src/main/fc/fc_core.c
Labels: RN: BUGFIX

#6077 Added a list of known issues for the CrazyBee FC
  docs/boards/Board - CrazyBeeF3FR.md
  docs/boards/Board - CrazyBeeF3FS.md
Labels: Documentation update

#6221 Fixed call to checkBootloaderRequest()
  src/main/startup/startup_stm32f411xe.s
Labels: RN: BUGFIX

#6213 fixed open connection twice times and timeout logic
  src/main/interface/settings.c
  src/main/io/rcdevice.c
  src/main/io/rcdevice.h
  src/main/io/rcdevice_cam.c
  src/main/pg/pg_ids.h
  src/main/pg/rcdevice.c
  src/main/pg/rcdevice.h
  src/test/unit/rcdevice_unittest.cc
Labels: RN: BUGFIX

#6227 Revise GPS Rescue throttle and yaw handling to not modify rcCommand
  src/main/common/maths.c
  src/main/common/maths.h
  src/main/fc/fc_core.c
  src/main/fc/fc_rc.c
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/flight/mixer.c
Labels: RN: BUGFIX, Testing Required

#6242 Fixed firmware size issue on FURYF3OSD and STM32F3DISCOVERY.
  src/main/target/FURYF3/target.h
  src/main/target/STM32F3DISCOVERY/target.h
Labels: RN: TARGET UPDATE

#6241 Set yaw D default to 0 since it is unused anyway.
  src/main/flight/pid.c
  src/test/unit/pid_unittest.cc
Labels: RN: BUGFIX

#6235 Fix throttle angle correction when smoothing throttle; reduce processing overhead
  src/main/fc/config.c
  src/main/fc/fc_core.c
  src/main/flight/imu.c
  src/main/flight/imu.h
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/test/unit/flight_imu_unittest.cc
Labels: RN: BUGFIX
