Repository betaflight/betaflight, pull requests merged in 2018-05, with the labels that each got.

#5776 FLASH: Handle overloaded SPI CS pin
  src/main/drivers/flash.c
Labels: RN: BUGFIX

#5769 New target OmniNXT F4/F7
  make/targets.mk
  src/main/target/OMNINXT/OMNINXT4.mk
  src/main/target/OMNINXT/OMNINXT7.mk
  src/main/target/OMNINXT/config.c
  src/main/target/OMNINXT/hardware_revision.c
  src/main/target/OMNINXT/hardware_revision.h
  src/main/target/OMNINXT/target.c
  src/main/target/OMNINXT/target.h
  src/main/target/OMNINXT/target.mk
Labels: RN: NEW TARGET

#5795 Default OSD ESC current alarm to off
  src/main/io/osd.c
Labels: RN: BUGFIX

#5792 Avoid 0xFF character when writing to MAX7456 in auto-increment mode
  src/main/drivers/max7456.c
Labels: RN: BUGFIX

#5799 Fixed flash overflow for MIDELICF3
  src/main/target/MIDELICF3/target.h
Labels: RN: TARGET UPDATE

#5789 Use i2cUnstick() from bus_i2c_hal.c
  src/main/drivers/bus_i2c_hal.c
  src/main/drivers/bus_i2c_stm32f10x.c
Labels: RN: BUGFIX

#5757 Revonano Baro is on I2C bus 3
  src/main/target/REVONANO/target.h
Labels: RN: TARGET UPDATE

#5797 Change M25P16 to FLASH where appropriate
  src/main/drivers/flash.c
  src/main/fc/fc_init.c
  src/main/pg/flash.c
  src/main/target/AIKONF4/target.h
  src/main/target/AIR32/target.h
  src/main/target/ALIENFLIGHTF4/target.h
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/ALIENWHOOP/target.h
  src/main/target/ANYFCM7/target.h
  src/main/target/BETAFLIGHTF4/target.h
  src/main/target/BLUEJAYF4/initialisation.c
  src/main/target/BLUEJAYF4/target.h
  src/main/target/CC3D/target.h
  src/main/target/CHEBUZZF3/target.h
  src/main/target/CLRACINGF4/target.h
  src/main/target/COLIBRI/target.h
  src/main/target/DALRCF405/target.h
  src/main/target/DOGE/target.h
  src/main/target/FF_FORTINIF4/target.h
  src/main/target/FF_PIKOF4/target.h
  src/main/target/FISHDRONEF4/target.h
  src/main/target/FURYF3/target.h
  src/main/target/FURYF4/target.h
  src/main/target/FURYF7/target.h
  src/main/target/IMPULSERCF3/target.h
  src/main/target/IRCFUSIONF3/target.h
  src/main/target/ISHAPEDF3/target.h
  src/main/target/KAKUTEF4/target.h
  src/main/target/KIWIF4/target.h
  src/main/target/LUMBAF3/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/MOTOLAB/target.h
  src/main/target/MULTIFLITEPICO/target.h
  src/main/target/NAZE/target.h
  src/main/target/NOX/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF4FW/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/OMNINXT/target.h
  src/main/target/RACEBASE/target.h
  src/main/target/REVO/target.h
  src/main/target/REVOLT/target.h
  src/main/target/SINGULARITY/target.h
  src/main/target/SPARKY2/target.h
  src/main/target/SPEEDYBEEF4/target.h
  src/main/target/SPEKTRUMF400/target.h
  src/main/target/SPRACINGF3/target.h
  src/main/target/STM32F3DISCOVERY/target.h
  src/main/target/TINYFISH/target.h
  src/main/target/VRRACE/target.h
  src/main/target/X_RACERSPI/target.h
  src/main/target/YUPIF7/target.h
Labels: Cleanup

#5801 Exclude KISSFCV2F7 from CI
  make/targets.mk
Labels: RN: TARGET UPDATE

#5768 Fix potential overflow in combined ESC sensor data
  src/main/sensors/esc_sensor.h
Labels: RN: BUGFIX

#5786 Improved distribution of telemetry bandwidth over sensors (fixes #5785).
  src/main/telemetry/smartport.c
Labels: RN: IMPROVEMENT

#5793 Fix incorrect double increment in MAX7456 screen drawing
  src/main/drivers/max7456.c
Labels: RN: BUGFIX

#5802 Add Board documentation for Matek F405-CTR
  docs/boards/Board - Matek F405-CTR.md
Labels: Documentation update

#5808 Add more info to F405-CTR board docs
  docs/boards/Board - Matek F405-CTR.md
Labels: Documentation update

#5798 YupiF4 Motor output Patch
  src/main/target/YUPIF4/target.c
  src/main/target/YUPIF4/target.h
Labels: RN: TARGET UPDATE

#5765 Fix GPS speed and max speed to respect the units selection
  src/main/common/maths.h
  src/main/io/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: BUGFIX

#5800 Fix dual gyro default logic
  src/main/sensors/gyro.c
  src/main/target/SPRACINGF7DUAL/target.h
Labels: RN: BUGFIX

#5805 Fixed flash overflow for FRSKYF3
  src/main/target/FRSKYF3/target.h
Labels: RN: TARGET UPDATE

#5766 Display ESC telemetry as real RPM in the OSD and telemetry
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/sensors/esc_sensor.c
  src/main/sensors/esc_sensor.h
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/smartport.c
Labels: RN: IMPROVEMENT

#5764 [GPS RESCUE] added gps for altitude estimation
  make/source.mk
  src/main/fc/fc_core.c
  src/main/fc/fc_tasks.c
  src/main/flight/altitude.c
  src/main/flight/imu.c
  src/main/flight/position.c
  src/main/flight/position.h
  src/main/interface/cli.c
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/io/osd.c
  src/main/scheduler/scheduler.h
  src/main/target/COLIBRI_RACE/i2c_bst.c
  src/main/target/common_fc_post.h
  src/main/target/common_fc_pre.h
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/hott.c
  src/main/telemetry/ibus_shared.c
  src/main/telemetry/jetiexbus.c
  src/main/telemetry/ltm.c
  src/main/telemetry/mavlink.c
  src/main/telemetry/smartport.c
  src/test/Makefile
  src/test/unit/altitude_hold_unittest.cc.txt
Labels: RN: MAJOR FEATURE

#5815 "Nuke" mysterious Notes.md file and clean up markdown
  Notes.md
  docs/development/Building in Ubuntu.md
Labels: Documentation update

#5807 Only allow gyro_to_use = BOTH if both detected gyros are the same type
  src/main/drivers/accgyro/accgyro.h
  src/main/interface/cli.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/test/unit/rc_controls_unittest.cc
Labels: RN: BUGFIX, Testing Required

#5809 Fix rx rate calculation when using fport
  src/main/fc/fc_rc.c
  src/main/fc/fc_rc.h
  src/main/fc/fc_tasks.c
  src/main/interface/cli.c
  src/test/unit/cli_unittest.cc
Labels: RN: BUGFIX

#5820 OMNIBUSF4FW and OMNINXT Use config helper function
  src/main/target/OMNIBUSF4FW/config.c
  src/main/target/OMNINXT/config.c
Labels: RN: TARGET UPDATE

#5816 Asgard32 F4/F7 support
  src/main/target/AG3X/AG3X.nomk
  src/main/target/AG3X/AG3XF4.mk
  src/main/target/AG3X/AG3XF7.mk
  src/main/target/AG3X/config.c
  src/main/target/AG3X/target.c
  src/main/target/AG3X/target.h
  src/main/target/AG3X/target.mk
Labels: RN: NEW TARGET

#5823 Licences missed during PRs
  src/main/flight/position.c
  src/main/target/OMNINXT/config.c
  src/main/target/OMNINXT/hardware_revision.c
  src/main/target/OMNINXT/hardware_revision.h
  src/main/target/OMNINXT/target.c
  src/main/target/OMNINXT/target.h
Labels: Ready to Merge

#5810 Configure smart port sensors based on runtime configuration.
  src/main/telemetry/smartport.c
Labels: RN: IMPROVEMENT

#5828 Licence update for newly added target
  src/main/target/AG3X/config.c
  src/main/target/AG3X/target.c
  src/main/target/AG3X/target.h
Labels: Cleanup

#5825 Timer clean up in preparation for configurable timers.
  make/source.mk
  src/main/drivers/camera_control.c
  src/main/drivers/light_ws2811strip_hal.c
  src/main/drivers/light_ws2811strip_stdperiph.c
  src/main/drivers/pwm_output.c
  src/main/drivers/rx/rx_pwm.c
  src/main/drivers/serial_escserial.c
  src/main/drivers/serial_softserial.c
  src/main/drivers/timer.c
  src/main/drivers/timer.h
  src/main/drivers/timer_common.c
  src/main/drivers/timer_hal.c
  src/main/drivers/transponder_ir_io_hal.c
  src/main/drivers/transponder_ir_io_stdperiph.c
  src/main/fc/config.c
  src/main/flight/mixer.c
  src/main/flight/servos.c
  src/main/io/ledstrip.c
  src/main/pg/rx_pwm.c
Labels: Cleanup, RN: IMPROVEMENT, Ready to Merge

#5833 Added generated timer definitions for STM32F7X2 universal target.
  src/main/target/STM32F7X2/target.c
  src/main/target/STM32F7X2/target.h
Labels: RN: TARGET UPDATE

#5813 Add new target Stack-X
  src/main/target/FISHDRONEF4/STACKX.mk
  src/main/target/FISHDRONEF4/target.h
Labels: RN: NEW TARGET

#5836 Updated patch release version to 3.3.3
  src/main/build/version.h
Labels: Applied to Branch

#5686 Display anti-gravity activity in OSD.
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#5840 Add cli parameter bit mapping mode
  src/main/interface/cli.c
  src/main/interface/settings.h
Labels: RN: IMPROVEMENT

#5834 Fix BARO altitude display.
  src/main/flight/position.c
Labels: RN: BUGFIX

#5841 Fixed flash overflow for SPRACINGF3NEO
  src/main/target/SPRACINGF3NEO/target.h
Labels: RN: IMPROVEMENT

#5842 Move defaults out of pg inits (I2C & SPI)
  src/main/pg/bus_i2c.c
  src/main/pg/bus_spi.c
  src/main/target/common_defaults_post.h
Labels: RN: IMPROVEMENT

#5848 Change enabled OSD stats storage to bitmap
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#5846 Cleaned up implementation of MSP port releasing when shared.
  src/main/fc/fc_core.c
  src/main/io/serial.h
  src/main/msp/msp_serial.c
  src/main/msp/msp_serial.h
  src/main/telemetry/telemetry.c
  src/main/telemetry/telemetry.h
  src/test/unit/arming_prevention_unittest.cc
Labels: RN: IMPROVEMENT

#5847 Removed 'tlm_switch', replaced with 'isModeActivationConditionPresent(BOXTELEMETRY)'.
  src/main/fc/fc_core.c
  src/main/interface/msp_box.c
  src/main/interface/settings.c
  src/main/io/serial.c
  src/main/telemetry/telemetry.c
  src/main/telemetry/telemetry.h
Labels: RN: IMPROVEMENT

#5855 Fix OSD GPS Lat and Lon symbols
  src/main/io/osd.c
Labels: RN: BUGFIX

#5853 Move serial.c from SPEED_OPTIMZED to SIZE_OPTIMIZED
  make/source.mk
Labels: RN: IMPROVEMENT

#5866 Removed uneeded USE_DSHOT_DMAR defines.
  src/main/target/OMNINXT/target.h
  src/main/target/STM32F4DISCOVERY/target.h
  src/main/target/WORMFC/target.h
Labels: RN: TARGET UPDATE

#5865 Enabled Dshot DMAR for SPRACINGF4NEO.
  src/main/target/SPRACINGF4NEO/target.c
  src/main/target/SPRACINGF4NEO/target.h
Labels: RN: TARGET UPDATE, Tested

#5862 [GPS RESCUE] - Remove navigation.c and all references to USE_NAV
  make/source.mk
  src/main/fc/config.c
  src/main/fc/fc_core.c
  src/main/fc/fc_init.c
  src/main/flight/navigation.c
  src/main/flight/navigation.h
  src/main/flight/pid.c
  src/main/interface/cli.c
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/io/dashboard.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/io/ledstrip.c
  src/main/target/COLIBRI_RACE/i2c_bst.c
  src/main/target/common_fc_pre.h
  src/main/telemetry/ibus_shared.c
  src/main/telemetry/mavlink.c
  src/test/unit/pid_unittest.cc
Labels: RN: IMPROVEMENT

#5787 update target SPEEDYBEE F4
  docs/boards/Board - SpeedyBee F4 AIO-1.md
  src/main/target/SPEEDYBEEF4/target.c
  src/main/target/SPEEDYBEEF4/target.h
Labels: RN: TARGET UPDATE

#5831 Changes to support enhancements to BFC for OSD stats field ordering
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#5850 UART Treat uarts without a pin as non-existent
  src/main/io/serial.c
Labels: RN: IMPROVEMENT

#5851 Add Paralyze mode support
  .travis.sh
  src/main/fc/fc_core.c
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/interface/msp_box.c
  src/test/Makefile
  src/test/unit/arming_prevention_unittest.cc
Labels: RN: MINOR FEATURE

#5857 FIX: Heli 120 Mixer
  src/main/flight/servos.c
Labels: RN: BUGFIX

#5858 Disable unavailable OSD characters.
  src/main/drivers/max7456_symbols.h
Labels: RN: IMPROVEMENT

#5860 Eliminated inefficient serial function calls at runtime.
  src/main/fc/fc_core.c
  src/main/fc/fc_tasks.c
  src/main/io/rcdevice_cam.c
  src/main/io/serial.c
  src/main/io/serial.h
  src/main/msp/msp_serial.c
  src/main/msp/msp_serial.h
Labels: RN: IMPROVEMENT

#5861 Optimised 'serialPort_t' struct.
  src/main/drivers/serial.h
Labels: RN: IMPROVEMENT

#5875 Add Dterm filter stage 2 info to blackbox
  src/main/blackbox/blackbox.c
Labels: RN: IMPROVEMENT

#5874 Add individual OSD warning options as cli parameters
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#5878 Enabled bidirectional communication with NMEA GPS for all targets.
  src/main/io/gps.c
Labels: RN: IMPROVEMENT, Testing Required

#5879 Cleaned up SmartAudio debugging.
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_smartaudio.h
Labels: RN: IMPROVEMENT

#5877 Removed some target dependencies, and added makefile target 'check-target-independence' to find dependencies.
  Makefile
  make/source.mk
  make/targets.mk
  src/main/drivers/adc.h
  src/main/drivers/system_stm32f10x.c
  src/main/drivers/timer.c
  src/main/fc/fc_init.c
  src/main/fc/fc_rc.c
  src/main/io/serial.c
  src/main/osd_slave/osd_slave_init.c
  src/main/platform.h
  src/main/sensors/compass.c
  src/main/target/CC3D/target.h
  src/main/target/SITL/target.h
Labels: RN: IMPROVEMENT

#5897 Temporary increase serial TX buffer sizes
  src/main/drivers/serial_uart_impl.h
Labels: RN: BUGFIX

#5889 Add handling for array of PG structures in cli resource command.
  src/main/drivers/bus_i2c_config.c
  src/main/drivers/bus_spi_pinconfig.c
  src/main/fc/fc_init.c
  src/main/interface/cli.c
  src/main/osd_slave/osd_slave_init.c
  src/main/pg/bus_i2c.c
  src/main/pg/bus_i2c.h
  src/main/pg/bus_spi.c
  src/main/pg/bus_spi.h
  src/main/target/ALIENFLIGHTF3/initialisation.c
  src/main/target/CJMCU/initialisation.c
  src/main/target/COLIBRI_RACE/target.c
  src/main/target/NAZE/initialisation.c
Labels: RN: IMPROVEMENT

#5898 Fix numeric overflow for gyro calibration samples when using 32KHz sampling
  src/main/sensors/gyro.c
Labels: RN: BUGFIX

#5907 Fix gyro calibration zero offset calculation
  src/main/sensors/gyro.c
Labels: RN: BUGFIX

#5900 Gradually retire stale/unused acc/gyro support
  make/source.mk
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro_legacy/accgyro_adxl345.c
  src/main/drivers/accgyro_legacy/accgyro_adxl345.h
  src/main/drivers/accgyro_legacy/accgyro_bma280.c
  src/main/drivers/accgyro_legacy/accgyro_bma280.h
  src/main/drivers/accgyro_legacy/accgyro_l3g4200d.c
  src/main/drivers/accgyro_legacy/accgyro_l3g4200d.h
  src/main/drivers/accgyro_legacy/accgyro_l3gd20.c
  src/main/drivers/accgyro_legacy/accgyro_l3gd20.h
  src/main/drivers/accgyro_legacy/accgyro_lsm303dlhc.c
  src/main/drivers/accgyro_legacy/accgyro_lsm303dlhc.h
  src/main/drivers/accgyro_legacy/accgyro_mma845x.c
  src/main/drivers/accgyro_legacy/accgyro_mma845x.h
  src/main/sensors/acceleration.c
  src/main/sensors/gyro.c
  src/main/target/CHEBUZZF3/target.h
  src/main/target/CHEBUZZF3/target.mk
  src/main/target/NAZE/target.h
  src/main/target/NAZE/target.mk
  src/main/target/STM32F3DISCOVERY/target.h
  src/main/target/STM32F3DISCOVERY/target.mk
Labels: RN: IMPROVEMENT

#5902 Optimised gyro sanity checks for F7.
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#5908 Fix doc typos
  docs/Inflight Adjustments.md
  docs/LedStrip.md
Labels: Documentation update

#5909 Gyro calibration cleanup and use floating point calculations for zero offset
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT, Testing Required

#5911 Removed unneeded declaration of 'updateRcCommands()'.
  src/main/fc/fc_core.h
Labels: RN: IMPROVEMENT

#5905 Break out rc interpolation as a separate task and run before pid controller and motor update
  src/main/fc/fc_core.c
Labels: For Discussion, RN: BUGFIX

#5912 Smartport not working without USE_ESC_SENSOR
  src/main/telemetry/smartport.c
Labels: RN: BUGFIX

#5913 Ignore leading whitespace for cli command parameters
  src/main/interface/cli.c
Labels: RN: IMPROVEMENT

#5914 Add responses for cli commands that were missing them for consistency
  src/main/interface/cli.c
Labels: RN: IMPROVEMENT

#5919 Reorganised static variables in SmartPort code.
  src/main/telemetry/smartport.c
Labels: RN: REFACTORING

#5947 Fix GPS Rescue (needs yaw smoothing but works).
  src/main/build/debug.c
  src/main/flight/gps_rescue.c
  src/main/interface/msp_box.c
  src/main/io/gps.c
  src/main/io/osd.c
Labels: RN: BUGFIX

#5926 Cleaned up SDK version check.
  .travis.yml
  make/tools.mk
Labels: Cleanup

#5928 Add compass exti configurability
  src/main/interface/cli.c
Labels: RN: IMPROVEMENT

#5929 Fixed RC modes PG version after GPS rescue.
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
Labels: RN: BUGFIX

#5935 Add default display to cli get command if value has been changed
  src/main/interface/cli.c
Labels: RN: IMPROVEMENT

#5936 Update Matek F405-CTR Docs
  docs/boards/Board - Matek F405-CTR.md
Labels: Documentation update

#5938 Added M25Q32 flash ID for completeness
  src/main/drivers/flash_m25p16.c
Labels: RN: IMPROVEMENT

#5940 Replaced PCRE with egrep for macOS users
  Makefile
Labels: REFACTORING

#5949 fix the requirement for easing on yaw changes by only changing relati…
  src/main/flight/gps_rescue.c
Labels: RN: IMPROVEMENT

#5950 Add new target FOXEERF405
  docs/boards/Board - FOXEERF405.md
  src/main/target/FOXEERF405/target.c
  src/main/target/FOXEERF405/target.h
  src/main/target/FOXEERF405/target.mk
Labels: RN: NEW TARGET

#5939 Make FAST_RAM initialized by default
  .travis.sh
  Makefile
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/serial_uart_pinconfig.c
  src/main/fc/fc_init.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/scheduler/scheduler.c
  src/main/sensors/acceleration.c
  src/main/sensors/gyro.c
  src/main/sensors/gyroanalyse.c
  src/main/target/common_fc_pre.h
  src/main/target/common_osd_slave.h
  src/test/unit/platform.h
Labels: RN: REFACTORING

#5927 [GPS RESCUE] - re-implement commented unit tests, add degrees suffix to minAngle and maxAngle in rescue mode
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/test/unit/flight_failsafe_unittest.cc
Labels: RN: IMPROVEMENT

#5953 correct mistaking change on BFF4 target.mk file
  src/main/target/BETAFLIGHTF4/target.mk
Labels: RN: BUGFIX

#5921 Linear Buffer for CRSF CMS display port
  src/main/interface/crsf_protocol.h
  src/main/interface/settings.c
  src/main/io/displayport_crsf.c
  src/main/io/displayport_crsf.h
  src/main/pg/pg_ids.h
  src/main/rx/crsf.c
  src/main/telemetry/crsf.c
  src/main/telemetry/crsf.h
Labels: RN: IMPROVEMENT

#5941 Apply NOINLINE conditionally on ITCM presence
  src/main/fc/fc_core.c
  src/main/fc/fc_rc.c
  src/main/flight/mixer.c
  src/main/main.c
  src/main/sensors/gyro.c
  src/main/target/common_fc_pre.h
  src/main/target/common_osd_slave.h
  src/test/unit/platform.h
Labels: RN: REFACTORING

#5948 Drop software SPI RX support
  make/source.mk
  src/main/drivers/bus_spi_soft.c
  src/main/drivers/bus_spi_soft.h
  src/main/drivers/rx/rx_spi.c
  src/main/drivers/rx/rx_spi.h
  src/main/fc/fc_init.c
  src/main/rx/rx_spi.c
Labels: RN: IMPROVEMENT

#5932 Make gyro calibration period user configurable and rename moron_threshold
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/sensors.h
Labels: RN: IMPROVEMENT

#5957 .fastram_data doesn't fit in FLASH section
  src/main/target/link/stm32_flash_split.ld
Labels: RN: BUGFIX

#5945 New calculation method for Dterm setpoint weight
  src/main/cms/cms_menu_imu.c
  src/main/fc/rc_adjustments.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/msp.c
  src/main/interface/settings.c
Labels: RN: IMPROVEMENT

#5965 Add barometer sensor QMP6988
  make/source.mk
  src/main/drivers/barometer/barometer_qmp6988.c
  src/main/drivers/barometer/barometer_qmp6988.h
  src/main/interface/settings.c
  src/main/sensors/barometer.c
  src/main/sensors/barometer.h
Labels: RN: IMPROVEMENT

#5967 OSD Slave Remove unnecessary include files
  src/main/osd_slave/osd_slave_init.c
Labels: RN: BUGFIX

#5971 Fixed flash overflow for COLIBRI_RACE
  src/main/target/COLIBRI_RACE/target.h
Labels: RN: IMPROVEMENT

#5976 Mark crucial inlined functions with FAST_CODE
  src/main/fc/fc_core.c
  src/main/flight/pid.c
Labels: REFACTORING, RN: REFACTORING

#5916 Convert spiPreInit for configurability
  src/main/drivers/barometer/barometer_bmp280.c
  src/main/drivers/barometer/barometer_ms5611.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_config.c
  src/main/drivers/compass/compass_ak8963.c
  src/main/drivers/flash.c
  src/main/drivers/io.c
  src/main/drivers/io.h
  src/main/drivers/max7456.c
  src/main/drivers/resource.c
  src/main/drivers/resource.h
  src/main/fc/fc_init.c
  src/main/interface/cli.c
  src/main/osd_slave/osd_slave_init.c
  src/main/pg/bus_spi.c
  src/main/pg/bus_spi.h
  src/main/pg/pg_ids.h
  src/main/target/KAKUTEF4/config.c
  src/main/target/STM32F7X2/config/NERO.config
  src/main/target/common_defaults_post.h
  src/test/unit/baro_bmp280_unittest.cc
  src/test/unit/baro_ms5611_unittest.cc
Labels: RN: IMPROVEMENT

#5959 Removed unneeded include (that was breaking layering as well).
  src/main/interface/cli.c
  src/main/pg/bus_i2c.h
Labels: RN: BUGFIX

#5973 Fixed stubbing of 'debug.c' in unittests.
  src/test/Makefile
  src/test/unit/sensor_gyro_unittest.cc
Labels: Cleanup

#5974 Renamed 'gpsRescue' to 'gpsRescueConfig' and moved it into the appropriate location.
  src/main/fc/fc_core.c
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/interface/cli.c
  src/main/interface/settings.c
  src/main/io/gps.c
  src/main/io/gps.h
Labels: RN: IMPROVEMENT

#5979 honor report_cell_voltage for DIY frsky modules
  src/main/telemetry/frsky_hub.c
Labels: RN: IMPROVEMENT

#5981 Fixed capitals in parameter names.
  src/main/interface/settings.c
Labels: RN: BUGFIX

#5977 Marked pidAudioUpdate not for inlining
  src/main/io/pidaudio.c
Labels: RN: IMPROVEMENT

#5987 Removed nonfunctional RX_SERIAL default feature from OMNIBUSF4.
  src/main/target/OMNIBUSF4/target.h
Labels: RN: TARGET UPDATE

#5962 If P and FF have same sign take larger one
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
Labels: RN: MINOR FEATURE

#5980 Added warning for core temperature to OSD.
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
Labels: RN: IMPROVEMENT

#5983 Added check to establish that PID audio is configured.
  src/main/fc/fc_core.c
Labels: RN: IMPROVEMENT

#5984 Fixed typo in 'Makefile'.
  Makefile
Labels: Cleanup

#5986 Fixed typo in CLI.
  src/main/interface/cli.c
Labels: RN: BUGFIX

#5992 Fix yaw reset and throttle angle correction to be before rc interpolation
  src/main/fc/fc_core.c
Labels: RN: BUGFIX

#5989 Cleaned up CLI output generation, added 'cliPrintErrorLinef'.
  src/main/common/printf.h
  src/main/interface/cli.c
Labels: RN: IMPROVEMENT

#5988 Fixed flash overflow in LUXV2_RACE.
  src/main/target/LUX_RACE/target.h
Labels: RN: BUGFIX

#5995 Fixed flash overflow for OMNIBUS.
  src/main/target/OMNIBUS/target.h
Labels: RN: BUGFIX

#5997 Fixed flash overflow on RG_SSD_F3 and FURYF3OSD.
  src/main/target/FURYF3/target.h
  src/main/target/RG_SSD_F3/target.h
Labels: RN: BUGFIX

#5991 Reset the entire config when parameter groups have changed.
  src/main/config/config_eeprom.c
  src/main/config/config_eeprom.h
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/fc_init.c
  src/main/osd_slave/osd_slave_init.c
  src/main/pg/pg.c
  src/main/pg/pg.h
Labels: RN: IMPROVEMENT

#5999 Reduce flash usage in OSD element display logic
  src/main/io/osd.c
  src/main/io/osd.h
Labels: RN: IMPROVEMENT

#5975 gyro & d-term filters: remove filtering options except biquad/pt1
  src/main/common/filter.c
  src/main/common/filter.h
  src/main/flight/pid.c
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/test/unit/common_filter_unittest.cc
  src/test/unit/sensor_gyro_unittest.cc
Labels: RN: IMPROVEMENT

#6005 Increase SPI_PREINIT_IPU_COUNT to accommodate I/O rich boards
  src/main/drivers/bus_spi.h
Labels: RN: IMPROVEMENT

#5963 ITerm relax feature
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
  src/main/interface/settings.h
  src/test/unit/pid_unittest.cc
Labels: RN: MINOR FEATURE

#5970 Acro trainer
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/fc/fc_core.c
  src/main/fc/rc_modes.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/msp_box.c
  src/main/interface/settings.c
  src/main/interface/settings.h
  src/main/target/common_fc_pre.h
Labels: RN: MINOR FEATURE

#6002 Add OSD support for AFNG F7 Horus30 board
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/ALIENFLIGHTNGF7/target.mk
Labels: RN: TARGET UPDATE, Ready to Merge

#6004 Added offset parameter to ESC sensor current calculation to compensate for non-ESC consumption.
  src/main/interface/settings.c
  src/main/sensors/current.c
  src/main/sensors/esc_sensor.h
Labels: RN: IMPROVEMENT

#6001 Make all RSSI sources scalable.
  src/main/io/ledstrip.c
  src/main/io/osd.c
  src/main/rx/cc2500_frsky_d.c
  src/main/rx/cc2500_frsky_shared.c
  src/main/rx/cc2500_frsky_x.c
  src/main/rx/flysky.c
  src/main/rx/fport.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/telemetry/ltm.c
  src/main/telemetry/mavlink.c
  src/test/unit/ledstrip_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: Needs entry in Release Notes, RN: IMPROVEMENT

#5968 Absolute control
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
Labels: RN: MINOR FEATURE

#6008 Add Galileo support to GPS
  src/main/interface/settings.c
  src/main/io/gps.c
  src/main/io/gps.h
Labels: RN: IMPROVEMENT

#5998 Failsafe switch choosable behavior
  docs/Failsafe.md
  src/main/flight/failsafe.c
  src/main/flight/failsafe.h
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/interface/settings.h
  src/test/unit/flight_failsafe_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#5796 Kakutef7 IMU change
  src/main/target/KAKUTEF7/target.c
  src/main/target/KAKUTEF7/target.h
  src/main/target/KAKUTEF7/target.mk
Labels: RN: TARGET UPDATE
