Repository betaflight/betaflight, pull requests merged in 2018-10, with the labels that each got.

#6834 SPI RX targets: Cleanup RX_SPI related pin defs
  src/main/target/CJMCU/target.h
  src/main/target/CRAZYBEEF3FR/target.h
  src/main/target/MATEKF411RX/target.h
  src/main/target/MIDELICF3/target.h
  src/main/target/NUCLEOF446RE/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6843 F3: Use ADC device from PG
  src/main/drivers/adc_stm32f30x.c
  src/main/drivers/adc_stm32f4xx.c
  src/main/drivers/adc_stm32f7xx.c
Labels: Bugfix, RN: BUGFIX

#6844 Dual gyro fixes - fix non-reentrant code in gyro sensor update and hardcoded gyroSensor1 logic
  src/main/sensors/gyro.c
  src/main/sensors/gyro_filter_impl.h
Labels: RN: BUGFIX

#6846 REVO: Remove stale ADC channel def
  src/main/target/REVO/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6862 Fixed dual gyro code for 3.5.
  src/main/sensors/gyro.c
Labels: Applied to Branch, RN: BUGFIX

#6863 Add conditional for rx_xn297.c
  src/main/drivers/rx/rx_xn297.c
  src/main/target/common_post.h
Labels: RN: BUGFIX

#6864 Fix ordering of gyro filtering and overflow/yaw-spin logic
  src/main/sensors/gyro.c
Labels: RN: BUGFIX

#6851 RX SPI: Refactor rx_spi to use spiBusXXX API
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/rx/rx_cc2500.c
  src/main/drivers/rx/rx_cc2500.h
  src/main/drivers/rx/rx_nrf24l01.c
  src/main/drivers/rx/rx_nrf24l01.h
  src/main/drivers/rx/rx_spi.c
  src/main/drivers/rx/rx_spi.h
  src/main/drivers/rx/rx_xn297.c
  src/main/drivers/rx/rx_xn297.h
Labels: RN: REFACTORING

#6850 Multiple targets: Remove or convert stale MPU_INT_EXTI defs
  src/main/target/DALRCF722DUAL/target.h
  src/main/target/NUCLEOF446RE/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/SPEDIXF4/target.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/SPRACINGF7DUAL/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6853 SPI: Constrain clock divisor range to 2~256.
  src/main/drivers/bus_spi_ll.c
  src/main/drivers/bus_spi_stdperiph.c
Labels: Bugfix, RN: BUGFIX

#6867 Fixes SD Card detect pin on SDIO targets.
  src/main/drivers/sdcard_sdio_baremetal.c
  src/main/interface/cli.c
Labels: RN: BUGFIX

#6874 Update Flash driver for generic target
  src/main/pg/flash.c
  src/main/target/common_defaults_post.h
Labels: RN: REFACTORING

#6872 Update Gyro driver for generic target
  src/main/interface/cli.c
  src/main/interface/settings.c
  src/main/target/STM32F7X2/config/NERO.config
  src/main/target/STM32F7X2/target.h
  src/main/target/common_defaults_post.h
Labels: RN: REFACTORING

#6871 Update MAX7456 driver for generic target
  src/main/drivers/max7456.c
  src/main/target/common_defaults_post.h
Labels: RN: REFACTORING

#6868 SDCARD: Consolidation of SPI and SDIO variants (Part 2: Use VTable to switch between SPI and SDIO)
  src/main/drivers/sdcard.c
  src/main/drivers/sdcard_impl.h
  src/main/drivers/sdcard_sdio_baremetal.c
  src/main/drivers/sdcard_spi.c
Labels: RN: REFACTORING

#6880 SPI: Refactor sdcard_spi.c to use busDevice_t (again)
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/sdcard_impl.h
  src/main/drivers/sdcard_spi.c
Labels: RN: REFACTORING

#6873 Update SDCARD driver for generic target
  src/main/drivers/sdcard_sdio_baremetal.c
  src/main/drivers/sdcard_spi.c
  src/main/fc/init.c
  src/main/pg/sdcard.c
  src/main/pg/sdcard.h
Labels: RN: REFACTORING

#6882 SDCARD: Prevent msp from calling sdcard_getMetadata when card is not ready
  src/main/drivers/sdcard.c
  src/main/interface/cli.c
  src/main/interface/msp.c
Labels: RN: BUGFIX

#6877 Add HEADFREE indicator to the OSD flight mode and warnings display elements
  src/main/io/osd.c
Labels: RN: SAFETY IMPROVEMENT

#6810 fix rcdevice can't work
  src/main/io/rcdevice.c
  src/main/io/rcdevice.h
  src/main/io/rcdevice_cam.c
  src/main/pg/rcdevice.c
  src/test/unit/rcdevice_unittest.cc
Labels: RN: BUGFIX

#6887 Fixed flash overflow of RACEBASE, SPRACINGF3NEO in 3.5.
  src/main/target/RACEBASE/target.h
  src/main/target/SPRACINGF3NEO/target.h
Labels: Applied to Branch, Needs entry in Release Notes, RN: TARGET UPDATE

#6895 Updated path in documentation for customised versions.
  docs/Customized Version.md
Labels: Documentation update

#6656 added esc max temp and rpm to OSD
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/test/unit/osd_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#6900 Fixed flash overflow on CRAZYBEEF3FR.
  src/main/target/CRAZYBEEF3FR/target.h
Labels: Needs entry in Release Notes, RN: TARGET UPDATE

#6890 OMNIBUSF4FW: Allow PC13 and PC14 for Omnibus F4 V6
  src/main/target/OMNIBUSF4FW/target.h
Labels: RN: TARGET UPDATE

#6889 Remove stale gyro cs defs from resource
  src/main/drivers/resource.c
  src/main/drivers/resource.h
Labels: Cleanup, RN: REFACTORING

#6909 target/system_stm32f{4,7}xxx.c: Prevent signed and unsigned comparison warning
  src/main/target/system_stm32f4xx.c
  src/main/target/system_stm32f7xx.c
Labels: RN: BUGFIX

#6906 Fix DEF_TIM_DMA_COND usage to including leading comma
  src/main/drivers/timer_def.h
Labels: Bugfix, RN: BUGFIX

#6907 Protect reportExtendedEscSensors with USE_ESC_SENSOR to avoid unused warning
  src/main/telemetry/smartport.c
Labels: Cleanup, RN: BUGFIX

#6899 Spektrum SRXL Telemetry tidying.
  src/main/rx/spektrum.c
  src/main/rx/spektrum.h
  src/main/telemetry/srxl.c
Labels: RN: BUGFIX

#6913 Fix overlooked USE_xxx case of ADC
  src/main/interface/settings.c
Labels: Bugfix, RN: BUGFIX

#6905 Add conditionals for receiver protocols
  src/main/rx/crsf.c
  src/main/rx/fport.c
  src/main/rx/ibus.c
  src/main/rx/jetiexbus.c
  src/main/rx/sbus.c
  src/main/rx/sbus_channels.c
  src/main/rx/spektrum.c
  src/main/rx/sumd.c
  src/main/rx/sumh.c
  src/main/rx/xbus.c
Labels: Cleanup, RN: IMPROVEMENT

#6904 Better handling of USE_UART and USE_INVERTER
  src/main/drivers/inverter.c
  src/main/drivers/inverter.h
  src/main/drivers/serial_pinconfig.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_init.c
  src/main/drivers/serial_uart_pinconfig.c
  src/main/drivers/serial_uart_stm32f10x.c
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/interface/cli.c
  src/main/target/common_defaults_post.h
  src/main/target/common_pre.h
Labels: Cleanup, RN: REFACTORING

#6901 Improve handling of USE_SERVOS in mixer.c
  src/main/flight/mixer.c
Labels: Cleanup, RN: IMPROVEMENT

#6891 Increase priority of arming disabled OSD warnings and cycle through all
  src/main/io/osd.c
Labels: RN: IMPROVEMENT

#6920 add some PR links in docs/Upgrading/Upgrading from 3.2 to 3.3.md
  docs/Upgrading/Upgrading from 3.2 to 3.3.md
Labels: Documentation update

#6918 Fix conditionals for telemetry protocols.
  src/main/rx/crsf.c
  src/main/rx/spektrum.c
  src/main/target/common_post.h
  src/main/telemetry/crsf.c
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/hott.c
  src/main/telemetry/ibus.c
  src/main/telemetry/ibus_shared.c
  src/main/telemetry/jetiexbus.c
  src/main/telemetry/ltm.c
  src/main/telemetry/mavlink.c
  src/main/telemetry/smartport.c
  src/main/telemetry/srxl.c
  src/main/telemetry/telemetry.c
Labels: RN: IMPROVEMENT

#6916 Refactor serial_usb_vcp.c for clarity
  src/main/drivers/serial_usb_vcp.c
Labels: RN: REFACTORING

#6930 Re-added removed features on F3 after rx / telemetry cleanup.
  src/main/target/COLIBRI_RACE/target.h
  src/main/target/FRSKYF3/target.h
  src/main/target/FURYF3/target.h
  src/main/target/IMPULSERCF3/target.h
  src/main/target/LUX_RACE/target.h
  src/main/target/OMNIBUS/target.h
  src/main/target/RACEBASE/target.h
  src/main/target/RCEXPLORERF3/target.h
  src/main/target/RG_SSD_F3/target.h
  src/main/target/SIRINFPV/target.h
  src/main/target/SPRACINGF3/target.h
  src/main/target/STM32F3DISCOVERY/target.h
Labels: RN: IMPROVEMENT

#6912 modify the scl pin -PB8 flywoo405 target
  docs/boards/Board - FLYWOOF405.md
  src/main/target/KAKUTEF4/target.h
Labels: RN: TARGET UPDATE

#6934 Fix stick arming auto-disarm timer not being reset
  src/main/fc/core.c
Labels: RN: BUGFIX

#6925 Increase fpv_mix_degrees maximum value
  src/main/interface/settings.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#6938 Fixed flash overflow on FLIP32F3OSD.
  src/main/target/FURYF3/target.h
  src/main/target/SIRINFPV/target.h
  src/main/target/SPRACINGF3/target.h
  src/main/target/SPRACINGF3MINI/target.h
Labels: Applied to Branch, RN: TARGET UPDATE

#6939 Fixed flash overflow on SPRACINGF3MINI.
  src/main/target/SPRACINGF3MINI/target.h
Labels: Applied to Branch, RN: TARGET UPDATE

#6940 F7: Remove txIrq from uartHardware_s
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stm32f7xx.c
Labels: Cleanup, RN: REFACTORING

#6946 Updated version to 3.5.3.
  src/main/build/version.h
Labels: Applied to Branch, Householding

#6933 Implement biquad on 2nd dterm lowpass filter.
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
Labels: RN: IMPROVEMENT

#6955 Fixed flash overflow on CRAZYBEEF3FR.
  src/main/target/CRAZYBEEF3FR/target.h
Labels: Needs entry in Release Notes, RN: TARGET UPDATE

#6956 Refactor mixer motor_stop handling - reduces flash usage
  src/main/flight/mixer.c
Labels: RN: REFACTORING

#6959 update switch example to fit current coding style
  docs/development/CodingStyle.md
Labels: Documentation update

#6961 FortiniF4 Camera Control and LED pin fix
  src/main/target/FF_FORTINIF4/target.c
  src/main/target/FF_FORTINIF4/target.h
Labels: RN: TARGET UPDATE

#6958 Reinstate UART TX DMA for F7 (HAL driver)
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stm32f7xx.c
Labels: Bugfix, RN: BUGFIX

#6957 cleanup dterm lowpass order
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#6953 Removed USE_LED_STRIP from individual targets.
  src/main/target/CRAZYBEEF3FR/target.h
  src/main/target/DALRCF722DUAL/target.h
  src/main/target/MATEKF411RX/target.h
  src/main/target/SPRACINGF7DUAL/target.h
Labels: RN: TARGET UPDATE

#6968 Update I/O and pwm define for target HAKRCF722 in production.
  src/main/target/HAKRCF722/target.c
  src/main/target/HAKRCF722/target.h
Labels: RN: TARGET UPDATE

#6971 Fix OSD artificial horizon division by zero
  src/main/io/osd.c
Labels: RN: BUGFIX

#6936 Fix initial stick arming when gyro_cal_on_first_arm is used
  src/main/fc/rc_controls.c
Labels: RN: BUGFIX

#6947 Changed visual beeper to respect beeper settings.
  src/main/io/beeper.c
Labels: RN: IMPROVEMENT

#6951 F4BY: Fix bad SDCARD DMA channel spec
  src/main/target/F4BY/target.h
Labels: RN: BUGFIX

#6967 OSD: Protect ESC stat max temp by USE_ESC_SENSOR
  src/main/io/osd.c
Labels: RN: BUGFIX

#6970 Improve OSD g-force display and avoid math when not needed
  src/main/io/osd.c
Labels: RN: IMPROVEMENT

#6973 OSD temperature display and calculations cleanup
  src/main/io/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: REFACTORING

#6974 Fix OSD time remaining division by zero
  src/main/io/osd.c
Labels: RN: BUGFIX

#6952 Improved handling of airmode detection.
  src/main/fc/core.c
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
  src/main/flight/mixer.c
  src/main/io/osd.c
  src/main/telemetry/crsf.c
  src/test/unit/osd_unittest.cc
  src/test/unit/telemetry_crsf_msp_unittest.cc
  src/test/unit/telemetry_crsf_unittest.cc
Labels: RN: IMPROVEMENT

#6976 Add new target FOXEERF722DUAL
  docs/boards/Board - FOXEERF722DUAL.md
  src/main/target/FOXEERF722DUAL/target.c
  src/main/target/FOXEERF722DUAL/target.h
  src/main/target/FOXEERF722DUAL/target.mk
Labels: RN: NEW TARGET

#6986 MAX7456: Bring CS down during device type detection
  src/main/drivers/max7456.c
Labels: Bugfix, RN: BUGFIX

#6979 Prevent MOTOR_STOP and auto-disarm for stick arming when GPS Rescue is active
  src/main/fc/core.c
  src/main/flight/mixer.c
Labels: RN: BUGFIX, Testing Required

#6985 Gryro configuration parameters cleanup
  src/main/pg/bus_spi.c
  src/main/sensors/acceleration.c
  src/main/target/ALIENFLIGHTF3/target.h
  src/main/target/DALRCF405/target.h
  src/main/target/DALRCF722DUAL/target.h
  src/main/target/FOXEERF405/target.h
  src/main/target/FOXEERF722DUAL/target.h
  src/main/target/KAKUTEF4/target.h
  src/main/target/LUX_RACE/target.h
  src/main/target/MATEKF722/target.h
  src/main/target/SPRACINGF7DUAL/target.h
  src/main/target/STM32F3DISCOVERY/target.h
Labels: RN: REFACTORING

#6994 Fixed flash overflow for SPRACINGF3, RMDO, AIORACERF3.
  src/main/target/FRSKYF3/target.h
  src/main/target/SPRACINGF3/target.h
  src/main/target/SPRACINGF3EVO/target.h
  src/main/target/SPRACINGF3MINI/target.h
Labels: Applied to Branch, Needs entry in Release Notes, RN: TARGET UPDATE

#6977 Converted 'SKIP_' defines to 'USE_'.
  src/main/flight/imu.c
  src/main/interface/cli.c
  src/main/interface/settings.c
  src/main/io/dashboard.c
  src/main/io/dashboard.h
  src/main/io/serial.c
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/main/target/CC3D/target.h
  src/main/target/CJMCU/target.h
  src/main/target/SITL/target.c
  src/main/target/SITL/target.h
  src/main/target/common_pre.h
  src/test/unit/target.h
Labels: RN: REFACTORING

#6981 fix incorrect throttle offset in airmode
  src/main/flight/mixer.c
Labels: RN: BUGFIX

#7007 Drop USE_CRSF_CMS_TELEMETRY if USE_CMS is not defined
  src/main/target/common_post.h
Labels: RN: BUGFIX

#6996 Added some improvements to FrSky X SPI.
  src/main/rx/cc2500_frsky_x.c
Labels: RN: IMPROVEMENT

#6997 Fixed build errors when building with USE_SERIALRX_FPORT but without USE_SERIALRX_SBUS or USE_TELEMETRY_SMARTPORT.
  src/main/rx/fport.c
  src/main/rx/sbus_channels.c
  src/main/target/common_post.h
Labels: RN: BUGFIX

#6998 Remove unused BARO, GPS_HOME, GPS_HOLD modes.
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.h
  src/main/interface/msp_box.c
  src/main/io/ledstrip.c
  src/main/target/COLIBRI_RACE/i2c_bst.c
  src/main/telemetry/ibus_shared.c
  src/main/telemetry/ltm.c
  src/main/telemetry/mavlink.c
  src/main/telemetry/smartport.c
Labels: RN: IMPROVEMENT

#7010 Mixer fix (cherry-pick from master #6981 to 3.5-maintenence)
  src/main/flight/mixer.c
Labels: Applied to Branch

#6114 Motor diagnostic OSD feature
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/test/unit/osd_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#7008 JETIEXBUS Telemetry: Conditional-ize GPS related functions with USE_GPS
  src/main/telemetry/jetiexbus.c
Labels: RN: BUGFIX

#6999 update docs for how to build under osx
  docs/development/Building in Mac OS X.md
Labels: Documentation update

#7011 Added documentation for dealing with parameter groups.
  docs/development/ParameterGroups.md
Labels: Documentation update
