Repository betaflight/betaflight, pull requests merged in 2018-09, with the labels that each got.

#6671 fix name of software in development.md
  docs/development/Development.md
Labels: Documentation update

#6048 F7 TIM8_CH1,2,3 dmaopt ordering to match that of F4
  src/main/drivers/timer_def.h
  src/main/target/AG3X/target.c
  src/main/target/ALIENFLIGHTNGF7/target.c
  src/main/target/ANYFCF7/target.c
  src/main/target/ANYFCM7/target.c
  src/main/target/KISSFCV2F7/target.c
  src/main/target/MATEKF722/target.c
  src/main/target/NERO/target.c
  src/main/target/NUCLEOF7/target.c
  src/main/target/NUCLEOF722/target.c
  src/main/target/OMNIBUSF7/target.c
  src/main/target/OMNINXT/target.c
  src/main/target/SPRACINGF7DUAL/target.c
  src/main/target/YUPIF7/target.c
Labels: RN: IMPROVEMENT

#6673 Rename level mode parameters to match their function
  src/main/interface/settings.c
Labels: Needs entry in Release Notes, RN: IMPROVEMENT

#6679 Initialize timers assigned to servos appropriately
  src/main/drivers/pwm_output.c
Labels: Bugfix, RN: BUGFIX

#6662 GPS over MSP related fixes
  src/main/fc/config.c
  src/main/interface/settings.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/telemetry/crsf.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#6682 Fix iterm relax interfering with crash recovery
  src/main/flight/pid.c
Labels: RN: BUGFIX

#6686 to prevent divide by zero possibility in pid.c
  src/main/interface/settings.c
Labels: RN: BUGFIX

#6670 Fixed Spektrum implementation inconsistency.
  src/main/rx/spektrum.c
  src/main/rx/spektrum.h
Labels: RN: BUGFIX

#6692 Remove F1 from list of supported processors.
  README.md
Labels: Documentation update

#6681 Remove IOConfigGPIOAF from timerInit
  src/main/drivers/timer.c
Labels: RN: IMPROVEMENT

#6402 CLI configurable limits for rates
  src/main/blackbox/blackbox.c
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/fc/rc.c
  src/main/fc/rc_controls.h
  src/main/interface/settings.c
Labels: RN: IMPROVEMENT

#6696 Fix USB HID parameter support in MSP_SET_RX_CONFIG msp message
  src/main/interface/msp.c
Labels: RN: BUGFIX

#6702 Accgyro: Remove soft reset facility
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
  src/main/drivers/system_stm32f4xx.c
  src/main/drivers/system_stm32f7xx.c
  src/main/drivers/usb_msc_f4xx.c
  src/main/drivers/usb_msc_f7xx.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/test/unit/sensor_gyro_unittest.cc
Labels: Cleanup, RN: IMPROVEMENT

#6701 Resolve upward inclusion of sensors/gyro.h from driver layer
  src/main/drivers/accgyro/accgyro.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/test/unit/sensor_gyro_unittest.cc
Labels: Cleanup

#6680 Added 'VTX CONTROL DISABLE' mode.
  src/main/fc/rc_modes.h
  src/main/interface/msp_box.c
  src/main/io/vtx.c
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_tramp.c
Labels: RN: IMPROVEMENT, Testing Required

#6688 Remove skipping of frames after suspension for serial RX.
  src/main/fc/config.c
  src/main/rx/rx.c
  src/main/rx/rx.h
Labels: RN: BUGFIX

#6668 Added '-fno-common' build option, fixed resulting problems.
  Makefile
  src/main/cms/cms.h
  src/main/drivers/bus_spi_ll.c
  src/main/drivers/bus_spi_stdperiph.c
  src/main/drivers/usb_msc_f7xx.c
  src/main/flight/servos.h
  src/main/io/displayport_hott.h
  src/main/io/displayport_srxl.h
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
  src/main/io/rcdevice_cam.h
  src/main/rx/nrf24_h8_3d.c
  src/main/rx/nrf24_inav.c
  src/main/target/SITL/target.c
  src/main/target/SITL/target.h
  src/main/vcpf4/usbd_cdc_vcp.c
  src/main/vcpf4/usbd_cdc_vcp.h
  src/test/unit/rcdevice_unittest.cc
Labels: RN: REFACTORING

#6715 Incremented maintenance release version to 3.5.2.
  src/main/build/version.h
Labels: Applied to Branch, Householding

#6720 add specific orientation for mag of the YupiF7 extension board
  src/main/target/YUPIF7/target.h
Labels: RN: TARGET UPDATE

#6669 Added support for STM32F765xx
  make/mcu/STM32F7.mk
  src/main/config/config_streamer.c
  src/main/drivers/adc_stm32f7xx.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_pinconfig.c
  src/main/drivers/serial_uart_stm32f10x.c
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/platform.h
  src/main/startup/startup_stm32f765xx.s
  src/main/target/link/stm32_flash_f765.ld
Labels: RN: MINOR FEATURE

#6726 use the defined value in both places
  src/main/flight/pid.c
Labels: RN: BUGFIX

#6721 Fix bug with antiwindup inversion
  src/main/flight/pid.c
  src/test/unit/pid_unittest.cc
Labels: Bugfix, RN: BUGFIX

#6731 Change dterm_notch_cutoff default to 0
  src/main/flight/pid.c
Labels: RN: BUGFIX

#6706 Added KAKUTEF7V2 target
  src/main/target/KAKUTEF7/KAKUTEF7V2.mk
  src/main/target/KAKUTEF7/target.h
  src/main/target/KAKUTEF7/target.mk
Labels: RN: NEW TARGET

#6729 Change itermWindupPointPercent default
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/pid.c
  src/main/interface/settings.c
  src/test/unit/pid_unittest.cc
Labels: RN: IMPROVEMENT

#6743 Fix issue 6722. SRXL data collection was not triggered.
  src/main/rx/spektrum.c
Labels: Bugfix

#6738 Adding a per-target unit test for timer metadata consistency.
  make/targets.mk
  make/targets_list.mk
  src/main/target/AIKONF4/target.h
  src/main/target/AIR32/target.h
  src/main/target/AIRHEROF3/target.h
  src/main/target/ALIENFLIGHTF3/target.h
  src/main/target/ANYFCF7/target.h
  src/main/target/BEEROTORF4/target.h
  src/main/target/BETAFLIGHTF3/target.h
  src/main/target/BLUEJAYF4/target.h
  src/main/target/COLIBRI_RACE/target.h
  src/main/target/CRAZYBEEF3FR/target.h
  src/main/target/CRAZYFLIE2/target.h
  src/main/target/DOGE/target.h
  src/main/target/F4BY/target.h
  src/main/target/FRSKYF3/target.h
  src/main/target/FRSKYF4/target.h
  src/main/target/HAKRCF722/target.h
  src/main/target/IRCFUSIONF3/target.h
  src/main/target/KISSFC/target.h
  src/main/target/KISSFCV2F7/target.h
  src/main/target/KIWIF4/target.h
  src/main/target/LUX_RACE/target.h
  src/main/target/MOTOLAB/target.h
  src/main/target/NUCLEOF446RE/target.h
  src/main/target/NUCLEOF7/target.h
  src/main/target/NUCLEOF722/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF4FW/target.h
  src/main/target/OMNINXT/target.h
  src/main/target/RACEBASE/target.h
  src/main/target/RCEXPLORERF3/target.h
  src/main/target/REVOLT/target.h
  src/main/target/RG_SSD_F3/target.h
  src/main/target/SINGULARITY/target.h
  src/main/target/SPARKY/target.h
  src/main/target/SPARKY2/target.h
  src/main/target/SPRACINGF4EVO/target.h
  src/main/target/SPRACINGF4NEO/target.h
  src/main/target/STM32F4DISCOVERY/target.h
  src/main/target/VRRACE/target.h
  src/main/target/WORMFC/target.h
  src/main/target/X_RACERSPI/target.h
  src/main/target/YUPIF7/target.h
  src/test/Makefile
  src/test/unit/timer_definition_unittest.cc
  src/test/unit/timer_definition_unittest.include/drivers/dma.h
  src/test/unit/timer_definition_unittest.include/drivers/io.h
  src/test/unit/timer_definition_unittest.include/drivers/timer.h
  src/test/unit/timer_definition_unittest.include/drivers/timer_def.h
  src/test/unit/timer_definition_unittest.include/mock_enums.h
  src/test/unit/timer_definition_unittest.include/pg/bus_bst.h
  src/test/unit/timer_definition_unittest.include/pg/bus_i2c.h
  src/test/unit/timer_definition_unittest.include/pg/bus_spi.h
  src/test/unit/timer_definition_unittest.include/platform.h
Labels: UNITTEST

#6774 STM32F7X2 Move default battery meter source to board config
  src/main/target/STM32F7X2/config/NERO.config
  src/main/target/STM32F7X2/target.h
Labels: RN: IMPROVEMENT

#6765 Add default CAMERA_CONTROL pin for DALRCF722DUAL
  src/main/target/DALRCF722DUAL/target.c
Labels: RN: TARGET UPDATE

#6770 Handle NULL SPI instance case
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi_ll.c
  src/main/drivers/bus_spi_stdperiph.c
  src/main/target/STM32F7X2/target.h
Labels: Bugfix, RN: BUGFIX

#6775 Relocate G-force calculation.
  src/main/io/osd.c
Labels: Bugfix

#6742 defaults to improve yaw behaviour, ITermWindupPointInv already define…
  src/main/config/config_unittest.h
  src/main/fc/core.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: RN: IMPROVEMENT

#6781 Add target UAVPNG030MINI for the UAVP-NG HW-0.30-mini board
  src/main/target/UAVPNG030MINI/target.c
  src/main/target/UAVPNG030MINI/target.h
  src/main/target/UAVPNG030MINI/target.mk
Labels: RN: NEW TARGET

#6760 Fixing a wrong defintion of TARGET in the test Makefile.
  src/test/Makefile
Labels: UNITTEST

#6757 add some PR links to 3.5 and 3.4 release notes
  docs/Release Notes/Betaflight 3.4 Release Notes.md
  docs/Release Notes/Betaflight 3.5 Release Notes.md
Labels: Documentation update

#6697 Add CLI validation of parameters and print a corrupted value message
  src/main/interface/cli.c
Labels: RN: IMPROVEMENT

#6672 fix building guide for all OS's
  docs/development/Building in Eclipse.md
  docs/development/Building in Fedora.md
  docs/development/Building in Mac OS X.md
  docs/development/Building in Ubuntu.md
  docs/development/Building in Windows.md
  docs/development/assets/building-in-eclipse/checkout-betaflight-001.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-002.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-003.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-004.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-005.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-006.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-007.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-008.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-009.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-010.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-011.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-012.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-013.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-014.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-015.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-016.PNG
  docs/development/assets/building-in-eclipse/checkout-betaflight-017.PNG
Labels: Documentation update

#6447 Enable Vario on targets that support barometers
  src/main/cms/cms_menu_osd.c
  src/main/flight/position.c
  src/main/flight/position.h
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/target/common_post.h
  src/main/target/common_pre.h
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/hott.c
  src/main/telemetry/ibus_shared.c
  src/main/telemetry/jetiexbus.c
Labels: RN: IMPROVEMENT

#6793 Fix CRSF telmetry GPS speed calculation
  src/main/telemetry/crsf.c
  src/test/unit/telemetry_crsf_unittest.cc
Labels: RN: BUGFIX

#6800 Added long-standing camera control pin on the SPRF7DUAL
  src/main/target/SPRACINGF7DUAL/target.c
  src/main/target/SPRACINGF7DUAL/target.h
Labels: RN: TARGET UPDATE

#6794 Fixed changed defines.
  src/main/target/AG3X/target.h
  src/main/target/UAVPNG030MINI/target.h
Labels: RN: BUGFIX

#6796 Optimize in-flight adjustments to only process configured ranges
  src/main/fc/core.c
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_adjustments.h
  src/main/interface/cli.c
  src/main/interface/msp.c
  src/test/unit/cli_unittest.cc
Labels: RN: REFACTORING

#6798 Fix zero throttle deadband when using switched 3D modes
  src/main/flight/mixer.c
Labels: RN: BUGFIX, Testing Required

#6790 CrazyBee F3 target update
  src/main/target/CRAZYBEEF3FR/CRAZYBEEF3DX.mk
  src/main/target/CRAZYBEEF3FR/target.c
  src/main/target/CRAZYBEEF3FR/target.h
Labels: RN: TARGET UPDATE

#6514 Add support for ST LIS3MDL MEMS Magnetometer
  docs/Gps.md
  make/source.mk
  src/main/drivers/compass/compass_lis3mdl.c
  src/main/drivers/compass/compass_lis3mdl.h
  src/main/interface/settings.c
  src/main/sensors/compass.c
  src/main/sensors/compass.h
  src/main/target/AG3X/target.h
  src/main/target/AG3X/target.mk
  src/main/target/ALIENFLIGHTF4/target.h
  src/main/target/ALIENFLIGHTF4/target.mk
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/ALIENFLIGHTNGF7/target.mk
  src/main/target/ALIENWHOOP/target.h
  src/main/target/ALIENWHOOP/target.mk
  src/main/target/BETAFLIGHTF4/target.h
  src/main/target/BETAFLIGHTF4/target.mk
  src/main/target/BLUEJAYF4/target.h
  src/main/target/BLUEJAYF4/target.mk
  src/main/target/DALRCF405/target.h
  src/main/target/DALRCF405/target.mk
  src/main/target/DALRCF722DUAL/target.h
  src/main/target/DALRCF722DUAL/target.mk
  src/main/target/F4BY/target.h
  src/main/target/F4BY/target.mk
  src/main/target/KAKUTEF4/target.h
  src/main/target/KAKUTEF4/target.mk
  src/main/target/KAKUTEF7/target.h
  src/main/target/KAKUTEF7/target.mk
  src/main/target/MATEKF405/target.h
  src/main/target/MATEKF405/target.mk
  src/main/target/MATEKF722/target.h
  src/main/target/MATEKF722/target.mk
  src/main/target/MULTIFLITEPICO/target.mk
  src/main/target/NUCLEOF7/target.h
  src/main/target/NUCLEOF7/target.mk
  src/main/target/NUCLEOF722/target.h
  src/main/target/NUCLEOF722/target.mk
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF4/target.mk
  src/main/target/OMNIBUSF4FW/target.h
  src/main/target/OMNIBUSF4FW/target.mk
  src/main/target/OMNIBUSF7/target.h
  src/main/target/OMNIBUSF7/target.mk
  src/main/target/OMNINXT/target.h
  src/main/target/OMNINXT/target.mk
  src/main/target/SKYZONEF405/target.h
  src/main/target/SKYZONEF405/target.mk
  src/main/target/SPEEDYBEEF4/target.h
  src/main/target/SPEEDYBEEF4/target.mk
  src/main/target/SPRACINGF4EVO/target.h
  src/main/target/SPRACINGF4EVO/target.mk
  src/main/target/SPRACINGF7DUAL/target.h
  src/main/target/SPRACINGF7DUAL/target.mk
  src/main/target/STM32F7X2/target.h
  src/main/target/YUPIF7/target.h
  src/main/target/YUPIF7/target.mk
Labels: RN: IMPROVEMENT

#6797 Made CLI error messages consistent.
  src/main/interface/cli.c
Labels: RN: IMPROVEMENT

#6801 Delete outdated or bogus DMA related defs
  src/main/target/MIDELICF3/target.h
  src/main/target/SPRACINGF7DUAL/target.h
  src/main/target/UAVPNG030MINI/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6748 Improved pid_unittests
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/test/unit/pid_unittest.cc
Labels: UNITTEST

#6811 Remove stale RCC defs
  src/main/target/MATEKF411RX/target.h
  src/main/target/MIDELICF3/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6807 Remove outdated ws2811 defs
  src/main/target/ISHAPEDF3/target.h
  src/main/target/SITL/target.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/TINYFISH/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6806 Fix rssi logging for fport.
  src/main/blackbox/blackbox.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/test/unit/blackbox_unittest.cc
Labels: RN: BUGFIX

#6768 Jeti telemetry: add GPS values and update others
  src/main/telemetry/jetiexbus.c
Labels: RN: IMPROVEMENT

#6813 Fix RSSI_ADC pin defines
  src/main/target/ANYFCF7/target.h
  src/main/target/MOTOLABF4/target.h
  src/main/target/NUCLEOF7/target.h
  src/main/target/NUCLEOF722/target.h
  src/main/target/YUPIF4/target.h
  src/main/target/YUPIF7/target.h
Labels: RN: BUGFIX

#6812 Remove stale RCC defs (Part2)
  src/main/target/AIKONF4/target.h
  src/main/target/BEEROTORF4/target.h
  src/main/target/BETAFLIGHTF4/target.h
  src/main/target/CHEBUZZF3/target.h
  src/main/target/CLRACINGF4/target.h
  src/main/target/COLIBRI/target.h
  src/main/target/ELLE0/target.h
  src/main/target/F4BY/target.h
  src/main/target/FRSKYF4/target.h
  src/main/target/FURYF4/target.h
  src/main/target/KAKUTEF4/target.h
  src/main/target/KIWIF4/target.h
  src/main/target/MOTOLABF4/target.h
  src/main/target/PYRODRONEF4/target.h
  src/main/target/REVO/target.h
  src/main/target/REVOLT/target.h
  src/main/target/RG_SSD_F3/target.h
  src/main/target/SPARKY2/target.h
  src/main/target/UAVPNG030MINI/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6788 Refactor USB toward generic target
  src/main/drivers/usb_io.c
  src/main/interface/cli.c
  src/main/pg/usb.c
  src/main/pg/usb.h
  src/main/target/common_defaults_post.h
Labels: RN: IMPROVEMENT

#6814 UAVPNG030MINI: Update some defs
  src/main/target/UAVPNG030MINI/target.h
Labels: RN: TARGET UPDATE

#6815 Fixed flash overflow in SPRACINGF3MINI for 3.5.
  src/main/target/SPRACINGF3MINI/target.h
Labels: Applied to Branch, Needs entry in Release Notes, RN: TARGET UPDATE

#6822 OMNIBUSF7 variants: Move board specifics to config.c
  src/main/target/OMNIBUSF7/config.c
  src/main/target/OMNIBUSF7/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6821 NOX: Fix esc serial pacer timer def
  src/main/target/NOX/target.h
Labels: Bugfix, RN: TARGET UPDATE

#6820 STM32F4DISCOVERY: Fix esc serial pacer timer def
  src/main/target/STM32F4DISCOVERY/target.h
Labels: Bugfix, RN: TARGET UPDATE

#6819 WORMFC: Fix esc serial pacer timer def
  src/main/target/WORMFC/target.h
Labels: Bugfix, RN: TARGET UPDATE

#6818 KAKUTEF7: Move board specific def to config.c
  src/main/target/KAKUTEF7/config.c
  src/main/target/KAKUTEF7/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6817 YUPIF7: Fix gyro exti def
  src/main/target/YUPIF7/target.h
Labels: RN: TARGET UPDATE

#6824 MIDELICF3: Fix esc serial pacer timer def
  src/main/target/MIDELICF3/target.h
Labels: Bugfix, RN: TARGET UPDATE

#6764 Avoid inactive telemetry port from being registered as a displayport …
  src/main/telemetry/crsf.c
  src/main/telemetry/hott.c
Labels: Bugfix, RN: BUGFIX, Testing Required

#6831 SPRACINGF4EVO: Remove stale/bogus gyro exti def, add a legit one
  src/main/target/SPRACINGF4EVO/target.h
Labels: RN: TARGET UPDATE

#6827 MOTOLABF4 & KISSFCV2F7: Change BOARD_HAS_VOLTAGE_DIVIDER to DEFAULT_VOLTAGE_METER_SOURCE
  src/main/target/KISSFCV2F7/target.h
  src/main/target/MOTOLABF4/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6826 SPRACINGF4NEO: Remove already moved board specific defs from target.h
  src/main/target/SPRACINGF4NEO/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6832 COLIBRI_RACE: Move board specifics out of target.h
  src/main/target/COLIBRI_RACE/bst.h
  src/main/target/COLIBRI_RACE/bus_bst_stm32f30x.c
  src/main/target/COLIBRI_RACE/config.c
  src/main/target/COLIBRI_RACE/target.c
  src/main/target/COLIBRI_RACE/target.h
Labels: RN: TARGET UPDATE

#6767 Jeti receiver doesnt need a resistor anymore
  src/main/rx/jetiexbus.c
Labels: RN: IMPROVEMENT

#6779 Added SPEDIX F4 target
  docs/boards/Board - SPEDIXF4.md
  docs/boards/images/spedixf4-top.png
  src/main/target/SPEDIXF4/config.c
  src/main/target/SPEDIXF4/target.c
  src/main/target/SPEDIXF4/target.h
  src/main/target/SPEDIXF4/target.mk
Labels: RN: NEW TARGET

#6787 Handle NULL SPI instance in spiBusSetInstance
  src/main/drivers/accgyro/accgyro_mpu.c
Labels: RN: BUGFIX

#6804 SDCARD: Use unified clock specs, remove per target specs.
  src/main/drivers/accgyro/accgyro_spi_icm20689.c
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
  src/main/drivers/bus_spi.h
  src/main/drivers/sdcard.c
  src/main/target/ALIENFLIGHTF4/target.h
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/ANYFCF7/target.h
  src/main/target/BEEROTORF4/target.h
  src/main/target/BETAFLIGHTF3/target.h
  src/main/target/BLUEJAYF4/target.h
  src/main/target/CHEBUZZF3/target.h
  src/main/target/CLRACINGF4/target.h
  src/main/target/CLRACINGF7/target.h
  src/main/target/F4BY/target.h
  src/main/target/FISHDRONEF4/target.h
  src/main/target/FRSKYF3/target.h
  src/main/target/FRSKYF4/target.h
  src/main/target/FURYF3/target.h
  src/main/target/FURYF4/target.h
  src/main/target/FURYF7/target.h
  src/main/target/KAKUTEF7/target.h
  src/main/target/KIWIF4/target.h
  src/main/target/KROOZX/target.h
  src/main/target/LUX_RACE/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/MATEKF722/target.h
  src/main/target/MIDELICF3/target.h
  src/main/target/MOTOLABF4/target.h
  src/main/target/NERO/target.h
  src/main/target/NUCLEOF446RE/target.h
  src/main/target/NUCLEOF7/target.h
  src/main/target/NUCLEOF722/target.h
  src/main/target/OMNIBUS/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/REVO/target.h
  src/main/target/RG_SSD_F3/target.h
  src/main/target/SIRINFPV/target.h
  src/main/target/SPRACINGF3EVO/target.h
  src/main/target/SPRACINGF3MINI/target.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/SPRACINGF4EVO/target.h
  src/main/target/SPRACINGF4NEO/target.h
  src/main/target/SPRACINGF7DUAL/target.h
  src/main/target/STM32F3DISCOVERY/target.h
  src/main/target/STM32F4DISCOVERY/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/UAVPNG030MINI/target.h
  src/main/target/VRRACE/target.h
  src/main/target/WORMFC/target.h
  src/main/target/YUPIF4/target.h
Labels: Cleanup, RN: IMPROVEMENT

#6823 SPRACINGF7DUAL: Move board specific to config.c
  src/main/target/SPRACINGF7DUAL/config.c
  src/main/target/SPRACINGF7DUAL/target.h
Labels: Cleanup, RN: TARGET UPDATE

#6838 Remove unused IMU parameters
  src/main/flight/imu.c
  src/main/flight/imu.h
  src/main/interface/settings.c
Labels: RN: REFACTORING

#6792 Increase MAX_ADJUSTMENT_RANGE_COUNT from 15 to 30
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_adjustments.h
Labels: RN: IMPROVEMENT

#6784 GENERIC Fix origins for timer channel list
  src/main/interface/cli.c
  src/main/pg/timerio.h
  src/main/target/common_defaults_post.h
Labels: RN: IMPROVEMENT

#6845 SDCARD: Refactor sdcard.c to use busDevice_t
  src/main/drivers/sdcard.c
Labels: RN: IMPROVEMENT
