Repository betaflight/betaflight, pull requests merged in 2018-12, with the labels that each got.

#7116 [CLI] Refactor status command to print things in more sensible order
  src/main/interface/cli.c
  src/main/platform.h
  src/test/unit/platform.h
Labels: RN: IMPROVEMENT

#7154 Fixed build dependency on EXTI for BMI160 driver.
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
Labels: RN: BUGFIX

#7148 Added missing osd_warn_rc_smoothing in settings
  src/main/interface/settings.c
Labels: RN: IMPROVEMENT

#7162 Blink GPS indicator on OSD when numsats is lower than minimum configu…
  src/main/io/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#7151 [SDCARD,MSC] Switch USBD storage fops table according to sdcard config
  src/main/drivers/usb_msc_f4xx.c
  src/main/drivers/usb_msc_f7xx.c
  src/main/msc/usbd_storage.h
  src/main/msc/usbd_storage_sd_spi.c
Labels: RN: BUGFIX

#7158 Arm prevention if Rescue is activated
  src/main/fc/core.c
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/flight/gps_rescue.c
  src/test/Makefile
  src/test/unit/arming_prevention_unittest.cc
Labels: RN: IMPROVEMENT

#7160 Calculate distance flown with a speed threshold
  src/main/io/gps.c
Labels: RN: IMPROVEMENT

#7159 GPS Rescue: check failsafe procedure when preventing arming
  src/main/fc/core.c
Labels: RN: IMPROVEMENT

#7169 [F411,SYSTEM] Delete bogus clock PLL parameter table entry
  src/main/target/system_stm32f4xx.c
Labels: RN: BUGFIX

#7078 Cascaded dynamic notches.
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
  src/main/interface/settings.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_filter_impl.h
  src/main/sensors/gyroanalyse.c
  src/main/sensors/gyroanalyse.h
Labels: RN: MINOR FEATURE

#7172 OSD GPS indicator blinks when numSats is below 5
  src/main/io/osd.c
Labels: RN: IMPROVEMENT

#7170 fix writeGpsPositionPrameToBST
  src/main/target/COLIBRI_RACE/i2c_bst.c
Labels: RN: BUGFIX

#7163 Numeric Vario calculated with GPS altitude
  src/main/flight/position.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/test/unit/flight_imu_unittest.cc
Labels: RN: IMPROVEMENT

#7157 Fix SmartAudio 'looping' after vtx_freq in MHz set
  src/main/io/vtx_smartaudio.c
Labels: RN: BUGFIX

#7176 Added postponement note for Betaflight 4.0.
  README.md
Labels: Documentation update

#7178 Fixed markdown for URL in README.
  README.md
Labels: Documentation update

#7175 CLRACING F7 add I2C support, and remove blackbox flash define
  src/main/target/CLRACINGF7/CLRACINGF7.md
  src/main/target/CLRACINGF7/CL_RACINGF7.md
  src/main/target/CLRACINGF7/target.h
  src/main/target/CLRACINGF7/target.mk
Labels: RN: TARGET UPDATE

#7183 Total Distance renamed to Flight Distance
  src/main/cms/cms_menu_osd.c
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#7177 Fix non-chronological element ordering.
  src/main/io/osd.h
Labels: Needs coordination with betaflight-configurator, RN: BUGFIX

#7166 [SYSTEM] Use RTC backup register for persistent storage
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  src/main/drivers/persistent.c
  src/main/drivers/persistent.h
  src/main/drivers/system.h
  src/main/drivers/system_stm32f4xx.c
  src/main/drivers/system_stm32f7xx.c
  src/main/startup/startup_stm32f40xx.s
  src/main/startup/startup_stm32f411xe.s
  src/main/startup/startup_stm32f446xx.s
  src/main/startup/startup_stm32f722xx.s
  src/main/startup/startup_stm32f745xx.s
  src/main/startup/startup_stm32f746xx.s
  src/main/startup/startup_stm32f765xx.s
  src/main/target/stm32f7xx_hal_conf.h
  src/main/target/system_stm32f4xx.c
  src/main/target/system_stm32f7xx.c
  src/main/vcpf4/usb_bsp.c
Labels: RN: IMPROVEMENT

#7188 Fix OSD throttle position element calculation and add 3D support
  src/main/fc/core.c
  src/main/fc/core.h
  src/main/io/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#7187 Launch Control: increase throttle trigger percent max to 90
  src/main/cms/cms_menu_imu.c
  src/main/fc/core.h
  src/main/interface/settings.c
Labels: RN: IMPROVEMENT

#7198 Add fix for issue 7196 OSD active elements menu moves items left by one
  src/main/cms/cms.c
Labels: RN: BUGFIX

#7200 Fix smartport GPS altitude
  src/main/telemetry/smartport.c
Labels: RN: BUGFIX

#7205 Ensure debug symbols are generated for startup code when needed.
  Makefile
Labels: Build System Improvement

#7184 TARGET: Add support code for EXF722DUAL board.
  docs/boards/Board - EXF722DUAL.md
  docs/boards/images/EXF722DUAL-bottom.png
  docs/boards/images/EXF722DUAL-top.png
  src/main/target/EXF722DUAL/target.c
  src/main/target/EXF722DUAL/target.h
  src/main/target/EXF722DUAL/target.mk
Labels: RN: NEW TARGET

#7190 [SPI] Introduce per device pin pre-init
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/barometer/barometer_bmp280.c
  src/main/drivers/barometer/barometer_ms5611.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_config.c
  src/main/drivers/compass/compass_ak8963.c
  src/main/drivers/flash.c
  src/main/drivers/flash.h
  src/main/drivers/io.c
  src/main/drivers/max7456.c
  src/main/drivers/max7456.h
  src/main/drivers/resource.c
  src/main/drivers/resource.h
  src/main/drivers/rx/rx_spi.c
  src/main/drivers/rx/rx_spi.h
  src/main/drivers/sdcard.c
  src/main/drivers/sdcard.h
  src/main/drivers/sdcard_impl.h
  src/main/drivers/sdcard_sdio_baremetal.c
  src/main/drivers/sdcard_spi.c
  src/main/fc/init.c
  src/main/interface/cli.c
  src/main/interface/settings.c
  src/main/pg/bus_spi.c
  src/main/pg/bus_spi.h
  src/main/pg/max7456.c
  src/main/pg/max7456.h
  src/main/sensors/barometer.c
  src/main/sensors/barometer.h
  src/main/sensors/compass.c
  src/main/sensors/compass.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/initialisation.c
  src/main/sensors/initialisation.h
  src/main/target/ALIENFLIGHTF3/initialisation.c
  src/main/target/CJMCU/initialisation.c
  src/main/target/FRSKYF3/target.h
  src/main/target/KAKUTEF4/config.c
  src/main/target/NAZE/initialisation.c
  src/main/target/STM32F7X2/config/NERO.config
  src/main/target/common_post.h
  src/test/unit/baro_bmp280_unittest.cc
  src/test/unit/baro_ms5611_unittest.cc
Labels: RN: IMPROVEMENT

#6432 For discussion: Integrated yaw control
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/interface/settings.c
  src/main/target/common_pre.h
Labels: RN: MINOR FEATURE

#6870 Update Baro driver for generic target
  src/main/drivers/barometer/barometer.h
  src/main/sensors/barometer.c
  src/main/target/AG3X/target.h
  src/main/target/AIRHEROF3/target.h
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/ALIENWHOOP/target.h
  src/main/target/DOGE/target.h
  src/main/target/FRSKYF4/target.h
  src/main/target/NOX/target.h
  src/main/target/OMNIBUS/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF4FW/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/OMNINXT/target.h
  src/main/target/REVO/target.h
  src/main/target/UAVPNG030MINI/target.h
  src/main/target/WORMFC/target.h
  src/main/target/common_defaults_post.h
Labels: RN: REFACTORING

#7129 Add target OMNIBUSF4V6
  src/main/target/OMNIBUSF4FW/OMNIBUSF4V6.mk
  src/main/target/OMNIBUSF4FW/config.c
  src/main/target/OMNIBUSF4FW/target.c
  src/main/target/OMNIBUSF4FW/target.h
Labels: RN: NEW TARGET

#6869 Update Mag driver for generic target
  src/main/drivers/compass/compass.h
  src/main/sensors/compass.c
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/common_defaults_post.h
Labels: RN: REFACTORING

#7215 Add OSD Active Elements menu update for OSD Profiles
  src/main/cms/cms.c
  src/main/cms/cms.h
  src/main/cms/cms_menu_osd.c
  src/main/io/osd.h
Labels: RN: IMPROVEMENT

#7210 Implemented SPI SPEKTRUM protocol
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/drivers/rx/rx_cyrf6936.c
  src/main/drivers/rx/rx_cyrf6936.h
  src/main/interface/cli.c
  src/main/interface/settings.c
  src/main/pg/pg_ids.h
  src/main/rx/cyrf6936_spektrum.c
  src/main/rx/cyrf6936_spektrum.h
  src/main/rx/rx_spi.c
  src/main/rx/rx_spi.h
  src/test/Makefile
  src/test/unit/rx_spi_spektrum_unittest.cc
Labels: RN: MAJOR FEATURE

#6805 Update STM32F7X2 generic target
  src/main/pg/gyrodev.c
  src/main/target/STM32F7X2/config/ALIENFLIGHTNGF7.config
  src/main/target/STM32F7X2/config/ALIENFLIGHTNGF7_Dual.config
  src/main/target/STM32F7X2/config/NERO.config
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32F7X2/target.mk
  src/main/target/common_defaults_post.h
Labels: RN: IMPROVEMENT, Ready to Merge

#7230 Fix OMNIBUSF4V6 Gyro2(External) align
  src/main/target/OMNIBUSF4FW/target.h
Labels: RN: TARGET UPDATE

#7227 Do call gyroPreInitsensor for gyro 2 even if it is not activated
  src/main/sensors/gyro.c
Labels: RN: BUGFIX

#7233 Incremented maintenance branch version to 3.5.5.
  src/main/build/version.h
Labels: Applied to Branch, Householding

#7156 MSC on-board flash: Persist RTC across reboot and use as file timestamp
  src/main/common/time.c
  src/main/common/time.h
  src/main/drivers/persistent.h
  src/main/drivers/usb_msc.h
  src/main/drivers/usb_msc_f4xx.c
  src/main/drivers/usb_msc_f7xx.c
  src/main/fc/init.c
  src/main/interface/cli.c
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/msc/emfat_file.c
  src/main/msc/usbd_storage.c
  src/main/msc/usbd_storage.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
  src/test/unit/osd_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#7231 Made timer tests respect 'USE_TIMER_MGMT'.
  src/main/drivers/serial.h
  src/test/Makefile
  src/test/unit/timer_definition_unittest.cc
Labels: UNITTEST

#7199 Speed up the first boot on generic firmware
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/init.c
  src/main/target/common_post.h
Labels: RN: IMPROVEMENT

#7222 STM32F405 Generic target
  src/main/target/STM32F405/config/ALIENFLIGHTNGF4.config
  src/main/target/STM32F405/target.c
  src/main/target/STM32F405/target.h
  src/main/target/STM32F405/target.mk
Labels: RN: NEW TARGET, Ready to Merge

#7240 Update L3GD20 gyro to modern gyro API.
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/accgyro/accgyro_spi_l3gd20.c
  src/main/drivers/accgyro/accgyro_spi_l3gd20.h
  src/main/drivers/accgyro_legacy/accgyro_lsm303dlhc.c
  src/main/sensors/gyro.c
  src/main/target/common_post.h
Labels: RN: IMPROVEMENT

#7242 Fixed gyro CS pin count in CLI.
  src/main/interface/cli.c
Labels: RN: BUGFIX

#7232 Fixed NULL dereference in 'printResource'.
  src/main/interface/cli.c
Labels: RN: BUGFIX

#7254 Sanity checks flyaway/stalled only done in crosstrack phase
  src/main/flight/gps_rescue.c
Labels: RN: BUGFIX

#7244 Reset GPS Rescue max altitude and distance on arming
  src/main/flight/gps_rescue.c
Labels: RN: BUGFIX

#7250 Added 'small_angle' indicator to OSD flip arrow.
  src/main/fc/core.c
  src/main/flight/imu.c
  src/main/flight/imu.h
  src/main/io/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#7246 Moved 'mcoInit()' to after 'OverclockRebootIfNecessary()' to have it execute only once.
  src/main/fc/init.c
Labels: RN: IMPROVEMENT

#7248 Add CAMERA_CONTROL_PIN define for DALRCF722DUAL
  src/main/target/DALRCF722DUAL/target.h
Labels: Applied to Branch, RN: TARGET UPDATE

#7265 Fixed minimum satellite detection.
  src/main/flight/gps_rescue.c
Labels: Applied to Branch, RN: BUGFIX

#7256 Add GPS rescue unreliable now warning in OSD
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
Labels: RN: IMPROVEMENT

#7269 Add missing OSD elements to OSD active elements menu
  src/main/cms/cms_menu_osd.c
Labels: RN: IMPROVEMENT

#7259 Add MPU6000 to generic targets
  src/main/target/STM32F405/target.h
  src/main/target/STM32F7X2/target.h
Labels: RN: TARGET UPDATE, Ready to Merge

#7272 [F3, ESCSERIAL] Conditionalize SimonK handling from escserial and drop it from F3
  src/main/drivers/serial_escserial.c
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#7267 Do not disable the vario feature if GPS is enabled.
  src/main/target/common_post.h
Labels: RN: IMPROVEMENT

#7266 Fix MacOS on-board flash MSC mode for F7 (HAL)
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c
Labels: RN: BUGFIX, Tested

#7263 add Variant Target CrazyBeeF4 Pro series
  docs/boards/Board - CrazyBeeF4DXPro.md
  docs/boards/Board - CrazyBeeF4FRPro.md
  docs/boards/Board - CrazyBeeF4FSPro.md
  docs/boards/images/CrazyBeeF4DXProBot.jpg
  docs/boards/images/CrazyBeeF4DXProTop.jpg
  docs/boards/images/CrazyBeeF4FRProBot.jpg
  docs/boards/images/CrazyBeeF4FRProTop.jpg
  docs/boards/images/CrazyBeeF4FSProBot.jpg
  docs/boards/images/CrazyBeeF4FSProTop.jpg
  src/main/target/MATEKF411RX/CRAZYBEEF4DX.mk
  src/main/target/MATEKF411RX/CRAZYBEEF4FR.mk
  src/main/target/MATEKF411RX/CRAZYBEEF4FS.mk
  src/main/target/MATEKF411RX/target.h
  src/main/target/MATEKF411RX/target.mk
Labels: RN: NEW TARGET

#7261 add support for BERGMICRO_W25Q32
  src/main/drivers/flash_m25p16.c
Labels: RN: IMPROVEMENT

#7257 Add flash definition to MATEKF722SE target
  src/main/target/MATEKF722SE/target.h
  src/main/target/MATEKF722SE/target.mk
Labels: RN: TARGET UPDATE

#7260 Make I2C pullups and overclocking configurable for generic targets
  src/main/interface/settings.c
  src/main/target/STM32F405/config/ALIENFLIGHTNGF4.config
  src/main/target/STM32F7X2/config/ALIENFLIGHTNGF7.config
  src/main/target/STM32F7X2/config/ALIENFLIGHTNGF7_Dual.config
Labels: RN: IMPROVEMENT

#7274 [F3, SERIAL4WAY] Drop SimonK boot loader for from serial_4way for F3
  src/main/io/serial_4way.h
  src/main/io/serial_4way_stk500v2.c
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: Needs entry in Release Notes, RN: IMPROVEMENT

#7241 Updated STM32F3DISCOVERY target to support on-board gyro/acc.
  src/main/target/STM32F3DISCOVERY/target.h
  src/main/target/STM32F3DISCOVERY/target.mk
Labels: RN: TARGET UPDATE

#7276 Prioritize pre-flight OSD warnings
  src/main/io/osd.c
Labels: RN: SAFETY IMPROVEMENT

#6528 Fix OSD Slave MSP
  src/main/msp/msp_serial.c
Labels: RN: IMPROVEMENT

#7278 Added sensor for core temperature to SmartPort.
  src/main/sensors/adcinternal.c
  src/main/telemetry/smartport.c
  src/main/telemetry/telemetry.h
Labels: RN: IMPROVEMENT

#7290 Secure Travis Slack notifications to betaflight/betaflight
  .travis.yml
Labels: Build System Improvement

#7293 Changed to new (and private) API keys to get rid of forks using stale published API keys.
  .travis.yml
Labels: Build System Improvement

#7280 Fixed MATEKF411RX after #7263.
  src/main/target/MATEKF411RX/target.h
Labels: RN: TARGET UPDATE

#7149 KISSCC: Fix soft serial on TLM pad
  src/main/target/KISSFC/target.c
  src/main/target/KISSFC/target.h
Labels: RN: TARGET UPDATE

#7298 Second attempt at adding secure integrations to travis.
  .travis.yml
Labels: Build System Improvement

#7300 Third attempt at adding secure integrations to travis.
  .travis.yml
Labels: Build System Improvement

#7302 Fourth attempt at adding secure integrations to travis.
  .travis.yml
Labels: Build System Improvement

#7255 Increased Vbat precision
  src/main/cms/cms_menu_power.c
  src/main/interface/cli.c
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/main/io/dashboard.c
  src/main/io/osd.c
  src/main/rx/cc2500_frsky_d.c
  src/main/rx/cc2500_frsky_x.c
  src/main/rx/cyrf6936_spektrum.c
  src/main/rx/flysky.c
  src/main/sensors/battery.c
  src/main/sensors/battery.h
  src/main/sensors/voltage.c
  src/main/sensors/voltage.h
  src/main/target/BEEBRAIN_V2F/config.c
  src/main/target/COLIBRI_RACE/i2c_bst.c
  src/main/target/MULTIFLITEPICO/config.c
  src/main/target/RG_SSD_F3/config.c
  src/main/telemetry/crsf.c
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/hott.c
  src/main/telemetry/ibus_shared.c
  src/main/telemetry/jetiexbus.c
  src/main/telemetry/ltm.c
  src/main/telemetry/mavlink.c
  src/main/telemetry/smartport.c
  src/main/telemetry/srxl.c
  src/test/unit/osd_unittest.cc
  src/test/unit/telemetry_crsf_msp_unittest.cc
  src/test/unit/telemetry_crsf_unittest.cc
  src/test/unit/telemetry_hott_unittest.cc
  src/test/unit/telemetry_ibus_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#7289 Add STM32F411DISCOVERY target
  docs/boards/Board - STM32Discovery.md
  src/main/target/STM32F411DISCOVERY/target.c
  src/main/target/STM32F411DISCOVERY/target.h
  src/main/target/STM32F411DISCOVERY/target.mk
Labels: RN: NEW TARGET

#7310 Updated policy on allowing 'if' without braces.
  docs/development/CodingStyle.md
Labels: Documentation update, For Discussion

#7311 Added rule for trailing comma in enums.
  docs/development/CodingStyle.md
Labels: Documentation update, For Discussion

#7308 Added note about embargo for new targets in 4.0.
  .github/pull_request_template.md
  README.md
Labels: Householding
