Repository betaflight/betaflight, pull requests merged in 2018-02, with the labels that each got.

#5118 DASHBOARD Separate pg related to pg directory
  make/source.mk
  src/main/drivers/display_ug2864hsweg01.c
  src/main/interface/settings.c
  src/main/io/dashboard.c
  src/main/io/dashboard.h
  src/main/pg/dashboard.c
  src/main/pg/dashboard.h
Labels: RN: BUGFIX

#5104 OMNIBUSF7* Revert ADC instance change
  src/main/target/OMNIBUSF7/target.h
Labels: RN: BUGFIX

#5151 Add support to Cypress S25FL128L flash memory
  src/main/drivers/flash_m25p16.c
Labels: RN: IMPROVEMENT

#5150 Update YupiF7 target
  src/main/target/YUPIF7/target.c
  src/main/target/YUPIF7/target.h
  src/main/target/YUPIF7/target.mk
Labels: RN: TARGET UPDATE

#3724 CMS power menu
  make/source.mk
  src/main/cms/cms_menu_builtin.c
  src/main/cms/cms_menu_misc.c
  src/main/cms/cms_menu_power.c
  src/main/cms/cms_menu_power.h
  src/main/interface/settings.c
  src/main/sensors/current.c
  src/main/sensors/current.h
  src/main/sensors/voltage.c
  src/main/sensors/voltage.h
Labels: RN: IMPROVEMENT

#5135 Corrected issue with telemetry init when battery cell estimation is undefined
  src/main/sensors/battery.c
  src/main/sensors/battery.h
  src/main/telemetry/crsf.c
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/mavlink.c
  src/main/telemetry/smartport.c
  src/test/unit/telemetry_crsf_msp_unittest.cc
  src/test/unit/telemetry_crsf_unittest.cc
Labels: RN: BUGFIX

#5152 Fixed OMNIBUS flash space issue.
  src/main/target/OMNIBUS/target.h
  src/main/target/common_fc_pre.h
Labels: RN: BUGFIX

#5156 Spektrum TM regression. Incomplete RPM/Voltage report corrected.
  src/main/telemetry/srxl.c
Labels: RN: BUGFIX, Ready to Merge

#5160 Fixed SPRACINGF3NEO flash size issue.
  src/main/target/SPRACINGF3NEO/target.h
Labels: RN: BUGFIX

#5148 Fix for #5117. Also, max character count was off by one.
  src/main/io/osd.c
Labels: RN: BUGFIX

#5098 DShot Make burst and non-burst runtime configurable
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/flight/mixer.c
  src/main/interface/settings.c
  src/main/target/BEEROTORF4/target.h
  src/main/target/BETAFLIGHTF3/target.h
  src/main/target/CLRACINGF4/target.h
  src/main/target/IMPULSERCF3/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/OMNIBUS/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/REVO/target.h
  src/main/target/common_fc_post.h
  src/main/target/common_fc_pre.h
Labels: RN: IMPROVEMENT

#5123 Implement getBoxIdState
  src/main/common/utils.h
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.h
  src/main/interface/msp_box.c
Labels: RN: IMPROVEMENT

#5108 PINIO Generic pin output driver
  make/source.mk
  src/main/drivers/pinio.c
  src/main/drivers/pinio.h
  src/main/drivers/resource.c
  src/main/drivers/resource.h
  src/main/fc/fc_init.c
  src/main/interface/cli.c
  src/main/interface/settings.c
  src/main/pg/pg_ids.h
  src/main/pg/pinio.c
  src/main/pg/pinio.h
  src/main/target/common_fc_pre.h
Labels: RN: MINOR FEATURE

#5140 Allow RX-only softserial
  src/main/io/serial.c
Labels: RN: BUGFIX

#5166 OMNIBUS Drop XBUS and MAVLINK in favor of FLASH & RAM
  src/main/target/OMNIBUS/target.h
Labels: RN: BUGFIX

#5165 Add proper conditional for XBUS
  src/main/rx/xbus.c
Labels: RN: BUGFIX

#4994 KN protocol over NRF24
  src/main/rx/nrf24_kn.c
  src/main/rx/nrf24_kn.h
  src/main/rx/rx_spi.c
  src/main/rx/rx_spi.h
Labels: RN: IMPROVEMENT, Rebase / Squash required

#5030 update jeti telemetry
  src/main/telemetry/jetiexbus.c
Labels: RN: IMPROVEMENT, Rebase / Squash required

#5167 Fixed DALRCF405 DMA assignments.
  src/main/target/DALRCF405/target.c
Labels: RN: BUGFIX

#5170 Fixed UART count for TINYBEEF3.
  src/main/target/SPRACINGF3MINI/target.h
Labels: RN: TARGET UPDATE, Tested

#5181 Spektrum iX12 adaption of CMS start screen.
  src/main/io/displayport_srxl.c
Labels: RN: IMPROVEMENT, Ready to Merge

#5144 Biquad RC+FIR2: Allow user to specify cutoff Hz parameter directly
  src/main/common/filter.c
  src/main/common/filter.h
  src/main/interface/settings.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: RN: IMPROVEMENT

#5191 Enable ESCSERIAL for MOTOLABF4 targets
  src/main/target/MOTOLABF4/target.c
  src/main/target/MOTOLABF4/target.h
Labels: RN: TARGET UPDATE

#5180 Disabled Dshot DMAR for CLRACINGF4.
  src/main/target/CLRACINGF4/target.h
Labels: RN: BUGFIX

#5175 Added Biquad RC + FIR2 filter to F3 targets.
  src/main/target/OMNIBUS/target.h
  src/main/target/RCEXPLORERF3/target.h
  src/main/target/SPRACINGF3EVO/target.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/common_fc_pre.h
Labels: RN: TARGET UPDATE

#5176 Disable runaway takeoff when crash-flip mode is active
  src/main/fc/fc_core.c
Labels: RN: BUGFIX

#5195 Fixed ordering of SPI RX protocols.
  src/main/interface/settings.c
  src/main/rx/rx_spi.h
Labels: RN: BUGFIX

#5185 Disarm when configurator sets ARMING_DISABLED_MSP arming disabled flag
  src/main/interface/msp.c
Labels: RN: BUGFIX

#5172 Runaway Takeoff Prevention - temporarily disable during configurator bench testing
  src/main/fc/fc_core.c
  src/main/fc/fc_core.h
  src/main/interface/msp.c
Labels: RN: BUGFIX

#5198 motorDevInit IOConfigGPIOAF instead of IOConfigGPIO
  src/main/drivers/pwm_output.c
Labels: BUG, RN: BUGFIX

#5216 Biquad RC+FIR2: Reverse interface settings DEFINE conditional
  src/main/interface/settings.c
Labels: RN: BUGFIX

#5205 Reactivate Runaway Takeoff Prevention after using crash-flip
  src/main/fc/fc_core.c
Labels: RN: SAFETY IMPROVEMENT

#5178 Fixed parameter group violations in `motorDevConfig_t`, incremented EEPROM config version before 3.3.0 release.
  src/main/config/config_eeprom.h
  src/main/drivers/pwm_output.h
  src/main/flight/mixer.c
Labels: RN: BUGFIX

#5179 Unified `BOX3DDISABLE` and `BOX3DONASWITCH` switches.
  src/main/fc/fc_core.c
  src/main/fc/fc_rc.c
  src/main/fc/rc_controls.c
  src/main/fc/rc_controls.h
  src/main/fc/rc_modes.h
  src/main/flight/mixer.c
  src/main/interface/msp_box.c
  src/main/interface/settings.c
  src/test/unit/arming_prevention_unittest.cc
Labels: RN: IMPROVEMENT

#5200 Change gyro_overflow_detect to use filtered instead of raw gyro data
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/sensors/gyro.c
Labels: RN: SAFETY IMPROVEMENT

#5226 YupiF7 - Correction of DMA conflict
  src/main/target/YUPIF7/target.c
Labels: RN: TARGET UPDATE

#5210 Adjustable overclock for F405 and F411
  src/main/drivers/max7456.c
  src/main/fc/config.c
  src/main/fc/fc_init.c
  src/main/interface/settings.c
  src/main/interface/settings.h
  src/main/startup/startup_stm32f411xe.s
  src/main/startup/startup_stm32f446xx.s
  src/main/target/common_fc_pre.h
  src/main/target/link/stm32_flash_split.ld
  src/main/target/system_stm32f4xx.c
  src/main/target/system_stm32f4xx.h
Labels: RN: BUGFIX, RN: MINOR FEATURE

#5222 Fixed problem with craft name overwriting elements in OSD.
  src/main/io/osd.c
Labels: RN: BUGFIX

#5208 PINIOBOX Separation of boxId and permanentId.
  src/main/fc/rc_modes.h
  src/main/interface/msp_box.c
  src/main/interface/msp_box.h
  src/main/interface/settings.c
  src/main/io/piniobox.c
  src/main/pg/piniobox.c
  src/main/pg/piniobox.h
Labels: RN: BUGFIX, Review Needed

#5217 Fixed motor order for KISSCC to match manual (QUADX1234).
  src/main/target/KISSFC/target.c
  src/main/target/KISSFC/target.h
Labels: RN: TARGET UPDATE

#5247 Removed duplicate legacy gyro_lpf validation from msp.c
  src/main/interface/msp.c
Labels: RN: BUGFIX

#5242 Spektrum CMS over TM performance increase.
  src/main/cms/cms.c
  src/main/cms/cms.h
  src/main/io/displayport_srxl.c
  src/main/io/displayport_srxl.h
  src/main/telemetry/srxl.c
Labels: RN: BUGFIX

#5236 Add gyro rate checking to runaway takeoff activation to improve bench testing
  src/main/fc/fc_core.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: RN: SAFETY IMPROVEMENT

#5239 Reordered arming disabled flags to give runaway takeoff a higher priority
  src/main/fc/fc_core.c
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
Labels: RN: BUGFIX

#5258 Makefile: fix clean_all trying to cleean SKIP_TARGETS
  Makefile
Labels: Bugfix

#5253 Change crash-flip OSD message to track actual state rather than switch
  src/main/io/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: BUGFIX

#5266 Optimize ledstip by disabling unassigned overlays
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
Labels: RN: BUGFIX

#5268 Fixed OSD warnings overlap to the right.
  src/main/fc/runtime_config.c
  src/main/io/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: BUGFIX

#5282 Fix 'fade' may be uninitialised warning in Spektrum RSSI handling.
  src/main/io/spektrum_rssi.c
Labels: RN: BUGFIX

#5281 SPRACINGF4EVO - Use ADC3 instead of ADC1
  src/main/target/SPRACINGF4EVO/target.h
Labels: RN: TARGET UPDATE

#5280 CF/BF - STMF72x - Ensure SRAM2 is unused and not part of 'RAM' linker section.
  src/main/target/link/stm32_flash_f722.ld
Labels: RN: BUGFIX

#5278 CF/BF - Fix incorrect ACC sensor name for ICM20608G.
  src/main/interface/settings.c
Labels: RN: BUGFIX

#5269 Fixed efficiency of FPort protocol.
  src/main/rx/fport.c
  src/main/rx/rx.c
Labels: RN: BUGFIX

#5291 Fix 3D on a switch throttle inversion/scale
  src/main/fc/fc_rc.c
Labels: RN: BUGFIX

#5288 Added MAX7456_SPI_CLOCK define and MAX7456_RESTORE_CLK to KAKUTEF4 target
  src/main/target/KAKUTEF4/target.h
Labels: Bugfix, RN: TARGET UPDATE

#5290 VTX low power on disarm correction
  src/main/io/vtx.c
Labels: RN: BUGFIX

#5284 Change gyro_overflow_detect to use filtered instead of raw gyro data - 2nd try
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/sensors/gyro.c
Labels: RN: SAFETY IMPROVEMENT

#5246 Add kalman filter to YupiF4
  src/main/target/YUPIF4/target.h
Labels: RN: TARGET UPDATE

#5299 Disable stick command processing while ARMING_DISABLED_RUNAWAY_TAKEOFF is set
  src/main/fc/rc_controls.c
  src/test/unit/rc_controls_unittest.cc
Labels: RN: BUGFIX

#5296 disable runcam camera control in runaway takeoff status
  src/main/io/rcdevice_cam.c
  src/test/unit/rcdevice_unittest.cc
Labels: RN: BUGFIX

#5339 Added missing `osd_stat_rtc_date_time` to CLI.
  src/main/interface/settings.c
Labels: RN: BUGFIX
