Repository betaflight/betaflight, pull requests merged in 2018-04, with the labels that each got.

#5578 Removed code marked as legacy from OMNIBUSF4.
  src/main/target/OMNIBUSF4/target.h
Labels: RN: TARGET UPDATE

#5602 LEDs on NucleoF7 are inverted.
  src/main/target/NUCLEOF7/target.h
Labels: RN: BUGFIX

#5598 Fix PWM rx 100% CPU load
  src/main/rx/rx.c
Labels: RN: BUGFIX

#5606 Fix PWM rx 100% CPU load in 3.3
  src/main/rx/rx.c
Labels: Applied to Branch, RN: BUGFIX

#5596 Add CDC+HID for F7
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC_HID/Inc/usbd_cdc_hid.h
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC_HID/Src/usbd_cdc_hid.c
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc/usbd_hid.h
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
  make/mcu/STM32F7.mk
  src/main/drivers/serial_usb_vcp.c
  src/main/fc/fc_tasks.c
  src/main/target/common_fc_post.h
  src/main/target/common_fc_pre.h
  src/main/vcp_hal/usbd_cdc_interface.c
  src/main/vcp_hal/usbd_conf.c
  src/main/vcp_hal/usbd_conf.h
  src/main/vcp_hal/usbd_desc.c
Labels: RN: MAJOR FEATURE

#5595 HotFix for sdcard driver on F7 when using DMA for TX
  src/main/drivers/sdcard.c
Labels: RN: BUGFIX, Testing Required

#5594 Change crashflip to normal on disarm
  src/main/fc/fc_core.c
Labels: RN: IMPROVEMENT

#5603 Simplify compilation of F4 SDIO enabled targets.
  make/mcu/STM32F4.mk
  make/source.mk
  src/main/target/WORMFC/target.mk
Labels: RN: IMPROVEMENT

#5465 Corrected CLI to include vtx_band=0 to enable freq selection mode.
  src/main/drivers/vtx_common.h
  src/main/interface/settings.c
Labels: RN: BUGFIX

#5613 Fix arming-releated IBUS telemetry bug
  src/main/telemetry/ibus_shared.c
Labels: RN: BUGFIX

#5604 Add SDIO (SDMMC) driver for F7 targets.
  make/mcu/STM32F7.mk
  src/main/drivers/sdio_f7xx.c
  src/main/drivers/sdmmc_sdio.h
Labels: RN: MINOR FEATURE

#5583 Added ESC temperature warning, fixed ESC warning issue with motor count > 8.
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
Labels: RN: IMPROVEMENT

#5193 Refactor startup assembly and reboot flags
  src/main/drivers/system.h
  src/main/drivers/system_stm32f4xx.c
  src/main/startup/startup_stm32f40xx.s
  src/main/startup/startup_stm32f411xe.s
  src/main/target/common_fc_pre.h
  src/main/target/link/stm32_flash_f405.ld
  src/main/target/link/stm32_flash_f405_opbl.ld
  src/main/target/link/stm32_flash_f411.ld
  src/main/target/link/stm32_flash_f411_opbl.ld
  src/main/target/link/stm32_flash_f446.ld
  src/main/target/link/stm32_flash_split.ld
  src/main/target/system_stm32f4xx.c
  src/main/target/system_stm32f4xx.h
Labels: Cleanup, RN: MINOR FEATURE

#5621 VTX Pit Mode control conflict resolved, Tx switch vs menues.
  src/main/io/spektrum_vtx_control.c
  src/main/io/vtx.c
Labels: RN: BUGFIX

#5612 Cache up SDIO Writing, add option to enable clock bypass.
  make/source.mk
  src/main/drivers/sdcard_sdio_baremetal.c
  src/main/drivers/sdio_f4xx.c
  src/main/interface/settings.c
  src/main/pg/pg_ids.h
  src/main/pg/sdio.c
  src/main/pg/sdio.h
Labels: RN: IMPROVEMENT

#5623 Increased MSP API version for 3.3.1 to 1.38.
  src/main/interface/msp_protocol.h
Labels: Applied to Branch

#5608 Throttle limit feature
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/interface/settings.c
  src/main/interface/settings.h
Labels: RN: MINOR FEATURE

#5627 Trimmed RCEXPLORERF3 firmware size.
  src/main/target/RCEXPLORERF3/target.h
Labels: RN: IMPROVEMENT

#5618 CF/BF - Add support for IR Transponder on STM32F7 boards.
  make/mcu/STM32F3.mk
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  make/source.mk
  src/main/drivers/transponder_ir.h
  src/main/drivers/transponder_ir_arcitimer.c
  src/main/drivers/transponder_ir_erlt.c
  src/main/drivers/transponder_ir_ilap.c
  src/main/drivers/transponder_ir_io_hal.c
  src/main/drivers/transponder_ir_io_stdperiph.c
  src/main/target/BEEROTORF4/target.mk
  src/main/target/SPRACINGF4NEO/target.mk
  src/main/target/SPRACINGF7DUAL/target.h
Labels: RN: IMPROVEMENT

#5637 Enable USE_BRUSHED_ESC_AUTODETECT for all targets
  src/main/target/ALIENFLIGHTF1/target.h
  src/main/target/ALIENFLIGHTF3/target.h
  src/main/target/ALIENFLIGHTF4/target.h
  src/main/target/ALIENFLIGHTNGF7/target.h
  src/main/target/ALIENWHOOP/target.h
  src/main/target/BEEBRAIN_V2F/target.h
  src/main/target/FF_PIKOBLX/target.h
  src/main/target/SITL/target.h
  src/main/target/SPRACINGF3EVO/target.h
  src/main/target/SPRACINGF3MINI/target.h
  src/main/target/common_fc_pre.h
Labels: RN: SAFETY IMPROVEMENT

#5600 Turtle/Flip after crash: Add options to use all the motors
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/interface/settings.c
Labels: RN: IMPROVEMENT

#5641 Expose vbat divider and multiplier parameters in CLI
  src/main/interface/settings.c
  src/main/sensors/voltage.h
Labels: RN: BUGFIX

#5630 update slack url
  README.md
Labels: Documentation update

#5581 Expose ESC telemetry over Smart port
  src/main/telemetry/smartport.c
Labels: RN: IMPROVEMENT

#5651 Expose ESC telemetry over smart port - bug fix
  src/main/telemetry/smartport.c
Labels: RN: BUGFIX

#5649 MSC support code: White space tidy
  src/main/drivers/usb_msc_f4xx.c
  src/main/drivers/usb_msc_f7xx.c
Labels: Cleanup

#5645 Fix Blackbox P interval
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox.h
  src/main/cms/cms_menu_blackbox.c
  src/main/interface/msp.c
  src/main/interface/settings.c
  src/test/unit/blackbox_unittest.cc
Labels: RN: BUGFIX

#5659 Fix CDC class buffer length validation
  src/main/vcp_hal/usbd_cdc_interface.c
  src/main/vcpf4/usbd_cdc_vcp.c
Labels: RN: BUGFIX

#5665 Fix timer definition for REVOLTOSD
  src/main/target/REVOLT/target.c
Labels: Bugfix, RN: BUGFIX

#5644 Added config checks for the RSSI config.
  src/main/fc/config.c
Labels: RN: IMPROVEMENT

#5663 Added checks for ESC_SENSOR feature being enabled when reading ESC sensor data.
  src/main/fc/config.c
  src/main/sensors/current.c
  src/main/sensors/esc_sensor.c
  src/main/sensors/voltage.c
  src/main/telemetry/frsky_hub.c
Labels: RN: IMPROVEMENT

#5668 Fixed help text for 'diff defaults'.
  src/main/interface/cli.c
Labels: RN: BUGFIX

#5675 F4 Fix broken BIDIR on PA9 (UART1_TX)
  lib/main/STM32_USB_OTG_Driver/src/usb_core.c
  src/main/drivers/usb_io.c
  src/main/fc/fc_init.c
  src/main/osd_slave/osd_slave_init.c
  src/main/target/AIKONF4/target.h
  src/main/target/ANYFCF7/target.h
  src/main/target/ANYFCM7/target.h
  src/main/target/BEEROTORF4/target.h
  src/main/target/BETAFLIGHTF4/target.h
  src/main/target/BLUEJAYF4/target.h
  src/main/target/CLRACINGF4/target.h
  src/main/target/COLIBRI/target.h
  src/main/target/F4BY/target.h
  src/main/target/FF_FORTINIF4/target.h
  src/main/target/FF_PIKOF4/target.h
  src/main/target/FISHDRONEF4/target.h
  src/main/target/FRSKYF4/target.h
  src/main/target/FURYF4/target.h
  src/main/target/FURYF7/target.h
  src/main/target/KAKUTEF4/target.h
  src/main/target/KAKUTEF7/target.h
  src/main/target/KIWIF4/target.h
  src/main/target/KROOZX/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/MATEKF411/target.h
  src/main/target/MATEKF722/target.h
  src/main/target/MOTOLABF4/target.h
  src/main/target/NERO/target.h
  src/main/target/NOX/target.h
  src/main/target/NUCLEOF7/target.h
  src/main/target/NUCLEOF722/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/REVO/target.h
  src/main/target/REVOLT/target.h
  src/main/target/REVONANO/target.h
  src/main/target/SPARKY2/target.h
  src/main/target/SPEEDYBEEF4/target.h
  src/main/target/STM32F4DISCOVERY/target.h
  src/main/target/VRRACE/target.h
  src/main/target/WORMFC/target.h
  src/main/target/YUPIF7/target.h
  src/main/vcpf4/usb_bsp.c
Labels: RN: BUGFIX

#5670 Fix MSP Flash FS supported
  src/main/interface/msp.c
  src/main/io/flashfs.c
  src/main/io/flashfs.h
Labels: RN: BUGFIX

#5684 MSP FLASHFS Don't call flashfsGetOffset if device is not found or unsupported
  src/main/interface/msp.c
Labels: RN: BUGFIX

#5688 Fix for blackbox I interval to be 32 ms even if PID denom isn't 1.
  src/main/blackbox/blackbox.c
  src/test/unit/blackbox_unittest.cc
Labels: RN: BUGFIX

#5700 Fixed 3.3.x-maintenance branch.
  src/main/interface/msp.c
Labels: Applied to Branch

#5701 Constrained D-term transition upper-bound
  src/main/flight/pid.c
Labels: Bugfix, RN: BUGFIX

#5699 Reduced firmware size for OMNIBUS.
  src/main/target/OMNIBUS/target.h
  src/main/target/RCEXPLORERF3/target.h
Labels: RN: IMPROVEMENT

#5685 Improve ESC warning message and include current threshold check.
  src/main/interface/settings.c
  src/main/io/osd.c
  src/main/io/osd.h
Labels: RN: BUGFIX

#5662 add target BeeStorm
  src/main/target/BEEBRAIN_V2F/BEESTORM.mk
  src/main/target/BEEBRAIN_V2F/config.c
  src/main/target/BEEBRAIN_V2F/target.h
  src/main/target/BEEBRAIN_V2F/target.mk
Labels: RN: NEW TARGET

#5683 Prepare flash code for multiple device type support
  make/source.mk
  src/main/blackbox/blackbox_io.c
  src/main/drivers/flash.c
  src/main/drivers/flash.h
  src/main/drivers/flash_impl.h
  src/main/drivers/flash_m25p16.c
  src/main/drivers/flash_m25p16.h
  src/main/fc/fc_init.c
  src/main/io/flashfs.c
  src/main/io/flashfs.h
  src/main/msc/usbd_storage_emfat.c
  src/main/target/BLUEJAYF4/hardware_revision.c
  src/main/target/common_fc_post.h
Labels: RN: IMPROVEMENT

#5703 Fixed priority of RSSI validation: ADC / RX channel / frame errors.
  src/main/fc/config.c
  src/main/rx/rx.c
Labels: RN: BUGFIX

#5711 Don't make the report_cell_voltage setting depend on IBUS
  src/main/interface/settings.c
Labels: RN: BUGFIX

#5714 Fixed a typo in HMC5883L driver for F7
  src/main/drivers/compass/compass_hmc5883l.c
Labels: RN: BUGFIX

#5716 Added timer for PA3 (PPM in) for OMNIBUSF7.
  src/main/target/OMNIBUSF7/target.c
  src/main/target/OMNIBUSF7/target.h
Labels: RN: TARGET UPDATE

#5720 FLASH Full (re)configurability
  src/main/interface/cli.c
  src/main/interface/settings.c
Labels: RN: IMPROVEMENT

#5717 Fixed condition in BEEBRAIN target.mk.
  src/main/target/BEEBRAIN_V2F/target.mk
Labels: RN: BUGFIX

#5723 Target update: AlienWhoop V2.1 blackbox via dataflash
  src/main/target/ALIENWHOOP/config.c
  src/main/target/ALIENWHOOP/target.h
  src/main/target/ALIENWHOOP/target.mk
Labels: RN: TARGET UPDATE

#5718 Revert accidental cherry pick into wrong branch.
  src/main/target/BEEBRAIN_V2F/BEESTORM.mk
  src/main/target/BEEBRAIN_V2F/config.c
  src/main/target/BEEBRAIN_V2F/target.h
  src/main/target/BEEBRAIN_V2F/target.mk
Labels: Applied to Branch

#5674 F7 optimizations
  lib/main/STM32F7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c
  make/mcu/STM32F7.mk
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_pinconfig.c
  src/main/fc/fc_core.c
  src/main/fc/fc_rc.c
  src/main/flight/mixer.c
  src/main/main.c
  src/main/platform.h
  src/main/sensors/gyro.c
  src/main/startup/startup_stm32f40xx.s
  src/main/startup/startup_stm32f722xx.s
  src/main/startup/startup_stm32f745xx.s
  src/main/startup/startup_stm32f746xx.s
  src/main/target/CLRACINGF7/target.c
  src/main/target/CLRACINGF7/target.h
  src/main/target/KISSFCV2F7/stm32_flash_f722_no_split.ld
  src/main/target/MATEKF722/target.c
  src/main/target/MATEKF722/target.h
  src/main/target/SPRACINGF7DUAL/config.c
  src/main/target/SPRACINGF7DUAL/target.c
  src/main/target/SPRACINGF7DUAL/target.h
  src/main/target/common_fc_pre.h
  src/main/target/link/stm32_flash_f722.ld
  src/main/target/link/stm32_flash_f745.ld
  src/main/target/link/stm32_flash_f746.ld
  src/main/target/link/stm32_flash_f74x.ld
  src/main/target/link/stm32_flash_f7_split.ld
  src/main/target/stm32f7xx_hal_conf.h
  src/main/target/system_stm32f7xx.c
  src/test/unit/platform.h
Labels: Cleanup, RN: MAJOR FEATURE

#5715 Fixed ownership of MPU_CS resource in case of multiple gyros
  src/main/drivers/accgyro/accgyro_l3gd20.c
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
  src/main/drivers/accgyro/accgyro_spi_icm20649.c
  src/main/drivers/accgyro/accgyro_spi_icm20689.c
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
  src/main/drivers/accgyro/accgyro_spi_mpu6500.c
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
  src/main/sensors/gyro.c
Labels: Bugfix, RN: BUGFIX, Tested

#5721 OMNIBUSF4SD Add onboard flash support
  src/main/target/OMNIBUSF4/target.h
Labels: RN: TARGET UPDATE

#5722 FLASH Add W25M homogeneous stack driver and W25M512 support
  make/source.mk
  src/main/drivers/flash.c
  src/main/drivers/flash_w25m.c
  src/main/drivers/flash_w25m.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/common_fc_post.h
Labels: RN: MAJOR FEATURE

#5728 Fixing the #5705 (D-Term spikes)
  src/main/flight/pid.c
Labels: RN: BUGFIX

#5726 Fixes to ranges of esc warning thresholds.
  src/main/interface/settings.c
  src/main/io/osd.h
  src/main/sensors/esc_sensor.h
Labels: RN: IMPROVEMENT

#5729 Post-cleanup of F7 optimizations
  lib/main/STM32F7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/stm32f7xx_ll_ex.h
  src/main/platform.h
  src/main/target/common_fc_pre.h
  src/main/target/system_stm32f7xx.c
Labels: RN: IMPROVEMENT, Testing Required

#5738 Fixed missed naming changes.
  src/main/target/AIKONF4/target.h
Labels: RN: BUGFIX

#5733 Added FAST_RAM_INITIALIZED
  src/main/fc/fc_init.c
  src/main/flight/pid.c
  src/main/target/KISSFCV2F7/stm32_flash_f722_no_split.ld
  src/main/target/common_fc_pre.h
  src/main/target/link/stm32_flash_f7_split.ld
  src/main/target/link/stm32_flash_split.ld
Labels: RN: BUGFIX, RN: IMPROVEMENT, Testing Required

#5740 Set FAST_RAM_INITIALIZED LMA to AXIM-FLASH
  src/main/target/link/stm32_flash_f7_split.ld
Labels: Bugfix

#5730 Change gyro overflow handling to be based on runtime detected gyro
  src/main/drivers/accgyro/accgyro.h
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#5734 PID controller unittest // bugfix yaw accel state
  src/main/flight/pid.c
  src/test/Makefile
  src/test/unit/pid_unittest.cc
  src/test/unit/platform.h
Labels: Bugfix, RN: BUGFIX, Staged for Merge, UNITTEST

#5747 Fixed inconsistent handling of servos for USE_QUAD_MIXER_ONLY.
  src/main/target/common_fc_post.h
Labels: RN: BUGFIX

#5753 [GPS RESCUE] - Use GPS when present for correcting attitude.values.yaw
  src/main/flight/imu.c
  src/main/flight/imu.h
Labels: RN: MAJOR FEATURE

#5743 CMS Telemetry over CRSF w/ Lua Script (X9D, so far)
  make/source.mk
  src/main/cms/cms.c
  src/main/cms/cms.h
  src/main/drivers/display.h
  src/main/fc/fc_init.c
  src/main/interface/crsf_protocol.h
  src/main/interface/settings.c
  src/main/io/displayport_crsf.c
  src/main/io/displayport_crsf.h
  src/main/pg/pg_ids.h
  src/main/rx/crsf.c
  src/main/target/MIDELICF3/target.h
  src/main/target/SPRACINGF3EVO/target.h
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/common_fc_pre.h
  src/main/telemetry/crsf.c
  src/main/telemetry/crsf.h
Labels: RN: MAJOR FEATURE

#5749 Omnibus F4 Fireworks support
  src/main/target/OMNIBUSF4FW/config.c
  src/main/target/OMNIBUSF4FW/target.c
  src/main/target/OMNIBUSF4FW/target.h
  src/main/target/OMNIBUSF4FW/target.mk
Labels: RN: NEW TARGET

#5755 Made FrSky SPI telemetry and external telemetry values configurable.
  src/main/interface/settings.c
  src/main/rx/cc2500_frsky_common.h
  src/main/rx/cc2500_frsky_d.c
  src/main/rx/cc2500_frsky_shared.c
  src/main/rx/cc2500_frsky_x.c
Labels: RN: IMPROVEMENT

#5758 Passive beeper: Handle non-existent timer case correctly
  src/main/drivers/pwm_output.c
  src/main/fc/config.c
Labels: RN: BUGFIX

#5761 Fixed flash overflow on SPRACINGF3EVO and friends.
  src/main/target/SPRACINGF3EVO/target.h
Labels: RN: BUGFIX

#5762 Fixed flash overflow for RCEXPLORERF3.
  src/main/target/RCEXPLORERF3/target.h
Labels: RN: BUGFIX

#5676 Disable CMS when USB is connected on CDC_HID enabled targets.
  src/main/cms/cms.c
Labels: RN: BUGFIX
