Repository betaflight/betaflight, pull requests merged in 2019-09, with the labels that each got.

#8778 Gyro filtering restructure
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/drivers/accgyro/accgyro.h
  src/main/fc/config.c
  src/main/flight/gyroanalyse.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_filter_impl.c
Labels: Needs coordination with betaflight-configurator, Needs coordination with blackbox-log-viewer, RN: IMPROVEMENT, RN: REFACTORING

#8785 Increase iTerm defaults slightly for 4.1
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#8784 Set default static lowpass1 gyro value to the same as default gyro lowpass1 min
  src/main/sensors/gyro.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8783 FF defaults increased to 90's
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#8791 Added announcement of the feature freeze for 4.1, updated the new tar…
  .github/pull_request_template.md
  README.md
Labels: Housekeeping

#8769 Added support for resetting to custom defaults to MSP.
  src/link/stm32_flash_f7_split.ld
  src/link/stm32_flash_split.ld
  src/main/cli/cli.c
  src/main/cli/cli.h
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/init.c
  src/main/msp/msp.c
  src/test/unit/cli_unittest.cc
Labels: RN: IMPROVEMENT

#8787 Fixed start / end addresses for custom defaults.
  src/link/stm32_flash_f7_split.ld
  src/link/stm32_flash_split.ld
  src/main/cli/cli.c
Labels: RN: BUGFIX

#8790 Extended configuration status to accommodate custom defaults.
  src/main/cli/cli.c
  src/main/cli/cli.h
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/init.c
  src/main/msp/msp.c
  src/main/target/common_post.h
  src/test/unit/cli_unittest.cc
Labels: RN: IMPROVEMENT

#8797 Changed Unified Target custom defaults to use sector 0 memory.
  src/main/target/OMNIBUSF4/target.h
  src/main/target/STM32F405/target.mk
  src/main/target/STM32F411/target.mk
  src/main/target/STM32F745/target.mk
  src/main/target/STM32F7X2/target.mk
  src/utils/make_config_hex.sh
Labels: RN: IMPROVEMENT

#8792 Write forward only servos
  src/main/flight/servos.c
Labels: Bugfix, RN: BUGFIX

#8779 GPIO Bit-banging Dshot with GCR Telemetry
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/drivers/dshot.c
  src/main/drivers/dshot.h
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_bitbang.h
  src/main/drivers/dshot_bitbang_decode.c
  src/main/drivers/dshot_bitbang_decode.h
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/dshot_bitbang_ll.c
  src/main/drivers/dshot_bitbang_stdperiph.c
  src/main/drivers/dshot_dpwm.c
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/motor.c
  src/main/drivers/motor.h
  src/main/drivers/pwm_esc_detect.c
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/drivers/pwm_output_dshot_shared.h
  src/main/drivers/resource.c
  src/main/drivers/resource.h
  src/main/drivers/timer_common.c
  src/main/drivers/timer_def.h
  src/main/fc/config.c
  src/main/fc/core.c
  src/main/fc/init.c
  src/main/fc/runtime_config.h
  src/main/pg/motor.c
  src/main/pg/motor.h
  src/main/target/common_pre.h
Labels: RN: MINOR FEATURE

#8804 change transient throttle limit default to 0
  src/main/flight/pid.c
Labels: RN: BUGFIX

#8807 Added manufacturer id for Racerstar.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8806 Removed Dshot1200 protocol.
  src/main/cli/settings.c
  src/main/drivers/dshot_dpwm.c
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/motor.c
  src/main/drivers/motor.h
  src/main/fc/config.c
  src/main/target/XILOF4/config.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8736 various ff2_0 improvements
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/fc/rc.c
  src/main/fc/rc.h
  src/main/flight/interpolated_setpoint.c
  src/main/flight/interpolated_setpoint.h
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: RN: IMPROVEMENT

#8818 Remove DShot1200 Protocol Part2
  src/main/drivers/dshot_bitbang.c
Labels: Fixes broken build, RN: BUGFIX

#8817 Added the parameters for RPM filtering to MSP.
  src/main/msp/msp.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8816 Added 'auto' setting for 'scheduler_optimize_rate'.
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/fc/config.c
  src/main/fc/config.h
Labels: RN: IMPROVEMENT

#8803 add speedybee f7
  docs/boards/Board - SpeedyBee F7 AIO.md
  src/main/target/SPEEDYBEEF7/config.c
  src/main/target/SPEEDYBEEF7/target.c
  src/main/target/SPEEDYBEEF7/target.h
  src/main/target/SPEEDYBEEF7/target.mk
  unified_targets/configs/SPEEDYBEEF7.config
Labels: RN: NEW TARGET, RN: UNIFIED TARGETS

#8829 Remove dshot1200 in SPEEDYBEE F7 and in dshot bitbang
  src/main/drivers/dshot_bitbang_impl.h
  src/main/target/SPEEDYBEEF7/config.c
Labels: Fixes broken build, RN: BUGFIX

#8824 Add RPM Filter, FF and Iterm Relax values to the Blackbox header
  src/main/blackbox/blackbox.c
Labels: RN: BUGFIX

#8825 Provide isMotorEnabled function for motorNullDevice
  src/main/drivers/motor.c
  src/main/msp/msp.c
Labels: RN: BUGFIX

#8826 Allow rpm filter to be reinitialized with new settings
  src/main/flight/rpm_filter.c
Labels: RN: BUGFIX

#8827 Bugfix: Vario GPS and 3D Total Distance overflow
  src/main/io/gps.c
Labels: RN: BUGFIX

#8828 Fix serial esc telemetry with bitbang dshot
  src/main/drivers/dshot_bitbang.c
Labels: RN: BUGFIX

#8830 Optimize ledstrip DMA buffer update and bug fix
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/light_ws2811strip.h
  src/main/io/ledstrip.c
  src/test/unit/ledstrip_unittest.cc
Labels: RN: BUGFIX

#8834 Add missing MAG support for FURYF4 and FURYF4OSD targets
  src/main/target/FURYF4/target.h
  src/main/target/FURYF4/target.mk
Labels: RN: TARGET UPDATE

#8835 busBusy for SPI in program I/O mode should always return false
  src/main/drivers/bus.c
Labels: RN: BUGFIX

#8796 Set default dyanmic notch range to medium
  src/main/sensors/gyro.c
Labels: RN: BUGFIX

#8832 update TALONF7FUSION unified target,ADD set pinio_box = 39,255,255,255
  unified_targets/configs/TALONF7FUSION.config
Labels: RN: UNIFIED TARGETS

#8833 update TALONF7V2 unified target, ADD set pinio_box = 39,255,255,255
  unified_targets/configs/TALONF7V2.config
Labels: RN: UNIFIED TARGETS

#8762 Unified Target: add baro sensor auto detect feature for IFF4 boards.
  unified_targets/configs/IFF4_TWIN_G.config
  unified_targets/configs/IFF7_TWIN_G.config
Labels: RN: UNIFIED TARGETS

#8839 use driver independent motor count
  src/main/drivers/dshot_command.c
Labels: RN: BUGFIX

#8842 Small modification to ff boost to improve spike suppression
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/flight/interpolated_setpoint.c
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: RN: BUGFIX

#8843 fix dshot_600 with dshot bitbang
  src/main/drivers/dshot_bitbang_decode.c
  src/main/drivers/dshot_bitbang_impl.h
Labels: RN: BUGFIX

#8848 Fix problem with empty string set as 'manufacturer_id'.
  src/main/cli/cli.c
  src/main/fc/board_info.c
Labels: RN: BUGFIX

#8849 Fixed 'sd_info' showing incorrect information when SD card not configured.
  src/main/cli/cli.c
  src/main/msp/msp.c
Labels: RN: BUGFIX

#8850 Added Unified Target configuration for AIKONF4.
  unified_targets/configs/AIKONF4.config
Labels: RN: UNIFIED TARGETS

#8852 Fix the problem of multiple timer allocations with bitbanged Dshot.
  src/main/cli/cli.c
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_bitbang.h
  src/main/drivers/timer.h
  src/main/drivers/timer_common.c
Labels: RN: BUGFIX

#8851 update unified configs - MatekF4Mini and MatekF7Mini
  unified_targets/configs/MATEKF405MINI.config
  unified_targets/configs/MATEKF722MINI.config
Labels: RN: UNIFIED TARGETS

#8853 Fix F411 pacing timer selection
  src/main/drivers/dshot_bitbang.c
Labels: RN: BUGFIX

#8856 Add dyn notch to blackbox header
  src/main/blackbox/blackbox.c
Labels: RN: BUGFIX

#8861 Fixed problems with bitbanged Dshot and lazily allocated timers.
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/drivers/dshot_bitbang.c
  src/main/pg/motor.c
  src/main/pg/motor.h
  src/main/target/common_defaults_post.h
Labels: RN: BUGFIX

#8860 Removed unavailable timers from STM32F411.
  src/main/drivers/timer.h
  src/main/drivers/timer_stm32f4xx.c
Labels: RN: BUGFIX

#8864 improvements to ff_boost for 4.1 RC's
  src/main/flight/interpolated_setpoint.c
  src/main/flight/pid.c
Labels: RN: BUGFIX

#8871 Make crash recovery settings limits rational to prevent infinite crash recovery and controls lockout
  src/main/cli/settings.c
Labels: RN: BUGFIX, RN: SAFETY IMPROVEMENT

#8874 Fix an erroneous constant in the calculation of altitude from barometric pressure.
  src/main/sensors/barometer.c
Labels: RN: BUGFIX

#8886 prevent using same timer channel twice
  src/main/drivers/dshot_bitbang.c
Labels: RN: BUGFIX

#8887 Add TBS Unify Pro32 examples
  docs/VTX.md
Labels: Documentation update

#8748 Target AIRF7
  src/main/target/AIRF7/config.c
  src/main/target/AIRF7/target.c
  src/main/target/AIRF7/target.h
  src/main/target/AIRF7/target.mk
  unified_targets/configs/AIRF7.config
Labels: RN: NEW TARGET, RN: UNIFIED TARGETS

#8897 Removed usage of UNUSED macro for motorCount as motorCount is used now
  src/main/drivers/dshot_command.c
Labels: RN: BUGFIX

#8893 prefer timer 8 for dshot_bitbang
  src/main/drivers/dshot_bitbang.c
Labels: RN: BUGFIX

#8899 Fixed checks and added target for all checks.
  .travis.sh
  make/checks.mk
Labels: Build System Improvement

#8903 Increase Tramp retry count and fix lockup if VTX out-of-sync with band/channel settings
  src/main/drivers/vtx_common.c
  src/main/drivers/vtx_common.h
  src/main/io/vtx_tramp.c
Labels: RN: BUGFIX

#8907 Revert Tramp power max check when setting power
  src/main/io/vtx_tramp.c
Labels: RN: BUGFIX

#8896 TARGET: add support for "IFLIGHT_H7_TWING" board.
  src/main/target/IFLIGHT_H7_TWING/target.c
  src/main/target/IFLIGHT_H7_TWING/target.h
  src/main/target/IFLIGHT_H7_TWING/target.mk
  unified_targets/configs/IFLIGHT_H7_TWING.config
Labels: RN: NEW TARGET

#8914 STM32F745 Do not define USE_SPI_DEVICE_5 and USE_SPI_DEVICE_6
  src/main/target/STM32F745/target.h
Labels: Bugfix, RN: BUGFIX

#8920 Added SPI5 pin definition for STM32H7.
  src/main/drivers/bus_spi_pinconfig.c
Labels: RN: BUGFIX

#8924 UART buffers for F4 should not be in CCM DATA RAM for DMA to work
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stm32f4xx.c
Labels: Bugfix, RN: BUGFIX

#8927 Prevent DSHOT commands during protocol initialization/detection
  src/main/drivers/dshot_command.c
  src/main/drivers/dshot_command.h
  src/main/drivers/motor.c
  src/main/drivers/motor.h
  src/main/fc/core.c
Labels: RN: BUGFIX

#8926 exclude yaw from ff_max_rate_limit
  src/main/flight/interpolated_setpoint.c
Labels: RN: BUGFIX

#8928 Fix compile errors if USE_DSHOT not defined
  src/main/target/common_post.h
Labels: RN: BUGFIX

#8930 Added missing compilation warning for unsupported F3 targets.
  src/main/build/version.c
Labels: Build System Improvement

#8936 Fix VTX low power disarm when USE_VTX_RTC6705 is defined
  src/main/drivers/vtx_table.h
  src/main/io/vtx.c
Labels: RN: BUGFIX

#8937 Add board name to CLI version command output for unified targets
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#8940 [VTX] Fixed version checks in smartaudio that disabled pitmode on SA2.1 devices
  src/main/io/vtx_smartaudio.c
Labels: RN: BUGFIX

#8942 Handle a lack of trailing newline in config file.
  src/main/cli/cli.c
Labels: RN: BUGFIX

#8946 Fixed hanging on 'defaults nosave' when RX_SERIAL is enabled.
  src/main/cli/cli.c
  src/main/fc/tasks.c
  src/main/rx/pwm.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/spektrum.c
  src/main/rx/xbus.c
  src/main/telemetry/telemetry.c
Labels: RN: BUGFIX

#8947 Added manufacturer id for FPV Model.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8955 Add TRANSTECF411 Target
  docs/boards/Board - TRANSTECF411.md
  docs/boards/images/TRANSTECF411-BottomSide.jpg
  docs/boards/images/TRANSTECF411-TopSide.jpg
  src/main/target/TRANSTECF411/config.c
  src/main/target/TRANSTECF411/target.c
  src/main/target/TRANSTECF411/target.h
  src/main/target/TRANSTECF411/target.mk
Labels: RN: NEW TARGET

#8956 add mag and bmp support for AIRBOTF7
  src/main/target/AIRBOTF7/target.h
  src/main/target/AIRBOTF7/target.mk
Labels: RN: TARGET UPDATE

#8961 H7 - Fix bi-directional DSHOT
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/pwm_output_dshot_hal.c
Labels: Bugfix, RN: BUGFIX

#8952 Fix "BIT_GYRO" definition error.
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
Labels: RN: BUGFIX
