Repository betaflight/betaflight, pull requests merged in 2019-12, with the labels that each got.

#9127 Add support for FrSky OSD
  make/source.mk
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/common/time.c
  src/main/common/uvarint.c
  src/main/common/uvarint.h
  src/main/drivers/display.c
  src/main/drivers/display.h
  src/main/drivers/display_canvas.c
  src/main/drivers/display_canvas.h
  src/main/drivers/max7456.c
  src/main/drivers/osd.h
  src/main/drivers/osd_symbols.h
  src/main/fc/init.c
  src/main/io/displayport_frsky_osd.c
  src/main/io/displayport_frsky_osd.h
  src/main/io/displayport_max7456.c
  src/main/io/frsky_osd.c
  src/main/io/frsky_osd.h
  src/main/io/serial.c
  src/main/io/serial.h
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/pg/vcd.h
  src/main/target/common_pre.h
  src/test/Makefile
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: RN: MINOR FEATURE

#9248 Refactored 'WAS_EVER_ARMED' arming flag to be only enabled on first disarm.
  src/main/fc/core.c
  src/main/flight/failsafe.c
  src/main/osd/osd.c
  src/main/osd/osd_elements.c
  src/test/unit/osd_unittest.cc
Labels: RN: REFACTORING

#9250 Add optional search string support for CLI "help" command
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#9249 Update RC smoothing "auto" settings to consider interpolated feedforward
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/fc/rc.c
  src/main/fc/rc_controls.h
  src/main/pg/rx.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#9252 Restructure flashfs MSC to prevent device timeout on MacOS
  src/main/drivers/usb_msc_f4xx.c
  src/main/drivers/usb_msc_f7xx.c
  src/main/fc/init.c
  src/main/msc/emfat_file.c
  src/main/msc/usbd_storage_emfat.c
Labels: RN: BUGFIX

#9253 Fix compile errors if USE_FLASHFS is defined but USE_FLASH_CHIP is not
  src/main/target/common_post.h
Labels: RN: BUGFIX

#9255 Refactor common USB MSC code and improve activity LED
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  make/mcu/STM32H7.mk
  src/main/drivers/usb_msc.h
  src/main/drivers/usb_msc_common.c
  src/main/drivers/usb_msc_f4xx.c
  src/main/drivers/usb_msc_f7xx.c
  src/main/fc/init.c
  src/main/msc/emfat_file.c
  src/main/msc/usbd_storage_emfat.c
  src/main/msc/usbd_storage_sd_spi.c
  src/main/msc/usbd_storage_sdio.c
Labels: RN: IMPROVEMENT, RN: REFACTORING

#9189 SRXL2 failsafe fix for newer receivers
  src/main/rx/srxl2.c
Labels: RN: BUGFIX

#9256 Fixed compiler warnings.
  src/main/common/string_light.c
  src/main/common/typeconversion.c
Labels: RN: IMPROVEMENT

#9258 Move MSP/OSD/CMS initialization to be near the end of the init process
  src/main/fc/init.c
Labels: RN: IMPROVEMENT

#9261 Add camera frame OSD element
  src/main/cli/settings.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#9269 Fixed missing parameter group version increment for 'osdConfig' after #9261.
  src/main/osd/osd.c
  src/main/osd/osd.h
Labels: RN: BUGFIX

#9271 Cleaned up CLI 'resource' implementation.
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#9267 Inhibit 'Save & Exit' menu when in RC preview.
  src/main/cms/cms.c
  src/main/cms/cms.h
  src/main/cms/cms_menu_main.c
  src/main/cms/cms_menu_misc.c
  src/main/cms/cms_menu_saveexit.c
  src/main/cms/cms_menu_saveexit.h
Labels: RN: BUGFIX

#9266 Fixed 'back' command for CMS menus.
  src/main/cms/cms.c
Labels: RN: BUGFIX

#9272 Renaming 'featureEnable' / 'featureDisable' to make their use a bit more obvious.
  src/main/cms/cms_menu_ledstrip.c
  src/main/config/config.c
  src/main/config/feature.c
  src/main/config/feature.h
  src/main/target/ALIENFLIGHTF3/config.c
  src/main/target/ALIENFLIGHTF4/config.c
  src/main/target/ALIENFLIGHTNGF7/config.c
  src/main/target/ALIENWHOOP/config.c
  src/main/target/FF_FORTINIF4/config.c
  src/main/target/FF_PIKOBLX/config.c
  src/main/target/XILOF4/config.c
  src/test/unit/link_quality_unittest.cc
  src/test/unit/rx_ranges_unittest.cc
Labels: RN: IMPROVEMENT

#9274 Add support for serial passthrough via MSP
  src/main/msp/msp.c
  src/main/msp/msp_protocol.h
Labels: RN: IMPROVEMENT

#9275 Make CMS OSD menu max7456 settings have realtime effect
  src/main/cms/cms.c
  src/main/cms/cms_menu_osd.c
Labels: RN: IMPROVEMENT

#9128 reduce antigravity gain default to 3.5
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#9277 Fix ESC protocol startup after rearranging MSP/OSD/CMS init
  src/main/fc/init.c
Labels: RN: BUGFIX

#9278 Move OSD elements into their own parameter group
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/target/BEEBRAIN_V2F/config.c
  src/main/target/KROOZX/config.c
  src/main/target/SPEEDYBEEF7/config.c
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#9295 Fix CLI vtx command parsing, range checks, and output order in diff
  src/main/cli/cli.c
Labels: RN: BUGFIX

#9291 SRXL2 frame drops reported more appropriately
  src/main/rx/srxl2.c
Labels: RN: BUGFIX

#9290 Fix undefined reference to mag when USE_MAG isn't defined
  src/main/flight/imu.c
Labels: RN: BUGFIX

#9289 Fix CLI rc_smoothing_info frame rate display formatting
  src/main/cli/cli.c
Labels: RN: BUGFIX

#9302 Incremented maintenance branch version to 4.1.3.
  src/main/build/version.h
Labels: Applied to Branch, Housekeeping

#9181 Move targets into legacy targets for 4.1.3.
  make/targets_list.mk
Labels: Housekeeping

#9303 Fix "may be used uninitialized" debug build warnings
  src/main/cli/cli.c
  src/main/rx/cc2500_frsky_d.c
  src/main/rx/cc2500_frsky_x.c
Labels: RN: BUGFIX

#9292 Added smartport pitch and roll sensors
  src/main/telemetry/smartport.c
Labels: RN: IMPROVEMENT

#9308 Revert "BugFix: time to first fix was sometimes abnormally high due t…
  src/main/io/gps.c
  src/main/io/gps.h
Labels: RN: BUGFIX

#9309 Clear sat list to avoid showing old data
  src/main/io/gps.c
Labels: RN: BUGFIX

#9304 Fix imuComputeQuaternionFromRPY warning.
  src/main/flight/imu.c
Labels: RN: BUGFIX

#9311 Prevent EXTI handler from crashing when EXTI lines 16-32 are used.
  src/main/drivers/exti.c
Labels: RN: BUGFIX

#9268 Unify rx spi exti handling
  src/main/drivers/rx/rx_a7105.c
  src/main/drivers/rx/rx_a7105.h
  src/main/drivers/rx/rx_cyrf6936.c
  src/main/drivers/rx/rx_cyrf6936.h
  src/main/drivers/rx/rx_spi.c
  src/main/drivers/rx/rx_spi.h
  src/main/rx/a7105_flysky.c
  src/main/rx/a7105_flysky.h
  src/main/rx/cc2500_common.c
  src/main/rx/cc2500_common.h
  src/main/rx/cc2500_frsky_common.h
  src/main/rx/cc2500_frsky_d.c
  src/main/rx/cc2500_frsky_shared.c
  src/main/rx/cc2500_frsky_x.c
  src/main/rx/cc2500_sfhss.c
  src/main/rx/cc2500_sfhss.h
  src/main/rx/cyrf6936_spektrum.c
  src/main/rx/cyrf6936_spektrum.h
  src/main/rx/nrf24_cx10.c
  src/main/rx/nrf24_cx10.h
  src/main/rx/nrf24_h8_3d.c
  src/main/rx/nrf24_h8_3d.h
  src/main/rx/nrf24_inav.c
  src/main/rx/nrf24_inav.h
  src/main/rx/nrf24_kn.c
  src/main/rx/nrf24_kn.h
  src/main/rx/nrf24_syma.c
  src/main/rx/nrf24_syma.h
  src/main/rx/nrf24_v202.c
  src/main/rx/nrf24_v202.h
  src/main/rx/rx_spi.c
  src/main/rx/rx_spi.h
  src/test/unit/rx_spi_spektrum_unittest.cc
Labels: RN: IMPROVEMENT

#9281 Reset protocol level RX frame delta after reading
  src/main/rx/crsf.c
  src/main/rx/ibus.c
  src/main/rx/jetiexbus.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/sbus.c
  src/main/rx/spektrum.c
  src/main/rx/sumd.c
Labels: RN: BUGFIX

#9288 Add protocol level receiver frame rate measurement for SRXL2
  src/main/rx/srxl2.c
Labels: RN: IMPROVEMENT

#9316 ICM42605 sensor support
  src/main/cli/settings.c
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/accgyro/accgyro_spi_icm42605.c
  src/main/drivers/accgyro/accgyro_spi_icm42605.h
  src/main/drivers/accgyro/accgyro_spi_mpu6500.c
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/gyro.c
  src/main/target/NUCLEOH743/target.h
  src/main/target/NUCLEOH743/target.mk
Labels: RN: IMPROVEMENT

#9321 switched pin desriptions
  src/main/target/JHEF7DUAL/target.h
Labels: Legacy target
