Repository betaflight/betaflight, pull requests merged in 2019-04, with the labels that each got.

#7901 Change absolute control default to disabled and reenable iterm_rotation
  src/main/flight/pid.c
Labels: RN: BUGFIX

#7906 Add target JHEF7DUAL to 4.0.
  docs/boards/Board - JHEF7DUAL.md
  src/main/target/JHEF7DUAL/config.c
  src/main/target/JHEF7DUAL/target.c
  src/main/target/JHEF7DUAL/target.h
  src/main/target/JHEF7DUAL/target.mk
  unified_targets/configs/JHEF7DUAL.config
  unified_targets/docs/Manufacturers.md
Labels: RN: NEW TARGET, RN: UNIFIED TARGETS

#7911 Edit typos - ElinF722 doc
  docs/boards/Board - ElinF722.md
Labels: Documentation update

#7912 Added 'KLEE' / Kevin Lee (WhitenoiseFPV) manufacturer id.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#7913 SYNERGYF4 updated target for 4.0 and unified targets
  docs/boards/Board - SYNERGYF4.md
  docs/boards/images/SYNERGYF4-bottom.png
  docs/boards/images/SYNERGYF4-main.jpg
  docs/boards/images/SYNERGYF4-top.png
  src/main/target/OMNIBUSF4/SYNERGYF4.mk
  src/main/target/OMNIBUSF4/config.c
  src/main/target/OMNIBUSF4/target.c
  src/main/target/OMNIBUSF4/target.h
  unified_targets/configs/SYNERGYF4.config
Labels: RN: TARGET UPDATE, RN: UNIFIED TARGETS

#7914 Fixed gyro detection for multi gyro setups.
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/msp/msp.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/common_defaults_post.h
  src/test/unit/sensor_gyro_unittest.cc
Labels: RN: BUGFIX

#7918 Unify lowpass settings regardless of whether USE_DYN_LPF is defined
  src/main/fc/config.c
  src/main/flight/pid.c
  src/main/sensors/gyro.c
Labels: Needs coordination with betaflight-configurator, RN: BUGFIX

#7919 Updated CMS to pass flags by reference into cmsDrawMenuEntry
  src/main/cms/cms.c
Labels: RN: BUGFIX

#7921 Added Unified Target configuration for FOXEERF722DUAL and manufacturer id.
  unified_targets/configs/FOXEERF722DUAL.config
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#7929 Fix erroneous dshot motor frame between multiple queued dshot commands at arming
  src/main/drivers/pwm_output.c
Labels: RN: BUGFIX

#7930 Added target RUSHCORE7 to 4.0.
  docs/boards/Board - RUSHCORE7.md
  src/main/target/RUSHCORE7/target.c
  src/main/target/RUSHCORE7/target.h
  src/main/target/RUSHCORE7/target.mk
  unified_targets/configs/RUSHCORE7.config
  unified_targets/docs/Manufacturers.md
Labels: RN: TARGET UPDATE, RN: UNIFIED TARGETS

#7931 Added target FF_RACEPIT to 4.0.
  src/main/target/FF_RACEPIT/config.c
  src/main/target/FF_RACEPIT/target.c
  src/main/target/FF_RACEPIT/target.h
  src/main/target/FF_RACEPIT/target.mk
Labels: RN: TARGET UPDATE

#7933 Added target FLYWOOF411 to 4.0.
  docs/boards/Board - FLYWOOF411.md
  src/main/target/FLYWOOF411/config.c
  src/main/target/FLYWOOF411/target.c
  src/main/target/FLYWOOF411/target.h
  src/main/target/FLYWOOF411/target.mk
Labels: RN: TARGET UPDATE

#7934 Add missing help text for CLI vtx command
  src/main/cli/cli.c
Labels: RN: BUGFIX

#7937 Avoid altitude to blink if its value exceeds the alarm threshold when…
  src/main/osd/osd_elements.c
Labels: RN: BUGFIX

#7939 doc update and motor output change
  docs/boards/Board - OMNIBUSF4NANOV7.md
  docs/boards/images/OMNIBUSF4NANOV7-BottomSide.png
  docs/boards/images/OMNIBUSF4NANOV7-TopSide.png
  src/main/target/OMNIBUSF4NANOV7/target.c
  unified_targets/configs/OMNIBUSF4NANOV7.config
Labels: RN: TARGET UPDATE

#7942 [F446] Add VECTAB region
  src/main/target/link/stm32_flash_f446.ld
Labels: RN: BUGFIX

#7944 Added event for Betaflight 4.1 release to README.md.
  README.md
Labels: Documentation update

#7960 Fixed gyro detection some more.
  src/main/drivers/accgyro/accgyro_mpu.c
Labels: RN: BUGFIX

#7962 Incremented EEPROM config version for the 4.0 release.
  src/main/config/config_eeprom.h
Labels: Householding

#7966 Incremented maintenance branch version to 4.0.1.
  src/main/build/version.h
Labels: Applied to Branch, Householding

#7967 Incremented version to 4.1.0.
  .github/pull_request_template.md
  README.md
  src/main/build/version.h
Labels: Householding

#7972 Added manufacturer id for HGLRC.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#7968 Incremented MSP API version to 1.42.
  src/main/msp/msp_protocol.h
Labels: Householding

#7626 Move memory section initialisation earlier into the init sequence.
  src/main/drivers/system.c
  src/main/drivers/system.h
  src/main/fc/init.c
  src/main/startup/system_stm32f30x.c
  src/main/startup/system_stm32f4xx.c
  src/main/startup/system_stm32f7xx.c
Labels: RN: REFACTORING

#7621 Allow compilation of the printf code when no serial ports are used.
  src/main/cli/cli.c
  src/main/common/printf.c
  src/main/common/printf.h
  src/main/common/printf_serial.c
  src/main/common/printf_serial.h
  src/main/fc/init.c
Labels: RN: REFACTORING

#7737 remove smart_feedforward
  src/main/cli/settings.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/msp/msp.c
  src/main/target/common_pre.h
  src/test/unit/pid_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#7970 Make F3 targets unsupported to improve build times.
  make/targets_list.mk
Labels: Householding, RN: TARGET UPDATE

#7839 Fix duplicate transponder task enable attempt.
  src/main/fc/tasks.c
Labels: Cleanup

#7843 Fixed warnings.
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/msc/emfat_file.c
Labels: RN: REFACTORING

#7858 Add DUAL_GYRO_SCALED debug mode to capture raw scaled roll/pitch for each gyro
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#7924 Added 'disarm' option to crash recovery.
  src/main/cli/settings.c
  src/main/fc/core.c
  src/main/fc/rc_controls.c
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/io/rcdevice_cam.c
  src/main/osd/osd.c
  src/test/unit/pid_unittest.cc
Labels: RN: IMPROVEMENT

#7927 Flight statistics (odometer) added.
  make/source.mk
  src/main/cli/settings.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/core.c
  src/main/fc/rc_adjustments.c
  src/main/fc/stats.c
  src/main/fc/stats.h
  src/main/pg/pg_ids.h
  src/main/pg/stats.c
  src/main/pg/stats.h
  src/main/target/common_pre.h
  src/test/unit/rc_controls_unittest.cc
Labels: RN: IMPROVEMENT

#7941 Add MCO2 output support for F4
  src/main/drivers/mco.c
  src/main/startup/system_stm32f4xx.c
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#7953 Change serial port config validation to require MSP on VCP port
  src/main/io/serial.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#7986 Added rate limit settings to MSP API 1.42 for configurator.
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#7950 Fix gyro/acc initialization when more than one MPU6000 (or MPU9250) sensor is connected
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
Labels: RN: BUGFIX

#7984 set dyn_notch_min_hz minimum to 60hz
  src/main/cli/settings.c
Labels: RN: BUGFIX

#7993 Fix OSD crash if vario element is enabled but not supported by target
  src/main/osd/osd_elements.c
Labels: RN: BUGFIX

#7995 Allocating OSD_CS resource for MATEKF411 unified config
  unified_targets/configs/MATEKF411.config
Labels: RN: UNIFIED TARGETS

#7935 Refactor dshot command output scheduling logic
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#7838 Improve target landing altitude in gps-rescue
  src/main/cli/settings.c
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
Labels: RN: IMPROVEMENT

#7963 Add target HGLRCF745 to 4.0. Also add Unified Target configuration.
  unified_targets/CONFIGS/HGLRCF745.config
Labels: RN: UNIFIED TARGETS

#7749 Adding string settings
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/test/Makefile
  src/test/unit/cli_unittest.cc
Labels: RN: IMPROVEMENT

#7952 Show only 3 significant digits in vbat OSD element
  src/main/osd/osd_elements.c
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#8007 Fix gps_rescue fast return speed in some edge cases
  src/main/flight/gps_rescue.c
Labels: Applied to Branch, RN: BUGFIX

#8017 Added RSSI and Link Quality warnings
  src/main/cli/settings.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#7859 Gps rescue menus for OSD
  make/source.mk
  src/main/cms/cms_menu_failsafe.c
  src/main/cms/cms_menu_gps_rescue.c
  src/main/cms/cms_menu_gps_rescue.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#8020 Fixed CLI help for 'feature'.
  src/main/cli/cli.c
Labels: RN: BUGFIX

#7841 Add DSHOT telemetry motor level packet stats
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/cli.c
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/fc/core.c
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#7994 OSD: combined ON/ARM timer
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8010 Replaced !FS! fly mode with *FS* due to missing '!' in OSD font
  src/main/osd/osd_elements.c
Labels: RN: BUGFIX

#8016 OSD timers safety checks
  src/main/fc/config.c
  src/main/osd/osd.c
  src/main/osd/osd.h
Labels: RN: BUGFIX

#8025 Maximize OSD stats display lines based on video mode
  src/main/osd/osd.c
Labels: RN: IMPROVEMENT

#8027 Add target HGLRCF405 to 4.0.
  HGLRCF405.config
Labels: RN: UNIFIED TARGETS

#8033 Really fix gyro detection code code for multi gyro setups.
  src/main/sensors/gyro.c
Labels: RN: BUGFIX

#8035 OSD: use nice AMP symbol in post flight stats instead of ordinary "A"
  src/main/osd/osd.c
Labels: RN: IMPROVEMENT

#8029 Add target HGLRCF411 to 4.0.
  unified_targets/configs/HGLRCF411.config
Labels: RN: UNIFIED TARGETS

#8097 VIVAF4AIO
  docs/boards/Board - VIVAF4AIO.md
  src/main/target/DALRCF405/VIVAF4AIO.mk
  src/main/target/DALRCF405/target.c
  src/main/target/DALRCF405/target.h
  unified_targets/configs/VIVAF4AIO.config
Labels: RN: NEW TARGET

#7881 Added rx configuration for DJI_HDL receiver
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/sbus.c
Labels: RN: IMPROVEMENT

#8005 Re-enabled VTX table support.
  src/main/target/STM32F4DISCOVERY/target.h
  src/main/target/common_pre.h
Labels: Householding

#8014 OSD: allow to present odometer on post flight screen
  src/main/cli/settings.c
  src/main/osd/osd.c
  src/main/osd/osd.h
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8093 Fixed assignment of random timer for pins without configured timer option.
  src/main/drivers/timer_common.c
Labels: RN: BUGFIX

#7917 Changes to vtx cli command
  src/main/cli/cli.c
  src/main/io/vtx_control.c
  src/main/io/vtx_control.h
Labels: RN: IMPROVEMENT

#8037 [Docs] Further update Building in Windows
  docs/development/Building in Windows.md
Labels: Documentation update

#8043 For Discussion: modify filter defaults to reduce risk of flyaways
  src/main/flight/pid.c
  src/main/sensors/gyro.c
Labels: RN: SAFETY IMPROVEMENT

#8063 prevent max7456 screen_buffer from overflow
  src/main/drivers/max7456.c
Labels: RN: BUGFIX

#8064 show power level in the smartaudio cms menu
  src/main/cms/cms_menu_vtx_smartaudio.c
Labels: RN: BUGFIX

#8068 Reduce feature cut for BFF3
  src/main/target/BETAFLIGHTF3/target.mk
Labels: Legacy target

#8078 CLRACINGF7 TARGET, add default feature OSD and default RX provider Sbus
  src/main/target/CLRACINGF7/target.h
Labels: RN: TARGET UPDATE

#8085 Move default DEBUG_MODE from common_pre.h into common_defaults_post.h
  src/main/target/common_defaults_post.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#8089 CMS Debug Mode fix
  src/main/blackbox/blackbox.c
Labels: RN: BUGFIX

#8012 pr Implements feature request #1887 rebase add osd
  docs/Battery.md
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/sensors/battery.c
  src/main/sensors/battery.h
Labels: RN: IMPROVEMENT

#8046 FuriousFPV RacePIT target updates
  src/main/target/FF_RACEPIT/config.c
  src/main/target/FF_RACEPIT/target.h
  unified_targets/configs/FF_RACEPIT.config
Labels: RN: TARGET UPDATE, Ready to Merge

#7616 moved the linker files to the src directory head
  Makefile
  src/link/stm32_flash.ld
  src/link/stm32_flash_f103_128k.ld
  src/link/stm32_flash_f103_128k_opbl.ld
  src/link/stm32_flash_f103_256k.ld
  src/link/stm32_flash_f103_64k.ld
  src/link/stm32_flash_f303_128k.ld
  src/link/stm32_flash_f303_256k.ld
  src/link/stm32_flash_f405.ld
  src/link/stm32_flash_f405_opbl.ld
  src/link/stm32_flash_f411.ld
  src/link/stm32_flash_f411_opbl.ld
  src/link/stm32_flash_f446.ld
  src/link/stm32_flash_f722.ld
  src/link/stm32_flash_f74x.ld
  src/link/stm32_flash_f765.ld
  src/link/stm32_flash_f7_split.ld
  src/link/stm32_flash_split.ld
Labels: Cleanup, RN: REFACTORING

#8117 Adding details for VIVA
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8102 Change gyro dynamic lpf throttle update to use the active gyro selection
  src/main/sensors/gyro.c
Labels: RN: BUGFIX

#8120 CC2500 resoure configuration fix
  src/main/cli/cli.c
Labels: RN: BUGFIX

#8091 [H7 LIB] Library patches
  lib/main/STM32H7/Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h743xx.h
  lib/main/STM32H7/Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h750xx.h
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_def.h
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_qspi.h
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_spi.h
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_sdmmc.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
Labels: RN: IMPROVEMENT

#8108 Call initEscEndPoints after changing profiles.
  src/main/cms/cms_menu_imu.c
  src/main/fc/config.c
  src/main/flight/mixer.h
Labels: RN: BUGFIX

#8121 Handle overlooked cases of missing USE_BARO and USE_MAG conditionals
  src/main/blackbox/blackbox.c
  src/main/msp/msp.c
  src/main/sensors/barometer.c
  src/main/target/ALIENWHOOP/config.c
  src/main/telemetry/ibus_shared.c
Labels: RN: BUGFIX

#7936 When GPS Rescue is engaged after a Failsafe, pilot has to manually sw…
  src/main/cli/settings.c
  src/main/fc/config.c
  src/main/fc/core.c
  src/main/fc/core.h
  src/main/flight/failsafe.c
  src/main/flight/failsafe.h
  src/test/Makefile
  src/test/unit/flight_failsafe_unittest.cc
Labels: RN: IMPROVEMENT

#8111 Fixed ordering of the manufacturer list.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8116 Added manufacturer id for Diatone.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8013 Use PT1 for source frame RSSI filtering
  src/main/cli/settings.c
  src/main/pg/rx.c
  src/main/pg/rx.h
  src/main/rx/rx.c
  src/test/unit/rx_ranges_unittest.cc
  src/test/unit/rx_rx_unittest.cc
Labels: RN: IMPROVEMENT

#8114 Added manufacturer id for V-Good.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8129 Fixed SPRACINGF3NEO on maintenance branch.
  src/main/target/SPRACINGF3NEO/config.c
Labels: Fixes broken build, RN: BUGFIX

#8125 Added release notes for 4.0.
  docs/Release Notes/Betaflight 4.0 Release Notes.md
Labels: Documentation update
