Repository betaflight/betaflight, pull requests merged in 2019-05, with the labels that each got.

#8130 Fix to make the AND Logic work on all modes
  src/main/fc/rc_modes.c
Labels: RN: BUGFIX

#8127 Altitde source calculation option
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/flight/position.c
  src/main/flight/position.h
  src/main/pg/pg_ids.h
Labels: RN: IMPROVEMENT

#8136 Respect USE_MAG in GPS rescue code
  src/main/cli/settings.c
  src/main/flight/gps_rescue.c
Labels: RN: BUGFIX

#8135 Report NONE for baro and mag MSP requests if not USE_ed.
  src/main/msp/msp.c
Labels: RN: BUGFIX

#8138 Add new symbols to max7456_symbols.h
  src/main/drivers/max7456_symbols.h
  src/main/osd/osd_elements.c
  src/test/unit/osd_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8153 clean up some spaces before newlines
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/drivers/persistent.c
  src/main/drivers/vtx_table.c
  src/main/msp/msp.c
  src/main/pg/rcdevice.h
  src/main/rx/sbus.c
  src/main/telemetry/hott.c
  src/main/telemetry/jetiexbus.c
  src/main/telemetry/msp_shared.c
  src/main/telemetry/smartport.c
  src/main/vcp_hal/usbd_cdc_interface.c
Labels: RN: IMPROVEMENT

#8145 update unified target MATEKF405
  unified_targets/configs/MATEKF405.config
Labels: RN: UNIFIED TARGETS

#8147 remove extra spaces in src/main/osd/osd_elements.c
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#8140 Incremented maintenance branch version to 4.0.2.
  src/main/build/version.h
Labels: Applied to Branch, Householding

#8133 Fixed USE_VARIO conditional.
  src/main/flight/position.c
  src/main/target/common_post.h
Labels: RN: BUGFIX

#8137 Add SPI RX to STM32F7xx unified targets
  src/main/rx/cc2500_frsky_shared.c
  src/main/target/STM32F745/target.mk
  src/main/target/STM32F7X2/target.mk
  src/main/target/common_unified.h
Labels: RN: IMPROVEMENT

#8146 Dshot bidir inverted
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/fc/core.c
  src/main/fc/init.c
Labels: RN: IMPROVEMENT

#8148 Fix and refactor timerGetXXX in presence/absence of USE_TIMER_MGMT
  src/main/drivers/timer_common.c
Labels: RN: BUGFIX

#8049 Furious FPV PIKOF4OSD motor timer fix
  src/main/target/FF_PIKOF4/target.c
  src/main/target/FF_PIKOF4/target.h
Labels: RN: BUGFIX

#8178 Removed features from AIORACERF3 to fix flash overflow.
  src/main/target/SPRACINGF3EVO/target.mk
Labels: Applied to Branch, Fixes broken build, RN: TARGET UPDATE

#8160 Added manufacturer id for ZeeZ Design.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8158 Fixed missing comments in 'msp.c'.
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#8157 [LED_STRIP] Protect against null timerHardware
  src/main/drivers/light_ws2811strip_hal.c
  src/main/drivers/light_ws2811strip_stdperiph.c
Labels: Bugfix, RN: BUGFIX

#8162 Some cosmetic fixes to 'rc_adjustments.c'.
  src/main/fc/rc_adjustments.c
Labels: Cleanup

#8165 Fixed feedback when changing timer from 'NONE' in CLI.
  src/main/cli/cli.c
Labels: RN: BUGFIX

#8164 Changed failsafe warning back to '!FS!'.
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#8159 Made temperature OSD display consistent.
  src/main/osd/osd_elements.c
  src/test/unit/osd_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8188 Incremented maintenance branch version to 4.0.3.
  src/main/build/version.h
Labels: Householding

#8168 Add conditional for useDshotTelemetry
  src/main/drivers/pwm_output.c
Labels: RN: BUGFIX

#8182 Add MAMBAF722 Target
  src/main/target/MAMBAF722/config.c
  src/main/target/MAMBAF722/target.c
  src/main/target/MAMBAF722/target.h
  src/main/target/MAMBAF722/target.mk
  unified_targets/configs/MAMBAF722.config
Labels: RN: NEW TARGET

#8180 USE_CRSF_LINK_STATISTICS Split from pr 8042
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/rx/crsf.c
  src/main/rx/rx.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
  src/test/unit/rx_crsf_unittest.cc
  src/test/unit/telemetry_crsf_msp_unittest.cc
  src/test/unit/telemetry_crsf_unittest.cc
Labels: RN: IMPROVEMENT

#8169 Change scheduler_optimze_rate to only affect realtime tasks
  src/main/scheduler/scheduler.c
Labels: RN: IMPROVEMENT

#8166 [H7] config_streamer
  src/main/config/config_streamer.c
  src/main/config/config_streamer.h
Labels: RN: IMPROVEMENT

#8167 Reset d_min to 0 if >= D gain for a given axis
  src/main/fc/config.c
Labels: RN: BUGFIX

#8170 [F7 VCP] Fix conditional for USE_USB_ID option
  src/main/vcp_hal/usbd_conf.c
Labels: RN: BUGFIX

#8171 [H7] RCC and IO
  src/main/drivers/io.c
  src/main/drivers/io.h
  src/main/drivers/rcc.h
  src/main/drivers/rcc_types.h
Labels: RN: IMPROVEMENT

#8172 [H7] Enable USB+VCP
  src/main/drivers/serial_usb_vcp.c
  src/main/drivers/serial_usb_vcp.h
  src/main/vcph7/usbd_cdc_interface.c
  src/main/vcph7/usbd_cdc_interface.h
  src/main/vcph7/usbd_conf.c
  src/main/vcph7/usbd_conf.h
  src/main/vcph7/usbd_desc.c
  src/main/vcph7/usbd_desc.h
Labels: RN: IMPROVEMENT

#8174 Allow EEPROM reset without power cycling in DEBUG build
  src/main/fc/init.c
Labels: RN: IMPROVEMENT

#8175 Add new basic feature conditionals
  src/main/drivers/dma.c
  src/main/drivers/dma_stm32f4xx.c
  src/main/drivers/dma_stm32f7xx.c
  src/main/drivers/pwm_output.c
  src/main/drivers/serial_uart.h
  src/main/drivers/sound_beeper.c
  src/main/drivers/timer.c
  src/main/drivers/timer_common.c
  src/main/drivers/timer_hal.c
  src/main/drivers/timer_stm32f10x.c
  src/main/drivers/timer_stm32f30x.c
  src/main/drivers/timer_stm32f4xx.c
  src/main/drivers/timer_stm32f7xx.c
  src/main/fc/config.c
  src/main/fc/init.c
  src/main/flight/mixer.c
  src/main/msp/msp.c
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#8181 Removed legacy F3 target from 'pre-push' target.
  Makefile
Labels: Build System Improvement

#8184 Added altitude symbol in OSD.
  src/main/drivers/max7456_symbols.h
  src/main/osd/osd_elements.c
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#8186 Moved 'rpm_filter' into 'flight'.
  make/source.mk
  src/main/cli/settings.c
  src/main/fc/config.c
  src/main/fc/core.c
  src/main/fc/init.c
  src/main/flight/gyroanalyse.c
  src/main/flight/gyroanalyse.h
  src/main/flight/pid.c
  src/main/flight/rpm_filter.c
  src/main/flight/rpm_filter.h
  src/main/osd/osd.c
  src/main/osd/osd_elements.c
  src/main/sensors/gyro.c
Labels: RN: REFACTORING

#8177 Revise data structures for DSHOT telemetry stats to avoid high CPU load
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot_shared.c
Labels: RN: BUGFIX

#8115 Removed non-library header from 'lib/'.
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC_HID/Inc/usbd_cdc_hid.h
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC_HID/Src/usbd_cdc_hid.c
  src/main/drivers/serial_usb_vcp.c
Labels: RN: REFACTORING

#8187 Renamed 'gyro_filter_impl.h' to 'gyro_filter_impl.c'.
  src/main/sensors/gyro.c
  src/main/sensors/gyro_filter_impl.c
Labels: RN: REFACTORING

#8190 Remove CLI "display_name" and notify that "name" will be removed
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#7696 Add PID and Rate profile names, osd elements and cli config
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/pg/pg_ids.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#8191 [H7] Port RTC backup register based persistent storage for H7
  src/main/drivers/persistent.c
Labels: RN: IMPROVEMENT

#8194 [H7] Enable software serial
  src/main/drivers/serial_softserial.c
Labels: RN: IMPROVEMENT

#8195 [H7] Enable CAMERA_CONTROL
  src/main/drivers/camera_control.c
Labels: RN: IMPROVEMENT

#8196 Add D_MIN Gain and Advance to CMS
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT

#8202 Add gps rescue landing altitude and distance to CMS
  src/main/cms/cms_menu_gps_rescue.c
Labels: RN: IMPROVEMENT

#8200 [H7] Enable DMA facility
  src/main/drivers/dma.h
  src/main/drivers/dma_stm32h7xx.c
Labels: RN: IMPROVEMENT

#8198 [H7] Enable UART
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stm32h7xx.c
Labels: RN: IMPROVEMENT

#8201 [H7] Enable timer
  src/main/drivers/timer.h
  src/main/drivers/timer_def.h
  src/main/drivers/timer_hal.c
  src/main/drivers/timer_stm32h7xx.c
Labels: RN: IMPROVEMENT

#8161 Extend the scope of BOXPARALYZE to cover stick commands, adjustments, and CMS.
  src/main/cms/cms.c
  src/main/cms/cms.h
  src/main/fc/core.c
  src/main/fc/rc_controls.c
  src/test/unit/cms_unittest.cc
Labels: RN: IMPROVEMENT, Testing Required

#8219 Fix MODE_STRING blank value output and improve validation messages
  src/main/cli/cli.c
Labels: RN: BUGFIX

#8220 [NUCLEOF722] Comment out unneeded def for CS pin
  src/main/target/NUCLEOF722/target.h
Labels: RN: TARGET UPDATE

#8221 [H7] STM32H750 - Fix CPU crash on cold boot when VCP is enabled.
  src/main/drivers/serial_usb_vcp.c
Labels: RN: BUGFIX

#8222 Fix pageMaxRow use before update
  src/main/cms/cms.c
Labels: RN: BUGFIX

#8225 [F7] Move non-library CDC-HID code out of lib tree
  make/mcu/STM32F7.mk
  src/main/vcp_hal/usbd_cdc_hid.c
Labels: RN: IMPROVEMENT

#8192 [H7] Enable EXTI
  src/main/drivers/exti.c
  src/main/drivers/io.h
Labels: RN: IMPROVEMENT

#8228 Add note in stack_check that refers developers to the linker scripts
  src/main/drivers/stack_check.c
Labels: Documentation update

#8231 Revise PID/Rate profile names to use get/set and eliminate extra PG's
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/osd/osd_elements.c
  src/main/pg/pg_ids.h
Labels: RN: IMPROVEMENT

#8234 Add unified target for IFLIGHT_F411_PRO board.
  unified_targets/configs/IFLIGHT_F411_PRO.config
Labels: RN: UNIFIED TARGETS

#8243 Add TRANSTECF7 target
  src/main/target/TRANSTECF7/config.c
  src/main/target/TRANSTECF7/target.c
  src/main/target/TRANSTECF7/target.h
  src/main/target/TRANSTECF7/target.mk
  unified_targets/configs/TRANSTECF7.config
Labels: RN: NEW TARGET, RN: UNIFIED TARGETS

#8209 Add XILOF4
  src/main/target/XILOF4/config.c
  src/main/target/XILOF4/target.c
  src/main/target/XILOF4/target.h
  src/main/target/XILOF4/target.mk
  unified_targets/configs/XILOF4.config
Labels: RN: NEW TARGET, RN: UNIFIED TARGETS

#8235 [H7] Modify USB Middleware library for composite device support
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc/usbd_hid.h
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
Labels: RN: IMPROVEMENT

#8236 [H7] Enable HID Device
  src/main/io/usb_cdc_hid.c
  src/main/target/common_pre.h
  src/main/vcph7/usbd_cdc_hid.c
  src/main/vcph7/usbd_cdc_interface.c
  src/main/vcph7/usbd_conf.c
Labels: RN: IMPROVEMENT

#8239 Add FLASH bootloader request to RESET reason
  src/main/drivers/persistent.h
Labels: RN: IMPROVEMENT

#8240 [H7] Add PID-Audio support
  src/main/drivers/audio_stm32h7xx.c
Labels: RN: IMPROVEMENT

#8199 [H7] Enable SPI with resurrected HAL-based driver from v3.1.7
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_hal.c
  src/main/drivers/bus_spi_impl.h
  src/main/drivers/bus_spi_pinconfig.c
  src/main/fc/init.c
  src/main/target/common_defaults_post.h
Labels: RN: IMPROVEMENT

#8227 [H7] Enable SDCard/SDIO using HAL driver
  src/main/drivers/sdcard_sdio_baremetal.c
  src/main/drivers/sdio_f4xx.c
  src/main/drivers/sdio_f7xx.c
  src/main/drivers/sdio_h7xx.c
  src/main/drivers/sdmmc_sdio.h
  src/main/fc/init.c
  src/main/io/asyncfatfs/asyncfatfs.c
  src/main/msc/usbd_storage_sdio.c
Labels: RN: IMPROVEMENT

#8237 [FLASHFS] Reinitialise flashFs after erasing flash chip.
  src/main/cli/cli.c
  src/main/msp/msp.c
Labels: RN: BUGFIX

#8238 [FLASH] Allow flash initialisation without flashfs support.
  src/main/fc/init.c
Labels: RN: BUGFIX

#8258 Disable MSC if BLACKBOX is disabled
  src/main/target/common_post.h
Labels: RN: IMPROVEMENT

#8259 Prevent flashfs from initializing in absence of a flash device
  src/main/fc/init.c
Labels: RN: IMPROVEMENT

#8260 [H7] USB LIB Middlewares change: Avoid null hhid from being deferenced
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c
Labels: RN: BUGFIX

#8261 [H7] Apply HAL VCP TX fix
  src/main/vcph7/usbd_cdc_interface.c
  src/main/vcph7/usbd_cdc_interface.h
Labels: RN: IMPROVEMENT

#8246 Use distance to home symbol into the OSD
  src/main/drivers/max7456_symbols.h
  src/main/osd/osd_elements.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8273 Update 4.0x filters
  src/main/flight/pid.c
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#8263 Add W25N01G 1Gb NAND flash support
  make/source.mk
  src/main/drivers/flash.c
  src/main/drivers/flash_w25n01g.c
  src/main/drivers/flash_w25n01g.h
  src/main/target/common_post.h
Labels: RN: IMPROVEMENT

#8269 Update overlooked license header
  src/main/drivers/bus_quadspi_hal.c
  src/main/drivers/bus_spi_hal.c
  src/main/io/displayport_hott.c
  src/main/io/displayport_hott.h
  src/main/msc/usbd_storage.h
  src/main/msc/usbd_storage_emfat.h
Labels: Householding

#8208 add AIRBOTF7
  src/main/target/AIRBOTF7/target.c
  src/main/target/AIRBOTF7/target.h
  src/main/target/AIRBOTF7/target.mk
  unified_targets/configs/AIRBOTF7.config
Labels: RN: NEW TARGET, RN: UNIFIED TARGETS

#8249 add a new target named "VGOODRCF4
  src/main/target/VGOODRCF4/target.c
  src/main/target/VGOODRCF4/target.h
  src/main/target/VGOODRCF4/target.mk
  unified_targets/configs/VGOODRCF4.config
Labels: RN: NEW TARGET, RN: UNIFIED TARGETS

#8264 Add camera control for Mamba Fury F4 Mini using PB9
  src/main/target/FURYF4/target.c
  src/main/target/FURYF4/target.h
  unified_targets/configs/FURYF4OSD.config
Labels: RN: TARGET UPDATE

#8278 Update flash drivers to support QuadSPI
  src/main/drivers/flash.c
  src/main/drivers/flash_impl.h
  src/main/drivers/flash_m25p16.c
  src/main/drivers/flash_w25m.c
  src/main/drivers/flash_w25n01g.c
  src/main/pg/flash.c
  src/main/pg/flash.h
Labels: RN: IMPROVEMENT

#8287 More ACC_x_ALIGN cleanup
  src/main/target/AIRBOTF7/target.h
  src/main/target/MAMBAF722/target.h
  src/main/target/OMNIBUSF7NANOV7/target.h
  src/main/target/TRANSTECF7/target.h
  src/main/target/VGOODRCF4/target.h
  src/main/target/XILOF4/target.h
Labels: RN: TARGET UPDATE

#8267 Enabled Multi Gyro on OmnibusF4 Nano V7
  src/main/target/OMNIBUSF4NANOV7/target.h
  src/main/target/OMNIBUSF4NANOV7/target.mk
  unified_targets/configs/OMNIBUSF4NANOV7.config
Labels: RN: TARGET UPDATE

#8279 Add CLI flash_verify command
  src/main/cli/cli.c
  src/main/io/flashfs.c
  src/main/io/flashfs.h
Labels: RN: IMPROVEMENT

#8281 Remove deprecated USE_MULTI_GYRO
  src/main/target/AG3X/target.h
  src/main/target/AIRBOTF7/target.h
  src/main/target/DALRCF722DUAL/target.h
  src/main/target/EXF722DUAL/target.h
  src/main/target/FLYWOOF7DUAL/target.h
  src/main/target/FOXEERF722DUAL/target.h
  src/main/target/MATEKF722SE/target.h
  src/main/target/OMNIBUSF4FW/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/SPRACINGF7DUAL/target.h
Labels: RN: TARGET UPDATE

#8284 Increase async FAT filesystem cache sectors to prevent blackbox header corruption
  src/main/io/asyncfatfs/asyncfatfs.c
Labels: RN: BUGFIX

#8256 Prevent 'system_hse_mhz' from showing in non-F4 'diff'/'dump'.
  src/main/cli/settings.c
  src/main/target/common_post.h
  unified_targets/configs/CLRACINGF7.config
  unified_targets/configs/ELINF722.config
  unified_targets/configs/FLYWOOF7DUAL.config
  unified_targets/configs/FOXEERF722DUAL.config
  unified_targets/configs/HGLRCF745.config
  unified_targets/configs/JHEF7DUAL.config
  unified_targets/configs/KAKUTEF7.config
  unified_targets/configs/KAKUTEF7MINI.config
  unified_targets/configs/MATEKF722.config
  unified_targets/configs/MATEKF722SE.config
  unified_targets/configs/NERO.config
  unified_targets/configs/OMNIBUSF4NANOV7.config
  unified_targets/configs/OMNIBUSF7NANOV7.config
  unified_targets/configs/OMNIBUSF7V2.config
  unified_targets/configs/RUSHCORE7.config
  unified_targets/configs/SPRACINGF7DUAL.config
  unified_targets/configs/TRANSTECF7.config
Labels: RN: BUGFIX, RN: UNIFIED TARGETS

#8254 Fixed 'flash' make rule, added support for DFU flashing (requires 'dfu-util').
  Makefile
Labels: Build System Improvement

#8290 Add tenths of a second OSD timer precision option
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/test/unit/osd_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8251 Added kiss rates
  src/main/cli/settings.c
  src/main/fc/controlrate_profile.h
  src/main/fc/rc.c
Labels: RN: IMPROVEMENT

#8295 Adding configuration for the 'no-response' app.
  .github/no-response.yml
Labels: Householding

#8297 Add flash partitioning system
  src/main/cli/cli.c
  src/main/cms/cms_menu_blackbox.c
  src/main/drivers/flash.c
  src/main/drivers/flash.h
  src/main/drivers/flash_w25n01g.c
  src/main/fc/init.c
  src/main/io/flashfs.c
  src/main/msp/msp.c
  src/main/osd/osd.c
Labels: RN: IMPROVEMENT

#8299 Add common_deprecated_post.h to flag deprecated target defines
  src/main/platform.h
  src/main/target/AIRBOTF7/target.h
  src/main/target/FF_RACEPIT/target.h
  src/main/target/FLYWOOF7DUAL/target.h
  src/main/target/JHEF7DUAL/target.h
  src/main/target/OMNIBUSF4NANOV7/target.h
  src/main/target/OMNIBUSF7NANOV7/target.h
  src/main/target/RUSHCORE7/target.h
  src/main/target/UAVPNG030MINI/target.h
  src/main/target/VGOODRCF4/target.h
  src/main/target/XILOF4/target.h
  src/main/target/common_deprecated_post.h
Labels: RN: IMPROVEMENT

#8300 Really fixed flash erasing.
  src/main/cli/cli.c
  src/main/msp/msp.c
Labels: RN: BUGFIX

#8301 Add gps rescue option for not climbing to highest altitude of flight
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
Labels: RN: IMPROVEMENT

#8302 Fixed setting / printing of VAR_UINT32 values.
  src/main/cli/cli.c
Labels: RN: BUGFIX

#8303 Fixed printing of reset DMA options in 'diff'.
  src/main/cli/cli.c
Labels: RN: BUGFIX

#8305 Add timer info to CLI 'timer' command.
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#8306 Added selection by alternate function to CLI 'timer'.
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#8282 Use RC Smoothing initialized settings rather than current PG values
  src/main/blackbox/blackbox.c
  src/main/cli/cli.c
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/fc/rc.c
  src/main/fc/rc.h
  src/main/fc/rc_controls.h
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT, RN: SAFETY IMPROVEMENT

#8247 Link Quality multiple sources without Aux DUP of 8232
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/rx/crsf.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/test/Makefile
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#8308 [H7] H743 system and build files
  make/mcu/STM32H7.mk
  make/source.mk
  make/targets.mk
  src/main/drivers/system_stm32h7xx.c
  src/main/platform.h
  src/main/startup/startup_stm32h743xx.s
  src/main/target/common_pre.h
  src/main/target/link/stm32_flash_h743_2m.ld
  src/main/target/link/stm32_flash_h750.ld
  src/main/target/stm32h7xx_hal_conf.h
  src/main/target/system_stm32h7xx.c
  src/main/target/system_stm32h7xx.h
Labels: RN: IMPROVEMENT

#8309 USE_RX_RSSI_DBM Split from pr 8042
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/rx/crsf.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#8316 Add CMS menu entry level control of forced reboot on changes
  src/main/cms/cms.c
  src/main/cms/cms.h
  src/main/cms/cms_menu_blackbox.c
  src/main/cms/cms_menu_builtin.c
  src/main/cms/cms_menu_misc.c
  src/main/cms/cms_menu_saveexit.c
  src/main/cms/cms_menu_saveexit.h
  src/main/cms/cms_types.h
  src/test/unit/cms_unittest.cc
Labels: RN: IMPROVEMENT

#8319 New target NUCLEOH743
  src/main/target/NUCLEOH743/config.c
  src/main/target/NUCLEOH743/target.c
  src/main/target/NUCLEOH743/target.h
  src/main/target/NUCLEOH743/target.mk
Labels: RN: NEW TARGET

#8318 Add gps rescue altitude mode to CMS
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms_menu_gps_rescue.c
Labels: RN: IMPROVEMENT

#8272 Add OSD profile names feature
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8276 [VTX] SmartAudio conversion to VTX table and V2.1 implementation
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/drivers/vtx_common.c
  src/main/drivers/vtx_table.c
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_smartaudio.h
Labels: RN: IMPROVEMENT

#8324 Add unit test for sumd serial rx implementation
  src/test/Makefile
  src/test/unit/rx_sumd_unittest.cc
Labels: UNITTEST

#8329 Fixed build for targets without RC smoothing.
  src/main/msp/msp.c
Labels: RN: BUGFIX

#8335 Require reboot for CMS failsafe submenu changes to be consistent with the Configurator
  src/main/cms/cms_menu_failsafe.c
  src/main/cms/cms_menu_gps_rescue.c
Labels: RN: IMPROVEMENT

#8339 Move the Altitude alignment left in the OSD
  src/main/osd/osd_elements.c
  src/test/unit/osd_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#8100 Add switchable gyro to cms options
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT

#8338 Fix VTX chan to 0 via SetFreqByMHz
  src/main/msp/msp.c
Labels: RN: BUGFIX

#8321 SPRacingF3NEO - Add BARO support.
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/SPRACINGF3NEO/target.mk
Labels: RN: TARGET UPDATE

#8322 Fix and remove USE_RTC6705_CLK_HACK
  src/main/drivers/vtx_rtc6705.c
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/SPRACINGF4NEO/target.h
Labels: RN: BUGFIX

#8323 Fix compile errors if USE_GPS_RESCUE is not defined
  src/main/target/common_post.h
Labels: RN: BUGFIX

#8328 fix adc pins
  src/main/target/AIRBOTF7/target.h
  unified_targets/configs/AIRBOTF7.config
Labels: RN: TARGET UPDATE, RN: UNIFIED TARGETS

#8331 Fix copy of profiles with last index
  src/main/flight/pid.c
Labels: RN: BUGFIX

#8333 TARGET Update: add IIC Baro, SoftSerial, 1G Flash support for EXF722DUAL board.
  src/main/target/EXF722DUAL/target.h
  unified_targets/configs/EXF722DUAL.config
Labels: RN: TARGET UPDATE, RN: UNIFIED TARGETS

#8346 SPARKY2 Assign correct pins for I2C1
  src/main/target/SPARKY2/target.h
Labels: Bugfix, RN: BUGFIX

#8341 Updated message for no-response bot.
  .github/no-response.yml
Labels: Householding

#8342 Fix flash m25p16 driver sector erase
  src/main/drivers/flash_m25p16.c
Labels: RN: BUGFIX

#8343 Use full erase when possible for FLASHFS erase - fixes single partition targets
  src/main/drivers/flash.c
  src/main/drivers/flash.h
  src/main/io/flashfs.c
Labels: RN: BUGFIX

#8320 Changed 'timer' output to list timers based on alternate function.
  src/main/cli/cli.c
  unified_targets/configs/AIRBOTF7.config
  unified_targets/configs/ALIENFLIGHTF4.config
  unified_targets/configs/ALIENFLIGHTNGF7.config
  unified_targets/configs/ALIENFLIGHTNGF7_Dual.config
  unified_targets/configs/BEEROTORF4.config
  unified_targets/configs/CLRACINGF4.config
  unified_targets/configs/CLRACINGF7.config
  unified_targets/configs/CRAZYBEEF4FR.config
  unified_targets/configs/DYSF4PRO.config
  unified_targets/configs/ELINF405.config
  unified_targets/configs/ELINF722.config
  unified_targets/configs/EXF722DUAL.config
  unified_targets/configs/FF_RACEPIT.config
  unified_targets/configs/FLYWOOF405.config
  unified_targets/configs/FLYWOOF411.config
  unified_targets/configs/FLYWOOF7DUAL.config
  unified_targets/configs/FOXEERF722DUAL.config
  unified_targets/configs/FURYF4OSD.config
  unified_targets/configs/HGLRCF405.config
  unified_targets/configs/HGLRCF411.config
  unified_targets/configs/HGLRCF745.config
  unified_targets/configs/IFLIGHTF4_TWIN_G.config
  unified_targets/configs/IFLIGHT_F411_PRO.config
  unified_targets/configs/JHEF7DUAL.config
  unified_targets/configs/KAKUTEF7.config
  unified_targets/configs/KAKUTEF7MINI.config
  unified_targets/configs/MAMBAF722.config
  unified_targets/configs/MATEKF405.config
  unified_targets/configs/MATEKF411.config
  unified_targets/configs/MATEKF722.config
  unified_targets/configs/MATEKF722SE.config
  unified_targets/configs/NERO.config
  unified_targets/configs/OMNIBUSF4.config
  unified_targets/configs/OMNIBUSF4FW.config
  unified_targets/configs/OMNIBUSF4NANOV7.config
  unified_targets/configs/OMNIBUSF4SD.config
  unified_targets/configs/OMNIBUSF4V6.config
  unified_targets/configs/OMNIBUSF7NANOV7.config
  unified_targets/configs/OMNIBUSF7V2.config
  unified_targets/configs/RUSHCORE7.config
  unified_targets/configs/SPRACINGF7DUAL.config
  unified_targets/configs/SYNERGYF4.config
  unified_targets/configs/TRANSTECF7.config
  unified_targets/configs/VGOODRCF4.config
  unified_targets/configs/VIVAF4AIO.config
  unified_targets/configs/XILOF4.config
Labels: RN: IMPROVEMENT

#7907 adjust Ki to keep total i action the same and reduce abs control defa…
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT
