Repository betaflight/betaflight, pull requests merged in 2019-10, with the labels that each got.

#8975 Removing directories with unused support code.
  support/buildserver/upload.php
  support/flash.bat
  support/stmloader/Makefile
  support/stmloader/loader.c
  support/stmloader/serial.c
  support/stmloader/serial.h
  support/stmloader/stmbootloader.c
  support/stmloader/stmbootloader.h
Labels: Cleanup

#8963 Updated the Unified Target creation documentation to reflect the new naming.
  .github/pull_request_template.md
  README.md
  docs/TargetMaintenance/CreatingAUnifiedTarget.md
  unified_targets/docs/Manufacturers.md
Labels: Documentation update, Unified Targets

#8973 Updated unified '.gitattributes' file.
  .gitattributes
Labels: Build System Improvement, Housekeeping

#8992 Add DSHOT bidir info to the Blackbox
  src/main/blackbox/blackbox.c
Labels: RN: IMPROVEMENT

#8979 Add LuxMiniF7
  docs/boards/Board - LuxMiniF7.md
  docs/boards/images/LuxMiniF7.png
  src/main/target/LUXMINIF7/config.c
  src/main/target/LUXMINIF7/target.c
  src/main/target/LUXMINIF7/target.h
  src/main/target/LUXMINIF7/target.mk
Labels: RN: NEW TARGET

#8982 Register changes fired by modified EOL code for html files
  lib/main/STM32F1/Drivers/STM32F1xx_HAL_Driver/Release_Notes.html
  lib/main/STM32F1/Middlewares/ST/STM32_USB_Device_Library/Release_Notes.html
  lib/main/STM32F1/Middlewares/ST/STM32_USB_Host_Library/Release_Notes.html
  lib/main/STM32F3/Drivers/STM32F3xx_HAL_Driver/Release_Notes.html
  lib/main/STM32F3/Middlewares/ST/STM32_USB_Device_Library/Release_Notes.html
  lib/main/STM32F4/Drivers/STM32F4xx_StdPeriph_Driver/Release_Notes.html
  lib/main/STM32F4/Middlewares/ST/STM32_USB_Device_Library/Release_Notes.html
  lib/main/STM32F7/Drivers/CMSIS/Device/ST/STM32F7xx/Release_Notes.html
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Release_Notes.html
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Release_Notes.html
  lib/main/STM32_USB_OTG_Driver/Release_Notes.html
Labels: Housekeeping

#8985 doc update for OMNIBUSF4NANOV7
  docs/boards/Board - OMNIBUSF4NANOV7.md
Labels: Documentation update

#9000 Fixed RX / telemetry port sharing for iBus.
  src/main/io/serial.c
  src/main/rx/cc2500_frsky_x.c
  src/main/rx/ibus.c
  src/main/rx/sbus.c
  src/main/rx/spektrum.c
  src/main/rx/sumd.c
  src/main/rx/sumh.c
  src/main/rx/xbus.c
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/ltm.c
  src/main/telemetry/mavlink.c
  src/main/telemetry/smartport.c
  src/main/telemetry/telemetry.c
  src/main/telemetry/telemetry.h
  src/test/unit/io_serial_unittest.cc
  src/test/unit/rx_sumd_unittest.cc
  src/test/unit/telemetry_crsf_unittest.cc
Labels: RN: BUGFIX

#9009 Fixed instances of int functions being used in float expressions.
  src/main/sensors/gyro.c
Labels: RN: BUGFIX

#9012 Added more details on how to request a manufacturer id to the documentation.
  docs/TargetMaintenance/CreatingAUnifiedTarget.md
Labels: Documentation update

#9010 Fixed telemetry for FrSky X SPI.
  src/main/rx/cc2500_frsky_d.c
  src/main/rx/cc2500_frsky_x.c
Labels: RN: BUGFIX

#9017 Fix targets with broken ADC DMA definition.
  src/main/target/LUXMINIF7/target.h
  src/main/target/RUSHCORE7/target.h
  src/main/target/XILOF4/target.h
  src/main/target/common_deprecated_post.h
Labels: RN: BUGFIX

#9022 Add missing ARMING_DISABLED_DSHOT_BITBANG name string
  src/main/fc/runtime_config.c
Labels: RN: BUGFIX

#9036 Fix MC type STM32F711
  src/main/target/ALIENFLIGHTF1/AlienFlight.md
  src/main/target/ALIENFLIGHTF3/AlienFlight.md
  src/main/target/ALIENFLIGHTF4/AlienFlight.md
  src/main/target/ALIENFLIGHTNGF7/AlienFlight.md
Labels: Documentation update

#9038 Fix Incorrect Gyro Setting For SP Racing H7 Ex
  unified_targets/configs/SPRACINGH7EXTREME.config
Labels: Unified Targets

#9040 Support per MSP client arming disable
  src/main/msp/msp.c
  src/main/msp/msp.h
  src/main/msp/msp_serial.c
  src/main/msp/msp_serial.h
  src/main/telemetry/msp_shared.c
  src/test/unit/telemetry_crsf_msp_unittest.cc
Labels: RN: SAFETY IMPROVEMENT

#8978 Change selected F411 targets to use timer dshot instead of bitbang dshot
  src/main/cli/settings.c
  src/main/drivers/dshot_dpwm.c
  src/main/fc/config.c
  src/main/pg/motor.h
  src/main/target/AG3X/target.h
  src/main/target/AIKONF4/target.h
  src/main/target/AIRBOTF7/target.h
  src/main/target/AIRF7/target.h
  src/main/target/BEEROTORF4/target.h
  src/main/target/BETAFLIGHTF3/target.h
  src/main/target/CLRACINGF4/target.h
  src/main/target/CLRACINGF7/target.h
  src/main/target/CRAZYBEEF3FR/target.h
  src/main/target/DALRCF405/target.h
  src/main/target/DALRCF722DUAL/target.h
  src/main/target/ELINF722/target.h
  src/main/target/EXF722DUAL/target.h
  src/main/target/FF_PIKOBLX/target.h
  src/main/target/FLYWOOF7DUAL/target.h
  src/main/target/FOXEERF405/target.h
  src/main/target/FOXEERF722DUAL/target.h
  src/main/target/HAKRCF405/target.h
  src/main/target/HAKRCF411/target.h
  src/main/target/HAKRCF722/target.h
  src/main/target/IMPULSERCF3/target.h
  src/main/target/JHEF7DUAL/target.h
  src/main/target/LUXMINIF7/target.h
  src/main/target/MAMBAF411/target.h
  src/main/target/MAMBAF722/target.h
  src/main/target/MATEKF405/target.h
  src/main/target/MATEKF411/target.h
  src/main/target/MATEKF411RX/target.h
  src/main/target/MATEKF722/target.h
  src/main/target/MATEKF722SE/target.h
  src/main/target/MERAKRCF405/target.h
  src/main/target/MERAKRCF722/target.h
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF4NANOV7/target.h
  src/main/target/OMNIBUSF7NANOV7/target.h
  src/main/target/OMNINXT/target.h
  src/main/target/REVO/target.h
  src/main/target/REVOLT/target.h
  src/main/target/RUSHCORE7/target.h
  src/main/target/SKYZONEF405/target.h
  src/main/target/SPEEDYBEEF4/target.h
  src/main/target/SPEEDYBEEF7/target.h
  src/main/target/SPRACINGF4NEO/target.h
  src/main/target/SPRACINGF7DUAL/target.h
  src/main/target/TMOTORF4/target.h
  src/main/target/TMOTORF7/target.h
  src/main/target/TRANSTECF411/target.h
  src/main/target/TRANSTECF7/target.h
  src/main/target/WORMFC/target.h
  src/main/target/XILOF4/target.h
  src/main/target/YUPIF7/target.h
  src/main/target/common_deprecated_post.h
  src/main/target/common_post.h
Labels: RN: BUGFIX

#9046 Incremented version to 4.2.0, updated README, templates.
  .github/pull_request_template.md
  README.md
  src/main/build/version.h
Labels: Housekeeping

#8813 Add RC channel values to OSD
  src/main/cli/settings.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#8929 Add NUCLEOF103RG target
  make/targets_list.mk
  src/link/stm32_flash_f103_1024k.ld
  src/main/target/NUCLEOF103RG/README.txt
  src/main/target/NUCLEOF103RG/config.c
  src/main/target/NUCLEOF103RG/hardware_revision.c
  src/main/target/NUCLEOF103RG/hardware_revision.h
  src/main/target/NUCLEOF103RG/initialisation.c
  src/main/target/NUCLEOF103RG/target.c
  src/main/target/NUCLEOF103RG/target.h
  src/main/target/NUCLEOF103RG/target.mk
Labels: Legacy target

#8977 Add ascend and descend rate to MSP
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#8980 UART DMA code refactor
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stm32f10x.c
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/drivers/serial_uart_stm32h7xx.c
Labels: RN: REFACTORING

#9007 Fix flash filesystem mass storage support for > 128MB flash
  src/main/msc/emfat_file.c
Labels: RN: IMPROVEMENT

#9021 Fix W25M (stacked die SPI flash) support
  src/main/drivers/flash_w25m.c
  src/main/drivers/flash_w25n01g.c
  src/main/drivers/flash_w25n01g.h
  src/main/target/NUCLEOF7/target.h
  src/main/target/NUCLEOF7/target.mk
  src/main/target/common_unified.h
Labels: RN: BUGFIX

#9027 add gps_ublox_use_galileo and gps_set_home_point_once to MSP
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#9011 Clarified the name of the 'clear to send' function in SmartPort.
  src/main/rx/cc2500_frsky_x.c
  src/main/telemetry/smartport.c
  src/main/telemetry/smartport.h
Labels: RN: REFACTORING

#8921 Removed pins not available in LPQFP-100 or 144 packages.
  src/main/drivers/timer_stm32f4xx.c
  src/main/drivers/timer_stm32f7xx.c
  src/main/drivers/timer_stm32h7xx.c
Labels: RN: IMPROVEMENT

#9053 Add W25N01G driver to AlienFlightNG F7 target
  src/main/target/ALIENFLIGHTNGF7/target.h
Labels: RN: TARGET UPDATE

#9013 MSP DisplayPort support improvement
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/drivers/display.h
  src/main/drivers/max7456.c
  src/main/fc/init.c
  src/main/io/serial.h
  src/main/msp/msp_serial.c
  src/main/msp/msp_serial.h
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#9056 Update W25N01G driver to work with floating /WP pin in SPI mode
  src/main/drivers/flash_w25n01g.c
Labels: RN: IMPROVEMENT

#9051 Update target flywoof411 config
  src/main/target/FLYWOOF411/target.h
Labels: RN: TARGET UPDATE

#8764 F3 - Fix type conversion warning in ADC code.
  src/main/drivers/adc_stm32f30x.c
Labels: Legacy target

#8772 DSHOT telemetry optimizations
  src/link/stm32_flash.ld
  src/main/drivers/dma.c
  src/main/drivers/dma.h
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/system.c
  src/main/target/common_pre.h
Labels: Rebase / Squash required

#8938 Add NUCLEOF303RE target
  make/targets_list.mk
  src/link/stm32_flash_f303_512k.ld
  src/main/target/NUCLEOF303RE/README.txt
  src/main/target/NUCLEOF303RE/config.c
  src/main/target/NUCLEOF303RE/target.c
  src/main/target/NUCLEOF303RE/target.h
  src/main/target/NUCLEOF303RE/target.mk
Labels: Legacy target

#8981 Add deprecated checking for CAMERA_CONTROL_PIN
  src/main/target/AIRBOTF7/target.c
  src/main/target/AIRBOTF7/target.h
  src/main/target/CLRACINGF4/target.h
  src/main/target/HAKRCF405/target.h
  src/main/target/HAKRCF411/target.h
  src/main/target/KAKUTEF4/target.h
  src/main/target/KAKUTEF7/target.c
  src/main/target/KAKUTEF7/target.h
  src/main/target/TRANSTECF7/target.h
  src/main/target/WORMFC/target.h
  src/main/target/XILOF4/target.c
  src/main/target/XILOF4/target.h
  src/main/target/common_deprecated_post.h
Labels: RN: REFACTORING

#9064 Added flash tools support to Unified Targets.
  src/main/target/common_unified.h
Labels: RN: TARGET UPDATE

#9062 Stamp out use of box 39 for pinio, use 40 USER1 instead
  src/main/target/CLRACINGF4/config.c
  src/main/target/CLRACINGF7/config.c
Labels: RN: TARGET UPDATE

#9066 Replace individual CMS vtx menus with a single entry that redirects to the correct protocol menu
  make/source.mk
  src/main/cms/cms.c
  src/main/cms/cms_menu_blackbox.c
  src/main/cms/cms_menu_builtin.c
  src/main/cms/cms_menu_failsafe.c
  src/main/cms/cms_menu_gps_rescue.c
  src/main/cms/cms_menu_imu.c
  src/main/cms/cms_menu_ledstrip.c
  src/main/cms/cms_menu_misc.c
  src/main/cms/cms_menu_osd.c
  src/main/cms/cms_menu_power.c
  src/main/cms/cms_menu_saveexit.c
  src/main/cms/cms_menu_vtx_common.c
  src/main/cms/cms_menu_vtx_common.h
  src/main/cms/cms_menu_vtx_rtc6705.c
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/cms/cms_menu_vtx_tramp.c
  src/main/cms/cms_types.h
  src/test/unit/cms_unittest.cc
Labels: RN: IMPROVEMENT

#9067 Added documentation for limitation on EXF722DUAL.
  docs/boards/Board - EXF722DUAL.md
Labels: Documentation update

#8774 Fix F3 DMA request mapping when using `USE_DMA_SPEC`.
  src/main/drivers/dma_reqmap.c
  src/main/pg/adc.c
  src/main/pg/adc.h
  src/main/target/common_defaults_post.h
Labels: Legacy target

#8862 Add OSD distance from home alarm
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#9070 Renamed 'fcTasksInit' to 'tasksInit'.
  src/main/fc/init.c
  src/main/fc/tasks.c
  src/main/fc/tasks.h
Labels: RN: REFACTORING

#9071 Made 'cliProcessCustomDefaults' static.
  src/main/cli/cli.c
Labels: RN: REFACTORING

#9074 Cleaned up W25N01G code.
  src/main/drivers/flash_w25n01g.c
Labels: Cleanup

#9075 Remove rc is duplicate frame
  src/main/fc/rc.c
  src/main/fc/rc.h
Labels: Cleanup

#9029 Revise feature logic to separate runtime and config settings
  src/main/cli/cli.c
  src/main/config/feature.c
  src/main/config/feature.h
  src/main/fc/config.c
  src/main/fc/config.h
  src/main/msp/msp.c
  src/main/target/COLIBRI_RACE/i2c_bst.c
  src/test/unit/cli_unittest.cc
Labels: RN: IMPROVEMENT

#9073 Cleaned up 'taskUpdateRxMain'.
  src/main/fc/tasks.c
Labels: RN: REFACTORING

#9060 Add debug code for blackbox output bandwidth measurement
  src/main/blackbox/blackbox_io.c
  src/main/build/debug.c
  src/main/build/debug.h
  src/test/unit/blackbox_unittest.cc
Labels: RN: IMPROVEMENT

#9031 Add ACC_CALIB arming disabled reason if ACC is required but not calibrated
  src/main/cli/settings.c
  src/main/fc/core.c
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/osd/osd_elements.h
  src/main/sensors/acceleration.c
  src/main/sensors/compass.c
  src/main/sensors/sensors.h
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT, RN: SAFETY IMPROVEMENT

#9076 Update CreatingAUnifiedTarget.md to make process clearer, step by step
  docs/TargetMaintenance/CreatingAUnifiedTarget.md
Labels: Documentation update

#9026 Add MSP allowArmingWithoutFix
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#9080 Cleanup unused accResetFlightDynamicsTrims() function
  src/main/sensors/acceleration.c
Labels: Cleanup

#9081 Fix CLI task output header alignment
  src/main/cli/cli.c
Labels: RN: BUGFIX

#9092 Add compass support for EXF722DUAL board.
  src/main/target/EXF722DUAL/target.h
  src/main/target/EXF722DUAL/target.mk
Labels: RN: TARGET UPDATE

#9100 QUADSPI - Fix quadSpiTransmit1LINE when writing 1 or more bytes of data.
  src/main/drivers/bus_quadspi_hal.c
Labels: Bugfix, RN: BUGFIX

#9089 Serial blackbox: check TX buffer space before calling serialWrite
  src/main/blackbox/blackbox_io.c
Labels: RN: BUGFIX

#9094 Add gps rescue altitude mode setting to MSP
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#9087 Fix ESC_SENSOR blackbox debug array overflow for more than 4 motors
  src/main/sensors/esc_sensor.c
Labels: RN: BUGFIX

#9099 amend notes in make_config_hex.sh for what released
  src/utils/make_config_hex.sh
Labels: Documentation update

#9111 Change max7456 driver to only perform stall check once a second instead of every drawScreen call
  src/main/drivers/max7456.c
Labels: RN: IMPROVEMENT

#9049 Removed legacy targets from the list of targets built in CI.
  Makefile
  make/targets_list.mk
Labels: Build System Improvement

#9112 Fix data type overflow in HDOP calculation in Smartport telemetry
  src/main/telemetry/smartport.c
Labels: RN: BUGFIX

#9129 Add OSD background support for the static portions of display elements
  src/main/cms/cms.c
  src/main/drivers/display.c
  src/main/drivers/display.h
  src/main/drivers/max7456.c
  src/main/drivers/max7456.h
  src/main/io/displayport_crsf.c
  src/main/io/displayport_hott.c
  src/main/io/displayport_max7456.c
  src/main/io/displayport_msp.c
  src/main/io/displayport_oled.c
  src/main/io/displayport_srxl.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/osd/osd_elements.h
Labels: RN: IMPROVEMENT

#9116 Cleaned up parameter groups in Makefile.
  make/source.mk
Labels: Build System Improvement

#9117 Moved MCU specific defines into 'common_pre.h' if not used in the STM32 libraries.
  make/mcu/STM32F7.mk
  make/mcu/STM32H7.mk
  src/main/target/common_pre.h
Labels: RN: REFACTORING

#9120 [Clean-up]Remove redundant 'MAX_ADC_SUPPORTED' def in pg/adc.h
  src/main/pg/adc.h
Labels: Cleanup, RN: BUGFIX
