Repository betaflight/betaflight, pull requests merged in 2019-07, with the labels that each got.

#8511 Fixed formatting in the 'VTX' documentation.
  docs/VTX.md
Labels: Documentation update

#8015 Gps rescue pid controller based on vertical velocity
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
Labels: RN: IMPROVEMENT

#8513 Revert #7907 to return abs control default to zero
  src/main/flight/pid.c
Labels: RN: BUGFIX

#8515 Add FF to yaw, reduce yaw P and I
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#8518 Incremented maintenance branch version to 4.0.5.
  src/main/build/version.h
Labels: Applied to Branch, Housekeeping

#8517 Fixed file permissions.
  src/main/rx/cc2500_common.c
  src/main/rx/cc2500_common.h
  src/main/rx/cc2500_sfhss.c
  src/main/rx/cc2500_sfhss.h
  src/main/startup/startup_stm32h743xx.s
  src/main/startup/stm32h7xx_hal_conf.h
  src/main/startup/system_stm32h7xx.h
  src/main/target/FLYWOOF411/config.c
  src/main/target/FLYWOOF411/target.c
  src/main/target/FLYWOOF411/target.h
  src/main/target/FLYWOOF411/target.mk
  src/main/target/FLYWOOF7DUAL/target.c
  src/main/target/FLYWOOF7DUAL/target.mk
  src/main/target/HAKRCF405/target.c
  src/main/target/HAKRCF405/target.mk
  src/main/target/HAKRCF722/target.c
  src/main/target/MATEKF722SE/config.c
  src/main/target/MATEKF722SE/target.c
  src/main/target/MATEKF722SE/target.mk
  src/main/vcp_hal/usbd_conf_stm32h7xx.c
Labels: Cleanup

#8519 Add ascend and descend rates to CMS
  src/main/cms/cms_menu_gps_rescue.c
Labels: RN: IMPROVEMENT

#8512 Reset out of range filter cutoffs
  src/main/fc/config.c
Labels: RN: BUGFIX

#8503 Fixed CLI DMA presence mask support.
  src/main/cli/cli.c
Labels: RN: BUGFIX

#8484 Minor conditional-compilation fixes.
  src/main/cli/cli.c
  src/main/drivers/pwm_output.c
  src/main/drivers/rx/rx_pwm.c
  src/main/flight/mixer.c
  src/main/msp/msp_box.c
  src/main/target/SITL/target.c
  src/main/target/common_post.h
Labels: RN: BUGFIX

#8524 Fixed two typos in PR template
  .github/pull_request_template.md
Labels: Housekeeping

#8527 Added manufacturer id for T-motor.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8528 Added manufacturer id for AIKON.
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8530 Properly add hex file building to '<target>_flash'.
  Makefile
Labels: Build System Improvement

#8529 Added RTC6705 driver to Unified Targets.
  src/main/target/STM32F405/target.mk
  src/main/target/STM32F411/target.mk
  src/main/target/STM32F745/target.mk
  src/main/target/STM32F7X2/target.mk
  src/main/target/common_unified.h
  unified_targets/configs/SPRACINGF7DUAL.config
Labels: RN: IMPROVEMENT, RN: UNIFIED TARGETS

#8533 Added TMOTORF4 target
  docs/boards/Board - TMOTORF4.md
  docs/boards/images/TMOTORF4-BottomSide.jpg
  docs/boards/images/TMOTORF4-TopSide.png
  src/main/target/TMOTORF4/config.c
  src/main/target/TMOTORF4/target.c
  src/main/target/TMOTORF4/target.h
  src/main/target/TMOTORF4/target.mk
  unified_targets/configs/SPEDIXF4.config
  unified_targets/configs/TMOTORF4.config
Labels: RN: NEW TARGET

#8540 Fixed DMA resource conflicts for target BEEROTORF4.
  src/main/target/BEEROTORF4/target.c
  src/main/target/BEEROTORF4/target.h
  unified_targets/configs/BEEROTORF4.config
Labels: RN: TARGET UPDATE, RN: UNIFIED TARGETS

#8543 Fixed resource ownership / define for SPI RX bind pin.
  src/main/pg/rx_spi.c
  src/main/rx/rx_spi_common.c
  src/main/target/CRAZYBEEF3FR/target.h
  src/main/target/EACHIF3/target.h
  src/main/target/MATEKF411RX/target.h
  src/main/target/MIDELICF3/target.h
  src/main/target/common_defaults_post.h
  unified_targets/configs/CRAZYBEEF4FR.config
  unified_targets/configs/MATEKF411RX.config
Labels: RN: BUGFIX

#8544 Fixed default setting for gyro 2.
  src/main/target/common_defaults_post.h
Labels: RN: BUGFIX

#8552 Expose camera control button resistance values
  src/main/cli/settings.c
  src/main/drivers/camera_control.c
  src/main/drivers/camera_control.h
Labels: RN: IMPROVEMENT

#8558 add launch configuration directories to .gitignore
  .gitignore
Labels: Housekeeping

#8564 Update Development.md
  docs/development/Development.md
Labels: Documentation update

#8474 Refactored arbitrary gyro and mag alignment.
  src/main/cli/settings.c
  src/main/common/maths.c
  src/main/common/maths.h
  src/main/common/sensor_alignment.c
  src/main/common/sensor_alignment.h
  src/main/common/sensor_alignment_impl.h
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/compass/compass.h
  src/main/drivers/sensor.h
  src/main/fc/config.c
  src/main/msp/msp.c
  src/main/pg/gyrodev.c
  src/main/pg/gyrodev.h
  src/main/sensors/acceleration.c
  src/main/sensors/boardalignment.c
  src/main/sensors/boardalignment.h
  src/main/sensors/compass.c
  src/main/sensors/compass.h
  src/main/sensors/gyro.c
  src/main/target/BLUEJAYF4/config.c
  src/main/target/FF_RACEPIT/config.c
  src/main/target/OMNIBUSF4/target.h
  src/main/target/OMNIBUSF7/target.h
  src/main/target/common_defaults_post.h
  src/test/Makefile
  src/test/unit/alignsensor_unittest.cc
  src/test/unit/sensor_gyro_unittest.cc
Labels: RN: MINOR FEATURE

#8549 Fix beeper support for IF_F411_PRO and IF_F405_TWING unified targets
  unified_targets/configs/IFLIGHTF4_TWIN_G.config
  unified_targets/configs/IFLIGHT_F411_PRO.config
Labels: RN: UNIFIED TARGETS

#8555 COLIBRI_RACE: BST GPS fix
  src/main/target/COLIBRI_RACE/i2c_bst.c
Labels: RN: TARGET UPDATE

#8566 we got moved from travis-ci.org to travis-ci.com awhile back
  README.md
Labels: Documentation update

#8557 Fix use of sdcard.cardDetectPin before it is initialised.
  src/main/drivers/sdcard.c
  src/main/drivers/sdcard.h
  src/main/drivers/sdcard_impl.h
  src/main/drivers/sdcard_sdio_baremetal.c
  src/main/drivers/sdcard_spi.c
  src/main/fc/init.c
Labels: Bugfix, RN: BUGFIX

#8536 SPRacingH7EXTREME - First betaflight STM32H750 400Mhz FC.
  docs/boards/Board - SPRacingH7EXTREME.md
  docs/boards/images/spracingh7extreme-pcb-bottom.jpg
  docs/boards/images/spracingh7extreme-pcb-top.jpg
  docs/boards/images/spracingstackingvtx-pcb-bottom.jpg
  docs/boards/images/spracingstackingvtx-pcb-top.jpg
  docs/boards/images/spracingstackingvtx-with-module.jpg
  docs/boards/images/spracingstackingvtx-with-unify-pro.jpg
  make/targets_list.mk
  src/main/target/SPRACINGH7EXTREME/config.c
  src/main/target/SPRACINGH7EXTREME/target.c
  src/main/target/SPRACINGH7EXTREME/target.h
  src/main/target/SPRACINGH7EXTREME/target.mk
  unified_targets/configs/SPRACINGH7EXTREME.config
Labels: New Target, RN: NEW TARGET, RN: UNIFIED TARGETS

#8537 SPRACINGH7NANO - First betaflight STM32H750 400Mhz 20x20 mount FC.
  docs/boards/Board - SPRacingH7NANO.md
  docs/boards/images/spracingh7nano-cpu-e-s.jpg
  docs/boards/images/spracingh7nano-cpu.jpg
  docs/boards/images/spracingh7nano-pcb-top-with-connectors.jpg
  docs/boards/images/spracingh7nano-pcb-top.jpg
  src/main/target/SPRACINGH7NANO/config.c
  src/main/target/SPRACINGH7NANO/target.c
  src/main/target/SPRACINGH7NANO/target.h
  src/main/target/SPRACINGH7NANO/target.mk
  unified_targets/configs/SPRACINGH7NANO.config
Labels: New Target, RN: NEW TARGET, RN: UNIFIED TARGETS

#8574 Refactored SD card initialisation to contain SD card detection initialisation.
  src/main/drivers/sdcard.c
  src/main/drivers/sdcard.h
  src/main/drivers/sdcard_impl.h
  src/main/fc/init.c
Labels: RN: REFACTORING

#8534 Motor code refactor (Phase 1)
  make/source.mk
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms.c
  src/main/drivers/dshot.c
  src/main/drivers/dshot.h
  src/main/drivers/dshot_command.c
  src/main/drivers/dshot_command.h
  src/main/drivers/dshot_dpwm.c
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/motor.c
  src/main/drivers/motor.h
  src/main/drivers/nvic.h
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/pwm_output_dshot_hal_hal.c
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/drivers/pwm_output_dshot_shared.h
  src/main/drivers/serial_escserial.c
  src/main/drivers/sound_beeper.c
  src/main/fc/config.c
  src/main/fc/core.c
  src/main/fc/init.c
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/pid.c
  src/main/flight/rpm_filter.c
  src/main/io/beeper.c
  src/main/io/serial_4way.c
  src/main/msp/msp.c
  src/main/osd/osd_elements.c
  src/main/pg/motor.c
  src/main/pg/motor.h
  src/main/sensors/esc_sensor.c
  src/main/target/SITL/target.c
  src/main/telemetry/srxl.c
  src/test/unit/cli_unittest.cc
  src/test/unit/cms_unittest.cc
Labels: RN: REFACTORING

#8542 Enabled support for targets supporting RTC6705 on hardware and software SPI.
  src/main/drivers/vtx_rtc6705.c
  src/main/drivers/vtx_rtc6705_soft_spi.c
  src/main/drivers/vtx_rtc6705_soft_spi.h
  src/main/target/FISHDRONEF4/target.mk
  src/main/target/MOTOLABF4/target.mk
  src/main/target/SPRACINGF3NEO/target.h
  src/main/target/SPRACINGF4EVO/target.h
  src/main/target/SPRACINGF4NEO/target.h
  src/main/target/SPRACINGF7DUAL/target.h
  src/main/target/SPRACINGF7DUAL/target.mk
  src/main/target/SPRACINGH7EXTREME/target.mk
  src/main/target/common_post.h
Labels: RN: IMPROVEMENT

#8587 [F1] Legacy maintenance: Update boot loader request related to current
  src/main/drivers/system_stm32f10x.c
Labels: Legacy target

#8580 Add target HGLRCF405AS to 4.0
  unified_targets/configs/HGLRCF405AS.config
Labels: RN: UNIFIED TARGETS

#8579 Allow resorting to fake gyro if USE_FAKE_GYRO is defined
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#8570 Set the filesystem timestamps of Blackbox files using the local timezone
  src/main/io/asyncfatfs/asyncfatfs.c
Labels: RN: IMPROVEMENT

#8594 Fix incorrect VREF calibration
  src/main/drivers/adc.c
  src/main/drivers/adc.h
  src/main/drivers/adc_impl.h
  src/main/drivers/adc_stm32f7xx.c
  src/main/sensors/adcinternal.c
  src/main/target/OMNINXT/hardware_revision.c
Labels: RN: BUGFIX

#8599 Added idle interrupt callback to UART driver
  src/main/drivers/serial.h
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_init.c
  src/main/drivers/serial_uart_stm32f10x.c
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32f7xx.c
Labels: RN: IMPROVEMENT

#8600 Fix BMP388 driver for build without USE_EXTI
  src/main/drivers/barometer/barometer_bmp388.c
Labels: RN: BUGFIX

#8601 Added manufacturer id for 'MerakRC'.
  unified_targets/docs/Manufacturers.md
Labels: Documentation update, RN: UNIFIED TARGETS

#8556 Add uint32 support to the MODE_ARRAY CLI parameter type
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#8595 MPU configuration service
  make/mcu/STM32H7.mk
  src/link/stm32_flash_h743_2m.ld
  src/link/stm32_flash_h750_128k.ld
  src/link/stm32_flash_h750_exst.ld
  src/main/drivers/memprot.h
  src/main/drivers/memprot_hal.c
  src/main/drivers/memprot_stm32h7xx.c
  src/main/drivers/system_stm32h7xx.c
  src/main/io/asyncfatfs/asyncfatfs.c
  src/main/startup/system_stm32h7xx.c
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#8610 [F7] Set DShot DMA buffer attribute to FAST_RAM_ZERO_INIT
  src/main/drivers/dshot_dpwm.h
Labels: Bugfix, RN: BUGFIX

#8488 Added target variant NUCLEOH743_RAMCONFIG.
  Makefile
  docs/boards/Board - NucleoH743 RAM based.md
  docs/boards/images/NUCLEOH743_RAMBASED_boot_address.png
  docs/boards/images/NUCLEOH743_RAMBASED_option_bytes.png
  docs/boards/images/NUCLEOH743_RAMBASED_program.png
  docs/boards/images/NUCLEOH743_RAMBASED_run.png
  make/mcu/STM32H7.mk
  make/source.mk
  src/link/stm32_flash_h743_ram_based.ld
  src/main/target/NUCLEOH743/NUCLEOH743_RAMBASED.mk
  src/main/target/NUCLEOH743/target.mk
  unified_targets/configs/OMNIBUSF4_test.config
Labels: RN: NEW TARGET

#8586 Unify DMA stream and channel handling
  src/main/drivers/adc_impl.h
  src/main/drivers/adc_stm32f10x.c
  src/main/drivers/adc_stm32f30x.c
  src/main/drivers/adc_stm32f4xx.c
  src/main/drivers/adc_stm32f7xx.c
  src/main/drivers/adc_stm32h7xx.c
  src/main/drivers/dma.c
  src/main/drivers/dma.h
  src/main/drivers/dma_reqmap.c
  src/main/drivers/dma_reqmap.h
  src/main/drivers/dma_stm32f4xx.c
  src/main/drivers/dma_stm32f7xx.c
  src/main/drivers/dma_stm32h7xx.c
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/light_ws2811strip_hal.c
  src/main/drivers/light_ws2811strip_stdperiph.c
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/pwm_output_dshot_hal_hal.c
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/drivers/sdcard_sdio_baremetal.c
  src/main/drivers/sdcard_spi.c
  src/main/drivers/sdio_f4xx.c
  src/main/drivers/sdio_f7xx.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_init.c
  src/main/drivers/serial_uart_stm32f10x.c
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/drivers/serial_uart_stm32h7xx.c
  src/main/drivers/timer.h
  src/main/drivers/timer_def.h
  src/main/drivers/transponder_ir_io_hal.c
  src/main/drivers/transponder_ir_io_stdperiph.c
  src/main/msc/usbd_storage_sdio.c
Labels: RN: REFACTORING

#8613 Correct IMU gyro input to be based on sample loop time rather than actual delta time
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#7128 Add support for IRC Tramp race lock flag, and extended VTX status.
  src/main/drivers/vtx_common.c
  src/main/drivers/vtx_common.h
  src/main/io/ledstrip.c
  src/main/io/spektrum_vtx_control.c
  src/main/io/vtx.c
  src/main/io/vtx_rtc6705.c
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_tramp.c
  src/main/msp/msp.c
  src/main/osd/osd_elements.c
  src/main/telemetry/srxl.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT, Tested

#8614 Added Unified Target configuration for MLTEMPF4.
  unified_targets/configs/MLTEMPF4.config
  unified_targets/configs/MLTYPHF4.config
  unified_targets/docs/Manufacturers.md
Labels: RN: UNIFIED TARGETS

#8618 Updating travis to use bionic.
  .travis.yml
Labels: Build System Improvement

#8619 Clear reset reason also upon button initiated EEPROM reset
  src/main/fc/init.c
Labels: RN: BUGFIX

#8628 Fix H7 crashing on boot due to #8599
  src/main/drivers/serial_uart_stm32h7xx.c
Labels: Bugfix

#8625 Let LL Dshot to build without USE_DSHOT_TELEMETRY option
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/pwm_output_dshot_shared.c
Labels: RN: BUGFIX
