Repository betaflight/betaflight, pull requests merged in 2020-12, with the labels that each got.

#10388 Fix BIDIR UART issue #10220
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/drivers/serial_uart_stm32g4xx.c
  src/main/drivers/serial_uart_stm32h7xx.c
Labels: RN: BUGFIX

#10348 Fix VTX tramp protocol for all
  src/main/io/vtx.c
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_tramp.c
Labels: RN: BUGFIX

#10370 New linear mixer (credits to @tylercorleone)
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/mixer_init.c
Labels: RN: IMPROVEMENT, Testing Required

#10383 Optimize pin reconfiguration in DSHOT ISR for H7
  src/main/drivers/io.h
  src/main/drivers/pwm_output_dshot_hal.c
Labels: RN: IMPROVEMENT

#10378 H7 LED strip
  src/link/stm32_flash_h750_128k.ld
  src/link/stm32_flash_h750_1m.ld
  src/link/stm32_ram_h750_exst.ld
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/light_ws2811strip.h
  src/main/drivers/memprot_hal.c
  src/main/target/NUCLEOH743/target.h
Labels: RN: IMPROVEMENT

#10402 Removed deprecated Dshot commands to enable / disable bidirectional Dshot.
  src/main/drivers/dshot_command.c
  src/main/drivers/dshot_command.h
  src/main/drivers/pwm_output_dshot_shared.c
Labels: RN: IMPROVEMENT

#10403 Make test compatible with clang 11 on linux
  src/test/Makefile
Labels: Build System Improvement

#10389 Add debug support to GHST protocol driver
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/rx/ghst.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#10405 Added missing CLI parameter for RSSI dBm.
  src/main/cli/settings.c
Labels: RN: BUGFIX

#10382 Add action to close issues that don't follow any template
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/firmware-bug-report.md
  .github/workflows/issues.yml
Labels: Build System Improvement, Not following template, Template: Bug, Template: Feature Request

#10409 Fixed RAM overflow on NUCLEOH743_RAMBASED.
  src/link/stm32_ram_h743.ld
Labels: Fixes broken build, RN: BUGFIX

#10416 Enabled pull request builds in Azure.
  azure-pipelines.yml
Labels: Build System Improvement

#10419 Add more flash chip support for IFLIGHT_H743_AIO board.
  src/main/target/IFLIGHT_H743_AIO/target.h
Labels: RN: TARGET UPDATE

#10406 Fixed problem when sending blocking Dshot commands with bitbanged Dshot enabled.
  src/main/drivers/dshot_command.c
  src/main/drivers/motor.c
  src/main/drivers/motor.h
Labels: RN: BUGFIX

#10424 Improve OSD blink timing logic
  src/main/fc/tasks.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#10425 Fix multiple div-by-zero related to battery cell count
  src/main/sensors/battery.c
  src/main/telemetry/ibus_shared.c
  src/main/telemetry/smartport.c
  src/test/unit/telemetry_ibus_unittest.cc
Labels: RN: BUGFIX

#10426 Remove heading for 'Additional Context' from issue templates, improve clarity.
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/firmware-bug-report.md
Labels: Documentation update

#10407 Fixed MSP command to send Dshot commands.
  src/main/cli/cli.c
  src/main/msp/msp.c
Labels: RN: BUGFIX

#10408 Cleaned up debug code in Dshot.
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/drivers/pwm_output_dshot_shared.h
Labels: RN: IMPROVEMENT

#10429 Fix logic error for RACEFLIGHT and KISS rates range checks
  src/main/config/config.c
Labels: RN: BUGFIX
