Repository betaflight/betaflight, pull requests merged in 2020-05, with the labels that each got.

#9742 Fixed support for USE_SPI_TRANSACTION.
  src/main/drivers/bus.c
Labels: RN: BUGFIX

#9757 Add 'clean' target to 'unified_zip' Makefile target.
  Makefile
Labels: Build System Improvement

#9751 Fixed the display of lowercase characters in the git revision string in CMS.
  src/main/cms/cms_menu_firmware.c
  src/main/ctype.h
Labels: RN: BUGFIX

#9764 Added instructions for how to add test targets to pull requests.
  .github/pull_request_template.md
  docs/development/Development.md
  docs/development/assets/pull_request_test_targets.png
Labels: Documentation update

#9758 Fixed max_esc_rpm osd statistic to show RPM when dshot telemetry is enabled
  src/main/osd/osd.c
Labels: RN: BUGFIX

#9765 Change gyro driver initialize-only files to size-optimized
  make/source.mk
  src/main/drivers/accgyro/accgyro_mpu3050.c
  src/main/drivers/accgyro/accgyro_spi_icm20649.c
  src/main/drivers/accgyro/accgyro_spi_icm42605.c
  src/main/drivers/accgyro_legacy/accgyro_adxl345.c
  src/main/drivers/accgyro_legacy/accgyro_bma280.c
  src/main/drivers/accgyro_legacy/accgyro_l3g4200d.c
  src/main/drivers/accgyro_legacy/accgyro_mma845x.c
Labels: RN: REFACTORING

#9771 Fix CRC algo for FrSky S.Port and F.Port
  make/source.mk
  src/main/rx/fport.c
  src/main/rx/frsky_crc.c
  src/main/rx/frsky_crc.h
  src/main/telemetry/smartport.c
Labels: RN: BUGFIX

#9775 Added QMC-5883 magnetometer support to SPRACING H7 NANO / ZERO targets
  src/main/target/SPRACINGH7NANO/target.h
  src/main/target/SPRACINGH7NANO/target.mk
  src/main/target/SPRACINGH7ZERO/target.h
  src/main/target/SPRACINGH7ZERO/target.mk
Labels: RN: TARGET UPDATE

#9779 Fixed condition for the 'ANTI GRAVITY' mode switch to hide it wen anti-gravity is disabled.
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/flight/pid.h
  src/main/msp/msp_box.c
Labels: RN: BUGFIX

#9780 Prevent possible buffer overrun in MSPv2 message parsing
  src/main/msp/msp_serial.c
Labels: RN: BUGFIX

#9788 SPRACINGH7NANO - Support I2C4 on motor outputs 5/6.
  src/main/target/SPRACINGH7NANO/target.c
  src/main/target/SPRACINGH7NANO/target.h
Labels: RN: TARGET UPDATE

#9790 Fixed problem with USB VCP when sending packets with a length of a multiple of 64 bytes.
  src/main/vcp_hal/usbd_cdc_interface.c
Labels: Library Patch, RN: BUGFIX

#9789 Fix HAL USB vcp serial 64 byte packet receive bug
  src/main/vcp_hal/usbd_cdc_interface.c
Labels: Library Patch, RN: BUGFIX

#9785 Fix the FrSky CRC fix from #9771 (sorry)
  src/main/rx/frsky_crc.c
Labels: RN: BUGFIX

#9816 Fixed typo in CLI.
  src/main/cli/cli.c
Labels: RN: BUGFIX

#9813 Better description of LED animations
  docs/LedStrip.md
Labels: Documentation update

#9841 Increase minimum gyro rpm Q to 250 for 4.2
  src/main/cli/settings.c
Labels: Bugfix, RN: BUGFIX

#9850 Added timeout for Ublox commands
  src/main/io/gps.c
  src/main/io/gps.h
Labels: RN: BUGFIX

#9842 Fixed display / editing of int16 in CMS.
  src/main/cms/cms.c
Labels: RN: BUGFIX

#9849 Fixing cms power settings
  src/main/cms/cms_menu_power.c
Labels: RN: BUGFIX

#9845 Add ApexF7 docs
  docs/boards/Board - ApexF7.md
  docs/boards/images/APEXF7_small_back.png
  docs/boards/images/APEXF7_small_front.png
Labels: Documentation update

#9810 Fixed pin ownership checks for I2C.
  src/main/drivers/bus_i2c_hal_init.c
  src/main/drivers/bus_i2c_stm32f10x.c
Labels: RN: BUGFIX

#9807 Fixed reporting of configured / detected OSD device.
  src/main/cli/cli.c
  src/main/fc/init.c
  src/main/msp/msp.c
  src/main/osd/osd.c
Labels: RN: BUGFIX
