Repository betaflight/betaflight, pull requests merged in 2020-01, with the labels that each got.

#9342 Fix SITL target build and runtime segfaults
  src/main/fc/init.c
  src/main/target/SITL/target.c
Labels: RN: BUGFIX

#9333 [MSP] Correctly report the configured and active OSD type
  src/main/fc/init.c
  src/main/io/displayport_max7456.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#9319 Merge pull request #9319 from mikeller/fix_osd_tests_for_real
  src/test/unit/osd_unittest.cc
Labels: REFACTORING, UNITTEST

#9317 Merge pull request #9317 from mikeller/make_unit_tests_more_comprehensive
  src/test/unit/pid_unittest.cc
  src/test/unit/rx_ibus_unittest.cc
  src/test/unit/rx_sumd_unittest.cc
  src/test/unit/timer_definition_unittest.cc
Labels: UNITTEST

#9357 Merge pull request #9357 from Asizon/movedebugmode
  src/main/cms/cms_menu_blackbox.c
  src/main/cms/cms_menu_misc.c
Labels: RN: IMPROVEMENT

#9358 Merge pull request #9358 from jflyper/bfdev-g4-libpatch
  lib/main/STM32G4/Drivers/STM32G4xx_HAL_Driver/Inc/stm32g4xx_hal_flash.h
  lib/main/STM32G4/Drivers/STM32G4xx_HAL_Driver/Inc/stm32g4xx_hal_spi.h
  lib/main/STM32G4/Drivers/STM32G4xx_HAL_Driver/Inc/stm32g4xx_ll_dma.h
  lib/main/STM32G4/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi.c
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc/usbd_hid.h
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc/usbd_def.h
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
Labels: Library Patch

#9350 Merge pull request #9350 from s-ol/archlinux-dev-docs
  docs/development/Building in Arch Linux.md
Labels: Documentation update

#9356 fixed CLI segfault when no USE_OSD is set
  src/main/cli/settings.c
  src/main/osd/osd_elements.c
Labels: RN: BUGFIX

#9293 Merge pull request #9293 from Tdogb/crashflip_power
  src/main/cli/settings.c
  src/main/flight/mixer.c
  src/main/flight/mixer.h
Labels: RN: IMPROVEMENT

#9360 Merge pull request #9360 from mikeller/fix_max7456_detection
  src/main/drivers/max7456.c
  src/main/fc/init.c
Labels: Applied to Branch, RN: BUGFIX

#9359 Merge pull request #9359 from mikeller/add_osd_to_status
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/io/displayport_crsf.h
  src/main/io/displayport_frsky_osd.h
  src/main/io/displayport_msp.h
  src/main/osd/osd.h
  src/test/unit/cli_unittest.cc
Labels: RN: IMPROVEMENT

#9372 Add board info to Blackbox log headers
  src/main/blackbox/blackbox.c
Labels: RN: IMPROVEMENT

#9367 [H7] Fix ADC DMA buffer transposing bug
  src/main/drivers/adc_stm32h7xx.c
Labels: RN: BUGFIX

#9329 Fix battery osd precision
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#9368 Added '<target>_zip' target to Makefile.
  Makefile
Labels: Build System Improvement

#9365 Dterm dynamic lowpass filter configurable curve
  src/main/cli/settings.c
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: RN: IMPROVEMENT

#9315 Log disarm reason.
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox.h
  src/main/blackbox/blackbox_fielddefs.h
  src/main/fc/core.c
  src/main/fc/core.h
  src/main/fc/rc_controls.c
  src/main/flight/failsafe.c
  src/main/flight/gps_rescue.c
  src/main/flight/pid.c
  src/main/msp/msp.c
  src/main/target/COLIBRI_RACE/i2c_bst.c
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/flight_failsafe_unittest.cc
  src/test/unit/pid_unittest.cc
  src/test/unit/rc_controls_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: RN: IMPROVEMENT

#9370 [G4] config_streamer support
  src/main/config/config_streamer.c
  src/main/config/config_streamer.h
Labels: RN: IMPROVEMENT

#9371 [G4] Handle symbol collisions for universal EXTI wrapper
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
  src/main/drivers/accgyro/accgyro_spi_l3gd20.c
  src/main/drivers/barometer/barometer_bmp085.c
  src/main/drivers/barometer/barometer_bmp388.c
  src/main/drivers/compass/compass_hmc5883l.c
  src/main/drivers/exti.c
  src/main/drivers/exti.h
  src/main/drivers/rangefinder/rangefinder_hcsr04.c
  src/main/drivers/rx/rx_spi.c
  src/main/rx/a7105_flysky.c
  src/main/rx/cyrf6936_spektrum.c
  src/main/rx/rx_spi.c
Labels: RN: IMPROVEMENT

#9375 Incremented maintenance branch version to 4.1.4.
  src/main/build/version.h
Labels: Applied to Branch, Housekeeping

#9383 Rename FLASH_SIZE to TARGET_FLASH_SIZE
  Makefile
  make/mcu/SITL.mk
  make/mcu/STM32F1.mk
  make/mcu/STM32F3.mk
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  make/mcu/STM32H7.mk
  src/main/sensors/gyro.c
  src/main/target/CJMCU/target.mk
  src/main/target/NUCLEOF103RG/README.txt
  src/main/target/NUCLEOF103RG/target.mk
  src/main/target/NUCLEOF303RE/README.txt
  src/main/target/NUCLEOF303RE/target.mk
  src/main/target/SITL/target.h
  src/main/target/common_pre.h
Labels: Build System Improvement

#9386 Add dterm lpf curve expo to CMS
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT

#9388 Ublox mode selectable with an option
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/io/gps.c
  src/main/io/gps.h
Labels: RN: IMPROVEMENT

#9307 Move targets into legacy targets for 4.1.4.
  make/targets_list.mk
Labels: Housekeeping

#9373 Fix CMS Menu Navigation
  src/main/cms/cms.c
Labels: RN: BUGFIX

#9390 Prevent accidental flash erase in CMS
  src/main/cms/cms_menu_blackbox.c
Labels: RN: IMPROVEMENT

#9363 Add device local blinking support for MSP displayport devices
  src/main/cli/settings.c
  src/main/drivers/display.h
  src/main/io/displayport_msp.c
  src/main/io/displayport_msp.h
  src/main/osd/osd_elements.c
  src/main/pg/displayport_profiles.h
Labels: RN: IMPROVEMENT

#9369 Added 'unified' target to Makefile.
  Makefile
  make/targets_list.mk
Labels: Build System Improvement, Review Required

#9398 [F7][H7] Add pin traverse facility and unused pin initialization
  src/main/drivers/io.c
  src/main/drivers/io.h
  src/main/drivers/system.c
  src/main/drivers/system.h
  src/main/drivers/system_stm32f7xx.c
  src/main/drivers/system_stm32h7xx.c
  src/main/fc/init.c
  src/main/target/SITL/target.c
Labels: RN: BUGFIX

#9395 [G4] MEMPROT support
  src/main/drivers/memprot_stm32g4xx.c
Labels: RN: IMPROVEMENT

#9396 [G4] IO and RCC support
  src/main/drivers/io.c
  src/main/drivers/io.h
  src/main/drivers/rcc.h
Labels: RN: IMPROVEMENT

#9397 [G4] DMA support
  src/main/cli/cli.c
  src/main/drivers/dma.h
  src/main/drivers/dma_reqmap.c
  src/main/drivers/dma_reqmap.h
  src/main/drivers/dma_stm32g4xx.c
  src/main/pg/timerup.c
Labels: RN: IMPROVEMENT

#9402 Fix tasks check function max time not being reset along with other stats
  src/main/cli/cli.c
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/test/unit/cli_unittest.cc
Labels: RN: BUGFIX

#9401 fixed bricked #beeper and #beacon enrty
  src/main/io/beeper.c
Labels: RN: BUGFIX

#9376 Handle unused pin state at the end of initialization
  src/main/drivers/system_stm32f10x.c
  src/main/drivers/system_stm32f30x.c
  src/main/drivers/system_stm32f4xx.c
Labels: RN: IMPROVEMENT

#9392 Improve duplicate packet handling
  src/main/flight/interpolated_setpoint.c
Labels: RN: IMPROVEMENT

#9406 [G4] Persistent object support
  src/main/drivers/persistent.c
  src/main/drivers/system.h
Labels: RN: IMPROVEMENT

#9332 [MSP] Add support for MSP2_COMMON_SERIAL_CONFIG / MSP2_COMMON_SET_SERIAL_CONFIG
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_common.h
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#9389 Antigravity gain decoupled from Iterm
  src/main/fc/rc.c
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: RN: IMPROVEMENT

#9411 Updating documentation to include 'Disable VTX Control' and 'Launch Control'
  docs/Modes.md
Labels: Documentation update

#9327 Simplify and improve Dynamic Notch
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms_menu_imu.c
  src/main/flight/gyroanalyse.c
  src/main/flight/gyroanalyse.h
  src/main/msp/msp.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: RN: IMPROVEMENT

#9414 Added the git revision to the names of generated files.
  Makefile
Labels: Build System Improvement

#9416 Fixed missing spaces after 'if'.
  src/main/cms/cms_menu_vtx_rtc6705.c
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
  src/main/drivers/sdio_f7xx.c
  src/main/drivers/serial_escserial.c
  src/main/fc/core.c
  src/main/flight/gps_rescue.c
  src/main/flight/pid.c
  src/main/rx/a7105_flysky.c
  src/main/rx/cc2500_frsky_x.c
  src/test/unit/link_quality_unittest.cc
Labels: Cleanup

#9418 Fixed initialisation of unused pins on STM32F411.
  src/main/drivers/timer_stm32f4xx.c
  src/main/target/STM32F411/target.h
Labels: RN: BUGFIX

#9408 Skip DYNAMIC read only entries in CMS
  src/main/cms/cms.c
Labels: RN: IMPROVEMENT

#9421 Fix compile errors if USE_VTX_TABLE is not defined
  src/main/cli/cli.c
  src/main/io/vtx_smartaudio.c
Labels: RN: BUGFIX

#9420 Exclude SWD pins from being initialised as pull up if unused.
  src/main/drivers/resource.c
  src/main/drivers/resource.h
  src/main/drivers/system.c
  src/main/drivers/system.h
  src/main/fc/init.c
  src/main/target/SITL/target.c
Labels: RN: BUGFIX
