Repository betaflight/betaflight, pull requests merged in 2020-03, with the labels that each got.

#9518 REBOOT_REQUIRED flag to cms power options, unified confirm page options
  src/main/cms/cms_menu_power.c
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/cms/cms_menu_vtx_tramp.c
Labels: RN: BUGFIX

#9528 [G4] Treat LPUART1 as UART9
  src/main/drivers/dma_reqmap.c
  src/main/drivers/serial_pinconfig.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stm32g4xx.c
  src/main/io/serial.c
  src/main/io/serial.h
  src/main/pg/serial_uart.c
  src/main/target/common_defaults_post.h
Labels: RN: IMPROVEMENT

#9524 [H7] LPUART support
  src/main/drivers/serial_uart_stm32h7xx.c
  src/main/target/NUCLEOH743/target.h
Labels: RN: IMPROVEMENT

#9526 Added timeline for the 4.2 release.
  README.md
Labels: Housekeeping

#9531 Added QMC-5883 magnetometer support to SPRACING H7 EXTREME target
  src/main/target/SPRACINGH7EXTREME/target.h
  src/main/target/SPRACINGH7EXTREME/target.mk
Labels: RN: TARGET UPDATE

#9535 Remove unused typedefs for DMA stream/channel
  src/main/drivers/pwm_output_dshot_shared.h
  src/main/drivers/transponder_ir_io_hal.c
Labels: RN: IMPROVEMENT

#9537 [Camera Control] Use timerClock() instead of predefined constant
  src/main/drivers/camera_control.c
Labels: RN: BUGFIX

#9527 Add missing acc calibration to status
  src/main/msp/msp.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#9506 quick rates system
  src/main/cli/settings.c
  src/main/fc/controlrate_profile.h
  src/main/fc/rc.c
Labels: RN: IMPROVEMENT

#9538 [G4] Transponder support
  src/main/drivers/transponder_ir.h
  src/main/drivers/transponder_ir_arcitimer.c
  src/main/drivers/transponder_ir_erlt.c
  src/main/drivers/transponder_ir_ilap.c
  src/main/drivers/transponder_ir_io_hal.c
Labels: RN: IMPROVEMENT

#9530 Show errors when resetting to custom defaults.
  src/main/cli/cli.c
  src/main/io/displayport_msp.c
Labels: RN: IMPROVEMENT

#9539 Add Dynamic Idle to msp
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#9544 Simplify and improve motor protocol PID loop limiting
  src/main/config/config.c
Labels: RN: IMPROVEMENT

#9545 Revise pid_process_denom default logic
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#9546 Fix CLI LED command validation
  src/main/cli/cli.c
Labels: RN: BUGFIX

#9511 Added protocol level RX frame rate measurement for FrSky FPort.
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/fc/core.c
  src/main/fc/tasks.c
  src/main/rx/crsf.c
  src/main/rx/fport.c
  src/main/rx/ibus.c
  src/main/rx/jetiexbus.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/sbus.c
  src/main/rx/spektrum.c
  src/main/rx/srxl2.c
  src/main/rx/sumd.c
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: RN: IMPROVEMENT

#9551 Removed legacy targets from 'pre-push' target.
  Makefile
Labels: Build System Improvement

#9554 fixes wrong comparison operators
  src/main/cli/cli.c
Labels: RN: BUGFIX

#9549 Add support for Bosch BMI270 gyro/accelerometer sensor
  lib/main/BoschSensortec/BMI270-Sensor-API/LICENSE
  lib/main/BoschSensortec/BMI270-Sensor-API/README.md
  lib/main/BoschSensortec/BMI270-Sensor-API/betaflight_info.txt
  lib/main/BoschSensortec/BMI270-Sensor-API/bmi2.c
  lib/main/BoschSensortec/BMI270-Sensor-API/bmi2.h
  lib/main/BoschSensortec/BMI270-Sensor-API/bmi270.c
  lib/main/BoschSensortec/BMI270-Sensor-API/bmi270.h
  lib/main/BoschSensortec/BMI270-Sensor-API/bmi2_defs.h
  lib/main/BoschSensortec/BMI270-Sensor-API/bmi2_ois.c
  lib/main/BoschSensortec/BMI270-Sensor-API/bmi2_ois.h
  lib/main/BoschSensortec/BMI270-Sensor-API/example/basic.c
  lib/main/BoschSensortec/BMI270-Sensor-API/example/crt_ex.c
  lib/main/BoschSensortec/BMI270-Sensor-API/example/motion_interrupt.c
  lib/main/BoschSensortec/BMI270-Sensor-API/example/step_counter.c
  lib/main/BoschSensortec/BMI270-Sensor-API/example/wrist_gesture.c
  lib/main/BoschSensortec/BMI270-Sensor-API/example/wrist_wear_wakeup.c
  make/source.mk
  src/main/cli/settings.c
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/accgyro/accgyro_spi_bmi270.c
  src/main/drivers/accgyro/accgyro_spi_bmi270.h
  src/main/drivers/accgyro/gyro_sync.c
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/gyro.c
  src/main/target/common_unified.h
Labels: RN: IMPROVEMENT

#9550 Added option to display RX SNR dB for CRSF instead of RSSI dBm.
  src/main/cli/settings.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/pg/rx.c
  src/main/pg/rx.h
  src/main/rx/a7105_flysky.h
  src/main/rx/crsf.c
  src/main/rx/crsf.h
  src/main/rx/rx.c
  src/main/rx/rx.h
Labels: Needs entry in Release Notes, RN: IMPROVEMENT

#9558 Revise pid_process_denom default logic - second try
  src/main/flight/pid.c
Labels: RN: BUGFIX

#9560 Add validation to MSP for the rc_smoothing_auto_factor setting
  src/main/cli/settings.c
  src/main/fc/rc.h
  src/main/msp/msp.c
Labels: RN: SAFETY IMPROVEMENT

#9565 Switched SBus to use the generic last frame time function.
  src/main/rx/sbus.c
Labels: RN: IMPROVEMENT

#9563 Fixed frame handling for FrSky SPI RX.
  src/main/rx/cc2500_frsky_x.c
Labels: RN: BUGFIX

#9562 Added warning about pull requests from 'master'.
  .github/issue_template.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  LICENSE
Labels: Documentation update

#9567 [H7] Explicitly initialize I2C peripheral clock sources
  src/main/startup/system_stm32h7xx.c
Labels: RN: IMPROVEMENT

#9564 Cleaned up the RX handler some.
  src/main/cli/cli.c
  src/main/fc/core.c
  src/main/fc/core.h
  src/main/fc/rc.c
  src/main/fc/rc.h
  src/main/fc/tasks.c
  src/main/flight/interpolated_setpoint.c
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/cli_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: RN: IMPROVEMENT

#9572 Rearranged how Unified Targets are defined.
  src/main/target/STM32F405/target.h
  src/main/target/STM32F405/target.mk
  src/main/target/STM32F411/target.c
  src/main/target/STM32F411/target.h
  src/main/target/STM32F745/target.c
  src/main/target/STM32F7X2/target.c
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32F7X2/target.mk
  src/main/target/STM32_UNIFIED/STM32F405.mk
  src/main/target/STM32_UNIFIED/STM32F411.mk
  src/main/target/STM32_UNIFIED/STM32F745.mk
  src/main/target/STM32_UNIFIED/STM32F7X2.mk
  src/main/target/STM32_UNIFIED/STM32_UNIFIED.nomk
  src/main/target/STM32_UNIFIED/target.c
  src/main/target/STM32_UNIFIED/target.h
  src/main/target/STM32_UNIFIED/target.mk
Labels: RN: IMPROVEMENT

#9575 [I2C] Introduce computational I2C waveform configuration for HAL based MCUs
  make/mcu/STM32F7.mk
  make/mcu/STM32H7.mk
  make/source.mk
  src/main/drivers/bus_i2c_hal.c
  src/main/drivers/bus_i2c_hal_init.c
  src/main/startup/system_stm32f7xx.c
  src/main/startup/system_stm32h7xx.c
  src/main/target/NUCLEOH743/target.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#9574 Increase OSD srate max setting for using new rate systems
  src/main/cms/cms_menu_imu.c
  src/main/config/config.c
Labels: RN: IMPROVEMENT

#9576 Generalised frame rate calculation.
  src/main/fc/rc.c
  src/main/rx/crsf.c
  src/main/rx/ibus.c
  src/main/rx/jetiexbus.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/spektrum.c
  src/main/rx/srxl2.c
  src/main/rx/sumd.c
Labels: RN: IMPROVEMENT

#9548 [G4] I2C support
  src/main/drivers/bus_i2c_config.c
  src/main/drivers/bus_i2c_hal_init.c
  src/main/drivers/bus_i2c_impl.h
Labels: RN: IMPROVEMENT

#9577 Cleaned up the inclusion of the microcode for BMI270.
  lib/main/BoschSensortec/BMI270-Sensor-API/betaflight_info.txt
  lib/main/BoschSensortec/BMI270-Sensor-API/bmi270.h
  make/source.mk
  src/main/drivers/accgyro/accgyro_spi_bmi270.c
  src/main/target/STM32F745/target.h
  src/main/target/STM32F745/target.mk
  src/main/target/STM32_UNIFIED/target.h
  src/main/target/STM32_UNIFIED/target.mk
Labels: RN: IMPROVEMENT

#9578 Added custom (switch) box naming.
  src/main/cli/settings.c
  src/main/config/config.h
  src/main/fc/rc_modes.c
  src/main/fc/rc_modes.h
  src/main/msp/msp_box.c
  src/main/pg/pg_ids.h
  src/main/pg/piniobox.c
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#9579 Max rate independent of deadband
  src/main/fc/rc.c
Labels: RN: IMPROVEMENT

#9582 Split initialization from gyro.c for flash savings
  make/source.mk
  src/main/cli/cli.c
  src/main/fc/init.c
  src/main/msp/msp.c
  src/main/sensors/acceleration.c
  src/main/sensors/compass.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_filter_impl.c
  src/main/sensors/gyro_init.c
  src/main/sensors/gyro_init.h
  src/main/sensors/initialisation.c
  src/test/Makefile
  src/test/unit/sensor_gyro_unittest.cc
Labels: RN: REFACTORING

#9569 apply iterm_windup to yaw only
  src/main/flight/pid.c
  src/test/unit/pid_unittest.cc
Labels: RN: IMPROVEMENT

#9580 CMS dynamic setup popup menu
  src/main/cms/cms.c
  src/main/cms/cms.h
  src/main/cms/cms_menu_blackbox.c
  src/main/cms/cms_menu_failsafe.c
  src/main/cms/cms_menu_firmware.c
  src/main/cms/cms_menu_firmware.h
  src/main/cms/cms_menu_gps_rescue.c
  src/main/cms/cms_menu_imu.c
  src/main/cms/cms_menu_ledstrip.c
  src/main/cms/cms_menu_main.c
  src/main/cms/cms_menu_main.h
  src/main/cms/cms_menu_misc.c
  src/main/cms/cms_menu_osd.c
  src/main/cms/cms_menu_power.c
  src/main/cms/cms_menu_vtx_common.c
  src/main/cms/cms_menu_vtx_rtc6705.c
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/cms/cms_menu_vtx_tramp.c
  src/main/cms/cms_types.h
  src/test/unit/cms_unittest.cc
Labels: RN: IMPROVEMENT

#9583 Reduce gyro temperature read rate from 250hz to every 3 seconds
  src/main/fc/core.c
Labels: RN: IMPROVEMENT

#9596 Revert "apply iterm_windup to yaw only"
  src/main/flight/pid.c
  src/test/unit/pid_unittest.cc
Labels: RN: BUGFIX

#9584 Change BMI270 driver compilation to speed-optimized
  make/source.mk
Labels: RN: REFACTORING

#9591 Revert #9215: Vendor specific displayport initialisation.
  src/main/cli/settings.c
  src/main/io/displayport_msp.c
  src/main/pg/displayport_profiles.h
  src/main/target/common_defaults_post.h
Labels: Cleanup

#9586 Made RSSI inversion apply to all RSSI sources.
  src/main/rx/rx.c
Labels: RN: IMPROVEMENT

#9587 Fixed collection of RSSI data for CRSF.
  src/main/rx/crsf.c
Labels: RN: BUGFIX

#9588 Made LQ calculation comply with coding standards.
  src/main/rx/rx.c
Labels: RN: REFACTORING

#9590 Cleaned up the scheduler.
  src/main/cli/cli.c
  src/main/config/config_unittest.h
  src/main/fc/core.c
  src/main/fc/rc_controls.c
  src/main/fc/tasks.c
  src/main/fc/tasks.h
  src/main/io/dashboard.c
  src/main/msp/msp.c
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/main/sensors/rangefinder.c
  src/main/target/COLIBRI_RACE/i2c_bst.c
  src/main/telemetry/hott.c
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/cli_unittest.cc
  src/test/unit/rc_controls_unittest.cc
  src/test/unit/scheduler_unittest.cc
  src/test/unit/sensor_gyro_unittest.cc
  src/test/unit/telemetry_ibus_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: RN: REFACTORING

#9592 Fixed CRSF RF mode indication on link loss.
  src/main/rx/crsf.c
  src/main/rx/crsf.h
Labels: RN: BUGFIX

#9595 Added EXTI based frame timing measuring for RX SPI receivers.
  src/main/rx/rx_spi.c
Labels: RN: IMPROVEMENT

#9599 Incremented maintenance branch version to 4.1.6.
  src/main/build/version.h
Labels: Applied to Branch, Housekeeping

#9602 Fix OSD dbm element size
  src/main/cli/settings.c
Labels: RN: BUGFIX

#9597 Change iterm_windup to only apply to yaw
  src/main/flight/pid.c
  src/test/unit/pid_unittest.cc
Labels: RN: IMPROVEMENT

#9489 Move targets into legacy targets for 4.1.6.
  make/targets_list.mk
Labels: Housekeeping

#9601 Efficiency OSD element in mAh/km or mAh/mi
  src/main/cli/settings.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#7601 Redpine protocol with cc2500 chip - Low Latency/fast
  src/main/cli/settings.c
  src/main/rx/cc2500_redpine.c
  src/main/rx/cc2500_redpine.h
  src/main/rx/rx_bind.c
  src/main/rx/rx_spi.c
  src/main/rx/rx_spi.h
  src/main/target/CRAZYBEEF3FR/target.h
  src/main/target/CRAZYBEEF3FR/target.mk
  src/main/target/MATEKF411RX/target.h
  src/main/target/MATEKF411RX/target.mk
  src/main/target/MIDELICF3/target.h
  src/main/target/MIDELICF3/target.mk
  src/main/target/STM32_UNIFIED/target.h
  src/main/target/STM32_UNIFIED/target.mk
  src/main/target/common_post.h
Labels: RN: MINOR FEATURE

#9608 Fix initialization of mixer related pidProfile settings
  src/main/config/config.c
  src/main/flight/mixer.c
  src/main/flight/mixer.h
Labels: RN: BUGFIX

#9610 [H7] Add missing SPI1_MOSI pin
  src/main/drivers/bus_spi_pinconfig.c
Labels: RN: BUGFIX

#9612 Add RC channels, camera frame, efficiency elements to CMS OSD menu
  src/main/cms/cms_menu_osd.c
Labels: RN: IMPROVEMENT

#9613 cc2500: Use array-based register initialization
  src/main/rx/cc2500_common.c
  src/main/rx/cc2500_common.h
  src/main/rx/cc2500_frsky_shared.c
  src/main/rx/cc2500_redpine.c
  src/main/rx/cc2500_sfhss.c
Labels: RN: IMPROVEMENT

#9616 Absolute altitude before arming is now correct when using GPS and Baro
  src/main/flight/position.c
Labels: RN: BUGFIX

#9615 minor fix: missing ifdef and autoconfig check
  src/main/io/gps.c
Labels: RN: IMPROVEMENT

#9626 Improved CLI error messages.
  src/main/cli/cli.c
  src/test/unit/cli_unittest.cc
Labels: RN: IMPROVEMENT

#9631 Fixed build error from bad cherry-pick in maintenance branch.
  src/main/fc/init.c
Labels: Applied to Branch, Fixes broken build

#9625 [ADC] Fix ADC5_DMA_OPT def
  src/main/target/common_defaults_post.h
Labels: RN: BUGFIX

#9620 Updated the 'Contributing' list in README.md.
  README.md
Labels: Documentation update

#9623 Added Azure build for pull requests.
  azure-pipelines.yml
Labels: Build System Improvement

#9628 [F1] Maintenance to keep F1 buildable
  src/link/stm32_flash_f103_128k.ld
  src/main/target/NAZE/config.c
  src/main/target/NAZE/initialisation.c
  src/main/target/NAZE/target.h
Labels: Legacy target

#9617 SBAS_NONE, gps_sbas_integrity
  src/main/cli/settings.c
  src/main/io/gps.c
  src/main/io/gps.h
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#9561 Battery sag compensation by varying motor output
  src/main/cli/settings.c
  src/main/config/config.c
  src/main/fc/tasks.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/msp/msp.c
  src/main/sensors/battery.c
  src/main/sensors/battery.h
  src/main/sensors/voltage.c
  src/main/sensors/voltage.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#9635 SBAS_NONE part 2
  src/main/io/gps.c
  src/main/io/gps.h
Labels: RN: IMPROVEMENT

#9642 Change pidloop constraint when dshot bidir is enabled
  src/main/config/config.c
Labels: Needs entry in Release Notes, RN: BUGFIX

#9643 Fix unable to change video system for FrSkyPixelOSD.
  src/main/cli/settings.c
  src/main/cli/settings.h
Labels: RN: BUGFIX

#9644 Prevent division by 0 error in battery usage OSD element
  src/main/osd/osd_elements.c
Labels: RN: BUGFIX

#9645 Fix division by 0 risk in mixer vbat sag compensation
  src/main/flight/mixer.c
Labels: RN: BUGFIX

#9647 Fix division by zero in mixer crashflip
  src/main/flight/mixer.c
Labels: RN: BUGFIX
