Repository betaflight/betaflight, pull requests merged in 2020-02, with the labels that each got.

#9407 [G4] UART support
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stm32g4xx.c
Labels: RN: IMPROVEMENT

#9430 [G4] EXTI support
  src/main/drivers/exti.c
  src/main/drivers/io.h
Labels: RN: IMPROVEMENT

#9431 [G4] SPI support
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_hal.c
  src/main/drivers/bus_spi_impl.h
  src/main/drivers/bus_spi_pinconfig.c
Labels: RN: IMPROVEMENT

#9433 Fix GPS Rescue altitude mode behavior
  src/main/flight/gps_rescue.c
Labels: RN: BUGFIX

#9435 Rearrange parameter ordering so dynamic notch min/max are together
  src/main/cli/settings.c
Labels: Cleanup, RN: IMPROVEMENT

#9436 Added support for SDIO to Unified Targets.
  src/main/target/STM32F405/target.mk
  src/main/target/STM32F411/target.mk
  src/main/target/STM32F745/target.mk
  src/main/target/STM32F7X2/target.mk
  src/main/target/common_unified.h
Labels: RN: TARGET UPDATE, Unified Targets

#9439 [G4] SOFTSERIAL support
  src/main/drivers/serial_softserial.c
Labels: RN: IMPROVEMENT

#9438 [G4] timer support
  src/main/drivers/timer.h
  src/main/drivers/timer_def.h
  src/main/drivers/timer_hal.c
  src/main/drivers/timer_stm32g4xx.c
Labels: RN: IMPROVEMENT

#9441 Fix dashboard initialization order
  src/main/fc/init.c
Labels: Bugfix, RN: BUGFIX

#9444 Gyro native rate sampling, filtering, and scheduler restructuring
  src/main/blackbox/blackbox.c
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/config/config.c
  src/main/config/config_unittest.h
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu3050.c
  src/main/drivers/accgyro/gyro_sync.c
  src/main/drivers/accgyro/gyro_sync.h
  src/main/fc/core.c
  src/main/fc/core.h
  src/main/fc/init.c
  src/main/fc/tasks.c
  src/main/fc/tasks.h
  src/main/flight/pid.c
  src/main/flight/rpm_filter.c
  src/main/msp/msp.c
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_filter_impl.c
  src/main/sensors/initialisation.c
  src/main/target/ALIENFLIGHTF3/config.c
  src/main/target/CLRACINGF4/config.c
  src/main/target/COLIBRI_RACE/i2c_bst.c
  src/main/target/MOTOLAB/config.c
  src/main/target/MULTIFLITEPICO/config.c
  src/main/target/NAZE/config.c
  src/main/target/OMNIBUSF4/config.c
  src/main/target/common_pre.h
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/blackbox_unittest.cc
  src/test/unit/pid_unittest.cc
  src/test/unit/scheduler_unittest.cc
  src/test/unit/sensor_gyro_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#9449 Blackbox 32K code cleanup
  src/main/blackbox/blackbox.c
  src/test/unit/blackbox_unittest.cc
Labels: Cleanup

#9453 Fix compiler warnings if USE_BLACKBOX is not defined
  src/main/fc/core.c
Labels: RN: BUGFIX

#9452 Fix compile errors when USE_BOARD_INFO is not defined
  src/main/blackbox/blackbox.c
Labels: RN: BUGFIX

#9448 [G4] ADC support
  src/main/drivers/adc.h
  src/main/drivers/adc_impl.h
  src/main/drivers/adc_stm32g4xx.c
Labels: RN: IMPROVEMENT

#9455 Add "auto" mode to yaw spin recovery
  src/main/cli/settings.c
  src/main/fc/rc.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: Needs entry in Release Notes, RN: IMPROVEMENT

#9437 Added command to bind RX to MSP.
  make/source.mk
  src/main/cli/cli.c
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
  src/main/rx/rx.c
  src/main/rx/rx_bind.c
  src/main/rx/rx_bind.h
  src/main/target/common_post.h
Labels: RN: IMPROVEMENT

#9460 Rssi scale documentation
  docs/Rssi.md
Labels: Documentation update

#9459 Add instructions to CMS accelerometer calibration
  src/main/cms/cms_menu_firmware.c
Labels: RN: IMPROVEMENT

#9471 Adds CRSF rf_mode parameter to linkquality OSD element
  src/main/osd/osd_elements.c
  src/main/rx/crsf.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/test/unit/link_quality_unittest.cc
Labels: RN: IMPROVEMENT

#9463 [G4] LED_STRIP support
  src/main/drivers/light_ws2811strip_hal.c
Labels: RN: IMPROVEMENT

#9454 Add 'low capacity' warning shown when exceeding configured cap_alarm value
  src/main/cli/settings.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#9478 Added documentation for JetiExBus setup.
  docs/Rx.md
  docs/resources/How.to.setup.your.RX.and.FC.for.Jeti.Ex-Bus.pdf
Labels: Added by Cherry-pick

#9466 More aggresive FF for no or 2 point averaging; default to 2 point averaging
  src/main/flight/interpolated_setpoint.c
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#9474 [H7][G4] getFLASHSectorForEEPROM cleanup
  src/main/config/config_streamer.c
Labels: RN: IMPROVEMENT

#9479 Detect revisions of the STM32H743.
  src/main/build/build_config.c
  src/main/build/build_config.h
  src/main/cli/cli.c
  src/main/msp/msp.c
  src/main/platform.h
  src/test/unit/cli_unittest.cc
Labels: RN: IMPROVEMENT

#9472 [H7] Add 480MHz support for H743/H750 silicon revision V
  src/main/startup/system_stm32h7xx.c
Labels: RN: IMPROVEMENT

#9481 NFE Race Mode
  src/main/cli/settings.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/test/unit/pid_unittest.cc
Labels: RN: IMPROVEMENT

#9483 Incremented maintenance branch version to 4.1.5.
  src/main/build/version.h
Labels: Applied to Branch, Housekeeping

#9410 Move targets into legacy targets for 4.1.5.
  make/targets_list.mk
Labels: Housekeeping

#9484 Removed legacy timer index notation from CLI.
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#9482 Restore proper behaviour of iterm_relax_cutoff in setpoint mode
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/flight/pid.c
  src/test/unit/pid_unittest.cc
Labels: RN: IMPROVEMENT

#9464 [G4] MCO support
  src/main/cli/settings.c
  src/main/drivers/mco.c
  src/main/drivers/mco.h
  src/main/fc/init.c
  src/main/pg/mco.c
  src/main/pg/mco.h
Labels: RN: IMPROVEMENT

#9486 Updated DLPF curve
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#9485 White space tidy
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cms/cms.c
  src/main/cms/cms_menu_gps_rescue.c
  src/main/cms/cms_menu_vtx_common.c
  src/main/config/config.c
  src/main/drivers/adc_stm32g4xx.c
  src/main/drivers/adc_stm32h7xx.c
  src/main/drivers/bus_spi.h
  src/main/drivers/dma.h
  src/main/drivers/dshot.c
  src/main/drivers/dshot_bitbang_decode.c
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/dshot_bitbang_ll.c
  src/main/drivers/dshot_bitbang_stdperiph.c
  src/main/drivers/dshot_command.c
  src/main/drivers/flash.c
  src/main/drivers/flash_w25m.c
  src/main/drivers/flash_w25n01g.c
  src/main/drivers/pwm_output_dshot_hal_hal.c
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/drivers/serial_escserial.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32g4xx.c
  src/main/drivers/serial_uart_stm32h7xx.c
  src/main/fc/core.c
  src/main/fc/rc.c
  src/main/fc/rc_modes.c
  src/main/fc/tasks.c
  src/main/flight/failsafe.c
  src/main/flight/failsafe.h
  src/main/flight/gps_rescue.c
  src/main/flight/gyroanalyse.c
  src/main/flight/imu.c
  src/main/flight/interpolated_setpoint.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/position.c
  src/main/io/gps.c
  src/main/io/rcdevice.c
  src/main/io/rcdevice_cam.c
  src/main/msc/emfat.c
  src/main/msc/emfat_file.c
  src/main/msc/usbd_storage.c
  src/main/msc/usbd_storage_emfat.c
  src/main/msp/msp.c
  src/main/pg/motor.c
  src/main/pg/pg.h
  src/main/rx/crsf.c
  src/main/rx/srxl2.c
  src/main/sensors/acceleration.c
  src/main/sensors/battery.h
  src/main/sensors/compass.c
  src/main/sensors/gyro.c
  src/main/telemetry/srxl.c
Labels: Cleanup

#9490 Fix overlooked case in unified DMA instance handling
  src/main/drivers/pwm_output_dshot_hal_hal.c
Labels: RN: BUGFIX

#9488 Use library defined symbol instead of magic constant for UID_BASE
  src/main/platform.h
Labels: RN: IMPROVEMENT

#9487 Added FF Interpolate options to CMS
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT

#9491 Improved code to apply level modes.
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#9492 Made the CI build fail on missing changeset.
  .travis.yml
Labels: Build System Improvement

#9493 Reduced the number of target groups to build in CI from 6 to 3.
  .travis.yml
  Makefile
  make/targets_list.mk
Labels: Build System Improvement

#9494 Support RCC_ClockCmd and RCC_ResetCmd for HAL
  src/main/drivers/adc_stm32g4xx.c
  src/main/drivers/adc_stm32h7xx.c
  src/main/drivers/bus_i2c_hal.c
  src/main/drivers/pwm_output_dshot_hal_hal.c
  src/main/drivers/rcc.c
  src/main/drivers/rcc.h
  src/main/drivers/sdio_f7xx.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/drivers/serial_uart_stm32g4xx.c
  src/main/drivers/serial_uart_stm32h7xx.c
  src/main/drivers/system_stm32f7xx.c
  src/main/drivers/system_stm32h7xx.c
Labels: RN: IMPROVEMENT, Ready to Merge

#9497 CLI: Print range info for strings
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#9499 Motor_output_limit settings to msp
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#9502 [G4] Dshot support (LL)
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/stm32g4xx_ll_ex.h
Labels: RN: IMPROVEMENT

#9501 [G4] DShot support (pure HAL)
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/pwm_output_dshot_hal_hal.c
Labels: RN: IMPROVEMENT

#9505 [H7] Refactor enableDmaClock with RCC_ClockCmd
  src/main/drivers/dma_stm32h7xx.c
Labels: RN: IMPROVEMENT

#9507 Fix "may be used uninitialized" warnings
  src/main/scheduler/scheduler.c
  src/main/sensors/gyro.c
Labels: RN: REFACTORING

#9508 [F7] Remove bogus cplusplus stuff
  src/main/drivers/stm32f7xx_ll_ex.h
Labels: Cleanup

#9512 [F7] Refactor enableDmaClock with RCC_ClockCmd
  src/main/drivers/dma_stm32f7xx.c
Labels: RN: IMPROVEMENT

#9514 [H7] Clock code clean up
  src/main/startup/system_stm32h7xx.c
Labels: RN: IMPROVEMENT

#9515 [H7] Boot loader call cleanup
  src/main/drivers/system_stm32h7xx.c
Labels: RN: IMPROVEMENT

#9519 Added rates type to Msp
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#9520 Update RCC_ClockCmd related macros to accomodate G4 register naming convention
  src/main/drivers/rcc.c
  src/main/drivers/rcc.h
Labels: RN: IMPROVEMENT

#9521 [G4] UART update for RCC_ClockCmd
  src/main/drivers/serial_uart_stm32g4xx.c
Labels: RN: IMPROVEMENT

#9522 [G4] DMA update for RCC_ClockCmd
  src/main/drivers/dma_stm32g4xx.c
Labels: RN: IMPROVEMENT

#9523 [G4] LPUART support update
  src/main/drivers/serial_uart.c
Labels: RN: IMPROVEMENT
