Repository betaflight/betaflight, pull requests merged in 2020-09, with the labels that each got.

#10106 Fixed motorOutputLimitLow in blackbox and OSD.
  src/main/blackbox/blackbox.c
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/osd/osd_elements.c
  src/test/unit/blackbox_unittest.cc
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: Needs coordination with blackbox-log-viewer, RN: BUGFIX

#10121 update low rssi error of spektrum
  src/main/io/spektrum_rssi.c
Labels: RN: BUGFIX

#10126 Clean up linker script
  src/link/stm32_flash_f7_split.ld
Labels: RN: IMPROVEMENT

#10153 Remap and fix HID_MOUSE_ReportDesc (as part of #10150)
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc/usbd_hid.h
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc/usbd_hid.h
  lib/main/STM32G4/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc/usbd_hid.h
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c
  lib/main/STM32_USB_Device_Library/Class/hid/inc/usbd_hid_core.h
  lib/main/STM32_USB_Device_Library/Class/hid/src/usbd_hid_core.c
  src/main/vcpf4/usbd_conf.h
Labels: Library Patch, RN: BUGFIX

#10150 Fixed misaligned report 'usages' and added more channels to HID joystick
  src/main/fc/rc_controls.h
  src/main/io/usb_cdc_hid.c
Labels: RN: BUGFIX

#10164 Replace peak clipping of FF boost with lowpass filter
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/flight/interpolated_setpoint.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
Labels: RN: IMPROVEMENT

#10136 [G4] TIMER timer_def.h update
  src/main/drivers/timer_def.h
Labels: RN: IMPROVEMENT

#10159 Support MPU925x internal magnetometer over I2C
  src/main/cli/settings.c
  src/main/drivers/compass/compass_mpu925x_ak8963.c
  src/main/drivers/compass/compass_mpu925x_ak8963.h
  src/main/sensors/compass.c
  src/main/sensors/compass.h
  src/main/target/STM32_UNIFIED/target.h
Labels: RN: IMPROVEMENT

#10163 Add late P boost to antigravity
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
Labels: RN: IMPROVEMENT

#10178 [G4] USB_HID_CDC support
  src/main/io/usb_cdc_hid.c
  src/main/vcp_hal/usbd_conf.h
Labels: RN: IMPROVEMENT

#10181 Add target IFLIGHT_H743_AIO support.
  src/main/target/IFLIGHT_H743_AIO/target.c
  src/main/target/IFLIGHT_H743_AIO/target.h
  src/main/target/IFLIGHT_H743_AIO/target.mk
Labels: RN: NEW TARGET

#10183 Add box mode to disable stick commands
  src/main/cms/cms.c
  src/main/fc/rc_controls.c
  src/main/fc/rc_modes.h
  src/main/io/rcdevice_cam.c
  src/main/msp/msp_box.c
Labels: RN: IMPROVEMENT

#10195 Removed DPS310 baro from IFLIGHT_H743_AIO for maintenance branch.
  src/main/target/IFLIGHT_H743_AIO/target.h
  src/main/target/IFLIGHT_H743_AIO/target.mk
Labels: Applied to Branch, Fixes broken build, RN: TARGET UPDATE

#10174 Moved config for IFLIGHT_H7_TWING into internal flash.
  src/main/target/IFLIGHT_H7_TWING/target.h
Labels: RN: TARGET UPDATE

#10199 Made stick command disable mode name consistent with other names.
  src/main/msp/msp_box.c
Labels: RN: IMPROVEMENT

#10200 Revert "Clean up linker script"
  src/link/stm32_flash_f7_split.ld
Labels: RN: BUGFIX

#10198 Incremented maintenance branch version to 4.2.4.
  src/main/build/version.h
Labels: Applied to Branch, Housekeeping

#10191 Show stopped motors in Motor Diagnostic OSD element
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#10177 [G4] Add USB/VCP support
  src/main/drivers/serial_usb_vcp.c
  src/main/drivers/serial_usb_vcp.h
  src/main/vcp_hal/usbd_cdc_interface.h
  src/main/vcp_hal/usbd_conf.h
  src/main/vcp_hal/usbd_conf_stm32g4xx.c
Labels: RN: IMPROVEMENT

#10176 [G4] BB-DSHOT support (TIM1/TIM8 limited version)
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/dshot_bitbang_ll.c
Labels: RN: IMPROVEMENT
