Repository betaflight/betaflight, pull requests merged in 2020-08, with the labels that each got.

#10064 Add hdop in MSP_RAW_GPS
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#10075 Fixed crsf-cms
  src/main/io/displayport_crsf.c
Labels: RN: BUGFIX

#10071 Added board information to CMS 'firmware' menu.
  src/main/cms/cms_menu_firmware.c
Labels: RN: IMPROVEMENT

#10062 Fixed lockup when entering CMS.
  src/main/cms/cms.c
Labels: RN: BUGFIX

#10091 Fixed bug in FrSky X SPI code affecting RX range.
  src/main/rx/cc2500_frsky_shared.c
Labels: RN: BUGFIX

#10092 Fix CLI range check error message formatting
  src/main/cli/cli.c
Labels: RN: BUGFIX

#10082 Fix a format/argument mismatch in a call to tfp_sprintf()
  src/main/io/dashboard.c
Labels: RN: BUGFIX

#9946 Motor output reordering feature for CLI and MSP (Firmware part)
  src/main/cli/settings.c
  src/main/config/config.c
  src/main/drivers/dshot.c
  src/main/drivers/dshot.h
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_dpwm.c
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/pwm_output_dshot_hal_hal.c
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
  src/main/pg/motor.c
  src/main/pg/motor.h
  src/test/Makefile
  src/test/unit/motor_output_unittest.cc
Labels: RN: IMPROVEMENT

#10079 Added vbat_sag_compensation to Blackbox header
  src/main/blackbox/blackbox.c
Labels: RN: IMPROVEMENT

#10097 Fix underflow in channel based RSSI calculations for out of range values
  src/main/rx/rx.c
Labels: RN: BUGFIX

#10086 Updated dynamic gyro lowpass curve
  src/main/cli/settings.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_init.c
Labels: RN: IMPROVEMENT

#10098 Speed up gyro device detection; fix MPU6000 initialization
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_spi_icm20689.c
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
Labels: RN: IMPROVEMENT

#10099 Updated the instructions for the creation of Unified Target Configurations.
  docs/TargetMaintenance/CreatingAUnifiedTarget.md
Labels: Documentation update

#10100 Incremented maintenance branch version to 4.2.3.
  src/main/build/version.h
Labels: Applied to Branch, Housekeeping

#10101 Added missing 'USE_BOARD_INFO' conditionals in cms.c.
  src/main/cms/cms_menu_firmware.c
Labels: RN: BUGFIX

#10105 Cleaned up handling of 'oldMinRps' in dynamic idle code.
  src/main/flight/mixer.c
Labels: RN: IMPROVEMENT

#10112 feat: add additional min/warn battery cell voltages to CMS
  src/main/cms/cms_menu_power.c
Labels: RN: IMPROVEMENT

#10114 add thrust linearization to CSM
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT

#10080 Add support for British units in OSD
  docs/Units.md
  src/main/cli/settings.c
  src/main/common/unit.h
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/telemetry.c
  src/main/telemetry/telemetry.h
Labels: RN: IMPROVEMENT

#10128 Rename macros used in FAST_RAM/DATA
  make/checks.mk
  src/link/stm32_flash_f7_split.ld
  src/link/stm32_flash_h743_2m.ld
  src/link/stm32_flash_split.ld
  src/link/stm32_h750_common.ld
  src/link/stm32_ram_h743.ld
  src/main/drivers/adc.c
  src/main/drivers/dshot.c
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/dshot_dpwm.c
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/motor.c
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/drivers/pwm_output_dshot_shared.h
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart_pinconfig.c
  src/main/drivers/system.c
  src/main/fc/core.c
  src/main/fc/rc.c
  src/main/flight/gyroanalyse.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/rpm_filter.c
  src/main/scheduler/scheduler.c
  src/main/sensors/acceleration.c
  src/main/sensors/gyro.c
  src/main/target/common_pre.h
  src/test/unit/platform.h
Labels: RN: REFACTORING

#10134 Fixed broken tests after #10080.
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: Fixes broken build, RN: BUGFIX

#10135 Fixed the check if only documentation was changed in Travis.
  .travis.yml
Labels: Build System Improvement

#10137 [G4] I2C Add I2C pins overloaded with SWD pins
  src/main/drivers/bus_i2c_hal_init.c
Labels: RN: IMPROVEMENT

#10138 [G4] Camera control support
  src/main/drivers/camera_control.c
Labels: RN: IMPROVEMENT

#10095 Disable stick commands when HID is active and USB is connected
  src/main/cms/cms.c
  src/main/fc/rc_controls.c
  src/main/io/usb_cdc_hid.c
  src/main/io/usb_cdc_hid.h
Labels: RN: IMPROVEMENT

#10129 Fix default baro handling and address for DPS310
  src/main/drivers/barometer/barometer_dps310.c
  src/main/sensors/barometer.c
Labels: RN: IMPROVEMENT

#10146 Fix debug names not unique with only 12 chars
  src/main/build/debug.c
Labels: RN: IMPROVEMENT

#10103 Update PID tuning.md
  docs/PID tuning.md
Labels: Documentation update
