Repository betaflight/betaflight, pull requests merged in 2020-10, with the labels that each got.

#10214 add fc attitude request for rcdevice protocol
  src/main/io/rcdevice.c
  src/main/io/rcdevice.h
  src/main/io/rcdevice_cam.c
  src/test/unit/rcdevice_unittest.cc
Labels: RN: IMPROVEMENT

#10221 [G4] CLI and config changes for clock configuration
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/config/config.c
  src/main/config/config.h
  src/main/fc/init.c
Labels: RN: IMPROVEMENT

#10229 Remove unnecessary drawScreen() calls for MSP displayPort OSD
  src/main/osd/osd.c
Labels: RN: BUGFIX

#10132 Update Mixer.md
  docs/Mixer.md
Labels: Documentation update

#10230 Add compile-time option to enable MSP push messages over the VCP port
  src/main/msp/msp_serial.c
Labels: RN: IMPROVEMENT

#10232 [H7][ADC] Batch call DeInit() for all used devices
  src/main/drivers/adc_stm32h7xx.c
Labels: Bugfix, RN: BUGFIX

#10222 [G4][SYSTEM] Basic & build files
  make/mcu/STM32G4.mk
  make/targets.mk
  src/link/stm32_flash_g474.ld
  src/link/stm32_flash_split_g4.ld
  src/main/drivers/system.h
  src/main/drivers/system_stm32g4xx.c
  src/main/platform.h
  src/main/startup/startup_stm32g474xx.s
  src/main/startup/stm32g4xx_hal_conf.h
  src/main/startup/system_stm32g4xx.c
  src/main/startup/system_stm32g4xx.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#10236 [G4] Add missing TIMUP_TIMERS (TIM20)
  src/main/drivers/timer.h
Labels: Bugfix, RN: BUGFIX

#10226 [G4][ADC] Batch call DeInit() for all used devices
  src/main/drivers/adc_stm32g4xx.c
Labels: Bugfix, RN: BUGFIX

#10224 [H7] BB-Dshot support (TIM1/TIM8 limited version)
  make/mcu/STM32H7.mk
  src/main/drivers/dma.h
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/dshot_bitbang_ll.c
  src/main/drivers/timer_def.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#10245 Added vbat sag compensation in CMS
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT

#10243 Add optional high framerate OSD
  src/main/cli/settings.c
  src/main/fc/tasks.c
  src/main/osd/osd.c
  src/main/osd/osd.h
Labels: RN: IMPROVEMENT

#10223 Fix Dshot range
  src/main/drivers/dshot.c
Labels: RN: BUGFIX

#10238 Added dlpf gyro expo curve in CMS
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT

#10237 Fix dmaopt peripheral numbering for TIMUP
  src/main/cli/cli.c
Labels: Bugfix, RN: BUGFIX

#10225 New feature 'Beeper mute'
  src/main/fc/rc_modes.h
  src/main/io/beeper.c
  src/main/msp/msp_box.c
Labels: RN: IMPROVEMENT

#10256 Update Building in Fedora to 32
  docs/development/Building in Fedora.md
Labels: Documentation update

#10113 Improve custom builds
  src/main/cli/cli.c
  src/main/target/common_post.h
Labels: RN: IMPROVEMENT

#10246 Fix H7 USB MSC library support
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc.h
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c
Labels: Library Patch, RN: IMPROVEMENT

#10166 Allow exit from VTX pitmode when arming craft
  src/main/io/vtx.c
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_tramp.c
Labels: RN: IMPROVEMENT

#10257 Add feedforward to OSD PID elements
  src/main/osd/osd_elements.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#10258 Enable BMP085/BMP180 for F405 and F745 unified targets
  src/main/target/STM32_UNIFIED/target.h
Labels: RN: IMPROVEMENT

#10239 Enabled gyro dlpf by default
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#10260 cc2500_common.c: Modify (fix) outer level conditional to cover till the end
  src/main/rx/cc2500_common.c
Labels: RN: BUGFIX

#10255 Update Building in Ubuntu
  docs/development/Building in Ubuntu.md
Labels: Documentation update, hacktoberfest-accepted

#10263 Cleaned up Unified Target definition.
  src/main/target/STM32_UNIFIED/target.h
Labels: RN: IMPROVEMENT

#10264 Added release and license badges to the README.
  README.md
Labels: Documentation update

#10268 Add Thrust Linearization to MSP
  src/main/msp/msp.c
Labels: Needs coordination with lua scripts, RN: IMPROVEMENT

#10261 Split mixer code into initialisation and runtime to reduce flash space usage.
  make/source.mk
  src/main/fc/init.c
  src/main/flight/mixer.c
  src/main/flight/mixer_init.c
  src/main/flight/mixer_init.h
Labels: RN: REFACTORING

#10274 Added IRC GHST protocol
  make/mcu/SITL.mk
  make/source.mk
  src/main/cli/settings.c
  src/main/rx/ghst.c
  src/main/rx/ghst.h
  src/main/rx/ghst_protocol.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/target/CRAZYBEEF3FR/target.h
  src/main/target/MIDELICF3/target.h
  src/main/target/SITL/target.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
  src/main/telemetry/ghst.c
  src/main/telemetry/ghst.h
  src/main/telemetry/telemetry.c
Labels: RN: MINOR FEATURE

#10273 Improve CMS support of long lookup table names
  src/main/build/debug.c
  src/main/cms/cms.c
  src/main/cms/cms_types.h
Labels: RN: IMPROVEMENT

#10277 Make the MPU6050 (I2C) driver only build on Unified Targets with 1MB flash.
  src/main/drivers/accgyro/accgyro_mpu6050.c
  src/main/target/STM32_UNIFIED/target.h
Labels: Fixes broken build, RN: TARGET UPDATE

#10275 Fix and re-enable BMP085 unit test
  src/test/Makefile
  src/test/unit/baro_bmp085_unittest.cc
Labels: UNITTEST

#10262 Refactored mixer / servo init.
  src/main/fc/init.c
  src/main/flight/mixer.h
  src/main/flight/mixer_init.c
  src/main/flight/servos.c
  src/main/flight/servos.h
Labels: RN: REFACTORING

#10269 Fix dfuse and python check
  make/linux.mk
  make/macosx.mk
  make/tools.mk
  src/utils/dfuse-pack.py
Labels: Build System Improvement

#10279 Split acceleration code into init and runtime to save flash space
  make/source.mk
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration_init.c
  src/main/sensors/acceleration_init.h
Labels: RN: REFACTORING

#10266 Use PYTHON environment variable in Makefile.
  Makefile
Labels: Build System Improvement

#10286 [H7] Remove USB_USB_ID from target.h
  src/main/target/IFLIGHT_H743_AIO/target.h
  src/main/target/IFLIGHT_H7_TWING/target.h
Labels: Bugfix, RN: BUGFIX

#10287 Changed optimisation on F7X2 targets to '-O2' to save flash space.
  make/mcu/STM32F7.mk
Labels: RN: IMPROVEMENT

#10282 Fixed overly high RX task invocation caused by GHST telemetry.
  src/main/rx/ghst.c
Labels: RN: BUGFIX

#10291 Sets antigravity gain to 0 when the user wants none.
  src/main/flight/pid.h
Labels: Bugfix, Needs coordination with betaflight-configurator, Needs coordination with lua scripts, RN: BUGFIX

#10288 Fixed test build on MacOS Catalina with native clang.
  src/main/build/atomic.h
Labels: Build System Improvement

#10290 Update serial-4way-if to v20005
  src/main/io/serial_4way.c
Labels: RN: IMPROVEMENT

#10292 Incremented maintenance branch version to 4.2.5.
  src/main/build/version.h
Labels: Applied to Branch, Housekeeping

#10295 Move GitHub configuration issues to link
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/configuration-issue.md
  README.md
Labels: Documentation update

#10298 Moved hardware issue template to a link.
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/hardware-problem-report.md
  README.md
Labels: Documentation update

#10289 Fixed test build on Fedora and Ubuntu with native clang
  docs/development/Building in Ubuntu.md
  src/test/Makefile
Labels: Build System Improvement

#10300 Total flights stats for OSD (firmware part)
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/fc/core.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#10265 Use clang-10 as the official compiler version for tests.
  .travis.yml
  src/test/Makefile
Labels: Build System Improvement

#10304 Simplified the Makefile OS detection output.
  make/system-id.mk
  make/tools.mk
Labels: Build System Improvement

#10303 Fix SPI FLASH speed and cycle time impact
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
  src/main/drivers/accgyro/accgyro_spi_bmi270.c
  src/main/drivers/accgyro/accgyro_spi_icm20649.c
  src/main/drivers/accgyro/accgyro_spi_icm20689.c
  src/main/drivers/accgyro/accgyro_spi_icm42605.c
  src/main/drivers/accgyro/accgyro_spi_l3gd20.c
  src/main/drivers/accgyro/accgyro_spi_lsm6dso_init.c
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
  src/main/drivers/accgyro/accgyro_spi_mpu6500.c
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
  src/main/drivers/barometer/barometer_bmp280.c
  src/main/drivers/barometer/barometer_bmp388.c
  src/main/drivers/barometer/barometer_dps310.c
  src/main/drivers/barometer/barometer_lps.c
  src/main/drivers/barometer/barometer_ms5611.c
  src/main/drivers/barometer/barometer_qmp6988.c
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_ll.c
  src/main/drivers/bus_spi_stdperiph.c
  src/main/drivers/compass/compass_ak8963.c
  src/main/drivers/compass/compass_hmc5883l.c
  src/main/drivers/flash.c
  src/main/drivers/flash_m25p16.c
  src/main/drivers/flash_m25p16.h
  src/main/drivers/flash_w25m.c
  src/main/drivers/max7456.c
  src/main/drivers/rx/rx_spi.c
  src/main/drivers/sdcard_spi.c
  src/main/drivers/vtx_rtc6705.c
  src/main/target/AIRF7/target.h
  src/main/target/IMPULSERCF3/target.h
  src/main/target/NOX/target.h
  src/main/target/STM32F3DISCOVERY/target.h
  src/main/target/TMOTORF7/target.h
  src/main/target/common_defaults_post.h
  src/test/unit/baro_bmp280_unittest.cc
  src/test/unit/baro_bmp388_unittest.cc
  src/test/unit/baro_ms5611_unittest.cc
Labels: RN: IMPROVEMENT

#10306 bump SDK to latest Update
  make/tools.mk
Labels: RN: IMPROVEMENT

#10305 Moved parameter group defaults into main flash for STM32F722.
  src/link/stm32_flash_f722.ld
  src/link/stm32_flash_f74x.ld
  src/link/stm32_flash_f765.ld
  src/link/stm32_flash_f7_split.ld
Labels: RN: IMPROVEMENT

#10307 Added the dynamic idle throttle offset to the blackbox header to fix the motor output display.
  src/main/blackbox/blackbox.c
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/mixer_init.c
  src/main/rx/rx.h
Labels: RN: IMPROVEMENT

#10309 Disable HEADFREE flight mode when GPS Rescue is active
  src/main/fc/core.c
Labels: RN: BUGFIX

#10310 Added persistent stats to CMS
  make/source.mk
  src/main/cms/cms.c
  src/main/cms/cms_menu_main.c
  src/main/cms/cms_menu_persistent_stats.c
  src/main/cms/cms_menu_persistent_stats.h
  src/main/cms/cms_types.h
Labels: RN: IMPROVEMENT, hacktoberfest-accepted

#10315 Include gyro_to_use in blackbox header
  src/main/blackbox/blackbox.c
Labels: RN: IMPROVEMENT

#10316 Quick rates expo on rc command
  src/main/cli/settings.c
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/fc/rc.c
Labels: RN: IMPROVEMENT

#10247 Add USB MSC support for H7
  make/mcu/STM32H7.mk
  src/link/stm32_h750_common.ld
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/flash.c
  src/main/drivers/nvic.h
  src/main/drivers/persistent.c
  src/main/drivers/persistent.h
  src/main/drivers/sdio_h7xx.c
  src/main/drivers/system_stm32h7xx.c
  src/main/drivers/usb_msc.h
  src/main/drivers/usb_msc_common.c
  src/main/drivers/usb_msc_h7xx.c
  src/main/fc/init.c
  src/main/target/SPRACINGH7EXTREME/config.c
  src/main/target/SPRACINGH7EXTREME/target.h
  src/main/target/SPRACINGH7NANO/target.h
  src/main/target/SPRACINGH7ZERO/config.c
  src/main/target/SPRACINGH7ZERO/target.h
  src/main/target/common_pre.h
  src/main/vcp_hal/usbd_conf_stm32f7xx.c
  src/main/vcp_hal/usbd_conf_stm32h7xx.c
  src/main/vcp_hal/usbd_desc.c
Labels: RN: IMPROVEMENT
