Repository betaflight/betaflight, pull requests merged in 2021-10, with the labels that each got.

#10993 Fix simplified_dterm_filter_multiplier range
  src/main/cli/settings.c
  src/main/config/simplified_tuning.h
Labels: RN: BUGFIX

#10962 Remove redundant check representing same value
  src/main/cli/cli.c
Labels: RN: BUGFIX

#10985 Fix h743 board identifier
  src/main/target/STM32_UNIFIED/target.h
Labels: RN: BUGFIX

#10989 Refactoring of rxFrameTimeUs
  src/main/rx/crsf.c
  src/main/rx/fport.c
  src/main/rx/ghst.c
  src/main/rx/ibus.c
  src/main/rx/jetiexbus.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/sbus.c
  src/main/rx/spektrum.c
  src/main/rx/srxl2.c
  src/main/rx/sumd.c
  src/test/unit/rx_crsf_unittest.cc
  src/test/unit/rx_ibus_unittest.cc
  src/test/unit/rx_sumd_unittest.cc
  src/test/unit/telemetry_crsf_msp_unittest.cc
  src/test/unit/telemetry_crsf_unittest.cc
Labels: RN: REFACTORING

#10991 set default iterm_windup to 85 for yaw
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#10952 Keeping debug naming in-line with existing function naming convention.
  src/main/build/debug_pin.c
  src/main/build/debug_pin.h
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_bitbang_stdperiph.c
Labels: RN: IMPROVEMENT

#10990 Make unit test working on MacOS and clang 12/13
  src/test/Makefile
Labels: Build System Improvement

#10997 Support dual gyros sharing a common SPI bus
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/bus.h
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi_impl.h
  src/main/drivers/bus_spi_ll.c
  src/main/drivers/bus_spi_stdperiph.c
  src/main/drivers/compass/compass_ak8963.c
  src/main/drivers/exti.c
  src/main/drivers/flash_m25p16.c
Labels: RN: IMPROVEMENT

#10988 Changed the optimisation level for ITCM RAM code to free up some ITCM RAM space on F745.
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT
