Repository betaflight/betaflight, pull requests merged in 2021-06, with the labels that each got.

#10747 New memory section types for DMA
  lib/main/STM32H7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c
  src/main/target/common_pre.h
Labels: Library Patch, RN: IMPROVEMENT

#10730 SD Card fixes
  src/main/drivers/sdio_h7xx.c
  src/main/drivers/system.h
  src/main/fc/init.c
Labels: RN: BUGFIX

#10776 Fixed SPI access for SD cards for STM32G4 and STM32H7.
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_ll.c
  src/main/drivers/dma.h
  src/main/drivers/sdcard_spi.c
  src/main/target/STM32_UNIFIED/target.h
  src/main/target/STM32_UNIFIED/target.mk
Labels: RN: IMPROVEMENT

#10704 Add UART9/10 support.
  docs/Serial.md
  src/main/drivers/nvic.h
  src/main/drivers/serial_pinconfig.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stm32h7xx.c
  src/main/io/serial.c
  src/main/io/serial.h
  src/main/pg/serial_uart.c
  src/main/target/NUCLEOH723ZG/target.h
  src/main/target/NUCLEOH725ZG/target.h
  src/main/target/NUCLEOH743/target.h
  src/main/target/NUCLEOH7A3ZI/target.h
  src/main/target/common_defaults_post.h
Labels: RN: IMPROVEMENT, Ready to Merge

#10790 Fixed bugs in UART configuration introduced by #10704.
  src/main/io/serial.c
  src/main/target/STM32_UNIFIED/target.h
Labels: Fixes broken build, RN: BUGFIX

#10767 Dynamic notch changes
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/common/sdft.c
  src/main/common/sdft.h
  src/main/flight/gyroanalyse.c
  src/main/flight/gyroanalyse.h
  src/main/msp/msp.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: Needs coordination with betaflight-configurator, Needs coordination with blackbox-log-viewer, RN: IMPROVEMENT

#10755 Added resetting to defaults for individual parameter groups.
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#10791 Added a Unified Target for STM32H743.
  make/targets_list.mk
  src/link/stm32_flash_h743_2m.ld
  src/main/target/STM32_UNIFIED/STM32H743.mk
  src/main/target/STM32_UNIFIED/target.h
  src/main/target/STM32_UNIFIED/target.mk
Labels: RN: NEW TARGET
