Repository betaflight/betaflight, pull requests merged in 2021-11, with the labels that each got.

#11030 Force F7 reset after flashing
  src/main/drivers/system_stm32f7xx.c
  src/main/startup/system_stm32f7xx.c
Labels: RN: BUGFIX, Tested, hacktoberfest-accepted

#11053 Fixed burst Dshot.
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
Labels: RN: BUGFIX

#11056 Fix BMI270 gyro sync on H743
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_spi_bmi270.c
  src/main/scheduler/scheduler.h
Labels: RN: BUGFIX

#11055 Fix typo
  README.md
Labels: Documentation update

#11042 Fix dma compile error
  src/main/drivers/dma.c
Labels: RN: BUGFIX, Legacy target, hacktoberfest-accepted

#11059 Fix crsf msp over telemetry
  src/main/telemetry/crsf.c
Labels: Testing Required, RN: BUGFIX

#11049 Fix yaw value bug in CRSF telemetry frame
  src/main/telemetry/crsf.c
Labels: RN: BUGFIX, hacktoberfest-accepted

#11017 add feedforward max_rate_limit and jitter_factor to msp for 4.3
  src/main/msp/msp.c
Labels: Ready to Merge, Needs coordination with lua scripts, Tested, hacktoberfest-accepted

#11061 Make deduplication explicit
  Makefile
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
Labels: Rebase Required, Ready to Merge, Tested, RN: REFACTORING

#11060 Add constant (i.e. string) deduplication, including at link time.
  Makefile
Labels: RN: IMPROVEMENT, Tested

#11050 Change filter slider
  src/main/config/simplified_tuning.c
Labels: Ready to Merge, Needs coordination with betaflight-configurator, RN: IMPROVEMENT, Tested

#11083 Fix thrust_linear and transient_throttle_limit value type in CLI
  src/main/cli/settings.c
Labels: RN: BUGFIX, Tested
