Repository betaflight/betaflight, pull requests merged in 2021-01, with the labels that each got.

#10430 Improve rate settings range checking
  src/main/config/config.c
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
Labels: RN: IMPROVEMENT

#10434 Remove unused CLI variables from documentation page
  docs/Cli.md
Labels: Documentation update

#10438 Removed unused BUILD_DIR target from Makefile.
  Makefile
Labels: Build System Improvement

#10439 Minor Makefile improvement.
  Makefile
Labels: Build System Improvement

#10442 Disabled voltage sag compensation in crash flip mode
  src/main/flight/mixer.c
Labels: RN: BUGFIX

#9119 Implement tuning sliders, add to CMS, MSP
  make/source.mk
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms_menu_imu.c
  src/main/config/simplified_tuning.c
  src/main/config/simplified_tuning.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/msp/msp.c
  src/main/msp/msp_protocol.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/target/common_pre.h
Labels: RN: MINOR FEATURE

#10440 Simplified the OSD blink frequency calculation.
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/osd/osd_elements.h
  src/test/unit/osd_unittest.cc
Labels: RN: IMPROVEMENT

#10444 Revert #10383: 'Optimize pin reconfiguration in DSHOT ISR for H7' in maintenance branch.
  src/main/drivers/io.h
  src/main/drivers/pwm_output_dshot_hal.c
Labels: Applied to Branch, RN: BUGFIX

#10445 Revert #10388: 'Fix BIDIR UART issue' in maintenance branch.
  src/main/drivers/serial_uart_stm32f30x.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/drivers/serial_uart_stm32g4xx.c
  src/main/drivers/serial_uart_stm32h7xx.c
Labels: Applied to Branch, RN: BUGFIX

#10454 Added missing GUI box for MSP override.
  src/main/config/config.c
  src/main/msp/msp_box.c
Labels: RN: BUGFIX

#10451 Add more feature for iFlight_H743_AIO support.
  src/main/target/IFLIGHT_H743_AIO/target.c
  src/main/target/IFLIGHT_H743_AIO/target.h
  src/main/target/IFLIGHT_H743_AIO/target.mk
Labels: RN: TARGET UPDATE

#10459 Refactor SD_Init() to return proper SD_Error_t code.
  src/main/drivers/sdio_f4xx.c
  src/main/drivers/sdio_f7xx.c
  src/main/drivers/sdio_h7xx.c
  src/main/drivers/sdmmc_sdio.h
Labels: RN: IMPROVEMENT

#10413 Added vtx device status to MSP
  src/main/drivers/vtx_common.c
  src/main/drivers/vtx_common.h
  src/main/io/vtx_rtc6705.c
  src/main/io/vtx_smartaudio.c
  src/main/io/vtx_tramp.c
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
Labels: RN: IMPROVEMENT

#10410 fixed problem msp_displayport send lost when serial port buffer full
  src/main/drivers/serial_uart_impl.h
Labels: RN: IMPROVEMENT

#10450 Incremented maintenance branch version to 4.2.7.
  src/main/build/version.h
Labels: Applied to Branch, Housekeeping

#10458 [H7] Update power supply configuration
  src/main/startup/system_stm32h7xx.c
Labels: RN: IMPROVEMENT

#10461 Fixed CLI parameter for simplified gyro filters.
  src/main/cli/settings.c
Labels: RN: BUGFIX

#10462 Exclude yaw from AntiGravity generated P boost
  src/main/flight/pid.c
Labels: RN: IMPROVEMENT

#10464 Fix compile errors for ak8975 magnetometer driver
  src/main/drivers/compass/compass_ak8975.c
Labels: RN: BUGFIX

#10467 Altitude hold removal cleanup
  src/main/flight/imu.c
  src/main/flight/imu.h
Labels: Cleanup, RN: IMPROVEMENT

#10469 Fixed unit tests.
  src/test/unit/vtx_unittest.cc
Labels: Fixes broken build, RN: BUGFIX

#10470 Added unit test / sanity check runs to the Azure script.
  azure-pipelines.yml
Labels: Build System Improvement

#10443 Add option to display OSD menus over a solid gray background
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms.c
  src/main/cms/cms_menu_osd.c
  src/main/drivers/display.c
  src/main/drivers/display.h
  src/main/drivers/max7456.c
  src/main/drivers/max7456.h
  src/main/io/displayport_max7456.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/test/unit/cms_unittest.cc
Labels: Needs entry in Release Notes, RN: IMPROVEMENT

#10472 Fix baro sample size minimum range
  src/main/cli/settings.c
Labels: RN: BUGFIX, RN: SAFETY IMPROVEMENT

#10471 Fix possible div-by-zero in current meter
  src/main/sensors/current.c
Labels: RN: BUGFIX

#10468 Added AK8975 magnetometer driver to Unified Targets.
  src/main/target/STM32_UNIFIED/target.h
Labels: RN: TARGET UPDATE

#10448 Only register CMS displayPort for SRXL and CRSF when appropriate
  src/main/cms/cms.c
  src/main/io/displayport_crsf.c
  src/main/io/displayport_srxl.c
Labels: RN: BUGFIX

#10473 Validate that the battery min cell voltage is less than the max cell voltage
  src/main/config/config.c
  src/main/sensors/battery.c
  src/main/sensors/battery.h
Labels: RN: BUGFIX

#10477 Fixed AK8975 driver in maintenance branch.
  src/main/drivers/compass/compass_ak8975.c
Labels: Fixes broken build, RN: BUGFIX

#10478 Updated the CI build status in README.md.
  README.md
Labels: Documentation update

#10479 Reordered configuration validation to put custom target validation to the end.
  src/main/config/config.c
Labels: RN: IMPROVEMENT

#10505 Clarifies and clean-up Formatting style > Curly braces
  docs/development/CodingStyle.md
Labels: Documentation update
