Repository betaflight/betaflight, pull requests merged in 2021-12, with the labels that each got.

#10764 Fix to CRSFv3 uplink debug information and corrects the variable channels amount calculation
  src/main/rx/crsf.c
Labels: RN: BUGFIX

#11016 Rename cms PITCH PI GAIN
  src/main/cms/cms_menu_imu.c
Labels: Ready to Merge, RN: BUGFIX, hacktoberfest-accepted

#10673 Remove Dynamic Notch from "Features"
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/config/config.c
  src/main/config/feature.c
  src/main/config/feature.h
  src/main/flight/dyn_notch_filter.c
  src/main/flight/dyn_notch_filter.h
  src/main/osd/osd.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro_filter_impl.c
  src/main/target/ALIENWHOOP/config.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT, Needs entry in Release Notes

#10930 Add 50 mW TX power level to CRSF protocol
  src/main/rx/crsf.c
  src/main/telemetry/crsf.c
Labels: RN: IMPROVEMENT

#11043 Dynamic idle - values retained, can be activated without RPM filtering, ignores DShot Idle percentage
  src/main/config/config.c
  src/main/flight/mixer.c
  src/main/flight/mixer_init.c
  src/main/flight/rpm_filter.c
  src/main/msp/msp.c
Labels: Ready to Merge, RN: IMPROVEMENT, Tested, hacktoberfest-accepted

#11088 Check for bus number 0 in spiSetBusInstance()
  src/main/drivers/bus_spi.c
Labels: RN: BUGFIX

#11101 Debug modes cleanup
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
  src/main/fc/core.c
  src/main/fc/rc.c
  src/main/sensors/barometer.c
Labels: RN: BUGFIX

#11007 Allow selection of SPI MOSI/MISO DMA streams
  src/main/cli/cli.c
  src/main/drivers/bus_spi.c
  src/main/drivers/dma_reqmap.c
  src/main/drivers/dma_reqmap.h
  src/main/fc/init.c
  src/main/pg/bus_spi.c
Labels: hacktoberfest-accepted

#11112 MSPv2 over telemetry
  src/main/msp/msp.h
  src/main/msp/msp_serial.c
  src/main/msp/msp_serial.h
  src/main/rx/crsf.c
  src/main/rx/crsf.h
  src/main/telemetry/crsf.c
  src/main/telemetry/crsf.h
  src/main/telemetry/msp_shared.c
  src/main/telemetry/msp_shared.h
  src/main/telemetry/smartport.c
  src/test/unit/telemetry_crsf_msp_unittest.cc
  src/test/unit/telemetry_crsf_unittest.cc
Labels: RN: IMPROVEMENT, Needs coordination with lua scripts

#11082 Remove old github issue template
  .github/issue_template.md
Labels: Cleanup

#11122 Only call sdCardAndFSInit() when SD card is in use
  src/main/fc/init.c
Labels: RN: BUGFIX

#11128 No space in sizeof() as per Betaflight coding standard
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
  src/main/drivers/bus_i2c_busdev.c
  src/main/drivers/bus_spi.c
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/flash.c
  src/main/drivers/flash_m25p16.c
  src/main/drivers/flash_w25m.c
  src/main/drivers/flash_w25n01g.c
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/light_ws2811strip.h
  src/main/drivers/max7456.c
  src/main/drivers/sdcard_spi.c
  src/main/drivers/timer.c
  src/main/drivers/timer_hal.c
  src/main/drivers/vtx_rtc6705.c
  src/main/vcp_hal/usbd_cdc_interface.c
  src/main/vcpf4/usbd_cdc_vcp.c
  src/test/unit/rc_controls_unittest.cc
Labels: RN: REFACTORING

#11129 Fix FrSky D8 protocol bind issues
  src/main/rx/cc2500_frsky_d.c
  src/main/rx/cc2500_frsky_shared.c
  src/main/rx/cc2500_frsky_shared.h
Labels: RN: BUGFIX

#10813 Track state execution time for OSD, baro, rx and GPS tasks and inform scheduler of next state execution time
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_ll.c
  src/main/drivers/bus_spi_stdperiph.c
  src/main/drivers/display.c
  src/main/drivers/display.h
  src/main/drivers/max7456.c
  src/main/drivers/max7456.h
  src/main/fc/init.c
  src/main/fc/tasks.c
  src/main/flight/position.c
  src/main/io/displayport_crsf.c
  src/main/io/displayport_frsky_osd.c
  src/main/io/displayport_hott.c
  src/main/io/displayport_max7456.c
  src/main/io/displayport_msp.c
  src/main/io/displayport_oled.c
  src/main/io/displayport_srxl.c
  src/main/io/gps.c
  src/main/io/ledstrip.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/osd/osd_elements.h
  src/main/pg/sdcard.c
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/main/sensors/barometer.c
  src/main/sensors/barometer.h
  src/main/target/common_pre.h
  src/main/vcpf4/usbd_desc.c
  src/test/unit/flight_imu_unittest.cc
  src/test/unit/ledstrip_unittest.cc
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
  src/test/unit/scheduler_unittest.cc
  src/test/unit/unittest_displayport.h
  src/test/unit/ws2811_unittest.cc
Labels: RN: IMPROVEMENT

#11116 Fix SDFT batch size
  src/main/common/sdft.c
Labels: RN: BUGFIX

#11123 Fix dynamic notch PT1 gain
  src/main/flight/dyn_notch_filter.c
Labels: RN: BUGFIX

#11103 Fix telemetry displayport initialisation
  src/main/fc/init.c
Labels: RN: BUGFIX

#11131 Remove shared MSP buffer
  src/main/msp/msp_serial.c
  src/main/msp/msp_serial.h
  src/main/telemetry/msp_shared.c
  src/main/telemetry/msp_shared.h
  src/test/unit/telemetry_crsf_msp_unittest.cc
Labels: RN: BUGFIX

#10694 Fix missing SPI5/6 configuration.
  src/main/drivers/bus_spi.c
  src/main/pg/bus_spi.c
  src/main/target/common_defaults_post.h
Labels: Ready to Merge, RN: IMPROVEMENT

#11113 deduplicate more blackbox names
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
Labels: RN: IMPROVEMENT, Tested, Needs coordination with blackbox-log-viewer

#11033 Fix peaky task duration estimation
  src/main/cli/settings.c
  src/main/config/config.c
  src/main/config/config.h
  src/main/drivers/light_ws2811strip.c
  src/main/fc/dispatch.c
  src/main/fc/tasks.c
  src/main/flight/imu.c
  src/main/flight/position.c
  src/main/io/beeper.c
  src/main/io/ledstrip.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/main/sensors/barometer.c
  src/main/sensors/battery.c
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/flight_imu_unittest.cc
  src/test/unit/ledstrip_unittest.cc
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
  src/test/unit/vtx_unittest.cc
  src/test/unit/ws2811_unittest.cc
Labels: hacktoberfest-accepted

#10972 Add ledstrip_brightness to control LED strip brightness by percentage
  src/main/cli/settings.c
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/light_ws2811strip.h
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
  src/test/unit/ledstrip_unittest.cc
Labels: RN: MINOR FEATURE

#11135 If GPS serial data remains, reschedule task to run again after 1ms
  src/main/fc/tasks.c
  src/main/io/gps.c
  src/main/io/gps.h
Labels: For Discussion, RN: BUGFIX

#11114 MSP commands for calculating/requesting but not setting simplified tuning/values
  src/main/cli/cli.c
  src/main/cms/cms_menu_imu.c
  src/main/config/simplified_tuning.c
  src/main/config/simplified_tuning.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/msp/msp.c
  src/main/msp/msp_protocol.h
  src/main/sensors/gyro.h
Labels: Needs coordination with betaflight-configurator, RN: BUGFIX

#11111 Make CMS fields readonly when overridden by a slider and mark with an S
  src/main/cms/cms.c
  src/main/cms/cms.h
  src/main/cms/cms_menu_blackbox.c
  src/main/cms/cms_menu_failsafe.c
  src/main/cms/cms_menu_firmware.c
  src/main/cms/cms_menu_gps_rescue.c
  src/main/cms/cms_menu_imu.c
  src/main/cms/cms_menu_ledstrip.c
  src/main/cms/cms_menu_main.c
  src/main/cms/cms_menu_misc.c
  src/main/cms/cms_menu_osd.c
  src/main/cms/cms_menu_persistent_stats.c
  src/main/cms/cms_menu_power.c
  src/main/cms/cms_menu_saveexit.c
  src/main/cms/cms_menu_vtx_common.c
  src/main/cms/cms_menu_vtx_rtc6705.c
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/cms/cms_menu_vtx_tramp.c
  src/main/cms/cms_types.h
  src/test/unit/cms_unittest.cc
Labels: For Discussion, Review Needed, RN: IMPROVEMENT

#10921 Added m9n support
  src/main/io/gps.c
  src/main/io/gps.h
Labels: RN: IMPROVEMENT

#11099 Fix code aligning in osd_elements.c
  src/main/osd/osd_elements.c
Labels: RN: REFACTORING

#11143 Enhance SDFT noise floor
  src/main/flight/dyn_notch_filter.c
Labels: RN: BUGFIX

#11096 Fix use of floating point math functions
  lib/main/MAVLink/mavlink_conversions.h
  src/main/flight/gps_rescue.c
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/io/vtx_smartaudio.c
  src/main/sensors/gyro.c
  src/test/unit/flight_imu_unittest.cc
  src/test/unit/maths_unittest.cc
  src/test/unit/pid_unittest.cc
Labels: RN: BUGFIX

#11011 Dshot dshot_bitbang=AUTO behaviour change for non-F4
  src/main/drivers/motor.c
Labels: RN: IMPROVEMENT

#11134 Disable OLC on low flash targets to save around 2kB
  src/main/target/common_pre.h
Labels: RN: TARGET UPDATE

#10762 add SK6812 RGBW 4-channel LEDs
  docs/LedStrip.md
  src/main/cli/settings.c
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/light_ws2811strip.h
Labels: RN: IMPROVEMENT

#11141 Disable GYRO_EXTI on boards with Gyro and OSD on same SPI channel
  src/main/target/KROOZX/target.h
  src/main/target/NOX/target.h
  src/main/target/OMNIBUSF4FW/target.h
  src/main/target/YUPIF4/target.h
  src/main/target/YUPIF7/target.h
Labels: RN: BUGFIX

#10695 Initial STM32H730 CPU Support
  Makefile
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.c
  make/mcu/STM32H7.mk
  make/targets.mk
  src/link/stm32_h730_common.ld
  src/link/stm32_h730_common_post.ld
  src/link/stm32_ram_h730_exst.ld
  src/link/stm32_ram_h730_exst_post.ld
  src/main/build/build_config.c
  src/main/build/build_config.h
  src/main/cli/cli.c
  src/main/config/config_streamer.c
  src/main/drivers/adc.h
  src/main/drivers/adc_stm32g4xx.c
  src/main/drivers/adc_stm32h7xx.c
  src/main/drivers/dma.h
  src/main/drivers/dma_reqmap.c
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/io.c
  src/main/drivers/io_def_generated.h
  src/main/drivers/light_ws2811strip_hal.c
  src/main/drivers/pwm_output_dshot_hal_hal.c
  src/main/drivers/sdio_h7xx.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/system_stm32h7xx.c
  src/main/drivers/timer_stm32h7xx.c
  src/main/drivers/transponder_ir_io_hal.c
  src/main/drivers/usb_msc_h7xx.c
  src/main/platform.h
  src/main/startup/startup_stm32h730xx.s
  src/main/startup/stm32h7xx_hal_conf.h
  src/main/startup/system_stm32h7xx.c
  src/main/target/common_pre.h
  src/main/vcp_hal/usbd_conf_stm32h7xx.c
  src/utils/def_generated.pl
Labels: RN: NEW TARGET

#10613 Allow H7 targets to specify an ADC device and channel
  src/main/drivers/adc_stm32h7xx.c
  src/main/pg/adc.c
  src/main/pg/adc.h
Labels: RN: IMPROVEMENT

#11168 fix for gps coordinates not shown on OSD
  src/main/io/gps.c
Labels: RN: BUGFIX

#11179 SPI: fix compilation on F4 when DSHOT_BITBANG is not used
  src/main/drivers/bus_spi.c
Labels: RN: BUGFIX

#11169 Reduce number of OSD bytes transferred in polled mode
  src/main/drivers/max7456.c
  src/main/osd/osd.c
  src/test/unit/osd_unittest.cc
Labels: RN: BUGFIX
