Repository betaflight/betaflight, pull requests merged in 2021-09, with the labels that each got.

#10835 Dynamic notch refactoring
  make/source.mk
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/config/config.c
  src/main/fc/core.c
  src/main/flight/dyn_notch_filter.c
  src/main/flight/dyn_notch_filter.h
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/pg/dyn_notch.c
  src/main/pg/dyn_notch.h
  src/main/pg/pg_ids.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_filter_impl.c
  src/main/sensors/gyro_init.c
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: Tested, RN: REFACTORING

#10927 Fix pg_resetdata location in FLASH
  src/link/stm32_flash_f7_split.ld
Labels: RN: BUGFIX

#10774 restore rc smoothing to level and horizon modes
  src/main/cli/cli.c
  src/main/fc/rc.c
  src/main/fc/rc_controls.h
Labels: RN: BUGFIX, Bugfix

#10777 move transition to feedforward
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/fc/rc_adjustments.c
  src/main/flight/feedforward.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/main/msp/msp.c
  src/main/target/ALIENWHOOP/config.c
  src/main/target/NAZE/config.c
  src/test/unit/pid_unittest.cc
Labels: RN: IMPROVEMENT, Tested

#10861 Fix typo in comment
  src/main/flight/pid.h
Labels: RN: BUGFIX

#10905 fix typos in code comments in main/common and main/drivers folders
  src/main/common/printf.h
  src/main/common/time.h
  src/main/common/utils.h
  src/main/drivers/barometer/barometer_bmp085.c
  src/main/drivers/compass/compass_ak8963.c
  src/main/drivers/dshot.c
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/dshot_command.c
  src/main/drivers/dshot_command.h
  src/main/drivers/exti.c
  src/main/drivers/max7456.c
  src/main/drivers/mco.c
  src/main/drivers/sdcard_standard.h
  src/main/drivers/sdio_f4xx.c
  src/main/drivers/system.c
  src/main/drivers/timer.c
  src/main/drivers/timer_stm32h7xx.c
Labels: Documentation update

#10845 Fix TIM15_CH2 IO assignment
  src/main/drivers/timer_def.h
  src/main/drivers/timer_stm32h7xx.c
Labels: RN: BUGFIX

#10904 Fix typo in gps_conversion.c
  src/main/common/gps_conversion.c
Labels: RN: REFACTORING

#10886 Fixed missing include in SITL file.
  src/main/target/SITL/udplink.c
Labels: RN: BUGFIX

#10800 spelling fixes in documentation
  docs/Battery.md
  docs/Cli.md
  docs/Customized Version.md
  docs/Failsafe.md
  docs/Inflight Adjustments.md
  docs/LedStrip.md
Labels: Documentation update

#10806 BV/BIT macro consolidation
  src/main/drivers/rx/rx_nrf24l01.c
  src/main/drivers/rx/rx_nrf24l01.h
  src/main/rx/nrf24_cx10.c
  src/main/rx/nrf24_inav.c
  src/main/rx/nrf24_kn.c
  src/main/rx/nrf24_syma.c
  src/main/rx/nrf24_v202.c
  src/main/telemetry/crsf.c
Labels: RN: REFACTORING

#10766 Fix the RESET_FORCED case not being used.
  src/main/drivers/system_stm32h7xx.c
  src/main/startup/system_stm32h7xx.c
Labels: RN: BUGFIX

#10785 MavLink RSSI Range
  src/main/telemetry/mavlink.c
Labels: RN: BUGFIX

#10585 hide DMIN RATIO unless USE_D_MIN
  src/main/cms/cms_menu_imu.c
  src/main/config/simplified_tuning.c
  src/main/msp/msp.c
Labels: RN: BUGFIX

#10706 ICM42688-P Acc/Gyro sensor support
  src/main/cli/settings.c
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/accgyro/accgyro_spi_icm42605.c
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
  src/main/drivers/accgyro/accgyro_spi_icm426xx.h
  src/main/drivers/accgyro/accgyro_spi_mpu6500.c
  src/main/sensors/acceleration.h
  src/main/sensors/acceleration_init.c
  src/main/sensors/gyro_init.c
  src/main/target/NUCLEOH723ZG/target.h
  src/main/target/NUCLEOH723ZG/target.mk
  src/main/target/NUCLEOH725ZG/target.h
  src/main/target/NUCLEOH725ZG/target.mk
  src/main/target/NUCLEOH743/target.h
  src/main/target/NUCLEOH743/target.mk
  src/main/target/NUCLEOH7A3ZI/target.h
  src/main/target/NUCLEOH7A3ZI/target.mk
  src/main/target/common_post.h
Labels: RN: MINOR FEATURE

#10897 Fix memory corruption caused by MSP_BOXNAMES buffer overflow.
  src/main/msp/msp_serial.h
Labels: RN: BUGFIX

#10879 STM32H7 - Fix SPI5 DMA RX mapping.
  src/main/drivers/dma_reqmap.c
Labels: RN: BUGFIX

#10873 RTC6705SOFTSPI - Fix null pointer de-reference caused by 87c8847c13d7f759548c2384e400d2bc387b159a
  src/main/drivers/vtx_rtc6705.c
Labels: RN: BUGFIX

#10877 Tidy up SPI sequence indexing and advance write address in m25p16_pageProgramContinue()
  lib/main/STM32F7/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c
  src/main/drivers/flash_m25p16.c
  src/main/fc/rc_controls.h
  src/main/target/ALIENWHOOP/config.c
Labels: RN: BUGFIX

#10818 Fix UART/USART mismatch for USART10.
  src/main/io/serial.c
Labels: RN: BUGFIX, Bugfix

#10885 Fixed the 'make pre-push' build on MacOS.
  Makefile
Labels: Pinned, Build System Improvement

#10940 UART - Add generic pin swap functionality.
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_pinconfig.c
Labels: RN: IMPROVEMENT

#10832 Suport for long range RC links with refresh rate lower than 33Hz down to 16Hz
  src/main/fc/rc.c
  src/main/fc/rc.h
  src/main/flight/feedforward.c
  src/main/rx/rx.c
Labels: RN: IMPROVEMENT

#10812 Add support for Zbit ZB25Q128 flash
  src/main/drivers/flash_m25p16.c
Labels: RN: IMPROVEMENT

#10856 Change RPM Filter minHz limit / rename CLI commands and parameters
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/flight/rpm_filter.c
  src/main/flight/rpm_filter.h
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#10919 New PID sliders and changed defaults
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/config/config.c
  src/main/config/simplified_tuning.c
  src/main/config/simplified_tuning.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/msp/msp.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
Labels: RN: IMPROVEMENT, Tested

#10970 Fixed 'timer show' for bitbanged Dshot timers.
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_bitbang.h
  src/main/drivers/timer_common.c
Labels: RN: BUGFIX

#10969 Clarified the macro name for the resourceValue_t max index.
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#10960 Cleaned up UART pin swap.
  src/main/drivers/serial_uart_hal.c
Labels: RN: REFACTORING

#10959 Fixed optimisation for board alignment.
  src/main/sensors/boardalignment.c
Labels: RN: IMPROVEMENT

#10978 change lowpass filter CLI names
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms_menu_imu.c
  src/main/config/config.c
  src/main/config/simplified_tuning.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/main/msp/msp.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_init.c
  src/main/target/ALIENWHOOP/config.c
  src/test/unit/pid_unittest.cc
  src/test/unit/sensor_gyro_unittest.cc
Labels: RN: IMPROVEMENT

#10923 Improved maintainability of the piniobox configuration.
  src/main/pg/piniobox.c
Labels: RN: REFACTORING

#10947 Fixed non-portable code.
  src/main/build/debug_pin.c
Labels: RN: IMPROVEMENT

#10949 Removed softserial loopback.
  src/main/fc/init.c
  src/main/fc/init.h
  src/main/main.c
Labels: RN: IMPROVEMENT

#10950 Cleanup of the bus switch functionality.
  src/main/fc/init.c
Labels: RN: IMPROVEMENT

#10953 Fixed instances of 'FAST_CODE FAST_CODE_NOINLINE'.
  src/main/main.c
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#10958 Cleaned up the reset reason handling code a bit.
  src/main/drivers/system.h
  src/main/drivers/system_stm32g4xx.c
  src/main/drivers/system_stm32h7xx.c
  src/main/startup/system_stm32g4xx.c
  src/main/startup/system_stm32h7xx.c
Labels: RN: REFACTORING

#10895 Added resource allocation for DMA.
  make/source.mk
  src/main/drivers/adc_stm32f10x.c
  src/main/drivers/adc_stm32f30x.c
  src/main/drivers/adc_stm32f4xx.c
  src/main/drivers/adc_stm32f7xx.c
  src/main/drivers/adc_stm32g4xx.c
  src/main/drivers/adc_stm32h7xx.c
  src/main/drivers/bus_spi.c
  src/main/drivers/dma.c
  src/main/drivers/dma.h
  src/main/drivers/dma_common.c
  src/main/drivers/dma_impl.h
  src/main/drivers/dma_stm32f4xx.c
  src/main/drivers/dma_stm32f7xx.c
  src/main/drivers/dma_stm32g4xx.c
  src/main/drivers/dma_stm32h7xx.c
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/light_ws2811strip_hal.c
  src/main/drivers/light_ws2811strip_stdperiph.c
  src/main/drivers/pwm_output_dshot.c
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/pwm_output_dshot_hal_hal.c
  src/main/drivers/sdio_f4xx.c
  src/main/drivers/sdio_f7xx.c
  src/main/drivers/sdio_h7xx.c
  src/main/drivers/sdmmc_sdio.h
  src/main/drivers/serial_uart.c
  src/main/drivers/transponder_ir_io_hal.c
  src/main/drivers/transponder_ir_io_stdperiph.c
  src/main/msc/usbd_storage_sdio.c
Labels: RN: IMPROVEMENT, Tested

#10986 Fixed header declaration for 'resetPidProfile()'.
  src/main/config/config.h
  src/main/flight/pid.h
Labels: RN: BUGFIX

#10976 Uprev PG config since 4.2.9
  src/main/pg/sdcard.c
Labels: RN: BUGFIX
