Repository betaflight/betaflight, pull requests merged in 2022-07, with the labels that each got.

#11714 Added invite to the Betaflight Discord server to the README
  README.md
Labels: RN: IGNORE

#11716 Fix mcu types
  src/main/cli/cli.c
Labels: RN: BUGFIX

#11708 Change DEFAULT_RX_FEATURE
  src/main/config/feature.h
Labels: Cleanup

#11032 Support for GCC 11.2.1
  Makefile
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  make/mcu/STM32G4.mk
  make/mcu/STM32H7.mk
  src/main/cli/cli.c
  src/main/common/utils.h
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/sdio_f4xx.c
  src/main/drivers/sdio_f7xx.c
  src/main/drivers/serial_uart_hal.c
  src/main/io/asyncfatfs/asyncfatfs.c
  src/main/io/displayport_crsf.c
  src/main/msc/usbd_storage_sd_spi.c
  src/main/startup/system_stm32f4xx.c
  src/main/target/common_pre.h
  src/test/Makefile
Labels: Build System Improvement

#11707 Add support for BMI160 gyro for unified targets where TARGET_FLASH_SIZE > 512
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
  src/main/drivers/accgyro/accgyro_spi_bmi270.c
  src/main/target/STM32_UNIFIED/target.h
Labels: RN: BUGFIX, RN: TARGET UPDATE

#11672 Make sure to write dshot stop cmd to all other motors when targeting …
  src/main/drivers/dshot_command.c
Labels: RN: BUGFIX

#11721 Fix debug mode D_LPF
  src/main/flight/pid.c
Labels: RN: BUGFIX

#11132 Use GitHub Actions for CI
  .github/workflows/ci.yml
  Makefile
  make/tools.mk
Labels: For Discussion, Rebase Required

#11713 Fix data overwriting in VCP_DataTx on F4
  src/main/vcpf4/usbd_cdc_vcp.c
Labels: For Discussion, RN: BUGFIX, Tested

#11184 Fix cli unit test on Clang 13
  src/main/scheduler/scheduler.c
  src/test/unit/cli_unittest.cc
Labels: RN: BUGFIX

#11680 Update ARM SDK to 11.2-2022
  make/tools.mk
Labels: Build System Improvement

#11724 Backport Ghost jitter fix #11234
  src/main/rx/ghst.c
Labels: RN: BUGFIX

#11581 Bump clang version
  .github/workflows/build-release.yml
  .github/workflows/ci.yml
  azure-pipelines.yml
  docs/development/Building in Ubuntu.md
  src/test/Makefile
Labels: Build System Improvement

#11726 Fix data overwriting in VCP_DataTx on F4 #11713 @daleckystepan
  src/main/vcpf4/usbd_cdc_vcp.c
Labels: RN: BUGFIX

#11727 Make sure to write dshot stop cmd to all other motors when targeting …
  src/main/drivers/dshot_command.c
Labels: RN: BUGFIX

#11728 Add ICM42688P for all unified builds
  src/main/target/STM32_UNIFIED/target.h
Labels: RN: IMPROVEMENT

#11729 Add STM32F411SX1280 unified target
  make/targets_list.mk
  src/main/rx/rx.c
  src/main/target/STM32_UNIFIED/STM32F411SX1280.mk
  src/main/target/STM32_UNIFIED/target.h
  src/main/target/STM32_UNIFIED/target.mk
Labels: RN: NEW TARGET

#11730 Fix compilation error when USE_RX_MSP_OVERRIDE is defined without
  src/main/target/common_post.h
Labels: RN: BUGFIX

#11723 Move to Github Actions for PRs
  .github/workflows/artifact-links.yml
  .github/workflows/ci.yml
  .github/workflows/hide-artifact-links.yml
  .github/workflows/nightly.yml
  .github/workflows/pr.yml
  azure-pipelines.yml
  make/targets_list.mk
  make/tools.mk
  src/main/fc/core.c
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT, Build System Improvement

#11719 Flashfs: Add support for asynchronous complete erase
  src/main/fc/tasks.c
  src/main/io/flashfs.c
  src/main/io/flashfs.h
Labels: RN: BUGFIX

#11734 Fix gcc required subversion
  make/tools.mk
Labels: Bugfix, Build System Improvement

#11750 Revert b6e2790f as this broke FrSky SPI
  lib/main/STM32_USB_Device_Library/Class/cdc/src/usbd_cdc_core.c
  src/main/cli/cli.c
  src/main/drivers/buf_writer.c
  src/main/drivers/buf_writer.h
  src/main/vcp_hal/usbd_cdc_interface.c
  src/main/vcpf4/usbd_cdc_vcp.c
  src/test/unit/cli_unittest.cc
Labels: RN: BUGFIX

#11679 update antigravity for 4.4
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms_menu_imu.c
  src/main/fc/parameter_names.h
  src/main/fc/rc.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/main/msp/msp.c
  src/main/msp/msp_box.c
  src/main/target/ALIENWHOOP/config.c
  src/test/unit/pid_unittest.cc
Labels: Needs coordination with betaflight-configurator, Tested, Needs coordination with blackbox-log-viewer

#11740 Don't set sleepTime to ut_delay in BARO_STATE_PRESSURE_SAMPLE state
  src/main/sensors/barometer.c
Labels: RN: IMPROVEMENT

#11769 CLI: Raise upper limit of dyn_idle_min_rpm
  src/main/cli/settings.c
  src/main/flight/pid.h
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT, Tested
