Repository betaflight/betaflight, pull requests merged in 2022-08, with the labels that each got.

#11771 Add OSD_CRAFTNAME_MSGS to insert additional data into CraftName
  src/main/cli/settings.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/target/common_pre.h
Labels: RN: MINOR FEATURE

#11761 Remove superfluous double ;
  lib/main/CMSIS/Core/Include/cmsis_iccarm.h
  lib/main/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c
  lib/main/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c
  lib/main/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c
  lib/main/STM32G4/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cryp.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.c
  lib/main/STM32H7/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c
  lib/main/STM32_USB_OTG_Driver/src/usb_core.c
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
  src/main/drivers/vtx_rtc6705.c
  src/main/osd/osd_elements.c
  src/main/osd/osd_warnings.c
  src/test/unit/flight_failsafe_unittest.cc
  src/test/unit/rx_crsf_unittest.cc
Labels: RN: BUGFIX

#11776 Adjusting .gitignore for automated build scratch space.
  .gitignore
Labels: Build System Improvement

#11795 Allow dyn_notch_min_hz as low as 20Hz
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT

#11801 Lower max CraftName length to avoid ugly truncation errors
  src/main/osd/osd_elements.c
Labels: RN: BUGFIX

#11756 Gps rescue - default to Ublox, fix landing phase criteria, fix level mode offsets
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_gps_rescue.c
  src/main/fc/parameter_names.h
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/io/gps.c
Labels: Ready to Merge, RN: BUGFIX
