Repository betaflight/betaflight, pull requests merged in 2022-06, with the labels that each got.

#11628 failsafe by switch aux channel hold change
  src/main/flight/failsafe.c
  src/main/rx/rx.c
Labels: RN: BUGFIX

#11627 Added BMI270 drivers to CRAZYBEEF4SX1280 target
  src/main/target/CRAZYBEEF4SX1280/target.h
  src/main/target/CRAZYBEEF4SX1280/target.mk
Labels: RN: TARGET UPDATE

#11644 Increment eeprom version before 4.3 release
  src/main/config/config_eeprom.h
Labels: Housekeeping

#11648 Add STM32F411SX1280 unified target
  make/targets_list.mk
  src/main/rx/rx.c
  src/main/target/STM32_UNIFIED/STM32F411SX1280.mk
  src/main/target/STM32_UNIFIED/target.h
  src/main/target/STM32_UNIFIED/target.mk
Labels: RN: NEW TARGET

#11658 Use gdwarf-5 debugging information.
  Makefile
Labels: Build System Improvement

#11659 Create variably named files as an additional make step.
  Makefile
Labels: Build System Improvement

#11678 Increment MSP version to 1.45 (4.4)
  src/main/msp/msp_protocol.h
  src/test/unit/rx_spi_expresslrs_telemetry_unittest.cc
Labels: Housekeeping

#11664 Add ICM42688P for all unified builds
  src/main/target/STM32_UNIFIED/target.h
Labels: RN: TARGET UPDATE

#11661 Fix compilation error when USE_RX_MSP_OVERRIDE is defined without USE_RX_MSP.
  src/main/target/common_post.h
Labels: RN: BUGFIX

#10054 Adds blackbox fields_disabled_mask to msp
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#11683 Remove unused F1 and F3 files
  src/main/drivers/adc_stm32f10x.c
  src/main/drivers/adc_stm32f30x.c
  src/main/startup/startup_stm32f10x_hd_gcc.S
  src/main/startup/startup_stm32f10x_md_gcc.S
  src/main/startup/startup_stm32f30x_md_gcc.S
  src/main/startup/startup_stm32f3_debug_hardfault_handler.S
  src/main/vcp/hw_config.h
Labels: Build System Improvement, RN: IGNORE

#11668 Remove unused rxRefreshRate
  src/main/rx/crsf.c
  src/main/rx/fport.c
  src/main/rx/ghst.c
  src/main/rx/ibus.c
  src/main/rx/jetiexbus.c
  src/main/rx/msp.c
  src/main/rx/pwm.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/rx/rx_spi.c
  src/main/rx/sbus.c
  src/main/rx/spektrum.c
  src/main/rx/srxl2.c
  src/main/rx/sumd.c
  src/main/rx/sumh.c
  src/main/rx/xbus.c
  src/test/unit/rx_ibus_unittest.cc
  src/test/unit/rx_sumd_unittest.cc
Labels: RN: REFACTORING

#11660 Allow FEATURE_CUT to be used on targets with any amount of flash.
  src/main/target/common_pre.h
Labels: Build System Improvement

#11579 Update GPS Rescue
  src/main/blackbox/blackbox.c
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/cms/cms_menu_gps_rescue.c
  src/main/fc/core.c
  src/main/fc/parameter_names.h
  src/main/fc/rc_controls.c
  src/main/flight/failsafe.c
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/flight/imu.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/osd/osd_elements.c
  src/main/rx/rx.c
  src/main/telemetry/ghst.c
  src/main/telemetry/hott.c
  src/main/telemetry/jetiexbus.c
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/flight_failsafe_unittest.cc
  src/test/unit/rc_controls_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: Testing Required, RN: SAFETY IMPROVEMENT

#11684 We are not in RC phase anymore
  .github/pull_request_template.md
Labels: Housekeeping, RN: IGNORE

#11313 Blackbox increase resolution on setpoint, gyro and rounding
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox.h
  src/main/cli/settings.c
Labels: For Discussion, Needs coordination with blackbox-log-viewer

#10801 IRC Ghost protocol improvements
  src/main/rx/ghst.c
  src/main/rx/ghst.h
  src/main/rx/ghst_protocol.h
  src/main/telemetry/ghst.c
  src/main/telemetry/ghst.h
Labels: Ready to Merge, RN: BUGFIX, Tested

#11693 Ghost rssi fix
  src/main/rx/ghst.c
Labels: RN: BUGFIX

#11682 Remove unused STM32 USB FS lib
  Makefile
  lib/main/STM32_USB-FS-Device_Driver/Release_Notes.html
  lib/main/STM32_USB-FS-Device_Driver/inc/usb_core.h
  lib/main/STM32_USB-FS-Device_Driver/inc/usb_def.h
  lib/main/STM32_USB-FS-Device_Driver/inc/usb_init.h
  lib/main/STM32_USB-FS-Device_Driver/inc/usb_int.h
  lib/main/STM32_USB-FS-Device_Driver/inc/usb_lib.h
  lib/main/STM32_USB-FS-Device_Driver/inc/usb_mem.h
  lib/main/STM32_USB-FS-Device_Driver/inc/usb_regs.h
  lib/main/STM32_USB-FS-Device_Driver/inc/usb_sil.h
  lib/main/STM32_USB-FS-Device_Driver/inc/usb_type.h
  lib/main/STM32_USB-FS-Device_Driver/src/usb_core.c
  lib/main/STM32_USB-FS-Device_Driver/src/usb_init.c
  lib/main/STM32_USB-FS-Device_Driver/src/usb_int.c
  lib/main/STM32_USB-FS-Device_Driver/src/usb_mem.c
  lib/main/STM32_USB-FS-Device_Driver/src/usb_regs.c
  lib/main/STM32_USB-FS-Device_Driver/src/usb_sil.c
  make/mcu/STM32F4.mk
Labels: Build System Improvement, Library

#11670 Extract function toUpperCase for osd elements
  src/main/osd/osd_elements.c
Labels: RN: REFACTORING

#11697 Only write to FLASH once 64 bytes are buffered
  src/main/blackbox/blackbox_io.c
  src/main/io/flashfs.c
  src/main/io/flashfs.h
Labels: RN: IMPROVEMENT

#11671 Save flash: Replace CLI params for OSD stats and warnings with bitmasks
  src/main/cli/settings.c
Labels: RN: IMPROVEMENT

#11669 Use timed timeouts for USB HAL functions, not simple counts, as per H7
  lib/main/STM32F4/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
  lib/main/STM32F7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c
Labels: RN: IMPROVEMENT

#11196 Style: Use angle brackets with standard library headers
  src/main/build/build_config.c
  src/main/common/sensor_alignment.c
  src/main/drivers/camera_control.c
  src/main/drivers/sdio_f4xx.c
  src/main/drivers/sdio_f7xx.c
  src/main/drivers/sdio_h7xx.c
  src/main/io/beeper.c
  src/main/sensors/battery.c
  src/main/sensors/current.c
  src/main/sensors/voltage.c
  src/main/vcp_hal/usbd_cdc_interface.c
  src/main/vcpf4/usbd_cdc_vcp.c
  src/test/unit/alignsensor_unittest.cc
Labels: RN: REFACTORING

#11662 MAX7456 cleanups 1
  src/main/drivers/display.c
  src/main/drivers/display.h
  src/main/drivers/max7456.c
  src/main/drivers/max7456.h
  src/main/io/displayport_max7456.c
Labels: Rebase / Squash required, RN: REFACTORING

#11663 Use the new render attribute for diff/resource yaml form
  .github/ISSUE_TEMPLATE/firmware-bug-report.yml
Labels: Housekeeping

#11302 Fixing segmentation fault of SITL.
  src/main/target/SITL/target.c
Labels: RN: BUGFIX

#11326 Refactoring IMU, ACC and small PID loop improvements
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/fc/core.c
  src/main/fc/tasks.c
  src/main/flight/imu.c
  src/main/flight/imu.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/main/osd/osd.c
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/acceleration_init.c
  src/main/sensors/acceleration_init.h
  src/main/sensors/gyro.c
  src/main/sensors/gyro.h
  src/main/sensors/gyro_init.c
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/flight_imu_unittest.cc
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
  src/test/unit/pid_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: Testing Required, RN: IMPROVEMENT, RN: REFACTORING
