Repository betaflight/betaflight, pull requests merged in 2022-04, with the labels that each got.

#11483 Fix ELRS lost connection race condition
  src/main/rx/expresslrs.c
Labels: RN: BUGFIX

#11494 Fix [Bidirectional] DShot issues on G4, F7 and H7 by reducing GPIO speed
  src/main/drivers/dshot_bitbang.c
Labels: RN: BUGFIX

#11497 fix for failsafe to apply throttle, aux and recovery delay settings
  src/main/flight/failsafe.c
  src/main/flight/failsafe.h
  src/main/rx/rx.c
  src/test/unit/flight_failsafe_unittest.cc
Labels: RN: BUGFIX

#11498 Create release.yml
  .github/release.yml
Labels: Housekeeping

#11504 Adding CLI min for failsafe_delay (value of '2' - 0.2s)
  src/main/cli/settings.c
  src/main/cms/cms_menu_failsafe.c
  src/main/flight/failsafe.c
Labels: RN: SAFETY IMPROVEMENT

#11509 Failsafe changes proposed for RC5
  docs/Failsafe.md
  docs/Failsafe_before_4.3.md
  src/main/fc/core.c
  src/main/flight/failsafe.c
  src/main/flight/failsafe.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/scheduler/scheduler.c
  src/test/unit/flight_failsafe_unittest.cc
  src/test/unit/rx_ranges_unittest.cc
  src/test/unit/rx_rx_unittest.cc
Labels: RN: SAFETY IMPROVEMENT, Bugfix

#11469 DSHOT/Bitbang - Hold the line at idle for 1 extra bit period.
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_bitbang_impl.h
Labels: RN: BUGFIX

#11461 ELRS / NVIC cleanup
  src/main/drivers/nvic.h
  src/main/drivers/rx/rx_sx127x.c
Labels: RN: REFACTORING

#11524 Prevent false failsafe / rx loss on eeprom write for all RX protocols
  src/main/config/config.c
  src/main/rx/rx.c
  src/main/rx/rx.h
Labels: RN: BUGFIX

#11523 Remove duplicate line in unit test
  src/test/unit/flight_failsafe_unittest.cc
Labels: RN: BUGFIX

#11513 widening range of BLHeli/_S device id
  src/main/io/serial_4way.c
Labels: RN: IMPROVEMENT

#11533 Initialize tasks data earlier
  src/main/fc/init.c
  src/main/fc/tasks.c
  src/main/fc/tasks.h
Labels: RN: BUGFIX, Tested

#11530 fix for GPS Return failure in RC4 and RC5
  src/main/fc/core.c
  src/main/rx/rx.c
Labels: RN: BUGFIX, Tested

#11419 Update Code of Conduct to 2.1
  CODE_OF_CONDUCT.md
Labels: Documentation update, Housekeeping

#11521 Fix READY_BEEP
  src/main/io/gps.c
Labels: RN: BUGFIX

#11534 Fix SPI LL Segment Repetition
  src/main/drivers/bus_spi_ll.c
Labels: RN: BUGFIX

#11525 Release.yml - Updated and Validated
  .github/release.yml
Labels: Build System Improvement

#11538 Fix OSD visual beeper
  src/main/io/beeper.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_warnings.c
Labels: RN: BUGFIX

#11537 Add Winbond 25Q128 flash driver
  src/main/target/IFLIGHT_H743_AIO/target.h
  src/main/target/IFLIGHT_H743_AIO_V2/target.h
  src/main/target/STM32_UNIFIED/target.h
Labels: RN: BUGFIX

#11541 Improve failsafe handling for Rx's that send bad channel information.
  src/main/rx/rx.c
  src/test/unit/rx_ranges_unittest.cc
Labels: RN: BUGFIX

#11500 Fix CRSF baud negotiation
  src/main/config/config.c
  src/main/config/config.h
  src/main/fc/tasks.c
  src/main/rx/crsf.c
  src/main/rx/crsf_protocol.h
  src/main/telemetry/crsf.c
  src/main/telemetry/crsf.h
Labels: RN: BUGFIX

#11536 Frsky range check issues
  src/main/drivers/rx/rx_cc2500.c
  src/main/fc/core.c
  src/main/fc/core.h
  src/main/rx/cc2500_frsky_shared.c
  src/main/scheduler/scheduler.c
  src/test/unit/scheduler_unittest.cc
Labels: RN: BUGFIX

#11188 Update and clean up GitHub workflows
  .github/no-response.yml
  .github/workflows/no-response.yml
  .github/workflows/stale.yaml
Labels: Housekeeping

#11545 Add more gyros for NeutronRCF411SX1280 target
  src/main/target/NEUTRONRCF411SX1280/target.h
Labels: RN: TARGET UPDATE

#11546 Updating documentation with minor spelling, grammar, and formatting corrections
  docs/Modes.md
Labels: RN: DOCUMENTATION, Tested

#11476 updated reference website link
  src/main/flight/imu.c
Labels: RN: DOCUMENTATION, Tested

#11490 Added doc comment requirement to styleguide
  docs/development/CodingStyle.md
Labels: RN: DOCUMENTATION

#11540 add EmaxModel STM32F411 SX1280 target
  src/main/target/EMAXF4SX1280/target.c
  src/main/target/EMAXF4SX1280/target.h
  src/main/target/EMAXF4SX1280/target.mk
Labels: RN: NEW TARGET

#11550 W25X32 FLASH support
  src/main/drivers/flash_m25p16.c
Labels: RN: BUGFIX, Tested

#11561 Reorder SPI_MOSI 1 and SPI_MISO 1 stream options
  src/main/drivers/dma_reqmap.c
Labels: RN: BUGFIX

#11559 Update a misleading TPA chart
  docs/PID tuning.md
Labels: Tested, RN: IGNORE
