Repository betaflight/betaflight, pull requests merged in 2022-02, with the labels that each got.

#11361 Update for Battery Efficiency Fix Issue #11277
  src/main/osd/osd_elements.c
  src/test/Makefile
Labels: RN: BUGFIX

#11429 Fix non DSHOT protocols
  src/main/flight/mixer_init.c
  src/main/msp/msp.c
Labels: Tested, Bugfix

#11320 removed outdated Dshot1200 and F3 processors from feature list in readme
  README.md
Labels: Documentation update

#11420 Fix USE_DSHOT_TELEMETRY & USE_DSHOT_BITBANG define compilation issues
  src/main/drivers/pwm_output_dshot_hal.c
  src/main/drivers/timer_common.c
Labels: RN: BUGFIX

#11403 Updated LED_STRIP docs with undocumented CLI commands
  docs/LedStrip.md
Labels: Documentation update
