Repository betaflight/betaflight, pull requests merged in 2022-05, with the labels that each got.

#11552 Fix DEBUG_SCHEDULER_DETERMINISM description
  src/main/scheduler/scheduler.c
Labels: RN: DOCUMENTATION

#11568 BMI270 driver was reading 1 byte too many
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_spi_bmi270.c
Labels: RN: BUGFIX

#11566 Adding standard SIGN function
  src/main/common/maths.h
Labels: RN: IMPROVEMENT, Tested

#11584 Fix ICM-20689 initialisation
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_spi_icm20689.c
  src/main/drivers/accgyro/accgyro_spi_icm20689.h
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
  src/main/drivers/accgyro/accgyro_spi_mpu6500.c
Labels: RN: BUGFIX, Tested

#11588 Change ACC Trim step to 1 (for stick commands)
  src/main/fc/rc_controls.c
Labels: RN: BUGFIX, Tested

#11609 Revert BMI270 read length change, but keep typo fix
  src/main/drivers/accgyro/accgyro_spi_bmi270.c
Labels: RN: BUGFIX

#11604 Fix SPI4 DMA assignment
  src/main/drivers/dma_reqmap.c
Labels: RN: BUGFIX

#11549 Add gyro lock/dma support to BMI160
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
Labels: RN: BUGFIX, Tested

#11573 ELRS SPI Fix eeprom write and reboot for msp over telemetry
  src/main/msp/msp.c
  src/main/rx/expresslrs_telemetry.c
  src/main/rx/rx_spi.c
  src/main/telemetry/msp_shared.c
  src/main/telemetry/msp_shared.h
Labels: RN: BUGFIX

#11597 Add CRCs to EEPROM PG records to enable check for dirty config
  src/main/common/crc.c
  src/main/common/crc.h
  src/main/config/config_eeprom.c
  src/main/pg/pg.c
  src/main/pg/pg.h
  src/test/Makefile
Labels: RN: BUGFIX

#11556 Removing travis files now that we have not utilised travis for some time
  .travis.sh
  .travis.yml
  JLinkSettings.ini
  fake_travis_build.sh
Labels: RN: IGNORE

#11613 Simplify SPI CLK speed setting during gyro detection
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu6050.c
  src/main/drivers/accgyro/accgyro_mpu6500.c
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
  src/main/drivers/accgyro/accgyro_spi_bmi270.c
  src/main/drivers/accgyro/accgyro_spi_icm20649.c
  src/main/drivers/accgyro/accgyro_spi_icm20689.c
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
  src/main/drivers/accgyro/accgyro_spi_lsm6dso_init.c
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
  src/main/drivers/accgyro/accgyro_spi_mpu6500.c
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
Labels: RN: BUGFIX

#11621 Changes in "crash flip" OSD warning
  src/main/fc/core.c
  src/main/osd/osd.c
  src/main/osd/osd_warnings.c
  src/main/osd/osd_warnings.h
Labels: RN: SAFETY IMPROVEMENT
