Repository betaflight/betaflight, pull requests merged in 2022-11, with the labels that each got.

#11920 Adding board scratch space.
  .gitignore
  Makefile
  make/source.mk
  src/link/stm32_flash_f4_split.ld
  src/link/stm32_flash_f7_split.ld
  src/link/stm32_flash_g4_split.ld
  src/main/build/version.h
  src/main/cli/cli.c
  src/main/platform.h
Labels: Ready to Merge, RN: REFACTORING

#11912 Parse GPS DOP values
  src/main/build/debug.h
  src/main/flight/position.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/msp/msp.c
  src/main/osd/osd_elements.c
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/smartport.c
  src/main/telemetry/srxl.c
Labels: Testing Required, Ready to Merge, RN: IMPROVEMENT

#11951 fix for CRSF not being present.
  src/main/io/vtx_msp.c
  src/main/target/common_pre.h
Labels: Ready to Merge, Bugfix, Cloud Build

#11947 Adding SDCARD as a cloud build option
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F411SX1280/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H743/target.h
Labels: Build System Improvement, Cloud Build

#11950 Allow serial port to share all MSP functions at once
  src/main/config/config.c
  src/main/io/serial.c
  src/main/io/serial.h
Labels: RN: BUGFIX

#11942 Added hint about dialout group to usb flashing docs
  docs/USB Flashing.md
Labels: Rebase / Squash required, RN: DOCUMENTATION

#11956 Fix debug GPS_DOP
  src/main/build/debug.c
Labels: Ready to Merge, RN: BUGFIX

#11959 Update Hardware Specification
  docs/Manufacturer Design Guidelines.md
  docs/TargetMaintenance/CreatingAUnifiedTarget.md
Labels: RN: DOCUMENTATION

#11960 FIX: for VTX and lack of telemetry
  src/main/io/vtx_msp.c
Labels: Bugfix, Cloud Build

#11961 FIX: for USE_TELEMETRY_FRSKY_HUB not being defined.
  src/main/rx/cc2500_frsky_d.c
Labels: Bugfix, Cloud Build

#11963 FIX: Using OSD config when USE_OSD not defined.
  src/main/cms/cms.c
Labels: BUG, Bugfix, Cloud Build

#11968 Update hardware specification
  docs/Manufacturer Design Guidelines.md
  docs/TargetMaintenance/CreatingAUnifiedTarget.md
Labels: Ready to Merge, Housekeeping

#11966 Removing SX1280 specific target
  src/main/target/STM32F411/target.mk
  src/main/target/STM32F411SX1280/target.c
  src/main/target/STM32F411SX1280/target.h
  src/main/target/STM32F411SX1280/target.mk
  src/main/target/common_post.h
Labels: Ready to Merge, Cleanup, Cloud Build

#11971 Fix F411 target
  src/main/target/STM32F411/target.h
Labels: Bugfix, Cloud Build

#11969 Fix TPA
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/msp/msp.c
Labels: Ready to Merge, Tested, Bugfix

#11973 Enable Instruction and Data cache and prefetch on G4
  src/link/stm32_flash_g474.ld
  src/main/drivers/dshot_bitbang.c
  src/main/startup/system_stm32g4xx.c
  src/main/target/common_pre.h
Labels: Ready to Merge, RN: BUGFIX, Build System Improvement

#11062 Added RSNR to the OSD
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/osd/osd_warnings.c
  src/main/pg/rx.c
  src/main/pg/rx.h
  src/main/rx/crsf.c
  src/main/rx/expresslrs.c
  src/main/rx/expresslrs_impl.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/target/common_pre.h
  src/test/unit/link_quality_unittest.cc
  src/test/unit/rx_ranges_unittest.cc
  src/test/unit/rx_rx_unittest.cc
Labels: Ready to Merge, RN: BUGFIX

#11975 Fix ATTITUDE task rate
  src/main/fc/core.c
Labels: Ready to Merge, RN: BUGFIX

#11972 Dedicated task for GPS Rescue
  src/main/fc/tasks.c
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/io/gps.c
  src/main/scheduler/scheduler.h
Labels: Ready to Merge, RN: BUGFIX, RN: IMPROVEMENT

#11938 Update workflow
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: Ready to Merge, Housekeeping

#11983 Removing deprecated define error checking
  src/main/platform.h
  src/main/target/common_deprecated_post.h
  src/main/target/common_pre.h
Labels: Ready to Merge, Cleanup, RN: IGNORE, Cloud Build

#11988 Fix RPM Filter copy instructions
  src/main/flight/rpm_filter.c
Labels: Testing Required, RN: BUGFIX

#11980 Fix compatibility for name field
  src/main/msp/msp.c
  src/main/msp/msp_protocol.h
Labels: Ready to Merge, RN: BUGFIX, Tested

#11993 Cleanup of defines for motor protocols
  src/main/target/common_pre.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#11992 Naming adjustment for USE_SERIAL_RX to USE_SERIALRX
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/config/config.c
  src/main/io/spektrum_rssi.c
  src/main/pg/rx.c
  src/main/rx/rx.c
  src/main/target/SITL/target.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
  src/test/unit/target.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#11982 Fix getRssiDbm compiler error
  src/main/osd/osd_elements.c
Labels: RN: IGNORE, Cloud Build

#11994 Revert RPM Filter copy instructions to old method
  src/main/flight/rpm_filter.c
Labels: RN: BUGFIX

#11964 Add HD OSD support
  docs/API/DisplayPort.md
  src/main/cli/settings.c
  src/main/cms/cms.c
  src/main/drivers/display.c
  src/main/drivers/display.h
  src/main/drivers/osd.h
  src/main/io/displayport_msp.c
  src/main/io/displayport_msp.h
  src/main/msp/msp.c
  src/main/msp/msp_protocol.h
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/test/unit/rx_spi_expresslrs_telemetry_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: MAJOR FEATURE

#11997 Update hardware spec documentation
  docs/Cloud build API.md
  docs/Manufacturer Design Guidelines.md
  docs/TargetMaintenance/CreatingAUnifiedTarget.md
Labels: RN: DOCUMENTATION

#11995 Fix minor typo in DisplayPort.md
  docs/API/DisplayPort.md
Labels: RN: DOCUMENTATION

#12000 Add missing gyro check
  src/main/sensors/gyro_init.c
Labels: RN: BUGFIX

#12001 Fix msp API_VERSION_MINOR
  src/main/msp/msp_protocol.h
  src/test/unit/rx_spi_expresslrs_telemetry_unittest.cc
Labels: RN: BUGFIX

#12002 Update hardware spec
  docs/Manufacturer Design Guidelines.md
Labels: RN: IGNORE

#12004 FIX: USE_PWM not working
  Makefile
  src/main/cli/cli.c
  src/main/drivers/motor.c
  src/main/msp/msp.c
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#12005 FIX: USE_FLASH_W25Q128FV not working
  src/main/target/common_post.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#12006 FIX: USE_VTX not active
  src/main/rx/cc2500_redpine.c
Labels: Cleanup, RN: IGNORE, Cloud Build

#12010 FIX: USE_ACCGYRO_BMI270 not enabling SPI
  src/main/target/common_post.h
Labels: Cleanup, Tested, RN: IGNORE, Cloud Build

#12011 Fix read of DPS310 coef C11
  src/main/drivers/barometer/barometer_dps310.c
Labels: RN: BUGFIX

#12014 Fix CC2500 driver gating on USE_RX_SPI.
  docs/Manufacturer Design Guidelines.md
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H723/target.h
  src/main/target/STM32H743/target.h
  src/main/target/common_post.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#12013 Flash - Fix incorrect gating on cli flash commands.
  src/main/cli/cli.c
Labels: Cleanup, RN: IGNORE, Cloud Build

#12016 Fix BLHeli32 Serial Passthrough
  src/main/target/common_post.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#12017 Update Development.md
  docs/development/Development.md
Labels: RN: DOCUMENTATION

#12018 CLEANUP: target.mk is now mandatory
  make/targets.mk
Labels: Cleanup, RN: IGNORE

#12007 FIX: for if CRSF Telemetry not selected, yet CRSF serial is
  src/main/rx/crsf.c
  src/main/rx/ghst.c
  src/main/target/common_post.h
Labels: Cleanup, Don't Merge, RN: IGNORE, Cloud Build

#12015 FLASH - Fix missing USE_FLASH_CHIP default when using W25M and W25Q drivers.
  src/main/target/common_post.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#12021 FIX: doBind param not used under certain gate conditions
  src/main/rx/rx_bind.c
Labels: Cleanup, RN: IGNORE, Cloud Build

#12023 FIX: when USE_RX_SX1280 not in use, yet EXPRESSLRS is.
  src/main/rx/expresslrs.c
Labels: Cleanup, RN: IGNORE, Cloud Build

#12024 FIX: flash chip already defined errors.
  src/main/target/common_post.h
Labels: Ready to Merge, Cleanup, RN: IGNORE, Cloud Build

#12027 Added Winbond W25q80 flash support
  src/main/drivers/flash_m25p16.c
Labels: Library Patch
