Repository betaflight/betaflight, pull requests merged in 2022-12, with the labels that each got.

#12026 Cleanup targets
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H723/target.h
  src/main/target/STM32H743/target.h
  src/main/target/common_pre.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#11957 STM32H750 as a standard target
  src/main/target/STM32H750/target.c
  src/main/target/STM32H750/target.h
  src/main/target/STM32H750/target.mk
Labels: RN: NEW TARGET

#12030 FIX: PINIO is now an option in configurator for cloud build.
  src/main/target/common_pre.h
Labels: Ready to Merge, Cleanup, RN: IGNORE, Cloud Build

#12020 MSP messages to get and set PID and rate profile names.
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
Labels: Ready to Merge, RN: MINOR FEATURE

#11962 Show PID and rate profile names in OSD menu.
  src/main/cms/cms_menu_imu.c
Labels: Future Enhancement, Ready to Merge, RN: MINOR FEATURE

#12039 FIX: USE_FLASH_W25M not executing flash detection
  src/main/drivers/flash.c
Labels: Bugfix, RN: IGNORE, Cloud Build

#12038 Fix OSD_X macro to correctly load the high bit
  src/main/osd/osd.h
  src/test/unit/osd_unittest.cc
Labels: Ready to Merge, RN: BUGFIX

#11999 Add HD OSD system elements for VTX temp and goggle fan speed
  docs/API/DisplayPort.md
  src/main/cli/settings.c
  src/main/drivers/display.h
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#12040 Link to flash types supported by M25P16 driver
  docs/Manufacturer Design Guidelines.md
Labels: Housekeeping, RN: IGNORE, Cloud Build

#12022 Fix/enhance NMEA & Ublox message polling for GPS
  src/main/cli/settings.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/pg/gps.c
  src/main/pg/gps.h
Labels: Ready to Merge, RN: BUGFIX, Tested, RN: REFACTORING

#12044 Update Manufacturer Design Guidelines.md
  docs/Manufacturer Design Guidelines.md
Labels: RN: DOCUMENTATION

#12042 Gps Rescue: Fix "velocityD" filtering
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/pg/gps_rescue.c
  src/main/pg/gps_rescue.h
  src/test/Makefile
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/osd_unittest.cc
  src/test/unit/vtx_unittest.cc
Labels: RN: BUGFIX

#12051 Display FLASH JEDEC ID in status and flash_info
  src/main/cli/cli.c
  src/main/drivers/flash.c
  src/main/drivers/flash.h
Labels: RN: IMPROVEMENT

#12050 Use USE_DMA_SPEC without preconditions
  src/main/target/common_post.h
Labels: Cleanup, RN: BUGFIX, Cloud Build

#12055 Fix ELRS gating issues.
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: Cleanup, RN: BUGFIX, Cloud Build

#12056 Center logo and CMS display for HD OSD
  src/main/cms/cms.c
  src/main/io/displayport_msp.c
  src/main/osd/osd.c
Labels: RN: BUGFIX

#12057 Ensure CS is negated at end of ELRS SPI transfers
  src/main/drivers/rx/rx_sx1280.c
Labels: Testing Required, RN: BUGFIX

#12060 DOCS: Update Development documentation to include fully working example (BETAFLIGHTF7)
  docs/development/Development.md
Labels: RN: DOCUMENTATION, Cloud Build

#12062 Update firmware bug report
  .github/ISSUE_TEMPLATE/firmware-bug-report.yml
Labels: Housekeeping

#12063 Extend error output
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#12066 Fix nightly build badge
  README.md
Labels: Bugfix, Housekeeping

#12059 Small fix for msp vtx over crsf framing
  src/main/io/vtx_msp.c
Labels: RN: BUGFIX

#12075 Add Discord chat badge
  README.md
Labels: Housekeeping

#12069 FIX: Include the legacy drivers (gated)
  src/main/target/STM32F411/target.mk
Labels: RN: TARGET UPDATE, RN: IGNORE, Cloud Build

#12077 Organize > 512K options
  docs/Cloud build API.md
  src/main/target/common_pre.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#12078 Update LedStrip.md
  docs/LedStrip.md
Labels: RN: DOCUMENTATION

#12083 FIX: USE_RX_CC2500 was not gating correctly
  src/main/target/common_post.h
Labels: RN: BUGFIX, Bugfix, Cloud Build

#12064 Cloud build option for 64 leds
  src/main/drivers/light_ws2811strip.h
  src/main/io/ledstrip.h
  src/main/target/common_pre.h
  src/test/unit/platform.h
Labels: RN: REFACTORING

#12085 FIX: Assist in debugging by including the build key
  src/main/cli/cli.c
Labels: RN: IGNORE, Cloud Build

#12086 Center ARMED message and stats
  src/main/osd/osd.c
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: RN: BUGFIX

#12092 Add MSP displayport HD OSD flow diagrams
  docs/API/DisplayPort.md
Labels: RN: DOCUMENTATION

#12096 Fix status output
  src/main/cli/cli.c
Labels: Cleanup, RN: IGNORE

#12089 Bake in the board information at build time
  src/main/build/version.h
  src/main/fc/board_info.c
Labels: RN: IGNORE, Cloud Build

#11173 Add support for Omron 2SMBP-02B barometer
  make/source.mk
  src/main/cli/settings.c
  src/main/drivers/barometer/barometer_2smpb_02b.c
  src/main/drivers/barometer/barometer_2smpb_02b.h
  src/main/sensors/barometer.c
  src/main/sensors/barometer.h
  src/main/target/common_post.h
Labels: RN: IMPROVEMENT

#12106 FIX: MSP Displayport now has dependency on OSD config
  src/main/io/displayport_msp.c
  src/main/target/common_pre.h
Labels: RN: BUGFIX, Bugfix, Cloud Build

#12091 Fix STM32H750 target support
  src/main/drivers/flash.c
  src/main/target/STM32H750/target.h
  src/main/target/common_pre.h
  support/scripts/build_spracingh7extreme.sh
Labels: RN: TARGET UPDATE

#12105 FIX: Barometers tend to be on boards
  src/main/target/common_post.h
Labels: RN: IGNORE, Cloud Build

#12107 Change Slack by Discord for translators in README
  README.md
Labels: Housekeeping

#12108 Display OSD canvas size in status command
  src/main/cli/cli.c
Labels: RN: IMPROVEMENT

#12090 Update CreatingAUnifiedTarget.md
  docs/TargetMaintenance/CreatingAUnifiedTarget.md
Labels: Housekeeping

#12116 FIX: EXTRA_FLAGS not forcing a rebuild when changed.
  Makefile
Labels: RN: IGNORE
