Repository betaflight/betaflight, pull requests merged in 2023-08, with the labels that each got.

#12983 Rename flight mode
  src/main/telemetry/crsf.c
Labels: RN: BUGFIX

#13000 Fix MSP_DISPLAYPORT_UART assignment
  src/main/io/serial.c
  src/main/io/serial.h
Labels: RN: BUGFIX

#13005 Use coloured fonts if supported
  src/main/osd/osd_elements.c
  src/main/osd/osd_warnings.c
  src/main/pg/displayport_profiles.c
Labels: RN: IMPROVEMENT

#12978 Added throttle flight statistics
  mk/source.mk
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/fc/core.c
  src/main/fc/tasks.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/rx/rc_stats.c
  src/main/rx/rc_stats.h
  src/main/scheduler/scheduler.h
Labels: RN: MINOR FEATURE

#13007 Remove sdcard include header from usb_io
  src/main/drivers/usb_io.c
Labels: Ready to Merge, Cleanup

#12992 Fix escserial for HAL targets.
  src/main/drivers/at32/timer_at32bsp.c
  src/main/drivers/serial_escserial.c
  src/main/drivers/stm32/timer_hal.c
  src/main/drivers/stm32/timer_stdperiph.c
  src/main/drivers/timer.h
  src/main/fc/init.c
  src/main/target/SITL/sitl.c
  src/main/target/STM32F7X2/target.h
Labels: RN: BUGFIX

#13018 Enable/disable the UART TX before changing the TX pin mode
  src/main/drivers/serial_uart_hal.c
Labels: RN: BUGFIX

#12987 Rename default configuration macro's for vbat divider and multiplier
  src/main/sensors/voltage.c
Labels: Ready to Merge, Cleanup

#12956 Revert 12512
  src/main/config/feature.h
  src/main/target/common_post.h
Labels: Ready to Merge, Cleanup

#12918 Fix: disable sag compensation if RPM limit is active
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/mixer_init.c
  src/main/sensors/voltage.c
Labels: Ready to Merge, RN: BUGFIX

#13017 Enable/disable the UART TX before changing the TX pin mode
  src/main/drivers/stm32/serial_uart_hal.c
Labels: Ready to Merge, RN: BUGFIX

#13019 UART enable disable f4
  src/main/drivers/at32/serial_uart_at32bsp.c
  src/main/drivers/stm32/serial_uart_stm32f4xx.c
Labels: RN: BUGFIX

#13020 4.4 maintenance uart enable/disable f4
  src/main/drivers/serial_uart_stm32f4xx.c
Labels: RN: BUGFIX

#12799 M10 ValSet support, unit connection and reconnect stability
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/drivers/serial_uart_impl.h
  src/main/fc/parameter_names.h
  src/main/fc/tasks.c
  src/main/io/dashboard.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/osd/osd_elements.c
  src/main/pg/gps.c
  src/main/pg/gps.h
  src/test/Makefile
  src/test/unit/cli_unittest.cc
  src/test/unit/target.h
Labels: Ready to Merge, RN: IMPROVEMENT

#13022 Allow for F7 UART idle preamble to be sent on startup - 4.4-maintenance
  src/main/drivers/serial_uart_stm32f7xx.c
Labels: RN: BUGFIX

#13021 Allow for F7 UART idle preamble to be sent on startup
  src/main/drivers/stm32/serial_uart_stm32f7xx.c
Labels: RN: BUGFIX

#13030 Fix MAX7456 clock configuration
  src/main/pg/max7456.c
Labels: Ready to Merge, RN: BUGFIX

#13027 Fix AT32 UART 7 and 8
  src/main/drivers/at32/serial_uart_at32f43x.c
Labels: Ready to Merge, RN: BUGFIX

#12997 Document where dshot documentation is found
  src/main/drivers/dshot.c
Labels: Informational

#12803 Fix debug_gps_altitude values
  src/main/flight/gps_rescue.c
  src/main/flight/position.c
Labels: RN: BUGFIX, Needs coordination with blackbox-log-viewer

#13032 Fix OSD VTX band/channel info when direct frequency is used
  src/main/osd/osd_elements.c
Labels: Ready to Merge, RN: BUGFIX

#13038 Add support for 'make CONFIG_clean' as per 'make TARGET_clean'
  Makefile
Labels: Ready to Merge

#13004 Added dynamic expo factors to blackbox header
  src/main/blackbox/blackbox.c
Labels: Ready to Merge, RN: IMPROVEMENT, Needs coordination with blackbox-log-viewer

#13048 Fix missing ACC MPU6050
  src/main/sensors/acceleration_init.c
Labels: Ready to Merge, RN: IGNORE

#13047 Fix GPS Rescue parameters confusion
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_gps_rescue.c
  src/main/fc/parameter_names.h
  src/main/flight/gps_rescue.c
  src/main/msp/msp.c
  src/main/msp/msp_protocol.h
  src/main/pg/gps_rescue.c
  src/main/pg/gps_rescue.h
Labels: Ready to Merge, Needs coordination with betaflight-configurator, RN: BUGFIX

#13055 Make use of all 8 debug values for the GPS Rescue debugs
  src/main/flight/gps_rescue.c
Labels: Ready to Merge, Needs coordination with blackbox-log-viewer
