Repository betaflight/betaflight, pull requests merged in 2023-06, with the labels that each got.

#12852 Remove target create / update workflow
  .github/workflows/target-creation.yml
Labels: RN: IGNORE

#12861 [4.4.3] Update version.h
  src/main/build/version.h
Labels: Housekeeping

#12862 Removing Timer Usage Flags
  src/main/drivers/at32/timer_at32f43x.c
  src/main/drivers/at32/timer_def.h
  src/main/drivers/stm32/dshot_bitbang.c
  src/main/drivers/stm32/timer_def.h
  src/main/drivers/stm32/timer_hal.c
  src/main/drivers/stm32/timer_stm32f4xx.c
  src/main/drivers/stm32/timer_stm32f7xx.c
  src/main/drivers/stm32/timer_stm32g4xx.c
  src/main/drivers/stm32/timer_stm32h7xx.c
  src/main/drivers/timer.h
  src/main/drivers/timer_common.c
  src/test/unit/timer_definition_unittest.include/mock_enums.h
Labels: RN: REFACTORING, Housekeeping

#12873 Fix USE_TELEMETRY_IBUS
  src/main/target/common_post.h
Labels: RN: BUGFIX

#12877 RPM Limiter Patch
  src/main/flight/mixer.c
Labels: Bugfix

#12857 Fix wrong test for BOXMSPOVERRIDE channel
  src/main/config/config.c
Labels: RN: BUGFIX

#12876 Enable retrieval of the BUILD_KEY using MSP2 (#12264)
  src/main/build/version.c
  src/main/build/version.h
  src/main/cli/cli.c
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
  src/test/unit/cli_unittest.cc
Labels: Added by Cherry-pick

#12878 Enables retrieval of the RELEASE_NAME using MSP2
  src/main/build/version.c
  src/main/build/version.h
  src/main/cli/cli.c
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
  src/test/unit/cli_unittest.cc
Labels: Ready to Merge, RN: IMPROVEMENT

#12865 Call updateInit() before writing motor command data
  src/main/drivers/dshot_command.c
  src/main/drivers/motor.c
  src/main/drivers/motor.h
Labels: RN: BUGFIX

#12882 Fix MAG redefines
  src/main/target/common_post.h
Labels: RN: BUGFIX, Cloud Build

#12678 [CONFIG] Add NUCLEOF446 Development Board
  Makefile
  src/main/target/STM32F446/target.h
  src/main/target/STM32F446/target.mk
Labels: Testing Required, RN: NEW TARGET

#11821 G4 LPUART rework
  src/main/cli/cli.c
  src/main/drivers/resource.c
  src/main/drivers/resource.h
  src/main/drivers/serial.h
  src/main/drivers/serial_pinconfig.c
  src/main/drivers/serial_softserial.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/stm32/serial_uart_stm32g4xx.c
  src/main/io/serial.c
  src/main/io/serial.h
  src/main/pg/pg_ids.h
  src/main/pg/serial_uart.c
  src/main/pg/serial_uart.h
Labels: RN: BUGFIX, Tested

#12890 fix led strip for h7
  src/main/drivers/light_ws2811strip.c
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#12892 Fix g force calculation
  src/main/osd/osd.c
Labels: RN: BUGFIX

#12893 Fix rcSmoothing warning
  src/main/fc/core.c
Labels: RN: BUGFIX

#11786 Separate resources for SOFTSERIAL_TX & SOFTSERIAL_RX
  src/main/cli/cli.c
  src/main/config/config.c
  src/main/drivers/serial.h
  src/main/drivers/serial_pinconfig.c
  src/main/drivers/serial_softserial.c
  src/main/drivers/serial_uart.h
  src/main/io/serial.c
  src/main/msp/msp.c
  src/main/target/SITL/target.h
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H723/target.h
  src/main/target/STM32H743/target.h
  src/main/target/STM32H750/target.h
Labels: RN: IMPROVEMENT

#12898 Fix rcSmoothing warning OSD
  src/main/osd/osd_warnings.c
Labels: RN: BUGFIX

#12859 Refactor imuCalcKpGain
  src/main/flight/imu.c
Labels: RN: IMPROVEMENT

#12823 Add (e)RPM field to blackbox logs
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox_fielddefs.h
  src/main/cli/settings.c
Labels: RN: MINOR FEATURE

#12866 Call updateInit() before writing motor command data
  src/main/drivers/dshot_command.c
  src/main/drivers/motor.c
  src/main/drivers/motor.h
Labels: RN: BUGFIX, Added by Cherry-pick

#12577 Implement DShot bit bang for AT32
  Makefile
  src/main/drivers/at32/dshot_bitbang.c
  src/main/drivers/at32/dshot_bitbang_stdperiph.c
  src/main/drivers/at32/platform_mcu.h
  src/main/drivers/at32/serial_uart_at32bsp.c
  src/main/drivers/at32/timer_at32bsp.c
  src/main/drivers/dshot_bitbang_decode.c
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/stm32/serial_uart_hal.c
  src/main/drivers/stm32/serial_uart_stm32f4xx.c
  src/main/drivers/timer.h
  src/main/target/AT32F435G/target.h
  src/main/target/AT32F435G/target.mk
  src/main/target/AT32F435M/target.h
  src/main/target/AT32F435M/target.mk
Labels: RN: TARGET UPDATE

#12903 [AT32] Change evaluation order
  src/main/target/AT32F435G/target.h
  src/main/target/AT32F435M/target.h
Labels: RN: TARGET UPDATE

#12911 Fix Serial USB COM port
  src/main/io/serial.c
Labels: RN: BUGFIX

#12930 Improve CI target visibility
  Makefile
Labels: Housekeeping
