Repository betaflight/betaflight, pull requests merged in 2023-04, with the labels that each got.

#12590 Exclude MSP_OSD_CONFIG if USE_OSD not defined (#12513)
  src/main/msp/msp.c
Labels: RN: BUGFIX

#12616 Add separate AAF values for ICM-42605
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
Labels: RN: BUGFIX

#12609 Add missing LUXF4OSD flash define
  src/config/LUXF4OSD/config.h
Labels: RN: TARGET UPDATE

#12602 CONFIG: Add BMI270 to SPEEDYBEEF7MINI
  src/config/SPEEDYBEEF7MINI/config.h
Labels: RN: TARGET UPDATE

#12596 Fix H7EXTREME
  src/config/SPRACINGH7EXTREME/config.h
Labels: RN: BUGFIX

#12593 CONFIG: Add SUB250F411
  src/config/SUB250F411/config.h
Labels: RN: NEW TARGET

#12561 Fix F411 PA10 Motor DMA Assignment
  src/config/EMAX_BABYHAWK_II_HD/config.h
  src/config/FLYWOOF411/config.h
  src/config/FLYWOOF411EVO_HD/config.h
  src/config/JHEF411/config.h
Labels: RN: TARGET UPDATE

#12610 More efficient PTn gain calculation
  src/main/common/filter.c
Labels: RN: REFACTORING

#12575 Add SPRO-SPRACINGH7NANO.config
  src/config/SPRACINGH7NANO/config.h
Labels: Ready to Merge, RN: NEW TARGET, Tested

#12554 Cleanup + led overlay expansion
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
  src/test/unit/ledstrip_unittest.cc
Labels: Testing Required, Cleanup, RN: IMPROVEMENT

#12608 add getCoreTemp
  src/main/msp/msp.c
  src/main/msp/msp_protocol.h
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#12626 Add more info for sensor in (get) MSP_SENSOR_CONFIG
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#12623 Implement Stopwatch
  make/source.mk
  src/main/common/stopwatch.c
  src/main/common/stopwatch.h
  src/main/drivers/system.c
  src/main/drivers/system.h
Labels: RN: IMPROVEMENT

#12587 Make UBLOX models more configurable
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/fc/parameter_names.h
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/pg/gps.c
  src/main/pg/gps.h
Labels: Testing Required, RN: IMPROVEMENT

#12619 update pid.c PG to 7
  src/main/flight/pid.c
Labels: Bugfix

#12639 CONFIG: Fix TMotor F7 BMP280 baro
  src/config/TMOTORF7/config.h
Labels: RN: TARGET UPDATE

#12612 If DSHOT telemetry is still being received, wait
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/drivers/dshot_bitbang_decode.c
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/stm32/dshot_bitbang.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#12652 CONFIG: Add W25Q128FV to OMNINXT4
  src/config/OMNINXT4/config.h
Labels: RN: TARGET UPDATE

#12630 CONFIG: Add BMP280 + W25Q128FV to AIRF7
  src/config/AIRF7/config.h
Labels: RN: TARGET UPDATE

#12649 CONFIG: Add BARO_SPI_BMP280 to FRSKYF4
  src/config/FRSKYF4/config.h
Labels: RN: TARGET UPDATE

#12650 CONFIG: Add BARO_BMP280 to FLYWOOF411
  src/config/FLYWOOF411/config.h
Labels: RN: TARGET UPDATE

#12651 CONFIG: Add W25Q128FV to REVOLTOSD
  src/config/REVOLTOSD/config.h
Labels: RN: TARGET UPDATE

#12627 CONFIG: Add ICM42688P to AIKONF7
  src/config/AIKONF7/config.h
Labels: RN: TARGET UPDATE

#12611 Fix Mercury G4 and fix TODO for PID_PROCESS_DENOM for all targets
  src/config/CLRACINGF4/config.h
  src/config/CLRACINGF7/config.h
  src/config/ELINF405/config.h
  src/config/ELINF722/config.h
  src/config/FLYCOLORF7/config.h
  src/config/HYBRIDG4/config.h
  src/config/IFLIGHT_F405_AIO/config.h
  src/config/IFLIGHT_F405_TWING/config.h
  src/config/IFLIGHT_SUCCEX_E_F4/config.h
  src/config/MAMBAG4/config.h
  src/config/MERCURYG4/config.h
  src/config/NBD_INFINITYF4/config.h
  src/config/NEUTRONRCG4AIO/config.h
  src/config/OMNIBUSF4NANOV7/config.h
  src/config/OMNIBUSF7NANOV7/config.h
  src/config/PYRODRONEF4/config.h
  src/config/PYRODRONEF4PDB/config.h
  src/config/PYRODRONEF7/config.h
  src/config/SIRMIXALOT/config.h
  src/config/SKYSTARSF7HDPRO/config.h
  src/config/SPEEDYBEEF7/config.h
  src/config/SUB250F411/config.h
  src/config/SYNERGYF4/config.h
  src/config/TALONF7DJIHD/config.h
  src/config/TALONF7FUSION/config.h
  src/config/TALONF7V2/config.h
  src/config/TMVELOXF7/config.h
  src/config/TRANSTECF411/config.h
  src/config/TRANSTECF411HD/config.h
  src/config/TRANSTECF7HD/config.h
  src/config/WIZZF7HD/config.h
  src/main/flight/pid.c
  src/main/target/STM32G47X/target.h
Labels: Ready to Merge, RN: TARGET UPDATE

#12633 Fix PG initialization of DMA defaults for TIMUP configuration
  src/main/pg/timerup.c
Labels: Ready to Merge, RN: BUGFIX, Bugfix

#12660 CONFIG: Add FLASH_W25Q128FV to SYNERGYF4
  src/config/SYNERGYF4/config.h
Labels: Ready to Merge, RN: TARGET UPDATE

#12632 Obtain HSE_VALUE from config.h where provided.
  Makefile
  src/main/platform.h
Labels: Ready to Merge, RN: IMPROVEMENT, Tested

#12669 Position: Remove 15 m/s limit on estimated vario
  src/main/flight/position.c
Labels: RN: BUGFIX

#12671 Fix SDC
  src/main/fc/init.c
Labels: RN: BUGFIX

#12670 Fix flash M25P16 ID with QUADSPI
  src/main/drivers/flash.c
Labels: RN: BUGFIX

#12659 UBLOX Full Power mode + default STATIONARY model
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
  src/main/io/gps.c
  src/main/pg/gps.c
  src/main/pg/gps.h
Labels: RN: IMPROVEMENT

#12672 Optimise DSHOT cache management loops
  src/main/drivers/stm32/dshot_bitbang.c
Labels: RN: IMPROVEMENT

#12675 fix bootloader jump for g4 mcu
  src/link/stm32_flash_g4_split.ld
  src/main/drivers/stm32/system_stm32g4xx.c
Labels: RN: BUGFIX

#12677 CONFIG: New Target FOXEERF745V4_AIO
  src/config/FOXEERF745V4_AIO/config.h
Labels: RN: NEW TARGET

#12695 Fix missing cfg_pms.version
  src/main/io/gps.c
Labels: RN: BUGFIX

#12679 Fix Softserial
  src/config/BETAFPVF411/config.h
  src/config/BETAFPVF4SX1280/config.h
  src/config/BLUEJAYF4/config.h
  src/config/DAKEFPVF411/config.h
  src/config/DARWINF411/config.h
  src/config/DARWINF4SX1280HD/config.h
  src/config/EACHINEF411_AIO/config.h
  src/config/ELINF405/config.h
  src/config/ELINF722/config.h
  src/config/FLYWOOF411HEX/config.h
  src/config/FLYWOOF411V2/config.h
  src/config/GEMEF411/config.h
  src/config/GEPRCF405/config.h
  src/config/GEPRCF411_AIO/config.h
  src/config/GEP_F405_VTX_V3/config.h
  src/config/HAKRCF411D/config.h
  src/config/IFLIGHT_F405_TWING/config.h
  src/config/IFLIGHT_F411_AIO32/config.h
  src/config/LDARC_F411/config.h
  src/config/MAMBAG4/config.h
  src/config/MATEKF411SE/config.h
  src/config/NEUTRONRCF411AIO/config.h
  src/config/SIRMIXALOT/config.h
  src/config/SKYSTARSF411/config.h
  src/config/SPEEDYBEEF7/config.h
  src/config/VGOODRCF4/config.h
  src/config/VRRACE/config.h
  src/config/YUPIF4/config.h
  src/config/YUPIF7/config.h
  src/config/ZEUSF4EVO/config.h
  src/main/config/config.c
Labels: Ready to Merge, RN: BUGFIX

#12697 [CONFIG] add ICM42688P to AXISFLYINGF7PRO
  src/config/AXISFLYINGF7PRO/config.h
Labels: RN: TARGET UPDATE

#12700 [CONFIG] Update VGOODRCF4
  src/config/VGOODRCF4/config.h
Labels: RN: TARGET UPDATE

#12690 CONFIG: AOCODAF722MINI Add missing motor 8 output
  src/config/AOCODAF722MINI/config.h
Labels: RN: TARGET UPDATE

#12702 [CONFIG] Fixes GYRO_2_ALIGN
  src/config/HGLRCF745/config.h
  src/config/VGOODRCF4/config.h
Labels: RN: BUGFIX

#12699 [CONFIG] Update NBD_INFINITYF4
  src/config/NBD_INFINITYF4/config.h
Labels: RN: TARGET UPDATE

#12681 Increment parameter group version of GPS config
  src/main/pg/gps.c
Labels: Ready to Merge, RN: BUGFIX

#12704 [CONFIG] ESCSERIAL for mambaf405us_i2c.
  src/config/MAMBAF405US_I2C/config.h
Labels: RN: TARGET UPDATE

#12701 Fix handling of attribute byte
  src/main/cms/cms.c
  src/main/cms/cms_menu_blackbox.c
  src/main/drivers/display.h
  src/main/io/displayport_hott.c
  src/main/io/displayport_msp.c
  src/main/io/displayport_msp.h
  src/main/io/displayport_srxl.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd_elements.c
  src/main/osd/osd_warnings.c
  src/main/pg/displayport_profiles.h
Labels: RN: BUGFIX

#12709 DSHOT timing improvements
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/config/config.c
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/dshot_bitbang_decode.c
  src/main/drivers/dshot_bitbang_impl.h
  src/main/drivers/dshot_command.c
  src/main/drivers/dshot_dpwm.c
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/motor.c
  src/main/drivers/motor.h
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/drivers/pwm_output_dshot_shared.h
  src/main/target/SITL/target.c
Labels: RN: IMPROVEMENT, Tested

#12705 [CONFIG] Add LPUART resources to MambaG4
  src/config/MAMBAG4/config.h
Labels: RN: TARGET UPDATE

#12605 Refactor Feedforward Angle and RC Smoothing - mashup of 12578 and 12594
  make/source.mk
  src/main/blackbox/blackbox.c
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/fc/parameter_names.h
  src/main/fc/rc.c
  src/main/fc/rc.h
  src/main/fc/rc_controls.h
  src/main/flight/feedforward.c
  src/main/flight/feedforward.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/main/flight/pid_init.h
  src/test/unit/cli_unittest.cc
  src/test/unit/pid_unittest.cc
Labels: RN: BUGFIX, Tested, Needs configurator change

#12519 [CONFIG] Add OMNIBUSF4NANO
  src/config/OMNIBUSF4NANO/config.h
Labels: RN: NEW TARGET

#12741 [CONFIG] Updates from master-config and more
  src/config/AXISFLYINGF7PRO/config.h
  src/config/GEPRCG4AIO/config.h
  src/config/HGLRCF745/config.h
  src/config/JHEF405/config.h
  src/config/MAMBAF405US_I2C/config.h
  src/config/MAMBAG4/config.h
  src/config/NBD_CRICKETF7/config.h
  src/config/NBD_CRICKETF7V2/config.h
  src/config/NBD_INFINITYF4/config.h
  src/config/NEUTRONRCF435/config.h
  src/config/OMNIBUSF4NANO/config.h
  src/config/SKYSTARSH7HD/config.h
  src/config/TMOTORH743/config.h
  src/config/VGOODF722DUAL/config.h
  src/config/VGOODRCF4/config.h
Labels: RN: TARGET UPDATE
