Repository betaflight/betaflight, pull requests merged in 2023-01, with the labels that each got.

#12124 Add RX_SPI to RX_CC2500
  docs/Manufacturer Design Guidelines.md
  docs/TargetMaintenance/CreatingAUnifiedTarget.md
  src/main/target/common_post.h
Labels: Cleanup, Build System Improvement, RN: IGNORE

#12125 FIX: CC2500 not building due to undefined pins.
  src/main/pg/rx_spi_cc2500.c
  src/main/target/common_defaults_post.h
Labels: RN: BUGFIX, Cloud Build

#12131 FIX: SPI_DPS310 not gated correctly
  src/main/drivers/barometer/barometer_dps310.c
  src/main/target/common_post.h
Labels: RN: BUGFIX, Bugfix, Cloud Build

#12132 Documentation for SPI/I2C bus
  docs/API/BusDrivers.md
Labels: RN: DOCUMENTATION

#12120 Disarm on fail-safe when `allow arming without fix` is enabled and failsafe procedure is set to GPS-RESCUE
  src/main/flight/gps_rescue.c
  src/main/rx/rx.c
Labels: RN: SAFETY IMPROVEMENT

#12144 Ensure OSD elements are on canvas
  src/main/osd/osd.c
Labels: RN: BUGFIX

#12152 Fix reset PG behaviour and configurator interactions based on USE_OSD_SD and USE_OSD_HD definitions
  src/main/drivers/display.h
  src/main/drivers/max7456.h
  src/main/io/displayport_msp.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#12139 Feature cutback making headroom for local development
  docs/Cloud build API.md
  src/main/target/common_pre.h
Labels: Cleanup, Target Change

#12157 Update artifact-links.yml
  .github/workflows/artifact-links.yml
Labels: Housekeeping

#12103 Flash M25P16: Add QSPI support
  src/main/drivers/flash.c
  src/main/drivers/flash_m25p16.c
Labels: RN: IMPROVEMENT

#12160 Move JETIEXBUS serial RX to targets > 512kb flash.
  src/main/target/common_pre.h
Labels: Cleanup, RN: IGNORE

#12162 Fix removing USE_LED_STRIP
  src/main/target/common_pre.h
Labels: Cleanup, RN: IGNORE

#12164 Add osd_canvas_width/height variables
  src/main/cli/settings.c
  src/main/io/displayport_crsf.c
  src/main/io/displayport_frsky_osd.c
  src/main/io/displayport_max7456.c
  src/main/io/displayport_msp.c
  src/main/msp/msp.c
  src/main/osd/osd.c
Labels: RN: IMPROVEMENT

#12161 Add gate for ICM20602
  src/main/target/common_post.h
Labels: Cleanup, RN: IGNORE, Cloud Build

#12165 Use Support ID in issue template
  .github/ISSUE_TEMPLATE/firmware-bug-report.yml
Labels: Housekeeping

#12166 Avoid debugging other data than RPM telemetry when decoding DSHOT RPM
  src/main/drivers/dshot.c
  src/main/drivers/dshot_bitbang.c
  src/main/drivers/pwm_output_dshot_shared.c
Labels: RN: BUGFIX, Tested

#11460 Improve performance for ELRS SX1280 SPI callbacks and SPI/ELRS handlers.
  src/main/common/filter.c
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi_ll.c
  src/main/drivers/rx/rx_sx1280.c
  src/main/flight/pid.c
  src/main/sensors/gyro.c
Labels: RN: BUGFIX

#12171 FIX: Hard fault on dump of settings if no OSD selected
  src/main/cli/settings.c
Labels: RN: BUGFIX, Tested, Bugfix

#12184 Automatically apply HD settings if HD VTX is detected
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#12178 Fixed getDshotAverageRpm function
  src/main/drivers/dshot.c
  src/main/drivers/dshot.h
Labels: Ready to Merge, RN: BUGFIX

#12199 Minor fixes for Dyn Notch & SDFT
  src/main/common/sdft.c
  src/main/flight/dyn_notch_filter.c
Labels: RN: BUGFIX

#12200 Missing define to activate TABLE_VIDEO_SYSTEM
  docs/Customized Version.md
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/config/config.c
  src/main/drivers/rx/rx_pwm.c
  src/main/fc/init.c
  src/main/pg/rx.c
  src/main/pg/rx_pwm.c
  src/main/rx/pwm.c
  src/main/rx/rx.c
  src/main/target/SITL/target.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: Cleanup, RN: IGNORE

#12201 Adding release name to the build key output (if provided).
  src/main/cli/cli.c
Labels: Ready to Merge, RN: IGNORE, Cloud Build

#12196 Adding comments to common PRE and POST
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: Cleanup, RN: IGNORE

#12195 GPS Rescue Bugfix, add a failsafe debug, refactor stick deflection
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/fc/core.c
  src/main/flight/failsafe.c
  src/main/flight/failsafe.h
  src/main/rx/rx.c
  src/test/unit/arming_prevention_unittest.cc
Labels: RN: BUGFIX

#12208 Include MSP over telemetry for ghost
  src/main/target/common_post.h
Labels: RN: BUGFIX

#12213 Fix DEBUG_ALTITUDE
  src/main/flight/position.c
Labels: RN: BUGFIX

#12217 Fix SITL
  src/main/target/SITL/target.h
Labels: RN: BUGFIX

#12218 Fix SDFT batch process
  src/main/common/sdft.c
Labels: RN: BUGFIX

#12220 fix SITL
  src/main/target/SITL/target.h
Labels: RN: BUGFIX

#12242 Increment EEPROM version for 4.4
  src/main/config/config_eeprom.h
Labels: Housekeeping, RN: IGNORE

#12234 Update version for next release
  src/main/build/version.h
Labels: Don't Merge, RN: IGNORE

#12244 Fix picture and update links
  README.md
  images/bf_logo.png
Labels: Ready to Merge, Housekeeping

#12221 Default blackbox device to NONE on reset
  src/main/blackbox/blackbox.c
  src/main/config/config.c
  src/main/config/config.h
  src/main/target/common_post.h
  src/test/unit/target.h
Labels: RN: IMPROVEMENT

#12179 Cleanup make
  Makefile
  make/mcu/SITL.mk
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  make/mcu/STM32G4.mk
  make/mcu/STM32H7.mk
  make/source.mk
  make/targets.mk
  src/main/target/SITL/target.mk
  src/main/target/STM32F405/target.mk
  src/main/target/STM32F411/target.mk
  src/main/target/STM32F745/target.mk
  src/main/target/STM32F7X2/target.mk
  src/main/target/STM32G47X/target.h
  src/main/target/STM32G47X/target.mk
  src/main/target/STM32H723/target.mk
  src/main/target/STM32H730/target.mk
  src/main/target/STM32H743/target.mk
  src/main/target/STM32H750/target.mk
Labels: Cleanup, RN: REFACTORING

#12175 Add Octo X8 + to mixer defaults
  src/main/flight/mixer.h
  src/main/flight/mixer_init.c
  src/main/telemetry/mavlink.c
Labels: RN: IMPROVEMENT

#12241 Add GYRO_CALIBRATION debug mode
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/sensors/gyro.c
Labels: RN: IMPROVEMENT

#12240 Fix gating for USE_ACC_SPI_MPU9250
  src/main/sensors/acceleration_init.c
  src/main/target/common_post.h
Labels: Cleanup, RN: BUGFIX

#12252 Don't bundle flash drivers and flash fs/tools together.
  src/main/target/common_post.h
Labels: Cleanup

#12247 AT32 development, introduction of AT32F435 target
  Makefile
  lib/main/AT32F43x/drivers/inc/at32f435_437_rcc_periph.h
  lib/main/AT32F43x/drivers/src/at32f435_437_crm.c
  lib/main/AT32F43x/drivers/src/at32f435_437_qspi.c
  lib/main/AT32F43x/drivers/src/at32f435_437_usb.c
  make/mcu/AT32F4.mk
  src/link/at32_flash_f43xM.ld
  src/link/at32_flash_f4_split.ld
  src/main/build/build_config.c
  src/main/build/build_config.h
  src/main/cli/cli.c
  src/main/config/config_streamer.c
  src/main/drivers/at32/bus_spi_at32bsp.c
  src/main/drivers/at32/dma_at32f43x.c
  src/main/drivers/at32/dma_atbsp.h
  src/main/drivers/at32/persistent_at32bsp.c
  src/main/drivers/at32/pwm_output_at32bsp.c
  src/main/drivers/at32/serial_uart_at32bsp.c
  src/main/drivers/at32/serial_uart_at32f43x.c
  src/main/drivers/at32/system_at32f43x.c
  src/main/drivers/at32/timer_at32bsp.c
  src/main/drivers/at32/timer_at32f43x.c
  src/main/drivers/at32/timer_def_at32.h
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_impl.h
  src/main/drivers/bus_spi_pinconfig.c
  src/main/drivers/dma.h
  src/main/drivers/dma_reqmap.c
  src/main/drivers/dma_reqmap.h
  src/main/drivers/exti.c
  src/main/drivers/io.c
  src/main/drivers/io.h
  src/main/drivers/nvic.h
  src/main/drivers/rcc.c
  src/main/drivers/rcc.h
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/system.c
  src/main/drivers/timer.c
  src/main/drivers/timer.h
  src/main/fc/init.c
  src/main/io/flashfs.c
  src/main/io/serial.c
  src/main/io/serial.h
  src/main/platform.h
  src/main/startup/at32/at32f435_437.h
  src/main/startup/at32/at32f435_437_clock.c
  src/main/startup/at32/at32f435_437_clock.h
  src/main/startup/at32/at32f435_437_conf.h
  src/main/startup/at32/startup_at32f435_437.s
  src/main/startup/at32/system_at32f435_437.c
  src/main/startup/at32/system_at32f435_437.h
  src/main/target/AT32F435/target.c
  src/main/target/AT32F435/target.h
  src/main/target/AT32F435/target.mk
  src/main/target/common_pre.h
Labels: RN: NEW TARGET

#12270 Fix Bug causing Dynamic Idle to fail if RPM filtering is turned off
  src/main/flight/rpm_filter.c
Labels: RN: BUGFIX

#12264 Enable retrieval of the BUILD_KEY using MSP2
  src/main/build/version.c
  src/main/build/version.h
  src/main/cli/cli.c
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
Labels: RN: IMPROVEMENT

#12259 Update ISSUE Template to require Support ID Only
  .github/ISSUE_TEMPLATE/firmware-bug-report.yml
Labels: Housekeeping
