Repository betaflight/betaflight, pull requests merged in 2023-05, with the labels that each got.

#12745 Detect if no motor GPIO is specified during DSHOT intialisation
  src/main/drivers/stm32/dshot_bitbang.c
Labels: RN: BUGFIX

#12760 Tri-state USART TX output if load due to powered down peripheral is detected
  src/main/drivers/at32/serial_uart_at32bsp.c
  src/main/drivers/at32/serial_uart_at32f43x.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/stm32/serial_uart_hal.c
  src/main/drivers/stm32/serial_uart_stdperiph.c
  src/main/drivers/stm32/serial_uart_stm32f4xx.c
  src/main/drivers/stm32/serial_uart_stm32f7xx.c
  src/main/drivers/stm32/serial_uart_stm32g4xx.c
  src/main/drivers/stm32/serial_uart_stm32h7xx.c
Labels: RN: BUGFIX

#12769 Add GPS Status Line to CLI Status Output
  src/main/cli/cli.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/test/unit/cli_unittest.cc
Labels: RN: IMPROVEMENT

#12604 If CS is asserted between transfers then consider bus to be busy for all but owning device
  src/main/drivers/at32/bus_spi_at32bsp.c
  src/main/drivers/bus.h
  src/main/drivers/bus_spi.c
  src/main/drivers/max7456.c
  src/main/drivers/stm32/bus_spi_ll.c
Labels: Ready to Merge, RN: BUGFIX

#12738 Converge IMU faster at higher groundspeed during GPS Rescue
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/flight/imu.c
  src/main/pg/gps_rescue.c
  src/test/unit/flight_imu_unittest.cc
Labels: RN: BUGFIX

#12725 Fix GNSS new data
  src/main/io/gps.c
Labels: RN: BUGFIX

#12787 [4.4.2] Fix GNSS new data
  src/main/io/gps.c
Labels: RN: BUGFIX

#12782 [4.4.2] Tri-state USART TX output if load due to powered down peripheral is d…
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart.h
  src/main/drivers/serial_uart_hal.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_uart_stdperiph.c
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/drivers/serial_uart_stm32g4xx.c
  src/main/drivers/serial_uart_stm32h7xx.c
Labels: RN: BUGFIX, Added by Cherry-pick

#12788 [4.4.2] Remove 15 m/s limit on estimated vario
  src/main/flight/position.c
Labels: RN: BUGFIX

#12783 [4.4.2] Fix bootloader jump for g4 mcu (#12675)
  src/link/stm32_flash_g4_split.ld
  src/main/drivers/system_stm32g4xx.c
Labels: RN: BUGFIX, Added by Cherry-pick

#12722 Minor pid.c refactoring
  src/main/flight/pid.c
  src/main/flight/pid_init.c
Labels: RN: REFACTORING

#12752 Update mode label for BOXBLACKBOXERASE
  src/main/msp/msp_box.c
Labels: Ready to Merge, Cleanup

#12721 TPA optimisations
  src/main/cli/settings.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
Labels: Ready to Merge, RN: IMPROVEMENT, Tested

#12291 Allow custom H7 HSE freqs. Allow H7 HSI. Limit H723 speed to 520Mhz
  src/main/startup/system_stm32h7xx.c
Labels: In Development, RN: IMPROVEMENT

#12796 Fix bidirectional dshot on F7
  src/main/drivers/dshot_bitbang_decode.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#12785 [4.4.2] Converge IMU faster at higher groundspeed during GPS Rescue
  src/main/flight/gps_rescue.c
  src/main/flight/gps_rescue.h
  src/main/flight/imu.c
  src/main/pg/gps_rescue.c
  src/test/unit/flight_imu_unittest.cc
Labels: RN: BUGFIX, Added by Cherry-pick

#12784 [4.4.2] If CS is asserted between transfers then consider bus to be busy for …
  src/main/drivers/bus.h
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi_ll.c
  src/main/drivers/max7456.c
Labels: RN: BUGFIX, Added by Cherry-pick

#12795 [4.4.2] Revert NVIC SPI priority
  src/main/drivers/bus_spi.c
Labels: RN: BUGFIX

#12809 fixes not working Ghost on F4xx
  src/main/drivers/stm32/serial_uart_stm32f4xx.c
Labels: RN: BUGFIX

#12811 [4.4.2] fixes not working Ghost on F4xx (#12809)
  src/main/drivers/serial_uart_stm32f4xx.c
Labels: RN: BUGFIX

#12789 GPS Rescue Bugfix to ensure IMU adaptation to GPS course over ground
  src/main/flight/gps_rescue.c
  src/main/flight/imu.c
Labels: RN: BUGFIX

#12591 Add NMEA Custom commands
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
  src/main/io/gps.c
  src/main/pg/gps.h
Labels: RN: IMPROVEMENT, Tested

#12821 [4.4.2] GPS Rescue Bugfix to ensure IMU adaptation to GPS course over ground
  src/main/flight/gps_rescue.c
  src/main/flight/imu.c
Labels: RN: BUGFIX, Added by Cherry-pick

#12824 [4.4.2] Fix MS5611
  src/main/sensors/barometer.c
Labels: RN: BUGFIX

#12817 Add cloud build instructions to Pull Request
  .github/workflows/artifact-links.yml
  .github/workflows/hide-artifact-links.yml
Labels: Housekeeping

#12815 Handle invalid baro pressure values
  src/main/sensors/barometer.c
Labels: RN: BUGFIX, Tested

#12720 Thrust linear code optimisations
  src/main/flight/pid.c
Labels: RN: REFACTORING

#11856 Add GPS Lap Timer
  make/source.mk
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms_menu_gps_lap_timer.c
  src/main/cms/cms_menu_gps_lap_timer.h
  src/main/cms/cms_menu_misc.c
  src/main/cms/cms_menu_osd.c
  src/main/drivers/osd_symbols.h
  src/main/fc/gps_lap_timer.c
  src/main/fc/gps_lap_timer.h
  src/main/fc/init.c
  src/main/fc/parameter_names.h
  src/main/fc/rc_modes.h
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/msp/msp_box.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/pg/gps.c
  src/main/pg/gps.h
  src/main/pg/gps_lap_timer.c
  src/main/pg/gps_lap_timer.h
  src/main/pg/pg_ids.h
  src/main/target/common_post.h
Labels: Testing Required, Needs coordination with betaflight-configurator, RN: MAJOR FEATURE

#12835 [4.4.2] gps rescue initiated too close, imu fixes
  src/main/cli/settings.c
  src/main/flight/gps_rescue.c
  src/main/pg/gps_rescue.c
Labels: Testing Required

#12837 Add PR cloud comment to maintenance branch too
  .github/workflows/pr-cloud-comment.yml
Labels: Housekeeping

#12054 RPM Limiter
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/mixer_init.c
  src/main/flight/mixer_init.h
  src/main/pg/motor.c
  src/main/pg/motor.h
  src/main/sensors/battery.c
  src/main/sensors/voltage.h
Labels: RN: MAJOR FEATURE

#12841 GPS rescue IMU adaptation 0.2
  src/main/cli/settings.c
  src/main/flight/gps_rescue.c
Labels: RN: BUGFIX, Tested

#12845 [4.4.2] GPS Rescue IMU adaptation 0.2
  src/main/cli/settings.c
  src/main/flight/gps_rescue.c
Labels: RN: BUGFIX

#12854 Revert PARAM_NAME_GPS_RESCUE_MAX_RESCUE_ANGLE range
  src/main/cli/settings.c
Labels: Revert
