Repository betaflight/betaflight, pull requests merged in 2023-12, with the labels that each got.

#13096 Fix: ledstrip vtx freq based color selection in RACE mode
  src/main/drivers/vtx_common.h
  src/main/io/ledstrip.c
Labels: RN: BUGFIX

#13121 Add OSD Link Quality alarm value to the MSP
  src/main/msp/msp.c
Labels: Ready to Merge, RN: IMPROVEMENT

#12548 Add additional timers for AT32F4
  src/main/drivers/at32/timer_at32f43x.c
  src/main/drivers/at32/timer_def.h
  src/main/drivers/stm32/timer_def.h
Labels: RN: IMPROVEMENT

#13012 Dshot RPM Telemetry Refactoring
  src/main/blackbox/blackbox.c
  src/main/build/debug.c
  src/main/cli/cli.c
  src/main/common/time.h
  src/main/drivers/dshot.c
  src/main/drivers/dshot.h
  src/main/fc/core.c
  src/main/fc/init.c
  src/main/flight/mixer.c
  src/main/flight/rpm_filter.c
  src/main/flight/rpm_filter.h
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd_elements.c
  src/main/osd/osd_warnings.c
  src/main/sensors/esc_sensor.c
  src/main/sensors/gyro_init.c
  src/main/target/SITL/sitl.c
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/smartport.c
  src/main/telemetry/srxl.c
  src/test/unit/arming_prevention_unittest.cc
Labels: Tested, RN: REFACTORING

#13187 at32: add PA0/PA1 as i2c pins
  src/main/drivers/at32/bus_i2c_atbsp_init.c
Labels: RN: IMPROVEMENT

#12909 Set serial duplex mode
  src/main/pg/rx.c
Labels: RN: IMPROVEMENT

#12509 Fix default PID DENOM
  src/main/config/config.c
  src/main/flight/pid.c
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32G47X/target.h
Labels: RN: BUGFIX

#13119 Allow CRSF RX binding via cli
  src/main/rx/crsf.c
  src/main/rx/crsf.h
  src/main/rx/crsf_protocol.h
  src/main/rx/rx_bind.c
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#13006 Additional TPA breakpoint for low Throttle
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/fc/parameter_names.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
Labels: RN: MINOR FEATURE, Tested, Needs coordination with blackbox-log-viewer

#13026 Fixed incorrect accelerometer scaling in MSP
  src/main/msp/msp.c
Labels: Ready to Merge, Needs coordination with betaflight-configurator, RN: BUGFIX, Needs coordination with blackbox-log-viewer

#13013 Fix #12908 Add ICM-42688-P IMU to list of IMUs with overflow protection
  src/main/sensors/gyro_init.c
Labels: RN: BUGFIX

#13127 Keep I-terms at zero throttle for fixed wings
  src/main/fc/core.c
Labels: RN: BUGFIX

#13150 STMicro LIS2MDL mag support
  mk/source.mk
  src/main/cli/settings.c
  src/main/drivers/compass/compass_lis2mdl.c
  src/main/drivers/compass/compass_lis2mdl.h
  src/main/sensors/compass.c
  src/main/sensors/compass.h
  src/main/target/common_post.h
Labels: Ready to Merge, RN: MINOR FEATURE

#13054 STMicro LPS22DF baro support
  src/main/cli/settings.c
  src/main/drivers/barometer/barometer_lps22df.c
  src/main/drivers/barometer/barometer_lps22df.h
  src/main/sensors/barometer.c
  src/main/sensors/barometer.h
Labels: Ready to Merge, RN: MINOR FEATURE

#13190 Add RPM Limiter to baseline build
  src/main/flight/mixer.c
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#13014 Fix # 12991 Change LSM6DSO gyro scaling to 70 mdps/LSB
  src/main/drivers/accgyro/accgyro_spi_lsm6dso_init.c
Labels: Testing Required, RN: BUGFIX

#13197 Add LPS22DF to core build
  src/main/drivers/barometer/barometer_lps22df.c
  src/main/drivers/barometer/barometer_lps22df.h
  src/main/target/common_pre.h
Labels: Ready to Merge, RN: BUGFIX

#13196 Encapsulate LSM6DSV16X driver specific macros
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/accgyro/accgyro_spi_lsm6dsv16x.c
  src/main/drivers/accgyro/accgyro_spi_lsm6dsv16x.h
Labels: Ready to Merge, RN: REFACTORING

#13200 Change WHO_AM_I to match datasheet
  src/main/drivers/accgyro/accgyro_mpu.h
Labels: Ready to Merge, Bugfix

#13204 Make lookupTableThrottleLimitType an extern variable
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/cms/cms_menu_imu.c
  src/main/cms/cms_menu_quick.c
Labels: Ready to Merge, RN: REFACTORING

#12094 Throttlebased EzLanding
  src/main/blackbox/blackbox.c
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/fc/parameter_names.h
  src/main/fc/rc.c
  src/main/fc/rc.h
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/mixer_init.c
  src/main/flight/mixer_init.h
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Testing Required, Needs coordination with betaflight-configurator, RN: MAJOR FEATURE

#13211 Fix OSD Quick Menu
  src/main/cms/cms_menu_quick.c
Labels: Ready to Merge, RN: BUGFIX

#13217 Fix jumpy baro debug
  src/main/flight/position.c
Labels: RN: BUGFIX

#13214 Fix: RPM Limit - reset I-term at arm
  src/main/fc/core.c
  src/main/flight/mixer.c
  src/main/flight/mixer_init.c
  src/main/flight/mixer_init.h
Labels: RN: BUGFIX

#13212 Fix defines for CI and add USE_RACE_PRO feature pack
  src/main/target/common_pre.h
Labels: Ready to Merge, Housekeeping

#13218 Break LED_STRIP update into 20us chunks
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/light_ws2811strip.h
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
  src/test/unit/ledstrip_unittest.cc
  src/test/unit/ws2811_unittest.cc
Labels: Ready to Merge, RN: BUGFIX

#13226 bugfix compassBiasEstimatorInit initialisation
  src/main/sensors/compass.c
Labels: Bugfix

#13227 Added d_min for PID osd elements
  src/main/osd/osd_elements.c
Labels: RN: BUGFIX

#13228 Fix error in I2C write operation on AT32
  lib/main/AT32F43x/middlewares/i2c_application_library/i2c_application.c
Labels: Bugfix

#13216 Remove custom defaults and enable features on boot
  src/main/cli/cli.c
  src/main/cli/cli.h
  src/main/config/config.c
  src/main/config/config.h
  src/main/msp/msp.c
Labels: Ready to Merge, Cleanup, RN: BUGFIX, Tested

#13222 at32: add mux 3 for tmr9 on port c
  src/main/drivers/at32/timer_at32f43x.c
  src/main/drivers/at32/timer_def.h
Labels: RN: IMPROVEMENT

#13230 Add gyro jitter analysis to DEBUG_SCHEDULER_DETERMINISM
  src/main/drivers/system.c
  src/main/drivers/system.h
  src/main/scheduler/scheduler.c
  src/main/target/SITL/sitl.c
  src/test/unit/scheduler_unittest.cc
Labels: RN: IMPROVEMENT

#13233 Fix dma pin <io> list
  src/main/cli/cli.c
  src/main/drivers/at32/dma_reqmap_mcu.c
Labels: RN: BUGFIX

#13231 Update hardware specification link
  README.md
Labels: Housekeeping

#13232 Revive MSP message for mag declination
  src/main/msp/msp.c
  src/main/msp/msp_protocol.h
Labels: RN: IMPROVEMENT

#13234 Add hardware LPF1 options for lsm6dsv16x gyro
  src/main/config/config.c
  src/main/drivers/accgyro/accgyro_spi_lsm6dsv16x.c
Labels: RN: IMPROVEMENT

#13235 Change MAX7456 AUTO default to PAL
  src/main/drivers/max7456.c
Labels: RN: BUGFIX

#13239 Revised LPF1+LPF2 filter cutoff bandwidths from STMicro
  src/main/drivers/accgyro/accgyro_spi_lsm6dsv16x.c
Labels: RN: IMPROVEMENT

#13240 Add MSP request for UBLOX SatInfo and disable SatInfo on ARMING.
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
  src/main/pg/gps.c
Labels: RN: BUGFIX, Tested

#13244 Fix arming when GPS included in build but no active GNSS device attached + revert msp request for SatInfo
  src/main/config/config.c
  src/main/fc/core.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
  src/main/pg/gps.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#13247 Led task optimistion
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
Labels: RN: BUGFIX

#13237 Fix BMI160 gate and optimize directives
  src/main/sensors/acceleration_init.c
  src/main/sensors/gyro_init.c
Labels: Cleanup, RN: BUGFIX
