Repository betaflight/betaflight, pull requests merged in 2023-02, with the labels that each got.

#12277 Fix max permissible CMS rows and up/down page arrows
  src/main/cms/cms.c
  src/main/io/displayport_crsf.c
Labels: RN: BUGFIX

#12146 Update ARM SDK to 11.3rel1
  make/tools.mk
Labels: Build System Improvement

#12284 Fix max permissible CMS rows and up/down page arrows (#12277)
  src/main/cms/cms.c
  src/main/io/displayport_crsf.c
Labels: RN: BUGFIX

#12281 Fix missing CUSTOM_DEFAULTS for H730/H750 targets.
  src/link/stm32_h730_common.ld
  src/link/stm32_h750_common.ld
  src/link/stm32_ram_h730_exst.ld
  src/link/stm32_ram_h750_exst.ld
  src/main/target/STM32H730/target.h
  src/main/target/STM32H750/target.h
Labels: Cleanup

#12282 Remove duplicate and sort *_SRC files [H7]
  make/mcu/STM32H7.mk
Labels: Cleanup

#12288 Add VARIO if BARO or GPS defined
  src/main/target/common_post.h
Labels: Cleanup

#12298 BF - Fix QuadSPI include paths.
  src/main/drivers/stm32/bus_quadspi_hal.c
Labels: Cleanup

#12303 ELRS - Simplify deferred ISR
  src/main/drivers/rx/rx_sx1280.c
Labels: RN: REFACTORING

#12293 Delete support directory
  support/scripts/build_nucleoh723zg_mmapped.sh
  support/scripts/build_spracingh7extreme.sh
  support/scripts/build_spracingh7rf.sh
Labels: Cleanup

#12302 NVIC - Update ELRS and SPI atomic_block usage to use appropriate priority levels.
  src/main/drivers/bus_spi.c
  src/main/drivers/rx/rx_sx1280.c
Labels: RN: IMPROVEMENT

#12301 SD - Use SDIO by default if target uses USE_SDCARD_SDIO.
  src/main/pg/sdcard.c
Labels: RN: BUGFIX

#12300 Don't enable all flash chips by default on EXST targets.
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#12294 Update .gitignore
  .gitignore
Labels: Cleanup, Housekeeping

#12314 Include smartport telemetry for Fport
  src/main/target/common_post.h
Labels: Cleanup

#12306 BF 4.4.1 rollup 1
  src/main/drivers/bus_spi.c
  src/main/drivers/rx/rx_sx1280.c
  src/main/pg/sdcard.c
Labels: RN: BUGFIX

#12327 Enable DMA on AT32F435 SPI
  src/main/fc/init.c
  src/main/target/AT32F435/target.h
Labels: RN: TARGET UPDATE, Development Instrumentation

#12334 Revert "Fix missing CUSTOM_DEFAULTS for H730/H750 targets. (#12281)"
  src/link/stm32_h730_common.ld
  src/link/stm32_h750_common.ld
  src/link/stm32_ram_h730_exst.ld
  src/link/stm32_ram_h750_exst.ld
  src/main/target/STM32H730/target.h
  src/main/target/STM32H750/target.h
Labels: Revert

#12329 Fix SDFT batchSize rounding
  src/main/common/sdft.c
Labels: Tested, Bugfix

#12338 Fix BMI160 accelerometer read in non-DMA SPI transfer
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
  src/main/drivers/bus_spi.c
Labels: RN: BUGFIX

#12328 Define USE_LATE_TASK_STATISTICS for AT32
  src/main/drivers/at32/platform_at32.h
Labels: RN: TARGET UPDATE

#12339 Tidy up of AT (timer defs), and STM specific init defines
  src/main/drivers/at32/pwm_output_at32bsp.c
  src/main/drivers/at32/timer_at32f43x.c
  src/main/fc/init.c
  src/main/target/AT32F435/target.h
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H723/target.h
  src/main/target/STM32H730/target.h
  src/main/target/STM32H743/target.h
  src/main/target/STM32H750/target.h
Labels: Cleanup, RN: IGNORE

#12333 Revert "Fix missing CUSTOM_DEFAULTS for H730/H750 targets. (#12261)"
  src/link/stm32_h730_common.ld
  src/link/stm32_h750_common.ld
  src/link/stm32_ram_h730_exst.ld
  src/link/stm32_ram_h750_exst.ld
  src/main/target/STM32H730/target.h
  src/main/target/STM32H750/target.h
Labels: Revert

#12324 Fix blackboxdevice missing
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#12337 add thrust_linear to blackbox header
  src/main/blackbox/blackbox.c
  src/main/fc/parameter_names.h
Labels: RN: IMPROVEMENT

#12342 Method for adding defaults using defines for resources.
  src/main/drivers/camera_control.c
  src/main/fc/init.c
  src/main/flight/servos.c
  src/main/io/ledstrip.c
  src/main/io/transponder_ir.c
  src/main/pg/motor.c
  src/main/pg/rx_pwm.c
  src/main/pg/timerio.c
Labels: Ready to Merge, RN: TARGET UPDATE, RN: REFACTORING

#12352 add BMP280 to target FLMO GRAVITYF7
  src/config/GRAVITYF7/config.h
Labels: Target Change

#12330 Refactor GPS state_position
  src/main/io/gps.c
Labels: RN: REFACTORING

#12360 FIX: Flash status compilation error
  src/main/drivers/flash_m25p16.c
Labels: Ready to Merge, RN: BUGFIX

#12354 Makefile Cleanup - further simplification of local building
  Makefile
Labels: Ready to Merge, RN: IMPROVEMENT, Tested

#12349 timerHardware removal - all targets use fullTimerHardware now.
  src/main/drivers/timer.h
  src/main/drivers/timer_common.c
  src/main/pg/timerup.c
  src/main/pg/timerup.h
  src/main/target/AT32F435/target.c
  src/main/target/SITL/sitl.c
  src/main/target/STM32F405/target.c
  src/main/target/STM32F411/target.c
  src/main/target/STM32F745/target.c
  src/main/target/STM32F7X2/target.c
  src/main/target/STM32G47X/target.c
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H723/target.c
  src/main/target/STM32H723/target.h
  src/main/target/STM32H730/target.c
  src/main/target/STM32H730/target.h
  src/main/target/STM32H743/target.c
  src/main/target/STM32H743/target.h
  src/main/target/STM32H750/target.c
  src/main/target/STM32H750/target.h
Labels: Ready to Merge, RN: REFACTORING

#12355 Simplified platform.h
  src/main/drivers/at32/platform_at32.h
  src/main/drivers/stm32/platform_stm32.h
  src/main/platform.h
  src/main/target/AT32F435/target.h
  src/main/target/SITL/target.h
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H723/target.h
  src/main/target/STM32H730/target.h
  src/main/target/STM32H743/target.h
  src/main/target/STM32H750/target.h
Labels: Ready to Merge, RN: REFACTORING

#12364 Adding additional MOTOR pin mappings for defaults
  src/main/pg/motor.c
Labels: Ready to Merge, RN: REFACTORING

#12357 Refactor I2C to use I2Cx_SCL_PIN and I2Cx_SDA_PIN
  src/config/SPRACINGH7EXTREME/config.h
  src/config/SPRACINGH7RF/config.h
  src/main/drivers/stm32/platform_stm32.h
  src/main/pg/bus_i2c.c
  src/main/target/common_defaults_post.h
Labels: Ready to Merge, RN: REFACTORING

#12361 Remove USE_SWDIO, simply refer to DEBUG
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  make/mcu/STM32G4.mk
  make/mcu/STM32H7.mk
  src/main/build/debug.h
  src/main/drivers/at32/debug.c
  src/main/drivers/stm32/debug.c
  src/main/fc/init.c
Labels: Ready to Merge, RN: REFACTORING

#12356 Initial ADC support for AT32
  lib/main/AT32F43x/drivers/src/at32f435_437_adc.c
  src/main/drivers/adc.c
  src/main/drivers/adc.h
  src/main/drivers/adc_impl.h
  src/main/drivers/at32/adc_at32f43x.c
  src/main/drivers/at32/platform_at32.h
  src/main/drivers/at32/timer_at32bsp.c
  src/main/drivers/timer.h
  src/main/target/AT32F435/target.h
Labels: Library Patch

#12368 Enable SPI DMA receive before transmit on AT32
  src/main/drivers/at32/bus_spi_at32bsp.c
Labels: RN: BUGFIX

#12367 Using SPI default pins
  src/main/drivers/at32/platform_at32.h
  src/main/drivers/stm32/platform_stm32.h
  src/main/target/common_defaults_post.h
Labels: Ready to Merge, Cleanup, RN: REFACTORING

#12373 FIX: Poor performance due to platform movements.
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: Ready to Merge, RN: BUGFIX, Tested

#12363 To enable display of pin mapping for config.h
  src/main/cli/cli.c
  src/main/pg/timerio.c
Labels: Ready to Merge, RN: REFACTORING

#12375 bump version 4.3.3
  src/main/build/version.h
Labels: Housekeeping

#12371 Fix MPU6000 reset
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_spi_mpu6000.c
Labels: RN: BUGFIX

#12376 4.4.1: Adding support for building by config
  Makefile
  make/source.mk
  src/config/SPRACINGH7EXTREME/config.h
  src/config/SPRACINGH7RF/config.h
  src/main/build/version.h
  src/main/platform.h
Labels: Ready to Merge, RN: TARGET UPDATE

#12346 Added SITL Gazebo
  src/main/fc/rc_modes.c
  src/main/fc/tasks.c
  src/main/main.c
  src/main/msp/msp.c
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/sensors/acceleration_init.c
  src/main/sensors/barometer.c
  src/main/sensors/barometer.h
  src/main/target/SITL/sitl.c
  src/main/target/SITL/target.h
  src/main/target/SITL/udplink.c
Labels: RN: IMPROVEMENT

#12389 FIX: Several build issues following configuration changes
  Makefile
  src/main/drivers/camera_control.c
  src/main/fc/init.c
  src/main/pg/rx_spi_expresslrs.c
  src/main/rx/expresslrs.c
  src/main/target/common_defaults_post.h
  src/main/target/common_post.h
Labels: RN: BUGFIX

#12299 Require explicit usage of firmware partition for EXST targets.
  src/main/drivers/flash.c
Labels: RN: TARGET UPDATE

#12394 Move FLASH_PAGE_SIZE definition to CPU specific target.h files
  src/main/config/config_streamer.c
  src/main/target/AT32F435/target.h
  src/main/target/SITL/target.h
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H723/target.h
  src/main/target/STM32H730/target.h
  src/main/target/STM32H743/target.h
  src/main/target/STM32H750/target.h
Labels: RN: TARGET UPDATE, RN: REFACTORING

#12404 FIX: Multi-gyro enabled but not configured at compile time.
  src/main/pg/gyrodev.c
Labels: RN: BUGFIX

#12397 REFACTOR: moving timer definitions to MCU locations.
  make/mcu/AT32F4.mk
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  make/mcu/STM32G4.mk
  make/mcu/STM32H7.mk
  make/source.mk
  src/main/drivers/at32/dma_reqmap_mcu.c
  src/main/drivers/at32/dma_reqmap_mcu.h
  src/main/drivers/at32/platform_mcu.h
  src/main/drivers/at32/timer_at32f43x.c
  src/main/drivers/at32/timer_def.h
  src/main/drivers/dma_reqmap.h
  src/main/drivers/stm32/dma_reqmap_mcu.c
  src/main/drivers/stm32/dma_reqmap_mcu.h
  src/main/drivers/stm32/platform_mcu.h
  src/main/drivers/stm32/timer_def.h
  src/main/drivers/stm32/timer_stm32f4xx.c
  src/main/drivers/stm32/timer_stm32f7xx.c
  src/main/drivers/stm32/timer_stm32g4xx.c
  src/main/drivers/stm32/timer_stm32h7xx.c
  src/main/drivers/timer.h
  src/main/platform.h
  src/main/target/AT32F435/target.h
  src/main/target/SITL/dma_reqmap_mcu.h
  src/main/target/SITL/platform_mcu.h
  src/main/target/SITL/sitl.c
  src/main/target/SITL/timer_def.h
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H723/target.h
  src/main/target/STM32H730/target.h
  src/main/target/STM32H743/target.h
  src/main/target/STM32H750/target.h
  src/test/Makefile
  src/test/unit/dma_reqmap_mcu.h
  src/test/unit/ledstrip_unittest.cc
  src/test/unit/timer_def.h
Labels: RN: REFACTORING

#12388 Enable cloud build features at runtime
  src/main/config/config.c
  src/main/config/feature.h
Labels: RN: IMPROVEMENT

#12386 Adding VMA address to config.h
  Makefile
  src/config/SPRACINGH7EXTREME/config.h
  src/config/SPRACINGH7RF/config.h
  src/main/target/STM32H750/target.mk
Labels: RN: TARGET UPDATE

#12410 FIX: Custom defaults - premature configuration
  src/main/sensors/gyro_init.c
Labels: RN: BUGFIX

#12411 FIX: Legacy drivers required for STM32F411DISCOVERY target
  make/source.mk
Labels: RN: BUGFIX

#12406 Remove GYRO defines from common_post_defaults
  src/main/pg/gyrodev.c
  src/main/pg/gyrodev.h
  src/main/target/common_defaults_post.h
Labels: REFACTORING

#12426 increase FF smoothing max to suit elrs 1000hz link rate
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
Labels: Needs coordination with betaflight-configurator, Bugfix

#12430 FIX: Autogeneration of config.h inadvertently used PNONE instead of NONE
  src/config/GEPRCF411/config.h
  src/config/GEPRCF411_AIO/config.h
  src/config/KROOZX/config.h
  src/config/MATEKF411/config.h
  src/config/NOX/config.h
  src/config/OMNIBUSF4FW/config.h
  src/config/SKYSTARSF411/config.h
  src/config/SPRACINGH7EXTREME/config.h
  src/config/SPRACINGH7RF/config.h
  src/config/YUPIF4/config.h
  src/config/YUPIF7/config.h
  src/config/ZEEZWHOOP/config.h
Labels: Ready to Merge, RN: BUGFIX, RN: TARGET UPDATE, Bugfix

#12423 Add AT32F435 I2C support
  lib/main/AT32F43x/middlewares/i2c_application_library/i2c_application.c
  src/config/REVO_AT/config.h
  src/main/drivers/at32/bus_i2c_atbsp_init.c
  src/main/drivers/at32/platform_mcu.h
  src/main/drivers/bus_i2c_config.c
  src/main/drivers/bus_i2c_impl.h
  src/main/target/AT32F435/target.h
  src/main/target/AT32F435/target.mk
Labels: RN: TARGET UPDATE

#12433 [4.4-maintenance] increase FF smoothing max to suit elrs 1000hz link rate (#12426)
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT

#12434 [4.3-maintenance] increase FF smoothing max to suit elrs 1000hz link rate (#12426)
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
Labels: RN: IMPROVEMENT
