Repository betaflight/betaflight, pull requests merged in 2023-03, with the labels that each got.

#12425 Removing Custom Defaults
  Makefile
  src/link/at32_flash_f43xM.ld
  src/link/at32_flash_f4_split.ld
  src/link/stm32_flash.ld
  src/link/stm32_flash_f405.ld
  src/link/stm32_flash_f411.ld
  src/link/stm32_flash_f4_split.ld
  src/link/stm32_flash_f722.ld
  src/link/stm32_flash_f74x.ld
  src/link/stm32_flash_f765.ld
  src/link/stm32_flash_f7_split.ld
  src/link/stm32_flash_g474.ld
  src/link/stm32_flash_g4_split.ld
  src/link/stm32_flash_h723_1m.ld
  src/link/stm32_flash_h743_2m.ld
  src/link/stm32_flash_h750_128k.ld
  src/link/stm32_flash_h750_1m.ld
  src/link/stm32_h723_common.ld
  src/link/stm32_h723_common_post.ld
  src/link/stm32_h730_common.ld
  src/link/stm32_h730_common_post.ld
  src/link/stm32_h750_common.ld
  src/link/stm32_h750_common_post.ld
  src/link/stm32_ram_h723_exst.ld
  src/link/stm32_ram_h723_exst_post.ld
  src/link/stm32_ram_h730_exst.ld
  src/link/stm32_ram_h730_exst_post.ld
  src/link/stm32_ram_h743.ld
  src/link/stm32_ram_h750_exst.ld
  src/link/stm32_ram_h750_exst_post.ld
  src/main/cli/cli.c
  src/main/config/config.c
  src/main/config/config.h
  src/main/drivers/at32/platform_mcu.h
  src/main/drivers/stm32/platform_mcu.h
  src/main/fc/init.c
  src/main/msp/msp.c
  src/main/sensors/gyro_init.c
  src/main/target/AT32F435/target.h
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H723/target.h
  src/main/target/STM32H743/target.h
  src/main/target/common_post.h
  src/test/unit/cli_unittest.cc
Labels: RN: TARGET UPDATE, RN: REFACTORING

#12439 H7 Fix frozen ADC values
  src/main/drivers/stm32/adc_stm32h7xx.c
Labels: RN: BUGFIX

#12443 4.4-maintenance H7 Fix frozen ADC values
  src/main/drivers/adc_stm32h7xx.c
Labels: RN: BUGFIX

#12440 OSD is always enabled for SPRACINGH7RF and comments in config fix
  src/config/FF_RACEPIT/config.h
  src/config/FF_RACEPIT_MINI/config.h
  src/config/PYRODRONEF4/config.h
  src/config/SPRACINGH7EXTREME/config.h
  src/config/SPRACINGH7RF/config.h
  src/config/TALONF4V2/config.h
  src/config/TALONF7FUSION/config.h
  src/config/TALONF7V2/config.h
Labels: RN: TARGET UPDATE, Bugfix

#12446 FIX: Multi gyro and SDIO hard fault
  src/config/MATEKH743/config.h
  src/config/NBD_GALAXYAIO255/config.h
  src/config/NEUTRONRCH743AIO/config.h
  src/config/NEUTRONRCH7BT/config.h
  src/config/SPRACINGH7RF/config.h
  src/main/pg/gyrodev.c
Labels: RN: BUGFIX

#12447 Fix Matek H743
  src/config/MATEKH743/config.h
Labels: RN: TARGET UPDATE

#12431 AT32F435 BlackBox FLASH support
  src/config/REVO_AT/config.h
  src/main/drivers/at32/bus_spi_at32bsp.c
  src/main/drivers/at32/platform_mcu.h
  src/main/drivers/stm32/bus_spi_stdperiph.c
  src/main/target/AT32F435/target.h
Labels: RN: TARGET UPDATE, RN: IMPROVEMENT

#12451 FIX: update & clean configuration
  src/config/ALIENFLIGHTNGF7_ELRS/config.h
  src/config/BETAFPVF4SX1280/config.h
  src/config/CRAZYBEEF4DX/config.h
  src/config/CRAZYBEEF4SX1280/config.h
  src/config/DALRCF722DUAL/config.h
  src/config/DARWINF4SX1280HD/config.h
  src/config/EMAX_TINYHAWKF4SX1280/config.h
  src/config/FLYWOOF405S_AIO/config.h
  src/config/GEPRCF411SX1280/config.h
  src/config/HGLRCF411SX1280/config.h
  src/config/KAKUTEF7MINI/config.h
  src/config/MATEKF722HD/config.h
  src/config/MATEKH743/config.h
  src/config/NBD_INFINITYAIOV2/config.h
  src/config/NEUTRONRCF411SX1280/config.h
  src/config/SPRACINGH7RF/config.h
  src/config/TMOTORF4SX1280/config.h
Labels: RN: TARGET UPDATE, Tested

#12444 Fix ICM426XX AA filter
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
Labels: Testing Required, Bugfix

#12458 FIX CONFIG: ESC and NONE for current meters
  src/config/AG3XF4/config.h
  src/config/AG3XF7/config.h
  src/config/GEPRCF722_BT_HD/config.h
  src/config/GEPRCF745_BT_HD/config.h
  src/config/JBF7/config.h
  src/config/NOX/config.h
  src/config/OMNIBUSF4NANOV7/config.h
  src/config/OMNIBUSF7NANOV7/config.h
  src/config/TRANSTECF411HD/config.h
Labels: RN: TARGET UPDATE

#12459 FIX CONFIG: LED INVERSION
  src/config/BETAFPVF411RX/config.h
  src/config/BETAFPVF4SX1280/config.h
  src/config/CRAZYBEEF4DXS/config.h
  src/config/DARWINF4SX1280HD/config.h
  src/config/EMAX_TINYHAWKF4SX1280/config.h
  src/config/EMAX_TINYHAWK_F411RX/config.h
  src/config/HGLRCF405/config.h
  src/config/HGLRCF411SX1280/config.h
  src/config/IFLIGHT_BLITZ_F411RX/config.h
  src/config/IFLIGHT_F4SX1280/config.h
  src/config/MATEKF411RX/config.h
  src/config/TALONF4V2/config.h
  src/config/TMOTORF4SX1280/config.h
Labels: RN: TARGET UPDATE

#12463 Add configuration
  src/config/IFLIGHT_H743_AIO_V2/config.h
Labels: RN: TARGET UPDATE

#12468 FIX CONFIG: MATEKF405TEMINI SPI3 + CONFIG DEFAULT_VOLTAGE_METER_SCALE + SYSTEM_HSE_MHZ
  src/config/DALRCF722DUAL/config.h
  src/config/GRAVITYF7/config.h
  src/config/JBF7/config.h
  src/config/JBF7_DJI/config.h
  src/config/KAKUTEH7/config.h
  src/config/KAKUTEH7MINI/config.h
  src/config/KAKUTEH7V2/config.h
  src/config/MAMBAH743/config.h
  src/config/MATEKF405TE/config.h
  src/config/MATEKF405TEMINI/config.h
  src/config/MATEKH743/config.h
  src/config/NEUTRONRCF7AIO/config.h
  src/config/PYRODRONEF4/config.h
  src/config/PYRODRONEF4PDB/config.h
  src/config/PYRODRONEF7/config.h
  src/config/SIRMIXALOT/config.h
  src/config/SPEEDYBEEF7V3/config.h
  src/config/TALONF7DJIHD/config.h
  src/config/TALONF7FUSION/config.h
  src/config/TALONF7V2/config.h
  src/config/TMOTORF722SE/config.h
  src/config/ZEEZF7/config.h
  src/main/config/config.c
  src/main/sensors/voltage.c
  src/main/target/SITL/target.h
  src/main/target/common_post.h
Labels: RN: BUGFIX, RN: TARGET UPDATE, Tested

#12343 Improve GPS Rescue Pitch smoothing and disarming
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_gps_rescue.c
  src/main/fc/parameter_names.h
  src/main/fc/rc_controls.c
  src/main/flight/failsafe.c
  src/main/flight/failsafe.h
  src/main/flight/gps_rescue.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/msp/msp.c
  src/main/pg/gps_rescue.c
  src/main/pg/gps_rescue.h
  src/main/rx/rx.c
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/flight_imu_unittest.cc
Labels: Testing Required, RN: BUGFIX

#12475 FIX CONFIG: GYRO
  src/config/AOCODARCF7DUAL/config.h
  src/config/AOCODARCH7DUAL/config.h
  src/config/CLRACINGF7/config.h
  src/config/DFR_F722_DUAL_HD/config.h
  src/config/EMAX_BABYHAWK_II_HD/config.h
  src/config/EXF722DUAL/config.h
  src/config/GEPRCF411_AIO/config.h
  src/config/GEPRCF722_BT_HD/config.h
  src/config/GEPRCF745_BT_HD/config.h
  src/config/HAKRCF722V2/config.h
  src/config/HGLRCF405/config.h
  src/config/HGLRCF745/config.h
  src/config/IFLIGHT_F405_TWING/config.h
  src/config/IFLIGHT_F411_AIO32/config.h
  src/config/IFLIGHT_F722_TWING/config.h
  src/config/IFLIGHT_H743_AIO_V2/config.h
  src/config/IFLIGHT_H7_TWING/config.h
  src/config/JBF7/config.h
  src/config/JBF7_DJI/config.h
  src/config/KAKUTEH7/config.h
  src/config/LDARC_F411/config.h
  src/config/MATEKF411/config.h
  src/config/MATEKF411SE/config.h
  src/config/MATEKF722HD/config.h
  src/config/MATEKH743/config.h
  src/config/NBD_CRICKETF7V2/config.h
  src/config/NBD_GALAXYAIO255/config.h
  src/config/NBD_INFINITYAIOV2PRO/config.h
  src/config/NEUTRONRCF407/config.h
  src/config/NEUTRONRCH743AIO/config.h
  src/config/NEUTRONRCH7BT/config.h
  src/config/NUCLEOF722/config.h
  src/config/SKYSTARSH7HD/config.h
  src/config/SPEEDYBEEF7V3/config.h
  src/config/SPRACINGF7DUAL/config.h
  src/config/SPRACINGH7EXTREME/config.h
  src/config/TALONF4V2/config.h
  src/config/TALONF7FUSION/config.h
  src/config/WIZZF7HD/config.h
  src/main/sensors/gyro.c
Labels: RN: TARGET UPDATE

#12476 FIX CONFIG: BARO
  src/config/BETAFPVF405/config.h
  src/config/BETAFPVF411/config.h
  src/config/DRONIUSF7/config.h
  src/config/FLYWOOF745NANO/config.h
  src/config/GEPRCF411/config.h
  src/config/GRAVITYF7/config.h
  src/config/HGLRCF405/config.h
  src/config/HGLRCF745/config.h
  src/config/KAKUTEF7/config.h
  src/config/KAKUTEF7HDV/config.h
  src/config/KAKUTEF7MINIV3/config.h
  src/config/LDARC_F411/config.h
  src/config/MATEKF405AIO/config.h
  src/config/MATEKF405MINI/config.h
  src/config/MATEKF405SE/config.h
  src/config/MATEKF411/config.h
  src/config/MATEKF722HD/config.h
  src/config/MATEKF722MINI/config.h
  src/config/NBD_INFINITYF4/config.h
  src/config/NEUTRONRCF407/config.h
  src/config/PYRODRONEF4/config.h
  src/config/RUSRACE_F4/config.h
  src/config/RUSRACE_F7/config.h
  src/config/SKYSTARSF411/config.h
  src/config/TALONF4V2/config.h
  src/config/TALONF7FUSION/config.h
  src/config/TALONF7V2/config.h
  src/config/TRANSTECF405HD/config.h
  src/config/TRANSTECF411/config.h
  src/config/TRANSTECF411HD/config.h
  src/config/TRANSTECF7/config.h
  src/config/TRANSTECF7HD/config.h
  src/config/ZEEZF7/config.h
  src/main/sensors/barometer.c
  src/main/target/common_post.h
Labels: RN: TARGET UPDATE

#12441 Cleanup of USB drivers for AT32F4
  lib/main/AT32F43x/middlewares/usb_drivers/src/usbd_core.c
  lib/main/AT32F43x/middlewares/usb_drivers/src/usbh_core.c
  lib/main/AT32F43x/middlewares/usb_drivers/src/usbh_ctrl.c
  lib/main/AT32F43x/middlewares/usbd_class/cdc/cdc_class.c
  make/mcu/STM32F4.mk
  make/mcu/STM32F7.mk
  make/mcu/STM32G4.mk
  make/mcu/STM32H7.mk
  make/source.mk
  src/main/drivers/at32/serial_usb_vcp_at32f4.c
  src/main/drivers/at32/usb/cdc_class.c
  src/main/drivers/at32/usb/cdc_class.h
  src/main/drivers/at32/usb/cdc_desc.c
  src/main/drivers/at32/usb/cdc_desc.h
  src/main/drivers/at32/usb/usb_core.c
  src/main/drivers/at32/usb/usb_core.h
  src/main/drivers/at32/usb/usb_std.h
  src/main/drivers/at32/usb/usbd_core.c
  src/main/drivers/at32/usb/usbd_core.h
  src/main/drivers/at32/usb/usbd_int.c
  src/main/drivers/at32/usb/usbd_int.h
  src/main/drivers/at32/usb/usbd_sdr.c
  src/main/drivers/at32/usb/usbd_sdr.h
  src/main/drivers/at32/usb/usbh_core.c
  src/main/drivers/at32/usb/usbh_core.h
  src/main/drivers/at32/usb/usbh_ctrl.c
  src/main/drivers/at32/usb/usbh_ctrl.h
  src/main/drivers/at32/usb/usbh_int.c
  src/main/drivers/at32/usb/usbh_int.h
  src/main/drivers/at32/usb_conf.h
  src/main/target/AT32F435/target.mk
Labels: Ready to Merge, RN: REFACTORING

#12474 added fake barometer sensor name to cli lookup table, fixes cli status crash for SITL
  src/main/cli/settings.c
Labels: RN: BUGFIX

#12478 FIX CONFIG: SDCARD Inversion
  src/config/AIRBOTF4SD/config.h
  src/config/ALIENFLIGHTF4/config.h
  src/config/ALIENFLIGHTNGF7/config.h
  src/config/ALIENFLIGHTNGF7_DUAL/config.h
  src/config/ALIENFLIGHTNGF7_ELRS/config.h
  src/config/ALIENFLIGHTNGF7_RX/config.h
  src/config/ANYFCF7/config.h
  src/config/BEEROTORF4/config.h
  src/config/BETAFPVF405/config.h
  src/config/BLUEJAYF4/config.h
  src/config/CLRACINGF7/config.h
  src/config/FISHDRONEF4/config.h
  src/config/FRSKYF4/config.h
  src/config/FURYF4/config.h
  src/config/HGLRCF745/config.h
  src/config/HOBBYWING_XROTORF4G3/config.h
  src/config/JBF7_V2/config.h
  src/config/KAKUTEF7/config.h
  src/config/KAKUTEF7HDV/config.h
  src/config/KAKUTEF7V2/config.h
  src/config/KAKUTEH7/config.h
  src/config/KROOZX/config.h
  src/config/MLTEMPF4/config.h
  src/config/MLTYPHF4/config.h
  src/config/NERO/config.h
  src/config/OMNIBUSF4SD/config.h
  src/config/OMNIBUSF7/config.h
  src/config/OMNIBUSF7V2/config.h
  src/config/SPRACINGF4EVO/config.h
  src/config/SPRACINGF4NEO/config.h
  src/config/STACKX/config.h
  src/config/WIZZF7HD/config.h
  src/config/YUPIF4/config.h
  src/main/pg/sdcard.c
  src/main/pg/sdio.c
  src/main/target/common_defaults_post.h
Labels: RN: TARGET UPDATE

#12464 AT32 initial dshot support
  src/config/ATSTARTF435/config.h
  src/main/drivers/at32/pwm_output_dshot.c
  src/main/drivers/dma.h
  src/main/drivers/dshot.c
  src/main/drivers/dshot_dpwm.h
  src/main/drivers/pwm_output_dshot_shared.c
  src/main/io/serial_4way.c
  src/main/target/AT32F435/target.h
  src/main/target/AT32F435/target.mk
Labels: RN: IMPROVEMENT

#12482 FIX: RX SPI modules not correctly activating (incorrect CS pin definition)
  src/config/SPRACINGH7RF/config.h
  src/main/pg/rx_spi.c
  src/main/target/common_defaults_post.h
Labels: RN: BUGFIX, Tested

#12480 FIX CONFIG
  src/config/FLYWOOF405NANO/config.h
  src/config/FOXEERF722V4/config.h
  src/config/MAMBAG4/config.h
  src/config/MATEKF405TE/config.h
  src/config/MATEKH743/config.h
  src/config/SPRACINGH7RF/config.h
Labels: Ready to Merge, RN: TARGET UPDATE

#12483 FIX: If local config applied, do not include all drivers.
  src/main/target/common_pre.h
Labels: Cleanup, RN: REFACTORING

#12486 FIX: ESCSERIAL_PIN not mapped correctly
  src/main/drivers/serial_escserial.c
Labels: RN: BUGFIX

#12490 Add 42688p gyro to JHEF411
  src/config/JHEF411/config.h
Labels: RN: TARGET UPDATE

#12491 CONFIG: Add BMP280 to GEPRCF722
  src/config/GEPRCF722/config.h
Labels: RN: TARGET UPDATE

#12432 Make dyn idle startup increase configurable
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
  src/main/flight/mixer.c
  src/main/flight/mixer_init.c
  src/main/flight/mixer_init.h
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: RN: IMPROVEMENT

#12487 FIX: SPI PIN defaults cleanup #2
  src/main/drivers/at32/platform_mcu.h
  src/main/drivers/stm32/bus_spi_ll.c
Labels: Cleanup, RN: REFACTORING

#12445 Debug 8 columns
  src/main/blackbox/blackbox.c
  src/main/build/debug.h
  src/main/drivers/dshot.c
Labels: RN: IMPROVEMENT

#12492 FIX CONFIG: MATEKF405TE /MINI
  src/config/MATEKF405TE/config.h
  src/config/MATEKF405TEMINI/config.h
Labels: Ready to Merge, RN: TARGET UPDATE

#12496 FIX: CRSF no active serial port and telem causing hardfault
  src/main/rx/crsf.c
Labels: RN: BUGFIX, Tested, Bugfix

#12497 Fix RX protocol config
  src/main/pg/rx.c
  src/main/target/common_defaults_post.h
Labels: RN: BUGFIX

#12495 Prevent SPRACINGH7RF accidentally using external storage for logging when required for EXST
  src/config/SPRACINGH7RF/config.h
Labels: RN: TARGET UPDATE

#12511 CONFIG: Fix blackbox
  src/config/MATEKH743/config.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#12500 Remove SPEK1024 as the default RX (set to NONE)
  src/main/cli/settings.c
  src/main/rx/ghst.c
  src/main/rx/rx.h
Labels: RN: IMPROVEMENT

#12494 CONFIG: Update FOXEERH743
  src/config/FOXEERH743/config.h
Labels: RN: TARGET UPDATE

#12493 Rename FAKE to VIRTUAL
  src/main/cli/settings.c
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_virtual.c
  src/main/drivers/accgyro/accgyro_virtual.h
  src/main/drivers/barometer/barometer_virtual.c
  src/main/drivers/barometer/barometer_virtual.h
  src/main/drivers/compass/compass_virtual.c
  src/main/drivers/compass/compass_virtual.h
  src/main/drivers/light_led.h
  src/main/fc/init.c
  src/main/io/serial_4way_avrootloader.c
  src/main/io/spektrum_rssi.c
  src/main/rx/spektrum.c
  src/main/sensors/acceleration.h
  src/main/sensors/acceleration_init.c
  src/main/sensors/barometer.c
  src/main/sensors/barometer.h
  src/main/sensors/compass.c
  src/main/sensors/gyro.c
  src/main/sensors/gyro_init.c
  src/main/target/AT32F435/target.h
  src/main/target/SITL/sitl.c
  src/main/target/SITL/target.h
  src/main/target/SITL/target.mk
  src/main/target/common_post.h
  src/main/target/common_pre.h
  src/test/Makefile
  src/test/unit/sensor_gyro_unittest.cc
  src/test/unit/target.h
Labels: RN: REFACTORING

#12513 Exclude MSP_OSD_CONFIG if USE_OSD not defined
  src/main/msp/msp.c
Labels: RN: BUGFIX, Tested

#12518 CONFIG: add BMP280 to SKYSTARSH7HD
  src/config/SKYSTARSH7HD/config.h
Labels: RN: TARGET UPDATE

#12231 Angle and Horizon Mode improvements
  src/main/blackbox/blackbox.c
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/fc/controlrate_profile.c
  src/main/fc/parameter_names.h
  src/main/fc/rc.c
  src/main/fc/rc.h
  src/main/flight/feedforward.c
  src/main/flight/feedforward.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/main/msp/msp.c
  src/test/unit/pid_unittest.cc
Labels: Ready to Merge, RN: MINOR FEATURE

#12505 Revert 12302 NVIC SPI Priority
  src/main/drivers/bus_spi.c
Labels: RN: BUGFIX

#12520 [4.4.1] FIX: Blackbox (as applied to 4.5.0)
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#12512 CONFIG: Fix VTX feature
  src/main/config/feature.h
  src/main/target/common_post.h
Labels: RN: BUGFIX

#12516 CONFIG: Add CAMERA_CONTROL if PIN defined
  src/main/target/common_post.h
Labels: RN: BUGFIX

#12508 Set DSHOT default
  src/main/pg/motor.c
  src/main/target/STM32F411/target.h
Labels: RN: IMPROVEMENT

#12515 CONFIG: Add FLASH_W25Q128FV to BETAFPVF722
  src/config/BETAFPVF722/config.h
Labels: RN: TARGET UPDATE

#12514 CONFIG: Add BMP280 to FLYWOOF411V2
  src/config/FLYWOOF411V2/config.h
Labels: RN: TARGET UPDATE

#12323 Add rainbow effect to led strip
  src/main/cli/settings.c
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
  src/main/msp/msp_protocol.h
  src/test/unit/rx_spi_expresslrs_telemetry_unittest.cc
Labels: Ready to Merge, Needs coordination with betaflight-configurator, RN: MINOR FEATURE

#12524 Fixes #12521 Add separate AAF values for ICM-42605
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
Labels: RN: BUGFIX, Tested

#12532 CONFIG: Add BMP280 to GEPRCF405
  src/config/GEPRCF405/config.h
Labels: Ready to Merge, RN: TARGET UPDATE

#12530 CONFIG: Add BMP280 to SPEEDYBEE_F745_AIO
  src/config/SPEEDYBEE_F745_AIO/config.h
Labels: Ready to Merge, RN: TARGET UPDATE

#12540 WORKFLOW: Adding call to create or update target list in API from config.h
  .github/workflows/target-creation.yml
Labels: RN: IMPROVEMENT, Build System Improvement

#12547 CONFIG: define W25Q128FV for OMNIBUSF4
  src/config/OMNIBUSF4/config.h
Labels: RN: TARGET UPDATE

#12536 CONFIG: define BMI270 for ATOMRCF405
  src/config/ATOMRCF405/config.h
Labels: RN: TARGET UPDATE

#12541 FIX: IBUS telemetry
  src/main/target/common_post.h
Labels: RN: BUGFIX

#12539 CONFIG: Register defaults for align-board
  src/config/GEPRC_F722_AIO/config.h
  src/config/IFLIGHT_BLITZ_F7_AIO/config.h
  src/config/NEUTRONRCF7AIO/config.h
  src/config/SKYSTARSF7HD/config.h
  src/config/TMOTORF4SX1280/config.h
  src/config/TMOTORF7_AIO/config.h
  src/config/TRANSTECF411HD/config.h
  src/main/sensors/boardalignment.c
Labels: Cleanup, RN: TARGET UPDATE

#12542 CONFIG: Update TODO
  src/config/GEPRCF722/config.h
  src/config/IFLIGHT_SUCCEX_E_F4/config.h
  src/config/NBD_INFINITYF4/config.h
  src/config/NOX/config.h
  src/config/OMNIBUSF4FW/config.h
  src/config/PIRXF4/config.h
  src/config/SPEEDYBEEF7MINI/config.h
  src/config/SPEEDYBEEF7MINIV2/config.h
  src/config/SPRACINGH7RF/config.h
  src/config/TRANSTECF405HD/config.h
  src/config/TRANSTECF411/config.h
  src/config/TRANSTECF411HD/config.h
  src/config/TRANSTECF7/config.h
  src/config/VGOODF722DUAL/config.h
  src/config/YUPIF4/config.h
  src/config/ZEEZWHOOP/config.h
Labels: Cleanup, RN: TARGET UPDATE

#12555 DShot zero between beacon commands for 4.4, from 12544
  src/main/drivers/dshot_command.c
  src/main/fc/core.c
  src/main/io/beeper.c
  src/main/io/beeper.h
Labels: RN: BUGFIX

#12560 Restore DShot Beacon control for 4.4
  src/main/io/beeper.c
Labels: RN: BUGFIX

#12558 Restore DShot Beacon control for 4.5
  src/main/io/beeper.c
Labels: RN: BUGFIX

#12563 Enable OSD feature if USE_OSD_SD or USE_OSD_HD is defined
  src/main/config/config.c
Labels: RN: BUGFIX

#12198 Remove getRcStickDeflection and areSticksInApModePosition
  src/main/fc/rc_controls.c
  src/main/fc/rc_controls.h
Labels: RN: REFACTORING

#12535 Fix NEUTRONRCG4AIO config file
  src/config/NEUTRONRCG4AIO/config.h
  src/main/cli/settings.c
  src/main/sensors/gyro_init.c
Labels: Ready to Merge, RN: TARGET UPDATE, Tested, Bugfix

#12510 AT32: Add AIRBOTF435 REV1.0
  src/config/AIRBOTF435/config.h
  src/main/target/AT32F435M/target.h
Labels: RN: NEW TARGET, Development Instrumentation

#12571 Remove USE_VIRTUAL_GYRO defintion for AT32F435
  src/main/target/AT32F435G/target.h
  src/main/target/AT32F435M/target.h
Labels: RN: TARGET UPDATE

#12570 AIRBOTF435 has AT32F435RMT7 processor
  src/config/AIRBOTF435/config.h
Labels: RN: TARGET UPDATE

#12528 CONFIG: Add BMP280 to TMOTORF7
  src/config/TMOTORF7/config.h
Labels: RN: TARGET UPDATE

#12572 4.4.1 Include smartport telemetry for Fport (#12314)
  src/main/target/common_post.h
Labels: RN: BUGFIX

#12359 Update RSSI_DBM to include diversity antenna in OSD element (CRSF)
  src/main/osd/osd_elements.c
  src/main/rx/crsf.c
  src/main/rx/rx.c
  src/main/rx/rx.h
Labels: RN: IMPROVEMENT

#12582 gyro_init.c remove duplicate include line for icm20689.h
  src/main/sensors/gyro_init.c
Labels: RN: REFACTORING

#12584 Enable AIRBOTF435 MAX7456
  src/config/AIRBOTF435/config.h
Labels: RN: TARGET UPDATE

#12579 CONFIG: Add ICM42688P to CRAZYBEEF4FS
  src/config/CRAZYBEEF4FS/config.h
Labels: RN: TARGET UPDATE

#12564 CONFIG: Add RUSHF7AIO
  src/config/RUSHF7AIO/config.h
Labels: RN: NEW TARGET

#12586 CONFIG: Add W25Q128FV to RUSHCORE7
  src/config/RUSHCORE7/config.h
Labels: RN: TARGET UPDATE

#12556 Add FLASH_W25M512 to EMAX_BABYHAWK_II_HD
  src/config/EMAX_BABYHAWK_II_HD/config.h
Labels: RN: TARGET UPDATE

#12588 Fix NEUTRONRCF7AIO Target Defines
  src/config/NEUTRONRCF7AIO/config.h
Labels: RN: TARGET UPDATE

#12461 Add MERCURYG4
  src/config/MERCURYG4/config.h
Labels: RN: NEW TARGET

#12489 CONFIG: Add AOCODARCF722_AIO
  src/config/AOCODARCF722_AIO/config.h
Labels: Ready to Merge, RN: NEW TARGET

#12592 Remove code comments using word retarded
  src/main/fc/rc_controls.c
  src/main/fc/rc_controls.h
Labels: RN: REFACTORING
