Repository betaflight/betaflight, pull requests merged in 2023-07, with the labels that each got.

#12929 Handle USART TX pulldown
  src/main/drivers/at32/serial_uart_at32bsp.c
  src/main/drivers/at32/serial_uart_at32f43x.c
  src/main/drivers/stm32/serial_uart_hal.c
  src/main/drivers/stm32/serial_uart_stm32f4xx.c
  src/main/drivers/stm32/serial_uart_stm32f7xx.c
  src/main/drivers/stm32/serial_uart_stm32g4xx.c
  src/main/drivers/stm32/serial_uart_stm32h7xx.c
  src/main/io/vtx_smartaudio.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#12900 GPS rescue IMU, velocity iTerm and other fixes
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_gps_rescue.c
  src/main/fc/parameter_names.h
  src/main/flight/gps_rescue.c
  src/main/flight/imu.c
  src/main/flight/pid.c
  src/main/pg/gps_rescue.c
  src/main/pg/gps_rescue.h
Labels: RN: BUGFIX, Tested

#12907 Add unfiltered gyro black box field
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox_fielddefs.h
  src/main/cli/settings.c
Labels: RN: IMPROVEMENT

#12928 add uart 6 and 7
  src/main/drivers/at32/serial_uart_at32f43x.c
Labels: RN: IMPROVEMENT

#12912 Add dshot_telemetry_start_margin setting
  src/main/cli/settings.c
  src/main/drivers/dshot_bitbang_decode.c
  src/main/pg/motor.c
  src/main/pg/motor.h
Labels: Development Instrumentation

#12913 AT32F435 camera control
  mk/mcu/STM32F4.mk
  mk/mcu/STM32F7.mk
  mk/mcu/STM32G4.mk
  mk/mcu/STM32H7.mk
  mk/source.mk
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/drivers/at32/camera_control.c
  src/main/drivers/camera_control_impl.h
  src/main/drivers/stm32/camera_control.c
  src/main/fc/init.c
  src/main/fc/rc_controls.c
  src/main/fc/tasks.c
  src/main/msp/msp.c
  src/main/target/AT32F435G/target.h
  src/main/target/AT32F435M/target.h
Labels: RN: IMPROVEMENT

#12951 Add H725 target support
  src/main/startup/system_stm32h7xx.c
  src/main/target/STM32H725/readme.txt
  src/main/target/STM32H725/target.h
  src/main/target/STM32H725/target.mk
Labels: Ready to Merge, RN: NEW TARGET, Tested

#12964 [MAINT] Add dshot_telemetry_start_margin setting (#12912)
  src/main/cli/settings.c
  src/main/drivers/dshot_bitbang_decode.c
  src/main/pg/motor.c
  src/main/pg/motor.h
Labels: Ready to Merge, RN: BUGFIX

#12969 Revert 12577 change for F4
  src/main/drivers/stm32/serial_uart_stm32f4xx.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#12971 Makefile - use -gddb2, not -gddb3 due to issues with GDB crashing.
  Makefile
Labels: Ready to Merge, Bugfix

#12977 Adding OSD quick menu
  mk/source.mk
  src/main/cli/settings.c
  src/main/cms/cms.c
  src/main/cms/cms_menu_quick.c
  src/main/cms/cms_menu_quick.h
  src/main/cms/cms_menu_rpm_limit.c
  src/main/cms/cms_menu_rpm_limit.h
  src/main/cms/cms_menu_vtx_smartaudio.c
  src/main/cms/cms_menu_vtx_tramp.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/test/unit/cms_unittest.cc
Labels: Ready to Merge, RN: MINOR FEATURE

#12986 Add default port settings for serial port functions
  src/main/io/serial.c
  src/main/io/serial.h
Labels: Ready to Merge, RN: IMPROVEMENT

#12982 Removing STM specific defines from common_pre, and other cleanups
  src/main/cli/cli.c
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/light_ws2811strip.h
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
  src/main/msp/msp.c
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32H723/target.h
  src/main/target/STM32H725/target.h
  src/main/target/STM32H730/target.h
  src/main/target/STM32H743/target.h
  src/main/target/STM32H750/target.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
  src/test/unit/ledstrip_unittest.cc
  src/test/unit/platform.h
Labels: Ready to Merge, Cleanup, Housekeeping
