Repository betaflight/betaflight, pull requests merged in 2023-10, with the labels that each got.

#13097 Fix marking of softserial port usage
  src/main/io/serial.c
Labels: Ready to Merge, RN: BUGFIX

#13108 fix ARTERY UART4 pin 'PH2&PH3'
  src/main/drivers/at32/serial_uart_at32f43x.c
Labels: Ready to Merge, RN: BUGFIX

#13072 rearrange rescue phase enum and keep Mag during landing
  src/main/flight/gps_rescue.c
Labels: Ready to Merge, RN: BUGFIX, RN: IMPROVEMENT, Tested

#13117 Removed SITL hardcoded state port number
  src/main/target/SITL/sitl.c
Labels: RN: BUGFIX

#12838 Dimmable RPM harmonics
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
  src/main/flight/rpm_filter.c
  src/main/pg/rpm_filter.c
  src/main/pg/rpm_filter.h
Labels: RN: IMPROVEMENT

#13114 Fix clang version (#13099)
  .github/workflows/ci.yml
  src/test/Makefile
Labels: Ready to Merge, Housekeeping

#13113 Check tx on MSP and GPS only
  src/main/drivers/serial.h
  src/main/drivers/serial_uart_stm32f4xx.c
  src/main/drivers/serial_uart_stm32f7xx.c
  src/main/drivers/serial_uart_stm32g4xx.c
  src/main/drivers/serial_uart_stm32h7xx.c
  src/main/io/gps.c
  src/main/msp/msp_serial.c
Labels: RN: BUGFIX

#13130 Fix buffer overflow in JETIEXBUS character reception
  src/main/rx/jetiexbus.c
Labels: RN: BUGFIX

#13132 Disable ICM426XX AFSR feature to prevent stalls
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
Labels: RN: BUGFIX, Tested

#13137 Disable ICM4268xx AFSR feature to prevent stalls
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
Labels: RN: BUGFIX, Tested

#13136 Fix buffer overflow in JETIEXBUS character reception (#13130)
  src/main/rx/jetiexbus.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#13100 Check tx on MSP and GPS only
  src/main/drivers/serial.h
  src/main/drivers/stm32/serial_uart_stm32f4xx.c
  src/main/drivers/stm32/serial_uart_stm32f7xx.c
  src/main/drivers/stm32/serial_uart_stm32g4xx.c
  src/main/drivers/stm32/serial_uart_stm32h7xx.c
  src/main/io/gps.c
  src/main/msp/msp_serial.c
Labels: Ready to Merge, RN: BUGFIX

#13145 bug fix for DMax Setpoint Factor
  src/main/flight/pid_init.c
Labels: Ready to Merge, Tested, Bugfix

#13123 Remove Special Chars from eRPM Blackbox Field
  src/main/blackbox/blackbox.c
Labels: RN: BUGFIX
