Repository betaflight/betaflight, pull requests merged in 2024-07, with the labels that each got.

#13745 [github workflow] auto-close PR's with branch named 'master'
  .github/workflows/auto-close.yml
Labels: Housekeeping

#13752 Put gyro debug axis in header
  src/main/blackbox/blackbox.c
Labels: RN: IMPROVEMENT

#13761 [4.5.1] AT32: Add PC6 and PC7 I2C pins
  src/main/drivers/at32/bus_i2c_atbsp_init.c
Labels: RN: IMPROVEMENT

#13760 at32: add PC6 and PC7 as i2c pins
  src/main/drivers/mcu/at32/bus_i2c_atbsp_init.c
Labels: RN: IMPROVEMENT

#12936 Add FLRC F-modes to ELRS SPI implementation
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/drivers/rx/rx_sx127x.c
  src/main/drivers/rx/rx_sx127x.h
  src/main/drivers/rx/rx_sx1280.c
  src/main/drivers/rx/rx_sx1280.h
  src/main/pg/rx_spi_expresslrs.c
  src/main/pg/rx_spi_expresslrs.h
  src/main/rx/expresslrs.c
  src/main/rx/expresslrs_common.c
  src/main/rx/expresslrs_common.h
  src/main/rx/expresslrs_impl.h
  src/test/unit/rx_spi_expresslrs_unittest.cc
Labels: Testing Required, RN: IMPROVEMENT

#13764 fix at32 serial bidir pp od init and smart audio
  src/main/drivers/mcu/at32/serial_uart_at32f43x.c
  src/main/drivers/mcu/stm32/serial_uart_stm32f4xx.c
  src/main/drivers/mcu/stm32/serial_uart_stm32g4xx.c
  src/main/io/vtx_smartaudio.c
Labels: RN: BUGFIX

#13768 rename fix: smoothStepUpTransition
  src/main/common/maths.h
Labels: Cleanup

#13771 [4.5.1] fix at32 serial bidir pp od init and smart audio (#13764)
  src/main/drivers/at32/serial_uart_at32f43x.c
  src/main/drivers/stm32/serial_uart_stm32f4xx.c
  src/main/drivers/stm32/serial_uart_stm32g4xx.c
  src/main/io/vtx_smartaudio.c
Labels: RN: BUGFIX, Added by Cherry-pick

#13774 Add SPI ELRS Model Match ID
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#13787 [4.5.1] Read gyro data from correct lsm6dsv16x registers
  src/main/drivers/accgyro/accgyro_spi_lsm6dsv16x.c
Labels: RN: BUGFIX

#13784 Read gyro data from correct lsm6dsv16x registers
  src/main/drivers/accgyro/accgyro_spi_lsm6dsv16x.c
Labels: RN: BUGFIX

#13778 TPA gravity factor (for wings)
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/common/maths.c
  src/main/common/maths.h
  src/main/fc/parameter_names.h
  src/main/flight/imu.c
  src/main/flight/imu.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
Labels: RN: IMPROVEMENT

#13660 Add all_configs make target to build all FC configs
  Makefile
Labels: Build System Improvement

#13707 Fix unused variable compile time error
  src/main/drivers/mcu/stm32/sdio_f7xx.c
Labels: RN: BUGFIX

#13750 Increase Number of Available Dynamic Notches to 7
  src/main/flight/dyn_notch_filter.c
  src/main/flight/dyn_notch_filter.h
  src/main/sensors/gyro_filter_impl.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT, Needs coordination with blackbox-log-viewer

#13708 Allow change of debug flags without forcing complete rebuild
  Makefile
Labels: Build System Improvement

#13789 Fix flash_scan
  src/main/io/flashfs.c
Labels: RN: BUGFIX
