Repository betaflight/betaflight, pull requests merged in 2024-12, with the labels that each got.

#14054 Fixed FLIGHT_MODE(PASSTHRU_MODE) not displayed in OSD
  src/main/osd/osd_elements.c
  src/main/telemetry/crsf.c
Labels: RN: BUGFIX

#14055 Adding check for speed optimised source validity
  Makefile
  mk/source.mk
  src/platform/APM32/mk/APM32F4.mk
  src/platform/AT32/mk/AT32F4.mk
  src/platform/PICO/mk/PICO.mk
  src/platform/SIMULATOR/dma_reqmap_mcu.h
  src/platform/SIMULATOR/link/sitl.ld
  src/platform/SIMULATOR/mk/SITL.mk
  src/platform/SIMULATOR/platform_mcu.h
  src/platform/SIMULATOR/sitl.c
  src/platform/SIMULATOR/target/SITL/README.md
  src/platform/SIMULATOR/target/SITL/target.h
  src/platform/SIMULATOR/target/SITL/target.mk
  src/platform/SIMULATOR/timer_def.h
  src/platform/SIMULATOR/udplink.c
  src/platform/SIMULATOR/udplink.h
  src/platform/SITL/mk/SITL.mk
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
Labels: RN: REFACTORING

#14057 Fix arming disable flag and OSD warning buffer size
  src/main/cli/cli.c
  src/main/fc/runtime_config.c
  src/main/fc/runtime_config.h
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd_warnings.c
  src/main/osd/osd_warnings.h
Labels: Ready to Merge, RN: BUGFIX

#14065 Support for apple silicon (M-series) chip. (Right version of Arm GNU toolchain)
  mk/tools.mk
Labels: Build System Improvement

#14070 AT32 SD card support
  src/main/drivers/bus_spi.h
  src/main/drivers/sdcard_impl.h
  src/main/drivers/sdcard_spi.c
  src/main/drivers/sdcard_standard.h
  src/platform/AT32/bus_spi_at32bsp.c
Labels: RN: BUGFIX

#14063 Adding 'size optimised' file list validity check
  Makefile
  mk/source.mk
  src/platform/APM32/mk/APM32F4.mk
  src/platform/AT32/mk/AT32F4.mk
  src/platform/SIMULATOR/target/SITL/target.mk
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
Labels: Build System Improvement

#14072 Fix PPM feature
  src/main/config/feature.c
Labels: RN: BUGFIX

#14078 Adjust BOX3D boxname
  src/main/msp/msp_box.c
Labels: RN: REFACTORING

#14013 PreArm allow Re-Arm (without resetting PreArm AUX)
  src/main/cli/settings.c
  src/main/fc/core.c
  src/main/fc/parameter_names.h
  src/main/fc/rc_controls.c
  src/main/fc/rc_controls.h
Labels: RN: MINOR FEATURE

#14081 [4.5.2] AT32 SD card support
  src/main/drivers/at32/bus_spi_at32bsp.c
  src/main/drivers/bus_spi.h
  src/main/drivers/sdcard_impl.h
  src/main/drivers/sdcard_spi.c
  src/main/drivers/sdcard_standard.h
Labels: RN: BUGFIX

#14079 MAKE - improvement
  mk/tools.mk
Labels: RN: BUGFIX, Build System Improvement

#14080 Update cloud build defines
  src/main/msp/msp_build_info.c
  src/main/msp/msp_build_info.h
Labels: Tested, Build System Improvement

#14088 Adjust info/warning status
  src/main/osd/osd_elements.c
  src/main/osd/osd_warnings.c
Labels: RN: IMPROVEMENT

#14091 Don't handle non-MSP characters on VTX MSP port
  src/main/io/displayport_msp.c
  src/main/io/displayport_msp.h
  src/main/msp/msp_serial.c
Labels: RN: BUGFIX

#14082 ./src/utils/ trim trailing whitestpaces
  src/main/msp/msp_build_info.c
  src/utils/dfuse-pack.py
  src/utils/make-build-info.py
Labels: Cleanup

#14096 Improve serial_post.h
  src/main/drivers/serial_softserial.c
  src/main/drivers/serial_uart.c
  src/main/io/serial.h
  src/main/io/serial_resource.c
  src/main/target/serial_post.h
  src/utils/gen-serial-j2.py
  src/utils/templates/serial_post.h
Labels: RN: IMPROVEMENT

#14038 opticalflow mt sensor added
  mk/source.mk
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/config/feature.c
  src/main/config/feature.h
  src/main/drivers/opticalflow/opticalflow.h
  src/main/drivers/rangefinder/rangefinder_lidarmt.c
  src/main/drivers/rangefinder/rangefinder_lidarmt.h
  src/main/fc/tasks.c
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
  src/main/msp/msp_protocol_v2_common.h
  src/main/pg/pg_ids.h
  src/main/scheduler/scheduler.h
  src/main/sensors/initialisation.c
  src/main/sensors/opticalflow.c
  src/main/sensors/opticalflow.h
  src/main/sensors/sensors.h
Labels: RN: IMPROVEMENT

#13685 STM32H5 timer definitions
  src/platform/STM32/timer_stm32h5xx.c
Labels: Help Wanted, H5

#14042 Add RANGEFINDER and OPTICALFLOW MT build option
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: Build System Improvement

#14097 Refactoring of PR 13050 - support for custom OSD messages from external device
  mk/source.mk
  src/main/blackbox/blackbox.c
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/config/config.c
  src/main/config/config.h
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/pg/pilot.c
  src/main/pg/pilot.h
  src/test/unit/cli_unittest.cc
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#13776 LED Dimmer
  src/main/fc/rc_adjustments.c
  src/main/fc/rc_adjustments.h
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
  src/test/unit/rc_controls_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: MINOR FEATURE

#14099 Ditching default target for `make` in favour of `make all`
  Makefile
Labels: RN: REFACTORING, Build System Improvement

#14101 Position hold depends on GPS
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#14105 PICO changes
  src/platform/PICO/bus_spi_pico.c
  src/platform/PICO/io_def_generated.h
  src/platform/PICO/io_pico.c
  src/platform/PICO/link/pico_rp2350.ld
  src/platform/PICO/mk/PICO.mk
  src/platform/PICO/pico/config_autogen.h
  src/platform/PICO/pico/platform.h
  src/platform/PICO/pico/version.h
  src/platform/PICO/platform_mcu.h
  src/platform/PICO/serial_uart_impl.h
  src/platform/PICO/serial_uart_pico.c
  src/platform/PICO/system.c
  src/platform/PICO/target/RP2350/target.h
  src/platform/PICO/target/RP2350/target.mk
  src/platform/PICO/target/RP2350B/.exclude
  src/platform/PICO/target/RP2350B/target.h
  src/platform/PICO/target/RP2350B/target.mk
Labels: RN: TARGET UPDATE

#14094 Adding support for UART0
  src/main/cli/cli.c
  src/main/drivers/serial_pinconfig.c
  src/main/drivers/serial_tcp.c
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart_impl.h
  src/main/io/displayport_msp.c
  src/main/io/serial.c
  src/main/io/serial.h
  src/main/io/serial_resource.c
  src/main/msp/msp.c
  src/main/pg/serial_uart.c
  src/main/target/common_defaults_post.h
  src/test/unit/cli_unittest.cc
Labels: Needs coordination with betaflight-configurator, RN: REFACTORING

#14113 update serTcpOpen declaration to fix compile errors
  src/main/drivers/serial_tcp.h
Labels: RN: BUGFIX

#14119 Enabling UART0 index for RP2350
  src/platform/PICO/platform_mcu.h
Labels: RPI

#14087 Adds missing ACCGYRO defines and remove legacy drivers
  mk/source.mk
  src/main/cli/settings.c
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu3050.c
  src/main/drivers/accgyro/accgyro_mpu3050.h
  src/main/drivers/accgyro/accgyro_mpu6500.c
  src/main/drivers/accgyro/accgyro_spi_icm20689.c
  src/main/drivers/accgyro/accgyro_spi_mpu6500.c
  src/main/drivers/accgyro/accgyro_spi_mpu9250.c
  src/main/drivers/accgyro/legacy/accgyro_adxl345.c
  src/main/drivers/accgyro/legacy/accgyro_adxl345.h
  src/main/drivers/accgyro/legacy/accgyro_bma280.c
  src/main/drivers/accgyro/legacy/accgyro_bma280.h
  src/main/drivers/accgyro/legacy/accgyro_l3g4200d.c
  src/main/drivers/accgyro/legacy/accgyro_l3g4200d.h
  src/main/drivers/accgyro/legacy/accgyro_lsm303dlhc.c
  src/main/drivers/accgyro/legacy/accgyro_lsm303dlhc.h
  src/main/drivers/accgyro/legacy/accgyro_mma845x.c
  src/main/drivers/accgyro/legacy/accgyro_mma845x.h
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/acceleration_init.c
  src/main/sensors/acceleration_init.h
  src/main/sensors/gyro_init.c
  src/main/target/common_post.h
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT, Tested, Needs coordination with blackbox-log-viewer

#14114 Update actions to ubuntu-latest
  .github/workflows/auto-close.yml
  .github/workflows/build-release.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/pr-cloud-comment.yml
Labels: Build System Improvement
