Repository betaflight/betaflight, pull requests merged in 2024-05, with the labels that each got.

#13615 Update README.md
  README.md
Labels: Housekeeping

#13599 battery - fix BATTERY_NOT_PRESENT detection, detection logic change
  src/main/sensors/battery.c
  src/main/sensors/voltage.c
  src/main/sensors/voltage.h
Labels: RN: BUGFIX, Tested

#13404 New led functions gps bar battery bar altitude
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
  src/test/unit/ledstrip_unittest.cc
Labels: RN: MINOR FEATURE, Pinned

#13558 Add CRSF vario sensor support
  src/main/rx/crsf_protocol.h
  src/main/telemetry/crsf.c
  src/test/unit/rx_spi_expresslrs_telemetry_unittest.cc
  src/test/unit/telemetry_crsf_msp_unittest.cc
  src/test/unit/telemetry_crsf_unittest.cc
Labels: RN: IMPROVEMENT

#13623 [4.5.1] battery - fix BATTERY_NOT_PRESENT detection, detection logic change
  src/main/sensors/battery.c
  src/main/sensors/voltage.c
  src/main/sensors/voltage.h
Labels: RN: BUGFIX

#13616 Fix ICM20469
  src/main/drivers/accgyro/accgyro_spi_icm20649.c
  src/main/sensors/acceleration_init.c
  src/main/sensors/gyro_init.c
Labels: RN: BUGFIX, Tested

#13597 timers - remove obsolete defines from SITL and unittests
  src/main/target/SITL/target.h
  src/test/unit/target.h
Labels: Cleanup

#13595 Remove canvas configuration in cli
  src/main/cli/settings.c
Labels: For Discussion, Cleanup

#13631 minor define fixes found during documentation work
  src/main/config/config.c
  src/main/drivers/accgyro_legacy/accgyro_lsm303dlhc.h
  src/main/drivers/stm32/vcpf4/usb_conf.h
  src/main/fc/init.c
Labels: RN: BUGFIX

#13614 Update CRSF spec
  src/main/rx/crsf_protocol.h
Labels: RN: BUGFIX

#13057 Display one of four logos on arming
  src/main/cli/settings.c
  src/main/osd/osd.c
  src/main/osd/osd.h
Labels: RN: IMPROVEMENT

#13633 Remove superfluous checks of useDshotTelemetry
  src/main/drivers/motor.c
  src/main/fc/core.c
Labels: RN: BUGFIX

#13634 [4.5.1] Remove superfluous checks of useDshotTelemetry
  src/main/drivers/motor.c
  src/main/fc/core.c
Labels: RN: BUGFIX

#13639 GPS Rescue using MSP is not getting Velocity to Home
  src/main/io/gps.c
Labels: RN: BUGFIX

#13492 Refactor beeper
  src/main/io/beeper.c
  src/main/io/beeper.h
Labels: REFACTORING

#13610 beeper - minor refactoring
  src/main/cli/cli.c
  src/main/io/beeper.h
Labels: REFACTORING

#13644 [4.5.1] Fix GPS Rescue using MSP is not getting Velocity to Home (#13639)
  src/main/io/gps.c
Labels: RN: BUGFIX

#13494 Improve features (+ cli)
  src/main/cli/cli.c
  src/main/config/config.c
  src/main/config/feature.c
  src/main/config/feature.h
Labels: RN: IMPROVEMENT

#11171 Tune huffman table to save nearly 500B
  src/main/common/huffman.c
  src/main/common/huffman.h
  src/main/common/huffman_table.c
Labels: RN: IMPROVEMENT

#13608 Do not enable features by default
  src/main/config/config.c
Labels: RN: BUGFIX

#13626 Add MSP support for gyro_cal_on_first_arm
  src/main/msp/msp.c
  src/test/unit/huffman_unittest.cc
Labels: RN: MINOR FEATURE

#13596 build - trigger rebuild on change of most flag change
  Makefile
Labels: Build System Improvement

#12286 Update ARM SDK
  Makefile
  mk/tools.mk
  src/main/drivers/flash.c
Labels: Build System Improvement

#13659 Fix Wstringop-overflow warning on latest ARM SDK
  src/main/drivers/dma_common.c
Labels: RN: BUGFIX
