Repository betaflight/betaflight, pull requests merged in 2024-08, with the labels that each got.

#13800 Add OSD display of 2nd block of debug values
  src/main/cli/settings.c
  src/main/cms/cms_menu_osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: RN: IMPROVEMENT

#13799 Add DEBUG_TASK mode
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/pg/scheduler.c
  src/main/pg/scheduler.h
  src/main/scheduler/scheduler.c
Labels: Needs coordination with betaflight-configurator, RN: MINOR FEATURE, Needs coordination with blackbox-log-viewer

#13798 Piecewise linear interpolation routine
  mk/source.mk
  src/main/common/pwl.c
  src/main/common/pwl.h
  src/test/Makefile
  src/test/unit/pwl_unittest.cc
Labels: RN: MINOR FEATURE

#13803 Auto-disarm on landing impact
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/fc/core.h
  src/main/fc/parameter_names.h
  src/main/flight/gps_rescue.c
  src/main/flight/imu.c
  src/main/flight/mixer.c
  src/main/flight/mixer.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/main/pg/gps_rescue.c
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/test/unit/pid_unittest.cc
Labels: Ready to Merge, Needs coordination with betaflight-configurator, Needs coordination with blackbox-log-viewer

#13818 build - remove -Wpedantic
  Makefile
Labels: Build System Improvement

#13815 FIX: make: Circular configs <- configs dependency dropped. #13695
  Makefile
Labels: RN: BUGFIX

#13814 Fix telemetry for Spektrum/SRXL
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#13820 [4.5.2] FIX: telemetry for Spektrum/SRXL (#13814)
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: BUGFIX, Added by Cherry-pick

#13769 Modify STM32F405 UID Address for MSC Enumeration
  src/main/drivers/mcu/stm32/usbd_msc_desc.c
Labels: RN: BUGFIX

#13826 Fix searching a resource
  src/main/cli/cli.c
Labels: RN: BUGFIX

#13825 Add MCU ID to blackbox
  src/main/blackbox/blackbox.c
Labels: RN: IMPROVEMENT, Needs coordination with blackbox-log-viewer

#13827 [4.5.2] FIX: Modify STM32F405 UID Address for MSC Enumeration (#13769)
  src/main/drivers/stm32/usbd_msc_desc.c
Labels: RN: BUGFIX, Added by Cherry-pick

#13637 Reschedule stats saving on disarm, if quad still moving
  src/main/cli/settings.c
  src/main/fc/stats.c
  src/main/pg/stats.c
  src/main/pg/stats.h
Labels: RN: IMPROVEMENT

#13831 bbx 3d speed when gps_use_3d_speed==true
  src/main/blackbox/blackbox.c
  src/test/Makefile
Labels: RN: BUGFIX

#13835 Re-name ezDisarm variables and tidying up
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/fc/parameter_names.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/test/unit/pid_unittest.cc
Labels: Tested, RN: REFACTORING

#13822 Fix d adjustment
  src/main/fc/rc_adjustments.c
  src/test/unit/rc_controls_unittest.cc
Labels: RN: BUGFIX

#13813 Split OSD element rendering into draw and display states
  src/main/osd/osd.c
  src/main/osd/osd_elements.c
  src/main/osd/osd_elements.h
  src/main/scheduler/scheduler.c
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: RN: BUGFIX, Tested

#13834 CLEANUP: Removing source wild cards from makefiles
  mk/mcu/APM32F4.mk
  mk/mcu/AT32F4.mk
  mk/mcu/STM32F4.mk
  mk/mcu/STM32G4.mk
  mk/mcu/STM32H7.mk
Labels: RN: REFACTORING

#13841 Fix incorrect timer channel comments TIM2_CH1
  src/main/drivers/mcu/stm32/timer_stm32f7xx.c
Labels: Bugfix

#13576 Feedforward improvements for 4.6
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
  src/main/fc/rc.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/test/unit/pid_unittest.cc
Labels: RN: IMPROVEMENT, Tested, Needs coordination with blackbox-log-viewer

#13848 Disable SPA for angle mode - fix (for wings)
  src/main/flight/pid.c
Labels: RN: BUGFIX

#12870 GPS GPS_home refactor
  src/main/blackbox/blackbox.c
  src/main/fc/gps_lap_timer.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/telemetry/ltm.c
  src/main/telemetry/mavlink.c
  src/test/unit/blackbox_unittest.cc
Labels: In Development, RN: REFACTORING

#13805 Hyperbolic PID multiplier curve (for wings)
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/fc/parameter_names.h
  src/main/flight/mixer.c
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/test/Makefile
  src/test/unit/pid_unittest.cc
Labels: RN: MINOR FEATURE

#13862 Fix angle mode rate profile change bug
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
Labels: RN: BUGFIX, Tested

#13860 if USE_WING is defined then define also ADVANCED_TPA and SERVOS
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#13838 Makefile - remove -j0
  Makefile
  mk/config.mk
Labels: Build System Improvement

#13839 [4.5.2] Split OSD element rendering into draw and display states (#13813)
  src/main/osd/osd.c
  src/main/osd/osd_elements.c
  src/main/osd/osd_elements.h
  src/main/scheduler/scheduler.c
  src/test/unit/link_quality_unittest.cc
  src/test/unit/osd_unittest.cc
Labels: RN: BUGFIX, Added by Cherry-pick

#13865 [4.5.2] version bump
  src/main/build/version.h
Labels: Housekeeping

#13864 [4.5.2] Fix angle mode rate change
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
Labels: RN: BUGFIX, Added by Cherry-pick
