Repository betaflight/betaflight, pull requests merged in 2024-04, with the labels that each got.

#13373 Improve IMU responsiveness, refactor
  src/main/common/vector.h
  src/main/flight/imu.c
  src/test/unit/flight_imu_unittest.cc
Labels: RN: BUGFIX, Tested

#13487 mag cal improvements
  src/main/sensors/compass.c
Labels: Ready to Merge, RN: IMPROVEMENT, Tested

#13411 Add ez_landing_speed parameter
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
  src/main/flight/mixer.c
  src/main/flight/mixer_init.c
  src/main/flight/mixer_init.h
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Ready to Merge, RN: BUGFIX

#13477 Use PDOP consistently, since it replaces HDOP
  src/main/cli/settings.c
  src/main/flight/position.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
  src/main/telemetry/frsky_hub.c
  src/main/telemetry/ghst.c
  src/main/telemetry/smartport.c
  src/main/telemetry/srxl.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#13503 Fix config write
  src/main/config/config_eeprom.h
  src/main/config/config_streamer.c
  src/main/config/config_streamer.h
Labels: RN: BUGFIX, Tested

#13398 Fix typo in [tools.mk]
  mk/tools.mk
Labels: Cleanup

#13397 Update softprops/action-gh-release
  .github/workflows/nightly.yml
Labels: Build System Improvement

#13495 Blackbox - use llog2 instead of LOG2
  src/main/blackbox/blackbox.c
Labels: RN: BUGFIX

#13509 Baro and Mag driver check for I2C bus being busy
  src/main/drivers/barometer/barometer.h
  src/main/drivers/barometer/barometer_2smpb_02b.c
  src/main/drivers/barometer/barometer_bmp085.c
  src/main/drivers/barometer/barometer_bmp280.c
  src/main/drivers/barometer/barometer_bmp388.c
  src/main/drivers/barometer/barometer_dps310.c
  src/main/drivers/barometer/barometer_lps.c
  src/main/drivers/barometer/barometer_lps22df.c
  src/main/drivers/barometer/barometer_ms5611.c
  src/main/drivers/barometer/barometer_qmp6988.c
  src/main/drivers/barometer/barometer_virtual.c
  src/main/drivers/bus_i2c_busdev.c
  src/main/drivers/compass/compass_ak8975.c
  src/main/drivers/compass/compass_hmc5883l.c
  src/main/drivers/compass/compass_ist8310.c
  src/main/drivers/compass/compass_lis2mdl.c
  src/main/drivers/compass/compass_lis3mdl.c
  src/main/drivers/compass/compass_qmc5883l.c
Labels: Testing Required, RN: BUGFIX, Tested

#13521 Fix for ITCM overflow for F722
  src/main/common/sdft.c
  src/main/drivers/rx/rx_sx1280.c
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/common_post.h
Labels: RN: BUGFIX, Fixes broken build

#13496 Barometer - remove unnecessary static variables
  src/main/sensors/barometer.c
Labels: Cleanup, Tested, RN: REFACTORING

#13516 new flash added: py25q128ha
  src/main/drivers/flash_m25p16.c
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#13549 make mpuIntExtiHandler() static (#13520)
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
Labels: REFACTORING

#13541 I2C - unify i2cUnstick implementation, improve unstick a bit
  mk/source.mk
  src/main/drivers/at32/bus_i2c_atbsp_init.c
  src/main/drivers/bus_i2c_utils.c
  src/main/drivers/bus_i2c_utils.h
  src/main/drivers/stm32/bus_i2c_hal_init.c
  src/main/drivers/stm32/bus_i2c_stm32f4xx.c
Labels: REFACTORING

#13547 set default of spec prearm screen to false if race pro not defined
  src/main/osd/osd.c
Labels: Cleanup

#13537 hmc5883l - fix wrong register value
  src/main/drivers/compass/compass_hmc5883l.c
Labels: BUG, Ready to Merge, RN: BUGFIX

#13546 STM32H725 - fix USE_SOFTSERIAL
  src/main/target/STM32H725/target.h
Labels: Ready to Merge, RN: BUGFIX

#13551 Fix clang unitests
  src/main/cli/cli.c
  src/main/scheduler/scheduler.c
  src/main/telemetry/hott.c
  src/test/Makefile
  src/test/unit/arming_prevention_unittest.cc
  src/test/unit/baro_bmp085_unittest.cc
  src/test/unit/baro_bmp280_unittest.cc
  src/test/unit/baro_bmp388_unittest.cc
  src/test/unit/blackbox_unittest.cc
  src/test/unit/flight_imu_unittest.cc
  src/test/unit/ledstrip_unittest.cc
  src/test/unit/link_quality_unittest.cc
  src/test/unit/rx_ranges_unittest.cc
  src/test/unit/rx_rx_unittest.cc
  src/test/unit/scheduler_unittest.cc
  src/test/unit/telemetry_crsf_msp_unittest.cc
  src/test/unit/unittest_displayport.h
  src/test/unit/vtx_unittest.cc
Labels: Build System Improvement

#13535 Fix setting pid denom
  src/main/config/config.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#13555 Make w25n01g FLASH driver non-blocking for SPI
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/flash_w25n01g.c
Labels: RN: BUGFIX

#13570 Fix debug mode DEBUG_ATTITUDE
  src/main/flight/imu.c
Labels: RN: BUGFIX

#13565 Fix index and ability to configure LPUART_RX due to typo
  src/main/cli/cli.c
  src/main/drivers/serial.h
Labels: Cleanup

#13554 Improve unittest build system
  src/main/cli/cli.c
  src/main/common/utils.h
  src/main/pg/pg.h
  src/test/Makefile
  src/test/unit/cli_unittest.cc
  src/test/unit/ledstrip_unittest.cc
  src/test/unit/pg.ld
  src/test/unit/pg_unittest.cc
  src/test/unit/rc_controls_unittest.cc
  src/test/unit/rx_ibus_unittest.cc
  src/test/unit/rx_spi_expresslrs_unittest.cc
  src/test/unit/rx_spi_spektrum_unittest.cc
  src/test/unit/rx_sumd_unittest.cc
  src/test/unit/scheduler_stubs.c
  src/test/unit/scheduler_stubs.h
  src/test/unit/scheduler_unittest.cc
  src/test/unit/telemetry_ibus_unittest.cc
Labels: Bugfix, Build System Improvement

#13562 Nonblocking w25n01g code tidy up
  src/main/drivers/bus_spi.c
  src/main/drivers/flash_w25n01g.c
Labels: RN: BUGFIX

#13564 Fix pointer alignment to 8 bytes for MacOS unit tests
  src/main/cli/settings.h
  src/main/cms/cms_types.h
  src/main/pg/pg.h
Labels: Bugfix, Build System Improvement

#13561 Use clang 15 as default
  .github/workflows/ci.yml
  src/test/Makefile
Labels: Build System Improvement

#13572 Remove functionality to enter flash bootloader by sending 'F' on a UART configued for MSP.
  src/main/msp/msp_serial.c
Labels: RN: BUGFIX

#13540 Fix smartport over softserial using override
  src/main/io/serial.c
Labels: RN: BUGFIX

#13529 Sync usbd_product_string behavior
  src/main/target/AT32F435G/target.h
  src/main/target/AT32F435M/target.h
  src/main/target/STM32F405/target.h
  src/main/target/STM32F411/target.h
  src/main/target/STM32F446/target.h
  src/main/target/STM32F745/target.h
  src/main/target/STM32F7X2/target.h
  src/main/target/STM32G47X/target.h
  src/main/target/STM32H743/target.h
Labels: RN: TARGET UPDATE, Pinned

#13584 Fix W25N01G lockup when using QUAD/OCTO SPI
  src/main/drivers/flash_w25n01g.c
Labels: RN: BUGFIX, Tested

#13589 Use the cached value of useDshotTelemetry to ensure consistent runtime use if dshot_bidir is changed
  src/main/blackbox/blackbox.c
  src/main/drivers/dshot.c
  src/main/drivers/dshot.h
  src/main/drivers/motor.c
  src/main/fc/core.c
  src/main/flight/mixer.c
  src/main/flight/mixer_init.c
  src/main/flight/rpm_filter.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/osd/osd_elements.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#13498 Update EEPROM version for 4.5
  src/main/config/config_eeprom.h
Labels: Housekeeping, RN: IGNORE

#13499 Update version to 4.6
  src/main/build/version.h
Labels: Housekeeping, RN: IGNORE

#13604 Fix stm32h730 hardcoded target IO
  src/main/target/STM32H730/target.h
Labels: RN: TARGET UPDATE

#13600 Bump patch level to 4.5.1
  src/main/build/version.h
Labels: Housekeeping

#13605 Fix hard-coded TARGET_IO_PORT* defines.
  src/main/target/STM32H730/target.h
Labels: RN: TARGET UPDATE

#13609 cppcheck - minor problems fixed
  src/main/cli/cli.c
  src/main/drivers/light_ws2811strip.c
  src/main/drivers/stm32/adc_stm32h7xx.c
  src/main/io/beeper.h
  src/main/io/serial_4way.c
  src/main/io/spektrum_rssi.c
  src/main/rx/srxl2.c
Labels: REFACTORING
