Repository betaflight/betaflight, pull requests merged in 2024-11, with the labels that each got.

#14002 [4.5.2] Make three attempts to not only write to FLASH, but also validate it
  src/main/config/config_eeprom.c
Labels: RN: BUGFIX

#13929 Yaw type rudder/diff_thrust for TPA calculations (for wings)
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/fc/parameter_names.h
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: RN: MINOR FEATURE

#13987 Add PRBS checking of BB FLASH with USE_FLASH_TEST_PRBS
  src/main/blackbox/blackbox.c
  src/main/drivers/flash/flash_w25n.c
  src/main/io/flashfs.c
Labels: RN: MINOR FEATURE

#14007 Serial refactor fix
  src/main/drivers/serial.h
  src/main/drivers/serial_pinconfig.c
  src/main/drivers/serial_uart_pinconfig.c
  src/main/io/serial.c
  src/main/io/serial.h
  src/main/msp/msp_serial.c
  src/main/rx/spektrum.c
  src/platform/APM32/usb/vcp/serial_usb_vcp.c
  src/platform/AT32/serial_usb_vcp_at32f4.c
  src/platform/STM32/serial_usb_vcp.c
Labels: RN: BUGFIX

#13995 Change default I2C adddress for IST8310
  src/main/drivers/compass/compass_ist8310.c
Labels: RN: IMPROVEMENT

#14009 Angle pitch offset (for wings)
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Ready to Merge, RN: IMPROVEMENT

#13996 Chainable vector operations
  src/main/common/vector.c
  src/main/common/vector.h
Labels: Ready to Merge, RN: REFACTORING

#14015 Revert restriction of reading across page boundary
  src/main/io/flashfs.c
Labels: RN: BUGFIX

#13980 MSP Range finder added
  mk/source.mk
  src/main/cli/settings.c
  src/main/drivers/rangefinder/rangefinder_lidarmt.c
  src/main/drivers/rangefinder/rangefinder_lidarmt.h
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_common.h
  src/main/sensors/rangefinder.c
  src/main/sensors/rangefinder.h
Labels: RN: IMPROVEMENT

#13926 Driver for CADDX camera GM3 gimbal
  mk/source.mk
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/fc/init.c
  src/main/fc/rc_controls.c
  src/main/fc/tasks.c
  src/main/io/gimbal_control.c
  src/main/io/gimbal_control.h
  src/main/io/serial.h
  src/main/pg/gimbal.c
  src/main/pg/gimbal.h
  src/main/pg/pg_ids.h
  src/main/scheduler/scheduler.h
Labels: RN: MAJOR FEATURE

#14010 TPA mode PDS + Wing setpoint attenuation (for wings)
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/flight/pid.c
  src/main/flight/pid.h
Labels: Rebase Required, RN: MAJOR FEATURE

#14012 Logging of the S -term values in blackbox for Fixed wings.
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox_fielddefs.h
Labels: Ready to Merge, RN: IMPROVEMENT, Needs coordination with blackbox-log-viewer

#14020 Added flight IMU pitch, roll, yaw attitudes to blackbox log
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox_fielddefs.h
  src/main/cli/settings.c
  src/main/flight/imu.c
  src/main/flight/imu.h
  src/test/unit/flight_imu_unittest.cc
Labels: RN: IMPROVEMENT

#14044 Adding common source location in ./src/platform
  Makefile
  lib/main/pico-sdk/rp2_common/cmsis/stub/CMSIS/Core/Include/m-profile/armv8m_mpu.h
  mk/source.mk
  src/main/drivers/bus.h
  src/main/drivers/dma_reqmap.h
  src/main/drivers/flash/flash.c
  src/main/drivers/io.h
  src/main/drivers/system.h
  src/main/drivers/timer.h
  src/main/platform.h
  src/platform/APM32/mk/APM32F4.mk
  src/platform/APM32/platform_mcu.h
  src/platform/AT32/mk/AT32F4.mk
  src/platform/AT32/platform_mcu.h
  src/platform/PICO/platform_mcu.h
  src/platform/PICO/target/RP2350/target.h
  src/platform/SITL/mk/SITL.mk
  src/platform/SITL/platform_mcu.h
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
  src/platform/STM32/platform_mcu.h
  src/platform/STM32/startup/system_stm32h7xx.c
  src/platform/common/stm32/system.c
  src/test/unit/platform.h
Labels: RN: REFACTORING

#14039 Bump ARM SDK to version 13.3.rel1
  mk/tools.mk
Labels: Build System Improvement

#14036 Add Winbond W25Q512J support
  src/main/drivers/flash/flash_m25p16.c
Labels: Ready to Merge, RN: IMPROVEMENT, Tested

#14051 ./src/platform stage 3
  Makefile
  mk/source.mk
  src/platform/APM32/mk/APM32F4.mk
  src/platform/AT32/mk/AT32F4.mk
  src/platform/SITL/mk/SITL.mk
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
  src/test/Makefile
  src/test/unit/io_serial_unittest.cc
Labels: RN: REFACTORING

#13010 Collision Detection
  src/main/flight/imu.c
  src/main/flight/pid.c
  src/main/osd/osd.c
  src/main/sensors/acceleration.c
  src/main/sensors/acceleration.h
  src/main/sensors/acceleration_init.c
  src/main/sensors/acceleration_init.h
Labels: RN: MINOR FEATURE

#14052 Workaround: SERIAL_CHECK_TX is broken on F7
  src/main/io/gps.c
  src/main/msp/msp_serial.c
Labels: Ready to Merge, RN: BUGFIX
