Repository betaflight/betaflight, pull requests merged in 2024-01, with the labels that each got.

#13253 Increasing frequency of MSP protocol in SITL
  src/main/target/SITL/sitl.c
Labels: RN: BUGFIX

#13250 Adding a few more gates in common post to assist in build errors.
  src/main/target/common_post.h
Labels: Cleanup

#13260 Increase EEPROM CONFIG version to force a configuration reset.
  src/main/config/config_eeprom.h
Labels: Bugfix, RN: IGNORE

#13264 Fix missing #undef in common_post.h for GHST
  src/main/target/common_post.h
Labels: Cleanup

#13248 Fix missing GPS PG parameter
  src/main/pg/gps.c
Labels: RN: BUGFIX

#13267 Fix CLI command "bind_rx" for CRSF
  src/main/cli/cli.c
  src/main/rx/rx_bind.c
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#13277 Add timeout to serial four way interface for ESC programming
  src/main/drivers/at32/serial_usb_vcp_at32f4.c
  src/main/io/serial_4way.c
Labels: RN: BUGFIX

#13270 Fix F7X2 AXIM flash region
  src/link/stm32_flash_f722.ld
Labels: RN: BUGFIX

#13273 Rename USE_QUICK_OSD_MENU
  src/main/cli/settings.c
  src/main/cms/cms.c
  src/main/cms/cms_menu_quick.c
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#13286 Fix ESC-Sensor RPM
  src/main/drivers/dshot.c
  src/main/fc/init.c
Labels: RN: BUGFIX, Tested

#13287 BLHeliSuite32 holds 4wayif code in indefinite loop waiting for ESC so remove timeout
  src/main/io/serial_4way.c
Labels: RN: BUGFIX, Tested

#13304 Make high rate IMU DcmKp change relative to user value
  src/main/flight/imu.c
Labels: RN: BUGFIX

#13303 Do not permit MSP on softserial ports as the load on the CPU is too great
  src/main/config/config.c
  src/main/io/serial.c
  src/main/io/serial.h
Labels: Tested, RN: SAFETY IMPROVEMENT

#13320 Fix OSD defaults based on SD/HD
  src/main/fc/init.c
  src/main/msp/msp.c
  src/main/osd/osd.c
  src/main/pg/vcd.c
Labels: RN: BUGFIX, Tested

#13315 Enable PINIO if PIN defined in config
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: BUGFIX

#13325 Set OSD elements to HD defaults if build includes USE_OSD_HD
  src/main/osd/osd.c
Labels: Cleanup

#13336 Fix unit test build under aarch64 Linux
  src/test/unit/cms_unittest.cc
Labels: Fixes broken build

#13335 Install linux tools for appropriate architecture
  mk/tools.mk
Labels: Build System Improvement
