Repository betaflight/betaflight, pull requests merged in 2024-02, with the labels that each got.

#13328 Do not return MSP_RESULT_ERROR when succesful
  src/main/msp/msp.c
Labels: RN: BUGFIX

#13352 Ensure MSP channel data is valid
  src/main/rx/msp_override.c
Labels: RN: BUGFIX

#13346 Allow overriding the spi clock speed for icm42688
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
Labels: RN: BUGFIX

#13356 Permit 8kHz PID loop on F405 overclocked to 216MHz
  src/main/config/config.c
  src/main/target/STM32F405/target.h
Labels: RN: TARGET UPDATE

#13347 Add gate to HD OSD elements
  src/main/osd/osd_elements.c
Labels: Cleanup

#13337 TPA_LOW tidy up
  src/main/cms/cms_menu_imu.c
Labels: Ready to Merge, RN: BUGFIX

#13339 Use fixed LED color table in RACE / BEACON LED profiles
  src/main/io/ledstrip.c
Labels: RN: BUGFIX

#13364 For now disable 4way-if timeout
  src/main/io/serial_4way.c
Labels: Testing Required, Bugfix

#13363 Naming LED Strip overlay rates
  src/main/io/ledstrip.c
  src/main/io/ledstrip.h
Labels: RN: BUGFIX

#13330 Use cpu_late_10ths_percent_limit to set limit on % of late tasks in 10th of a %
  src/main/cli/settings.c
  src/main/fc/core.c
  src/main/osd/osd.h
  src/main/osd/osd_warnings.c
  src/main/pg/scheduler.c
  src/main/pg/scheduler.h
  src/main/scheduler/scheduler.c
  src/main/scheduler/scheduler.h
  src/test/unit/arming_prevention_unittest.cc
Labels: Ready to Merge, RN: SAFETY IMPROVEMENT

#13355 Bump workflow action
  .github/workflows/build-release.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: Build System Improvement

#13371 Update SERIALRX_PROVIDER default
  src/main/pg/rx.c
  src/main/target/common_post.h
Labels: RN: BUGFIX

#13378 Add autocomplete for hydrating configuration
  Makefile
Labels: Build System Improvement

#13390 Replace tabs with spaces
  src/main/telemetry/srxl.c
Labels: Cleanup

#13375 Increase ez_landing_limit default to 15 (was 5)
  src/main/flight/pid.c
Labels: Ready to Merge, RN: BUGFIX

#13385 Ensure consistent openssl behaviour with version 3.2.x and 3.3.x
  Makefile
Labels: Build System Improvement

#13384 Fix Galileo toggling
  src/main/io/gps.c
Labels: Ready to Merge, RN: BUGFIX, Tested

#13249 Limit STM32F411 to use 32 leds only.
  src/main/target/STM32F411/target.h
Labels: Cleanup
