Repository betaflight/betaflight, pull requests merged in 2025-01, with the labels that each got.

#14018 AT32F435 SD card support
  lib/main/AT32F43x/middlewares/usbd_class/msc/msc_bot_scsi.c
  src/platform/AT32/mk/AT32F4.mk
  src/platform/AT32/usb_msc_at32f43x.c
Labels: RN: BUGFIX

#14107 Initial (untested) implementation of config in flash 16kb
  src/platform/PICO/config_flash.c
  src/platform/PICO/platform_mcu.h
  src/platform/PICO/system.c
  src/platform/PICO/target/RP2350B/target.h
Labels: RPI

#14120 Moving io_def_generated to platform
  src/platform/APM32/mk/APM32F4.mk
  src/platform/AT32/mk/AT32F4.mk
  src/platform/SIMULATOR/io_def_generated.h
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
  src/platform/STM32/mk/STM32_COMMON.mk
  src/platform/common/stm32/io_def_generated.h
  src/test/unit/io_def_generated.h
  src/test/unit/rx_spi_expresslrs_unittest.cc
  src/test/unit/rx_spi_spektrum_unittest.cc
Labels: RN: REFACTORING

#14116 Bump clang version to 18
  src/test/Makefile
  src/test/unit/cms_unittest.cc
  src/test/unit/pg_unittest.cc
  src/test/unit/rc_controls_unittest.cc
  src/test/unit/rx_ibus_unittest.cc
  src/test/unit/rx_spi_expresslrs_unittest.cc
  src/test/unit/rx_spi_spektrum_unittest.cc
  src/test/unit/rx_sumd_unittest.cc
  src/test/unit/scheduler_unittest.cc
  src/test/unit/telemetry_ibus_unittest.cc
  src/test/unit/unittest_displayport.h
Labels: Build System Improvement

#14122 AT32F435 SD card support (#14018)
  lib/main/AT32F43x/middlewares/usbd_class/msc/msc_bot_scsi.c
  mk/mcu/AT32F4.mk
  src/main/drivers/at32/usb_msc_at32f43x.c
Labels: RN: BUGFIX

#14112 Remove port "A" reference from IO
  src/main/drivers/io_def.h
  src/platform/PICO/io_def_generated.h
  src/platform/PICO/serial_uart_pico.c
  src/platform/PICO/target/RP2350B/target.h
Labels: For Discussion, RPI

#14058 Fixed - reset all PID controller terms when PASSTHRU_MODE is active
  src/main/flight/pid.c
Labels: RN: BUGFIX

#14124 Move STM (and clone) related SPI implementation to platform
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_impl.h
  src/platform/APM32/mk/APM32F4.mk
  src/platform/APM32/platform_mcu.h
  src/platform/AT32/mk/AT32F4.mk
  src/platform/AT32/platform_mcu.h
  src/platform/SIMULATOR/platform_mcu.h
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
  src/platform/STM32/mk/STM32_COMMON.mk
  src/platform/STM32/platform_mcu.h
  src/platform/common/stm32/bus_spi_hw.c
  src/platform/common/stm32/bus_spi_pinconfig.c
  src/test/unit/platform.h
Labels: RN: REFACTORING

#14123 Move STM (and clone) specific IO initialisation to platform
  src/main/drivers/io.c
  src/platform/APM32/mk/APM32F4.mk
  src/platform/AT32/mk/AT32F4.mk
  src/platform/SIMULATOR/sitl.c
  src/platform/STM32/mk/STM32_COMMON.mk
  src/platform/common/stm32/io_impl.c
Labels: RN: REFACTORING

#14127 Moved IO_GPIOPortIdx to platform
  src/main/drivers/io.c
  src/platform/common/stm32/io_impl.c
Labels: RN: REFACTORING

#14103 Move STM (and clone) related config in flash implementation to platform
  src/main/config/config_eeprom.c
  src/main/config/config_eeprom_impl.h
  src/main/config/config_streamer.c
  src/main/config/config_streamer.h
  src/main/config/config_streamer_impl.h
  src/main/drivers/system.h
  src/platform/APM32/mk/APM32F4.mk
  src/platform/APM32/platform_mcu.h
  src/platform/AT32/mk/AT32F4.mk
  src/platform/AT32/platform_mcu.h
  src/platform/SIMULATOR/sitl.c
  src/platform/SIMULATOR/target/SITL/target.h
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
  src/platform/STM32/mk/STM32_COMMON.mk
  src/platform/STM32/platform_mcu.h
  src/platform/common/stm32/config_flash.c
Labels: RN: REFACTORING

#14130 FIX: Flash page size check is STM (or clone) specific
  src/main/config/config_streamer.c
  src/platform/common/stm32/config_flash.c
Labels: RN: REFACTORING

#14132 FIX: explicit specification of float (build for RPI)
  src/main/flight/alt_hold_multirotor.c
Labels: RN: REFACTORING, RPI

#14134 FIX: Adding init for SPIDEV_0
  src/main/fc/init.c
Labels: RN: REFACTORING

#14133 FIX: Adding USE_DMA wrapper around those only available with USE_DMA active
  src/main/drivers/bus.h
  src/main/drivers/bus_spi.c
  src/platform/APM32/bus_spi_apm32.c
  src/platform/AT32/bus_spi_at32bsp.c
  src/platform/STM32/bus_spi_ll.c
  src/platform/STM32/bus_spi_stdperiph.c
Labels: RN: REFACTORING

#14019 Add gyro and magnetic custom alignment to MSP
  src/main/cli/settings.c
  src/main/fc/parameter_names.h
  src/main/flight/imu.c
  src/main/flight/imu.h
  src/main/msp/msp.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#14128 Move STM (and clone) related UART implementation to platform
  mk/source.mk
  src/main/drivers/serial_uart.c
  src/main/drivers/serial_uart_impl.h
  src/main/drivers/serial_usb_vcp.h
  src/platform/APM32/mk/APM32F4.mk
  src/platform/APM32/platform_mcu.h
  src/platform/AT32/mk/AT32F4.mk
  src/platform/AT32/platform_mcu.h
  src/platform/STM32/mk/STM32_COMMON.mk
  src/platform/STM32/platform_mcu.h
  src/platform/STM32/vcp_hal/usbd_cdc_interface.h
  src/platform/common/stm32/serial_uart_hw.c
Labels: RN: REFACTORING

#14129 FIX: Makefile such that `make CONFIG=config-target` works as expected
  Makefile
Labels: Build System Improvement

#14138 FIX: Adding RP2350B as MCU type and correcting lookup table error
  src/main/build/build_config.c
  src/main/build/build_config.h
  src/main/cli/cli.c
Labels: RN: BUGFIX

#14137 FIX: RCC is platform specific
  src/main/drivers/serial_uart_impl.h
  src/platform/APM32/platform_mcu.h
  src/platform/AT32/platform_mcu.h
  src/platform/STM32/platform_mcu.h
Labels: RN: REFACTORING

#14139 FIX: Missing USE_DMA conditions
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_spi_bmi160.c
  src/main/drivers/accgyro/accgyro_spi_bmi270.c
  src/main/drivers/accgyro/accgyro_spi_lsm6dsv16x.c
  src/main/drivers/bus_spi.c
  src/main/drivers/compass/compass_ak8963.c
  src/main/drivers/max7456.c
  src/main/drivers/rx/rx_spi.c
Labels: RN: BUGFIX

#14142 Leave SPI CPOL/CPHA at default for SD card
  src/main/drivers/sdcard_spi.c
Labels: RN: BUGFIX

#14143 [4.5.2] Leave SPI CPOL/CPHA at default for SD card (#14142)
  src/main/drivers/sdcard_spi.c
Labels: RN: BUGFIX

#14141 Adding ability to configure USB positive data pin (PA12 is STM specific)
  src/main/drivers/usb_io.c
  src/platform/APM32/platform_mcu.h
  src/platform/AT32/platform_mcu.h
  src/platform/STM32/platform_mcu.h
Labels: RN: REFACTORING

#14135 FIX: Invalid references when neither DSHOT nor PWM_OUTPUT is defined.
  src/main/drivers/motor.c
  src/platform/APM32/pwm_output_apm32.c
  src/platform/AT32/dshot_bitbang.c
  src/platform/AT32/pwm_output_at32bsp.c
  src/platform/STM32/pwm_output.c
Labels: RN: BUGFIX

#14144 h7: spi: SPI1 MISO add PG9 as AF option
  src/platform/common/stm32/bus_spi_pinconfig.c
Labels: RN: IMPROVEMENT

#14147 h7: sdmmc: add SDIO_USE_PULLUP option for config.h
  src/platform/STM32/sdio_h7xx.c
Labels: RN: IMPROVEMENT

#14152 Don't waste time displaying an empty OSD string
  src/main/drivers/display.c
Labels: RN: BUGFIX

#14154 lis2mdl: fix align define typo
  src/main/sensors/compass.c
Labels: RN: BUGFIX

#14095 Add IIM42653 IMU support
  src/main/cli/settings.c
  src/main/drivers/accgyro/accgyro.h
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/accgyro/accgyro_mpu.h
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
  src/main/sensors/acceleration.h
  src/main/sensors/acceleration_init.c
  src/main/sensors/gyro_init.c
  src/main/target/common_post.h
  src/main/target/common_pre.h
Labels: RN: IMPROVEMENT

#14131 The imitation of GPS is added for SITL
  src/main/cli/settings.c
  src/main/drivers/serial.c
  src/main/flight/imu.c
  src/main/io/gps.c
  src/main/io/gps.h
  src/main/io/gps_virtual.c
  src/main/io/gps_virtual.h
  src/main/pg/gps.c
  src/platform/SIMULATOR/sitl.c
  src/platform/SIMULATOR/target/SITL/target.h
  src/platform/SIMULATOR/target/SITL/target.mk
Labels: RN: IMPROVEMENT

#14161 Fix STM32G4 SPI2/SPI3 busses running at double intended clock rate (#14160)
  src/main/drivers/stm32/bus_spi_ll.c
Labels: RN: BUGFIX

#14160 Fix STM32G4 SPI2/SPI3 busses running at double intended clock rate
  src/platform/STM32/bus_spi_ll.c
Labels: RN: BUGFIX

#14167 h7: sdio: allow custom clock divider
  src/platform/STM32/sdio_h7xx.c
Labels: RN: IMPROVEMENT

#14171 Serial - BUGFIX - USART10 instead of UART10
  src/main/drivers/serial_uart.c
Labels: RN: BUGFIX

#14106 PICO: Adding VCP (CDC) support
  src/platform/PICO/link/pico_rp2350.ld
  src/platform/PICO/mk/PICO.mk
  src/platform/PICO/serial_usb_vcp_pico.c
  src/platform/PICO/target/RP2350B/target.h
  src/platform/PICO/usb/tusb_config.h
  src/platform/PICO/usb/usb_cdc.c
  src/platform/PICO/usb/usb_cdc.h
  src/platform/PICO/usb/usb_descriptors.c
Labels: RPI

#14162 Fix license header for files in AT and APM directories
  src/platform/APM32/adc_apm32f4xx.c
  src/platform/APM32/apm32f4xx_ddl_ex.h
  src/platform/APM32/bus_i2c_apm32.c
  src/platform/APM32/bus_i2c_apm32_init.c
  src/platform/APM32/bus_spi_apm32.c
  src/platform/APM32/dma_apm32.h
  src/platform/APM32/dma_apm32f4xx.c
  src/platform/APM32/dma_reqmap_mcu.c
  src/platform/APM32/dshot_bitbang.c
  src/platform/APM32/dshot_bitbang_ddl.c
  src/platform/APM32/eint_apm32.c
  src/platform/APM32/io_apm32.c
  src/platform/APM32/light_ws2811strip_apm32.c
  src/platform/APM32/persistent_apm32.c
  src/platform/APM32/pwm_output_apm32.c
  src/platform/APM32/pwm_output_dshot_apm32.c
  src/platform/APM32/rcm_apm32.c
  src/platform/APM32/serial_uart_apm32.c
  src/platform/APM32/serial_uart_apm32f4xx.c
  src/platform/APM32/system_apm32f4xx.c
  src/platform/APM32/target/APM32F405/target.h
  src/platform/APM32/target/APM32F407/target.h
  src/platform/APM32/timer_apm32.c
  src/platform/APM32/timer_apm32f4xx.c
  src/platform/APM32/timer_def.h
  src/platform/APM32/transponder_ir_io_apm32.c
  src/platform/APM32/usb/msc/usb_msc_apm32f4xx.c
  src/platform/APM32/usb/vcp/serial_usb_vcp.c
  src/platform/AT32/adc_at32f43x.c
  src/platform/AT32/bus_i2c_atbsp.c
  src/platform/AT32/bus_i2c_atbsp_init.c
  src/platform/AT32/bus_spi_at32bsp.c
  src/platform/AT32/dma_at32f43x.c
  src/platform/AT32/dma_atbsp.h
  src/platform/AT32/dshot_bitbang.c
  src/platform/AT32/exti_at32.c
  src/platform/AT32/io_at32.c
  src/platform/AT32/light_ws2811strip_at32f43x.c
  src/platform/AT32/persistent_at32bsp.c
  src/platform/AT32/pwm_output_at32bsp.c
  src/platform/AT32/pwm_output_dshot.c
  src/platform/AT32/serial_uart_at32bsp.c
  src/platform/AT32/serial_usb_vcp_at32f4.c
  src/platform/AT32/system_at32f43x.c
  src/platform/AT32/target/AT32F435G/target.h
  src/platform/AT32/target/AT32F435M/target.h
  src/platform/AT32/timer_at32bsp.c
  src/platform/AT32/timer_at32f43x.c
  src/platform/AT32/usb_msc_at32f43x.c
Labels: RN: IGNORE

#14159 Refactor compass align defines
  src/main/sensors/compass.c
Labels: RN: REFACTORING

#14165 Flip FM priority for ALTH / POSH (OSD, CRSF, LTM)
  src/main/osd/osd_elements.c
  src/main/telemetry/crsf.c
  src/main/telemetry/ltm.c
Labels: RN: IMPROVEMENT

#14148 Remove MCU name table from CLI (rely on build info), add MCU info MSP2 command
  src/main/build/build_config.c
  src/main/build/build_config.h
  src/main/cli/cli.c
  src/main/common/streambuf.c
  src/main/common/streambuf.h
  src/main/msp/msp.c
  src/main/msp/msp_protocol_v2_betaflight.h
  src/platform/SIMULATOR/sitl.c
  src/platform/common/stm32/system.c
  src/test/unit/cli_unittest.cc
Labels: RN: REFACTORING

#14092 Fix missing ACCGYRO custom alignment defines (used in config)
  src/main/common/sensor_alignment.h
  src/main/common/sensor_alignment_impl.h
  src/main/pg/gyrodev.c
Labels: RN: BUGFIX

#14176 lis2mdl: Enable OFF_CANC and BDU
  src/main/drivers/compass/compass_lis2mdl.c
Labels: RN: IMPROVEMENT

#14166 Tidy up MSP protocol header
  src/main/msp/msp_protocol.h
Labels: RN: REFACTORING

#14178 [4.5.2] Fix missing ACCGYRO custom alignment defines (#14092)
  src/main/common/sensor_alignment.h
  src/main/common/sensor_alignment_impl.h
  src/main/pg/gyrodev.c
Labels: RN: BUGFIX, Added by Cherry-pick

#14181 FIX: USE_STDPERIPH_DRIVER incorrectly defined for all targets (legacy)
  Makefile
  src/platform/STM32/mk/STM32F4.mk
Labels: Bugfix, RN: REFACTORING

#14150 Improve accuracy of dT used to update RPM filter
  src/main/flight/rpm_filter.c
Labels: RN: IMPROVEMENT

#14180 Add ability to specify a config.c file for a config target
  mk/config.mk
  mk/source.mk
  src/main/config/config.h
  src/main/fc/init.c
Labels: RN: IMPROVEMENT

#13105 Chirp signal generator as flight mode
  mk/source.mk
  src/main/blackbox/blackbox.c
  src/main/build/debug.c
  src/main/build/debug.h
  src/main/cli/settings.c
  src/main/common/chirp.c
  src/main/common/chirp.h
  src/main/fc/core.c
  src/main/fc/parameter_names.h
  src/main/fc/rc_modes.h
  src/main/fc/runtime_config.h
  src/main/flight/pid.c
  src/main/flight/pid.h
  src/main/flight/pid_init.c
  src/main/msp/msp_box.c
  src/main/osd/osd_elements.c
  src/main/osd/osd_warnings.c
  src/main/telemetry/crsf.c
Labels: RN: MAJOR FEATURE, Needs coordination with blackbox-log-viewer, Pinned

#14186 [4.5.2] Fix flash type
  src/main/drivers/flash.c
Labels: RN: BUGFIX

#14189 By default mark OSD element as rendered in case it's in the off blink state (#14188)
  src/main/osd/osd_elements.c
Labels: RN: BUGFIX

#14188 By default mark OSD element as rendered in case it's in the off blink state
  src/main/osd/osd_elements.c
Labels: RN: BUGFIX

#14174 Refactor SPI pre init to make it generic and usable from io.h
  mk/source.mk
  src/main/drivers/accgyro/accgyro_mpu.c
  src/main/drivers/barometer/barometer_2smpb_02b.c
  src/main/drivers/barometer/barometer_bmp280.c
  src/main/drivers/barometer/barometer_bmp388.c
  src/main/drivers/barometer/barometer_dps310.c
  src/main/drivers/barometer/barometer_lps22df.c
  src/main/drivers/barometer/barometer_ms5611.c
  src/main/drivers/bus_spi.h
  src/main/drivers/bus_spi_config.c
  src/main/drivers/compass/compass_ak8963.c
  src/main/drivers/flash/flash.c
  src/main/drivers/flash/flash.h
  src/main/drivers/io.h
  src/main/drivers/io_preinit.c
  src/main/drivers/max7456.c
  src/main/drivers/max7456.h
  src/main/drivers/rx/rx_spi.c
  src/main/drivers/rx/rx_spi.h
  src/main/drivers/sdcard.c
  src/main/drivers/sdcard.h
  src/main/drivers/sdcard_impl.h
  src/main/drivers/sdcard_spi.c
  src/main/sensors/barometer.c
  src/main/sensors/compass.c
  src/main/target/common_post.h
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
  src/platform/STM32/mk/STM32_COMMON.mk
  src/test/unit/baro_bmp280_unittest.cc
  src/test/unit/baro_bmp388_unittest.cc
  src/test/unit/baro_ms5611_unittest.cc
Labels: RN: REFACTORING

#14151 FIX: REVISION length not more than 7 symbols
  Makefile
Labels: RN: BUGFIX

#14193 Fix GPS UART representation (status command)
  src/main/cli/cli.c
Labels: RN: BUGFIX

#14195 GPS - simplify GPS baudrate handling
  src/main/io/gps.c
  src/main/io/gps.h
Labels: Tested, RN: REFACTORING

#14187 Add make preview and extend CI coverage
  Makefile
Labels: Build System Improvement

#14192 Add 230K4 baudrate support for GPS
  src/main/cli/cli.c
  src/main/io/gps.c
Labels: Needs coordination with betaflight-configurator, RN: IMPROVEMENT, Tested

#14199 h7: enable ports H and I
  src/platform/STM32/target/STM32H743/target.h
Labels: RN: IMPROVEMENT

#14201 FIX: Missing IFDEF USE_TIMER and USE_RPM_FILTER
  src/main/config/config.c
  src/main/drivers/dshot.c
Labels: RN: REFACTORING

#14197 Remove unused timer related defines
  src/platform/STM32/exti.c
Labels: Cleanup

#14198 Remove PARTIAL_REMAP_TIM3 defines for AT32 and STM32
  src/platform/AT32/timer_at32bsp.c
  src/platform/STM32/timer_stdperiph.c
Labels: Cleanup

#14206 Update mag_declination range in settings.c
  src/main/cli/settings.c
Labels: RN: BUGFIX

#14207 Fix G4 SPI clock being double what it should be
  src/platform/common/stm32/bus_spi_hw.c
Labels: RN: BUGFIX

#14153 h7: add timer pins
  src/platform/STM32/timer_def.h
  src/platform/STM32/timer_stm32h7xx.c
Labels: RN: IMPROVEMENT

#14212 fix: STM32H5 makefile oop debug
  src/platform/STM32/mk/STM32H5.mk
Labels: H5

#14194 Filter comment line while try to get SYSTEM_HSE_MHZ value.
  mk/config.mk
Labels: Build System Improvement

#14213 Fix GYRO_CLKIN
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
Labels: RN: BUGFIX

#14202 Remove redundant SITL ioPortDef_s array definition
  src/main/drivers/io.c
  src/main/drivers/serial_pinconfig.c
  src/main/fc/init.c
  src/main/io/serial.c
  src/main/io/serial.h
  src/platform/APM32/platform_mcu.h
  src/platform/AT32/platform_mcu.h
  src/platform/SIMULATOR/platform_mcu.h
  src/platform/STM32/platform_mcu.h
  src/test/unit/io_serial_unittest.cc
Labels: RN: REFACTORING

#14205 PICO: First stage of DSHOT and PWM implementation
  src/platform/PICO/dshot_pico.c
  src/platform/PICO/mk/PICO.mk
  src/platform/PICO/pwm_pico.c
  src/platform/PICO/target/RP2350B/target.h
Labels: RPI

#14215 Fix G4 SPI clock being double what it should be (#14207)
  src/main/drivers/bus_spi.c
Labels: RN: BUGFIX

#14214 FIX: Serial ESC communication when using digital protocols
  src/main/drivers/motor.c
  src/main/drivers/motor.h
  src/main/drivers/motor_types.h
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output_impl.h
  src/main/io/serial_4way.c
  src/platform/APM32/dshot_bitbang.c
  src/platform/APM32/pwm_output_apm32.c
  src/platform/AT32/pwm_output_at32bsp.c
  src/platform/SIMULATOR/sitl.c
  src/platform/STM32/pwm_output_hw.c
  src/platform/common/stm32/dshot_dpwm.c
Labels: RN: BUGFIX, Tested

#14220 FIX: AT32 not reading ESC
  src/main/drivers/pwm_output.c
  src/main/drivers/pwm_output.h
  src/platform/APM32/dshot_bitbang.c
  src/platform/APM32/pwm_output_apm32.c
  src/platform/AT32/dshot_bitbang.c
  src/platform/AT32/io_at32.c
  src/platform/AT32/pwm_output_at32bsp.c
  src/platform/SIMULATOR/sitl.c
  src/platform/STM32/dshot_bitbang.c
  src/platform/STM32/pwm_output_hw.c
  src/platform/common/stm32/dshot_bitbang_impl.h
  src/platform/common/stm32/dshot_bitbang_shared.c
  src/platform/common/stm32/dshot_dpwm.c
Labels: RN: BUGFIX
