Repository betaflight/betaflight, pull requests merged in 2025-04, with the labels that each got.

#14320 REFACTOR: Moving platform specific DMA code to include/platform
  src/main/drivers/dma.h
  src/platform/APM32/include/platform/dma.h
  src/platform/APM32/mk/APM32F4.mk
  src/platform/AT32/include/platform/dma.h
  src/platform/AT32/mk/AT32F4.mk
  src/platform/SIMULATOR/include/platform/dma.h
  src/platform/SIMULATOR/mk/SITL.mk
  src/platform/STM32/include/platform/dma.h
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
  src/test/unit/platform/dma.h
Labels: REFACTORING

#14324 Add PB0 to AT32 SPI3 mosi pins
  src/platform/AT32/platform_mcu.h
  src/platform/common/stm32/bus_spi_pinconfig.c
Labels: RN: TARGET UPDATE

#14331 [4.5.3] Maint at32 spi3 mosi (add PB0 pin)
  src/main/drivers/bus_spi_impl.h
  src/main/drivers/bus_spi_pinconfig.c
Labels: RN: TARGET UPDATE

#14334 [4.5.3] Revert gps flight model
  src/main/pg/gps.c
Labels: RN: BUGFIX

#14325 Added virtual blackbox for SITL
  src/main/blackbox/blackbox.c
  src/main/blackbox/blackbox.h
  src/main/blackbox/blackbox_io.c
  src/main/blackbox/blackbox_virtual.c
  src/main/blackbox/blackbox_virtual.h
  src/main/cli/settings.c
  src/platform/SIMULATOR/target/SITL/target.h
  src/platform/SIMULATOR/target/SITL/target.mk
Labels: RN: MINOR FEATURE

#14333 Revert GPS flight model change
  src/main/pg/gps.c
Labels: RN: BUGFIX

#14336 Jetiexbus -> function unused without GPS enabled.
  src/main/telemetry/jetiexbus.c
Labels: RN: BUGFIX

#14229 hover point throttle curve adjustment
  src/main/blackbox/blackbox.c
  src/main/cli/settings.c
  src/main/cms/cms_menu_imu.c
  src/main/fc/controlrate_profile.c
  src/main/fc/controlrate_profile.h
  src/main/fc/parameter_names.h
  src/main/fc/rc.c
  src/main/msp/msp.c
  src/test/unit/rc_controls_unittest.cc
Labels: RN: MINOR FEATURE

#14332 Add Launch Timer
  src/main/osd/osd.c
  src/main/osd/osd.h
  src/main/osd/osd_elements.c
Labels: Needs coordination with betaflight-configurator, RN: MINOR FEATURE

#14284 Fix SITL for MacOS M1
  Makefile
  src/platform/SIMULATOR/mk/SITL.mk
Labels: Build System Improvement

#14340 Properly handle USE_BARO_LPS22DF
  src/main/sensors/barometer.c
Labels: RN: BUGFIX

#14346 REFACTOR: Remove unused drivers/dma.c file
  src/main/drivers/dma.c
Labels: RN: REFACTORING

#14344 Add variant for RTC OSD element
  src/main/osd/osd_elements.c
Labels: Ready to Merge, Needs coordination with betaflight-configurator, RN: IMPROVEMENT

#14360 Fix ATRN
  src/main/osd/osd_elements.c
Labels: Ready to Merge, RN: BUGFIX

#14362 Fix turtle mode motor direction on rearm
  src/main/fc/core.c
Labels: RN: BUGFIX
