Repository betaflight/betaflight, pull requests merged in 2025-03, with the labels that each got.

#14276 Fix virtualled
  src/main/cli/cli.c
  src/main/cli/settings.c
  src/main/drivers/light_led.c
  src/main/drivers/light_led.h
  src/test/unit/target.h
Labels: RN: BUGFIX

#14290 Fix typo in accgyro_spi_icm426xx.c
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
Labels: RN: IGNORE

#14286 fix: led strip not working (#14279)
  src/main/drivers/light_ws2811strip.c
Labels: RN: BUGFIX

#14299 [4.5.2] Make UBLOX_MODEL_AIRBORNE_1G default
  src/main/pg/gps.c
Labels: RN: BUGFIX

#14271 Change airborne default
  src/main/pg/gps.c
Labels: Ready to Merge, RN: BUGFIX

#14311 Fix gimbalCmdIn.u.crc to gimbalCmdIn.u.gimbalCmd.crc
  src/main/io/gimbal_control.c
Labels: RN: BUGFIX

#14315 Fix typos
  src/main/flight/pos_hold_multirotor.c
  src/main/flight/pos_hold_wing.c
Labels: RN: IGNORE

#14321 Add NULL check for vTable->decodeTelemetry
  src/main/drivers/motor.c
Labels: RN: BUGFIX

#14319 fix: missing sitl motor count
  src/platform/SIMULATOR/sitl.c
Labels: RN: BUGFIX

#14228 Adding simplified timer calls for enabling ESC Serial and Soft Serial for AT32
  src/main/drivers/rx/expresslrs_driver.c
  src/main/drivers/serial_escserial.c
  src/main/drivers/serial_softserial.c
  src/main/drivers/timer.h
  src/platform/APM32/timer_apm32.c
  src/platform/AT32/target/AT32F435G/target.h
  src/platform/AT32/target/AT32F435M/target.h
  src/platform/AT32/timer_at32bsp.c
  src/platform/STM32/timer_hal.c
  src/platform/STM32/timer_stdperiph.c
Labels: RN: IMPROVEMENT
