Repository betaflight/betaflight, pull requests merged in 2025-06, with the labels that each got.

#14422 PICO: Preparing for I2C device using I2C0
  src/main/drivers/bus_i2c.h
  src/main/drivers/bus_i2c_impl.h
  src/main/platform.h
  src/platform/APM32/include/platform/platform.h
  src/platform/AT32/include/platform/platform.h
  src/platform/SIMULATOR/include/platform/platform.h
  src/platform/STM32/include/platform/platform.h
  src/test/unit/platform.h
Labels: RN: REFACTORING, RPI

#14435 REFACTOR: missed trait defines
  src/main/drivers/bus_i2c_config.c
Labels: Cleanup

#14437 PICO: Adding RP2350A MCU
  src/main/build/build_config.h
  src/main/common/strtol.c
  src/main/msp/msp.c
  src/main/target/common_post.h
Labels: RN: REFACTORING, RPI

#14441 Removed extraneous parentheses to resolve compiler warning
  src/main/cli/cli.c
Labels: RN: BUGFIX

#14446 Pico - fix getCycleCounter
  src/platform/PICO/system.c
Labels: RN: BUGFIX, RPI

#14455 Added MAYBE_UNUSED to get rid of compiler warning
  src/main/sensors/voltage.c
Labels: REFACTORING

#14454 Remove duplicate source file
  mk/source.mk
Labels: Cleanup

#14460 CLI allow for DEFIO_PORT_PINS pins per port.
  src/main/cli/cli.c
Labels: REFACTORING

#14462 Move serial_uart_pinconfig.c to platform.
  src/platform/APM32/mk/APM32F4.mk
  src/platform/AT32/mk/AT32F4.mk
  src/platform/STM32/mk/STM32F4.mk
  src/platform/STM32/mk/STM32F7.mk
  src/platform/STM32/mk/STM32G4.mk
  src/platform/STM32/mk/STM32H5.mk
  src/platform/STM32/mk/STM32H7.mk
  src/platform/STM32/mk/STM32_COMMON.mk
  src/platform/common/stm32/serial_uart_pinconfig.c
Labels: REFACTORING

#14463 REFACTOR: Removing platform specific defines from init.c
  mk/source.mk
  src/main/cli/settings.c
  src/main/drivers/mco.h
  src/main/fc/init.c
  src/platform/APM32/include/platform/platform.h
  src/platform/APM32/mk/APM32F4.mk
  src/platform/AT32/mk/AT32F4.mk
  src/platform/STM32/include/platform/platform.h
  src/platform/STM32/mk/STM32_COMMON.mk
  src/platform/common/stm32/mco.c
Labels: RN: REFACTORING

#14471 REFACTOR: More platform specific defines moved to platform
  src/main/cli/cli.c
  src/platform/APM32/include/platform/platform.h
  src/platform/AT32/include/platform/platform.h
  src/platform/STM32/include/platform/platform.h
Labels: RN: REFACTORING

#14470 Disable entering CMS menu when armed
  src/main/io/displayport_crsf.c
Labels: RN: SAFETY IMPROVEMENT

#14474 REFACTOR: Adding DMA_FIRST_HANDLER
  src/main/cli/cli.c
  src/main/drivers/dma.h
  src/platform/APM32/include/platform/dma.h
  src/platform/AT32/include/platform/dma.h
  src/platform/SIMULATOR/include/platform/dma.h
  src/platform/STM32/include/platform/dma.h
Labels: Tested, RN: REFACTORING

#14483 Add support for SPI DMA
  src/main/msp/msp.c
  src/platform/PICO/bus_spi_pico.c
  src/platform/PICO/dma_pico.c
  src/platform/PICO/include/platform/platform.h
  src/platform/PICO/target/RP2350B/target.h
Labels: RN: IMPROVEMENT, RPI

#14487 Fix ICM426XX_RA_DEVICE_CONFIG
  src/main/drivers/accgyro/accgyro_spi_icm426xx.c
Labels: RN: BUGFIX

#14478 Move beeper pwm functions to platform.
  src/main/drivers/pwm_output.h
  src/main/drivers/sound_beeper.c
  src/main/drivers/sound_beeper.h
  src/platform/APM32/mk/APM32F4.mk
  src/platform/AT32/mk/AT32F4.mk
  src/platform/STM32/mk/STM32_COMMON.mk
  src/platform/common/stm32/pwm_output_beeper.c
Labels: RN: REFACTORING
