Repository betaflight/betaflight, pull requests merged in 2025-09, with the labels that each got.

#14634 PICO: Adding reboot to flashing rom (like DFU)
  src/platform/PICO/system.c
Labels: RN: TARGET UPDATE

#14642 PRE-RELEASE: Preparing for beta release named 2025.12.0-beta
  Makefile
  src/main/build/version.h
  src/main/msp/msp.c
Labels: RN: IMPROVEMENT

#14644 fix-undefined-customAlignment1-variable
  src/main/pg/gyrodev.c
Labels: RN: BUGFIX

#14630 allow custom define for MAX_CHANNEL_ACTIVATION_CONDITION_COUNT
  src/main/io/vtx_control.h
Labels: RN: IMPROVEMENT

#14637 Fix mag custom alignment configuration
  src/main/sensors/compass.c
Labels: RN: BUGFIX

#14647 POSIX compatible awk rules in order to build under OSX
  Makefile
Labels: Housekeeping

#14658 Add a NOP to give processor time to handle interrupts
  src/main/drivers/rx/rx_sx1280.c
  src/main/drivers/usb_msc_common.c
Labels: RN: BUGFIX

#14648 GYRO: Remove ability for user to set the gyro alignment at run time.
  src/main/cli/settings.c
  src/main/msp/msp.c
Labels: Needs coordination with Betaflight App, RN: IMPROVEMENT, Needs Betaflight App change

#14650 Updating CLI device output for status command
  src/main/cli/cli.c
  src/main/sensors/gyro_init.c
  src/main/sensors/initialisation.c
  src/main/sensors/opticalflow.c
  src/main/sensors/rangefinder.c
  src/main/sensors/sensors.h
  src/test/unit/cli_unittest.cc
  src/test/unit/sensor_gyro_unittest.cc
Labels: RN: IMPROVEMENT

#14654 Debug modes should be unconditional
  src/main/build/debug.c
  src/main/build/debug.h
Labels: Bugfix

#14666 CLEANUP: Trailing white space
  src/main/common/chirp.c
  src/main/common/vector.c
  src/main/drivers/accgyro/accgyro_spi_icm40609.c
  src/main/drivers/accgyro/accgyro_spi_icm40609.h
  src/main/drivers/dshot.c
  src/main/drivers/opticalflow/opticalflow.h
  src/main/drivers/rangefinder/rangefinder_lidarmt.c
  src/main/flight/imu.c
  src/main/flight/pid.c
  src/main/msp/msp.c
  src/main/osd/osd_elements.c
  src/main/pg/piniobox.c
  src/main/sensors/opticalflow.c
  src/platform/PICO/bus_spi_pico.c
  src/platform/PICO/dshot_pico.c
  src/platform/STM32/rcc_stm32.c
  src/platform/STM32/sdio_h7xx.c
  src/platform/STM32/startup/system_stm32g4xx.c
  src/platform/STM32/target/STM32F745/target.h
  src/platform/STM32/timer_stm32h5xx.c
Labels: RN: IGNORE

#14663 PICO: maths performance - use pico_float and pico_double from SDK
  src/main/scheduler/scheduler.c
  src/platform/PICO/mk/RP2350.mk
Labels: RPI

#14673 Fix preprocess guard hash emission
  mk/preprocess.mk
Labels: Housekeeping

#14676 Use octal escape for preprocessor guard hash
  mk/preprocess.mk
Labels: RN: BUGFIX, Housekeeping

#14688 GYRO: Remove ability to set custom gyro alignment
  src/main/cli/settings.c
Labels: RN: SAFETY IMPROVEMENT
