Repository betaflight/betaflight, pull requests merged in 2025-10, with the labels that each got.

#14693 Update build options
  src/main/msp/msp_build_info.c
  src/main/msp/msp_build_info.h
Labels: Build System Improvement

#14681 MAVLink serial RX provider
  mk/source.mk
  src/main/cli/settings.c
  src/main/pg/rx.c
  src/main/rx/mavlink.c
  src/main/rx/mavlink.h
  src/main/rx/rx.c
  src/main/rx/rx.h
  src/main/target/common_post.h
  src/main/target/common_pre.h
  src/main/telemetry/mavlink.c
  src/main/telemetry/telemetry.c
  src/platform/STM32/include/platform/platform.h
  src/test/Makefile
Labels: RN: IMPROVEMENT

#14618 PICO RP2350 bidirectional dshot
  src/platform/PICO/dshot.pio
  src/platform/PICO/dshot_bidir_pico.c
  src/platform/PICO/dshot_pico.c
  src/platform/PICO/dshot_pico.h
  src/platform/PICO/dshot_pio_programs.h
  src/platform/PICO/io_pico.c
  src/platform/PICO/mk/RP2350.mk
  src/platform/PICO/target/RP2350A/target.h
  src/platform/PICO/target/RP2350B/target.h
Labels: RN: TARGET UPDATE, RN: IMPROVEMENT, RPI

#14672 Fix Dshot Beacon Logic
  src/main/drivers/usb_io.c
  src/main/flight/failsafe.c
  src/main/io/beeper.c
  src/main/io/beeper.h
  src/platform/SIMULATOR/sitl.c
  src/platform/SIMULATOR/target/SITL/target.h
  src/test/unit/flight_failsafe_unittest.cc
Labels: RN: BUGFIX

#14703 Initialize 8 servos when available in the target (instead of 4)
  src/main/flight/servos.c
Labels: RN: BUGFIX

#14701 Added MAVLink telemetries battery status data send
  src/main/telemetry/mavlink.c
Labels: RN: BUGFIX
