Repository betaflight/betaflight, pull requests merged in 2025-07, with the labels that each got.

#14497 PICO: Renamed MCU FAMILY to RP2350
  src/platform/PICO/mk/RP2350.mk
  src/platform/PICO/target/RP2350A/target.mk
  src/platform/PICO/target/RP2350B/target.mk
Labels: RN: REFACTORING

#14499 PICO: Revert uartPinConfigure code (pending updates for PIO UART)
  src/platform/PICO/serial_uart_pico.c
Labels: RPI

#14496 Register allocated DMA channels for dma show
  src/platform/PICO/bus_spi_pico.c
  src/platform/PICO/include/platform/platform.h
Labels: RPI

#14493 PICO: Beeper implementation (pwm)
  src/platform/PICO/mk/RP2350.mk
  src/platform/PICO/pwm_beeper_pico.c
  src/platform/PICO/target/RP2350B/target.h
Labels: RPI

#14501 SITL: Minor changes to simplify platform
  src/main/main.c
  src/main/pg/gps.c
  src/main/pg/gyrodev.c
  src/platform/SIMULATOR/include/platform/platform.h
Labels: RN: REFACTORING

#14515 Fix missing #if for PINIO_COUNT
  Makefile
  src/main/cms/cms_menu_firmware.c
  src/main/fc/board_info.c
  src/main/pg/pinio.c
Labels: RN: BUGFIX

#14513 USE_DMA_SPEC not needed on RP2350 as DMA channel use is unrestricted
  src/main/cli/cli.c
  src/main/drivers/dma_reqmap.h
  src/platform/PICO/dma_reqmap_mcu.c
  src/platform/PICO/dma_reqmap_mcu.h
Labels: Cleanup, RPI

#14528 accgyro_mpu initialise gyro->segments.
  src/main/drivers/accgyro/accgyro_mpu.c
Labels: RN: BUGFIX

#14529 PICO: Removing the flash CS pin as it will be defined in config.h
  src/platform/PICO/target/RP2350B/target.h
Labels: RN: IGNORE

#14502 Fix incorrect TIMUP DMA configuration dump on H743
  src/main/cli/cli.c
  src/main/drivers/timer.h
  src/main/pg/timerup.c
  src/main/pg/timerup.h
  src/platform/APM32/timer_apm32.c
  src/platform/APM32/timer_def.h
  src/platform/AT32/dma_reqmap_mcu.c
  src/platform/AT32/timer_at32bsp.c
  src/platform/AT32/timer_def.h
  src/platform/STM32/dma_reqmap_mcu.c
  src/platform/STM32/timer_def.h
  src/platform/STM32/timer_hal.c
  src/platform/STM32/timer_stdperiph.c
Labels: RN: BUGFIX

#14543 FIX: Skip undetected gyros (blocking VCP connection)
  src/main/sensors/gyro_init.c
Labels: RN: BUGFIX

#14525 SPI: Extract common preInit code from spiInternalInitStream, and fix Pico SPI implementation
  src/main/drivers/bus_spi.c
  src/main/drivers/bus_spi_impl.h
  src/platform/APM32/bus_spi_apm32.c
  src/platform/AT32/bus_spi_at32bsp.c
  src/platform/PICO/bus_spi_pico.c
  src/platform/PICO/include/platform/platform.h
  src/platform/STM32/bus_spi_ll.c
  src/platform/STM32/bus_spi_stdperiph.c
Labels: RN: REFACTORING, RPI

#14532 Add FORCE option to dshot_edt
  src/main/cli/settings.c
  src/main/cli/settings.h
  src/main/drivers/dshot.c
  src/main/pg/motor.c
  src/main/pg/motor.h
Labels: RN: IMPROVEMENT

#14537 PICO non-blocking I2C support
  src/platform/PICO/bus_i2c_pico.c
Labels: RPI

#14552 Fix IMU switching
  src/main/sensors/gyro_init.c
Labels: RN: BUGFIX
